// Auto-generated by scripts/regen-explorer-versions.mjs. Do not edit by hand.
import { services as mainServices } from "../playground/codegen/services.js";
import { types as mainTypes } from "./codegen/types.js";
import type { VersionEntry } from "./data-types.js";

export type { VersionEntry } from "./data-types.js";

/// Version string declared in `js/packages/truapi/package.json` at codegen
/// time. Mirrors the `truapi` crate version. Used by the explorer to render
/// the `main` selector label as `main (x.y.z)`.
export const packageVersion = "0.1.0";

export const versions: VersionEntry[] = [
  { id: "main", services: mainServices, types: mainTypes },
];
