use super::playground::split_playground_docs;
use super::*;

/// Generates standalone TypeScript files for every `truapi-client-example`
/// rustdoc block so package CI can typecheck examples against public exports.
pub fn generate_client_examples(
    api: &ApiDefinition,
    output_dir: &str,
    target_version: u32,
) -> Result<()> {
    let output_path = Path::new(output_dir);
    if output_path.exists() {
        fs::remove_dir_all(output_path)?;
    }
    fs::create_dir_all(output_path)?;
    validate_versioned_wrapper_shapes(api)?;

    let wrappers = collect_versioned_wrappers(api);
    let mut traits: Vec<&TraitDef> = api
        .traits
        .iter()
        .filter(|trait_def| service_order(&trait_def.name).is_some())
        .collect();
    traits.sort_by_key(|trait_def| {
        (
            service_order(&trait_def.name).unwrap_or(usize::MAX),
            trait_def.name.as_str(),
        )
    });

    for trait_def in traits {
        let mut methods = included_methods(trait_def, &wrappers, target_version)?;
        methods.sort_by_key(|method| (method_wire_sort_id(method), method.name.as_str()));

        for method in methods {
            let docs = split_playground_docs(method.docs.as_deref(), &method.name)?;
            let Some(client_example) = docs.client_example else {
                continue;
            };
            let filename = format!(
                "{}-{}.ts",
                ts_example_file_stem(&trait_def.name),
                ts_example_file_stem(&method.name)
            );
            let code =
                format!("// Auto-generated by truapi-codegen. Do not edit.\n\n{client_example}\n");
            fs::write(output_path.join(filename), code)?;
        }
    }

    Ok(())
}
