use super::playground::{playground_type_name, split_playground_docs};
use super::*;

/// Generates static registry data consumed by the GitHub Pages explorer.
pub fn generate_explorer_registry(
    api: &ApiDefinition,
    output_dir: &str,
    target_version: u32,
) -> Result<()> {
    fs::create_dir_all(output_dir)?;
    validate_versioned_wrapper_shapes(api)?;

    let code = generate_explorer_registry_code(api, target_version)?;
    fs::write(Path::new(output_dir).join("registry.ts"), code)?;

    Ok(())
}

fn generate_explorer_registry_code(api: &ApiDefinition, target_version: u32) -> Result<String> {
    let wrappers = collect_versioned_wrappers(api);
    let ctx = CodecContext::default();
    let mut out = String::new();

    writeln!(out, "// Auto-generated by truapi-codegen. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "export type ExplorerPattern = \"unary\" | \"subscription\";"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface ExplorerField {{").unwrap();
    writeln!(out, "  name: string;").unwrap();
    writeln!(out, "  type: string;").unwrap();
    writeln!(out, "  description?: string;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface ExplorerVariant {{").unwrap();
    writeln!(out, "  name: string;").unwrap();
    writeln!(out, "  type: string;").unwrap();
    writeln!(out, "  description?: string;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface ExplorerType {{").unwrap();
    writeln!(out, "  id: string;").unwrap();
    writeln!(out, "  name: string;").unwrap();
    writeln!(out, "  category: string;").unwrap();
    writeln!(out, "  definition: string;").unwrap();
    writeln!(out, "  description?: string;").unwrap();
    writeln!(out, "  source: string;").unwrap();
    writeln!(out, "  fields?: ExplorerField[];").unwrap();
    writeln!(out, "  variants?: ExplorerVariant[];").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface ExplorerMethod {{").unwrap();
    writeln!(out, "  id: string;").unwrap();
    writeln!(out, "  name: string;").unwrap();
    writeln!(out, "  groupId: string;").unwrap();
    writeln!(out, "  groupName: string;").unwrap();
    writeln!(out, "  wireId: number;").unwrap();
    writeln!(out, "  pattern: ExplorerPattern;").unwrap();
    writeln!(out, "  request: string;").unwrap();
    writeln!(out, "  response: string;").unwrap();
    writeln!(out, "  errorType?: string;").unwrap();
    writeln!(out, "  description?: string;").unwrap();
    writeln!(out, "  usageExample?: string;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface ExplorerGroup {{").unwrap();
    writeln!(out, "  id: string;").unwrap();
    writeln!(out, "  name: string;").unwrap();
    writeln!(out, "  description?: string;").unwrap();
    writeln!(out, "  methods: string[];").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface ExplorerVersion {{").unwrap();
    writeln!(out, "  id: string;").unwrap();
    writeln!(out, "  label: string;").unwrap();
    writeln!(out, "  slug: string;").unwrap();
    writeln!(out, "  status: \"stable\" | \"preview\";").unwrap();
    writeln!(out, "  groups: ExplorerGroup[];").unwrap();
    writeln!(out, "  methods: ExplorerMethod[];").unwrap();
    writeln!(out, "  dataTypes: ExplorerType[];").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export const versions: ExplorerVersion[] = [").unwrap();

    for version in 1..=target_version {
        let groups = explorer_groups(api, &wrappers, version)?;
        let methods = explorer_methods(api, &wrappers, &ctx, version)?;
        let types = explorer_types(api, &wrappers, version)?;
        writeln!(out, "  {{").unwrap();
        writeln!(
            out,
            "    id: {},",
            ts_string_literal(&protocol_minor(version))
        )
        .unwrap();
        writeln!(
            out,
            "    label: {},",
            ts_string_literal(&format!("v{}", protocol_minor(version)))
        )
        .unwrap();
        writeln!(
            out,
            "    slug: {},",
            ts_string_literal(&protocol_minor(version))
        )
        .unwrap();
        writeln!(out, "    status: \"stable\",").unwrap();
        write_explorer_groups_array(&mut out, "    ", &groups);
        write_explorer_methods_array(&mut out, "    ", &methods);
        write_explorer_types_array(&mut out, "    ", &types);
        writeln!(out, "  }},").unwrap();
    }

    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "export const defaultVersion: ExplorerVersion = versions[versions.length - 1];"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "export function getVersion(slug: string): ExplorerVersion | undefined {{"
    )
    .unwrap();
    writeln!(
        out,
        "  return versions.find((version) => version.slug === slug);"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "export function getTypeById(version: ExplorerVersion, id: string): ExplorerType | undefined {{"
    )
    .unwrap();
    writeln!(
        out,
        "  return version.dataTypes.find((typeDef) => typeDef.id === id);"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "export function getMethodById(version: ExplorerVersion, id: string): ExplorerMethod | undefined {{"
    )
    .unwrap();
    writeln!(
        out,
        "  return version.methods.find((method) => method.id === id);"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();

    Ok(out)
}

#[derive(Debug)]
struct ExplorerGroupRecord {
    id: String,
    name: String,
    description: Option<String>,
    methods: Vec<String>,
}

#[derive(Debug)]
struct ExplorerMethodRecord {
    id: String,
    name: String,
    group_id: String,
    group_name: String,
    wire_id: u8,
    pattern: &'static str,
    request: String,
    response: String,
    error_type: Option<String>,
    description: Option<String>,
    client_example: Option<String>,
}

#[derive(Debug)]
struct ExplorerTypeRecord {
    id: String,
    name: String,
    category: String,
    definition: String,
    description: Option<String>,
    source: String,
    fields: Vec<ExplorerFieldRecord>,
    variants: Vec<ExplorerVariantRecord>,
}

#[derive(Debug)]
struct ExplorerFieldRecord {
    name: String,
    ty: String,
    description: Option<String>,
}

#[derive(Debug)]
struct ExplorerVariantRecord {
    name: String,
    ty: String,
    description: Option<String>,
}

fn explorer_groups(
    api: &ApiDefinition,
    wrappers: &HashMap<String, VersionedWrapper>,
    target_version: u32,
) -> Result<Vec<ExplorerGroupRecord>> {
    let mut traits = explorer_traits(api);
    let mut groups = Vec::new();
    for trait_def in traits.drain(..) {
        let methods = included_methods(trait_def, wrappers, target_version)?
            .into_iter()
            .map(|method| method.name.clone())
            .collect::<Vec<_>>();
        if methods.is_empty() {
            continue;
        }
        groups.push(ExplorerGroupRecord {
            id: explorer_group_id(&trait_def.name),
            name: service_name(&trait_def.name),
            description: trait_def
                .docs
                .as_deref()
                .map(strip_playground_doc_blocks)
                .filter(|docs| !docs.is_empty()),
            methods,
        });
    }
    Ok(groups)
}

fn explorer_methods(
    api: &ApiDefinition,
    wrappers: &HashMap<String, VersionedWrapper>,
    ctx: &CodecContext,
    target_version: u32,
) -> Result<Vec<ExplorerMethodRecord>> {
    let mut methods = Vec::new();
    for trait_def in explorer_traits(api) {
        let mut included = included_methods(trait_def, wrappers, target_version)?;
        included.sort_by_key(|method| (method_wire_sort_id(method), method.name.as_str()));
        for method in included {
            let wire_version = method_wire_version(method, wrappers, target_version)?;
            let payload = emit_payload(&method.params, wrappers, ctx, wire_version)?;
            let docs = split_playground_docs(method.docs.as_deref(), &method.name)?;
            let (response, error_type) = explorer_response(method, wrappers, ctx, wire_version)?;
            methods.push(ExplorerMethodRecord {
                id: method.name.clone(),
                name: method.name.clone(),
                group_id: explorer_group_id(&trait_def.name),
                group_name: service_name(&trait_def.name),
                wire_id: wire_ids_for_method(trait_def, method)?.sort_id(),
                pattern: match method.kind {
                    MethodKind::Request => "unary",
                    MethodKind::Subscription | MethodKind::ResultSubscription => "subscription",
                },
                request: if method.name == "host_handshake" || payload.param_list.is_empty() {
                    "undefined".to_string()
                } else {
                    playground_type_name(&payload.inner_type_ts)
                },
                response,
                error_type,
                description: docs.description,
                client_example: docs.client_example,
            });
        }
    }
    methods.sort_by_key(|method| method.wire_id);
    Ok(methods)
}

fn explorer_response(
    method: &MethodDef,
    wrappers: &HashMap<String, VersionedWrapper>,
    ctx: &CodecContext,
    wire_version: Option<u32>,
) -> Result<(String, Option<String>)> {
    match (&method.kind, &method.return_type) {
        (MethodKind::Request, ReturnType::Result { ok, err }) => {
            let ok = emit_response(ok, wrappers, ctx, wire_version)?;
            let err = emit_error_response(err, wrappers, ctx, wire_version)?;
            Ok((
                playground_type_name(&ok.inner_type_ts),
                Some(playground_type_name(&err.inner_type_ts)),
            ))
        }
        (MethodKind::Subscription, ReturnType::Subscription(item)) => {
            let item = emit_response(item, wrappers, ctx, wire_version)?;
            Ok((playground_type_name(&item.inner_type_ts), None))
        }
        (MethodKind::ResultSubscription, ReturnType::ResultSubscription { item, err }) => {
            let item = emit_response(item, wrappers, ctx, wire_version)?;
            let err = emit_error_response(err, wrappers, ctx, wire_version)?;
            Ok((
                playground_type_name(&item.inner_type_ts),
                Some(playground_type_name(&err.inner_type_ts)),
            ))
        }
        (kind, return_type) => bail!(
            "Explorer internal mismatch for method `{}`: kind {:?} does not match return type {:?}",
            method.name,
            kind,
            return_type
        ),
    }
}

fn explorer_types(
    api: &ApiDefinition,
    wrappers: &HashMap<String, VersionedWrapper>,
    target_version: u32,
) -> Result<Vec<ExplorerTypeRecord>> {
    let visible = explorer_visible_type_names(api, wrappers, target_version)?;
    let emit_versions = versioned_wrapper_emit_versions(api, wrappers, target_version)?;
    let aliases = selected_public_aliases(api, wrappers, &emit_versions, target_version);
    let mut types = Vec::new();
    for ty in &api.types {
        if !visible.contains(&ty.name) {
            continue;
        }
        if version_prefixed_type(&ty.name).is_some() && !aliases.contains_key(&ty.name) {
            continue;
        }
        if should_rename_wire_wrapper(ty, &emit_versions, &aliases) {
            continue;
        }
        types.push(explorer_type_record(ty, target_version, &aliases)?);
    }
    types.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(types)
}

fn explorer_visible_type_names(
    api: &ApiDefinition,
    wrappers: &HashMap<String, VersionedWrapper>,
    target_version: u32,
) -> Result<BTreeSet<String>> {
    let mut names = BTreeSet::new();
    for trait_def in explorer_traits(api) {
        for method in included_methods(trait_def, wrappers, target_version)? {
            let wire_version = method_wire_version(method, wrappers, target_version)?;
            for param in &method.params {
                collect_explorer_type_ref(&param.type_ref, wrappers, wire_version, &mut names);
            }
            match &method.return_type {
                ReturnType::Result { ok, err } => {
                    collect_explorer_type_ref(ok, wrappers, wire_version, &mut names);
                    collect_explorer_type_ref(
                        call_error_inner(err).unwrap_or(err),
                        wrappers,
                        wire_version,
                        &mut names,
                    );
                }
                ReturnType::Subscription(item) => {
                    collect_explorer_type_ref(item, wrappers, wire_version, &mut names);
                }
                ReturnType::ResultSubscription { item, err } => {
                    collect_explorer_type_ref(item, wrappers, wire_version, &mut names);
                    collect_explorer_type_ref(
                        call_error_inner(err).unwrap_or(err),
                        wrappers,
                        wire_version,
                        &mut names,
                    );
                }
            }
        }
    }

    loop {
        let before = names.len();
        for ty in &api.types {
            if names.contains(&ty.name) {
                collect_explorer_type_def_refs(ty, wrappers, target_version, &mut names);
            }
        }
        if names.len() == before {
            break;
        }
    }

    Ok(names)
}

fn collect_explorer_type_def_refs(
    ty: &TypeDef,
    wrappers: &HashMap<String, VersionedWrapper>,
    target_version: u32,
    names: &mut BTreeSet<String>,
) {
    match &ty.kind {
        TypeDefKind::Alias(type_ref) => {
            collect_explorer_type_ref(type_ref, wrappers, None, names);
        }
        TypeDefKind::Struct(fields) => {
            for field in fields {
                collect_explorer_type_ref(&field.type_ref, wrappers, None, names);
            }
        }
        TypeDefKind::TupleStruct(items) => {
            for item in items {
                collect_explorer_type_ref(item, wrappers, None, names);
            }
        }
        TypeDefKind::Enum(variants) => {
            for variant in variants {
                if version_number(&variant.name).is_some_and(|version| version > target_version) {
                    continue;
                }
                match &variant.fields {
                    VariantFields::Unit => {}
                    VariantFields::Unnamed(items) => {
                        for item in items {
                            collect_explorer_type_ref(item, wrappers, None, names);
                        }
                    }
                    VariantFields::Named(fields) => {
                        for field in fields {
                            collect_explorer_type_ref(&field.type_ref, wrappers, None, names);
                        }
                    }
                }
            }
        }
    }
}

fn collect_explorer_type_ref(
    ty: &TypeRef,
    wrappers: &HashMap<String, VersionedWrapper>,
    wire_version: Option<u32>,
    names: &mut BTreeSet<String>,
) {
    match ty {
        TypeRef::Named { name, args } => {
            names.insert(name.clone());
            if args.is_empty() {
                if let Some(wrapper) = wrappers.get(name) {
                    let versions = match wire_version {
                        Some(version) => vec![version],
                        None => wrapper.variants.keys().copied().collect::<Vec<_>>(),
                    };
                    for version in versions {
                        if let Some(variant) = wrapper.variants.get(&version) {
                            if let VersionedKind::Tuple(inner) = &variant.kind {
                                collect_explorer_type_ref(inner, wrappers, None, names);
                            }
                        }
                    }
                }
            }
            for arg in args {
                collect_explorer_type_ref(arg, wrappers, None, names);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_explorer_type_ref(inner, wrappers, None, names);
        }
        TypeRef::Tuple(items) => {
            for item in items {
                collect_explorer_type_ref(item, wrappers, None, names);
            }
        }
        TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => {}
    }
}

fn explorer_type_record(
    ty: &TypeDef,
    target_version: u32,
    aliases: &BTreeMap<String, String>,
) -> Result<ExplorerTypeRecord> {
    let display_name = aliases
        .get(&ty.name)
        .map(String::as_str)
        .unwrap_or(&ty.name);
    let mut fields = Vec::new();
    let mut variants = Vec::new();
    match &ty.kind {
        TypeDefKind::Struct(items) => {
            for field in items {
                let (name, optional) = ts_field_name(&field.name, &field.type_ref);
                fields.push(ExplorerFieldRecord {
                    name,
                    ty: if optional {
                        ts_inner_option(&field.type_ref)?
                    } else {
                        ts_type(&field.type_ref)?
                    },
                    description: clean_explorer_docs(field.docs.as_deref()),
                });
            }
        }
        TypeDefKind::Enum(items) => {
            for variant in items {
                let include_variant =
                    version_number(&variant.name).is_none_or(|version| version <= target_version);
                if !include_variant {
                    continue;
                }
                variants.push(ExplorerVariantRecord {
                    name: variant.name.clone(),
                    ty: variant_value_type(&variant.fields)?,
                    description: clean_explorer_docs(variant.docs.as_deref()),
                });
            }
        }
        TypeDefKind::Alias(_) | TypeDefKind::TupleStruct(_) => {}
    }

    Ok(ExplorerTypeRecord {
        id: display_name.to_string(),
        name: display_name.to_string(),
        category: explorer_type_category(ty).to_string(),
        definition: explorer_type_definition(ty, target_version, display_name)?,
        description: clean_explorer_docs(ty.docs.as_deref()),
        source: explorer_type_source(&ty.name),
        fields,
        variants,
    })
}

fn explorer_type_definition(
    ty: &TypeDef,
    target_version: u32,
    display_name: &str,
) -> Result<String> {
    let generic_decl = generic_param_declaration(&ty.generic_params);
    match &ty.kind {
        TypeDefKind::Alias(type_ref) => Ok(format!(
            "type {}{} = {}",
            display_name,
            generic_decl,
            ts_type(type_ref)?
        )),
        TypeDefKind::Struct(fields) => Ok(format!(
            "interface {}{} {{ {} }}",
            display_name,
            generic_decl,
            fields
                .iter()
                .map(|field| {
                    let (name, optional) = ts_field_name(&field.name, &field.type_ref);
                    if optional {
                        Ok(format!("{}?: {}", name, ts_inner_option(&field.type_ref)?))
                    } else {
                        Ok(format!("{}: {}", name, ts_type(&field.type_ref)?))
                    }
                })
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        )),
        TypeDefKind::TupleStruct(types) => Ok(format!(
            "type {}{} = {}",
            display_name,
            generic_decl,
            unnamed_fields_type(types)?
        )),
        TypeDefKind::Enum(variants) if is_unit_only_enum(ty) => Ok(format!(
            "type {}{} = {}",
            display_name,
            generic_decl,
            unit_enum_union_type(variants)?
        )),
        TypeDefKind::Enum(variants) => {
            let rendered = variants
                .iter()
                .filter(|variant| {
                    version_number(&variant.name).is_none_or(|version| version <= target_version)
                })
                .map(|variant| {
                    Ok(format!(
                        "{{ tag: \"{}\"; value: {} }}",
                        variant.name,
                        variant_value_type(&variant.fields)?
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join(" | ");
            Ok(format!("type {display_name}{generic_decl} = {rendered}"))
        }
    }
}

fn explorer_type_category(ty: &TypeDef) -> &'static str {
    match &ty.kind {
        TypeDefKind::Alias(_) => "alias",
        TypeDefKind::Struct(_) => "struct",
        TypeDefKind::TupleStruct(_) => "tuple",
        TypeDefKind::Enum(variants)
            if !variants.is_empty()
                && variants.iter().all(|v| is_versioned_variant_name(&v.name)) =>
        {
            "versioned"
        }
        TypeDefKind::Enum(_) => "enum",
    }
}

fn explorer_type_source(name: &str) -> String {
    if name.starts_with("V01") {
        "v0.1".to_string()
    } else if name.starts_with("V02") {
        "v0.2".to_string()
    } else {
        "shared".to_string()
    }
}

fn clean_explorer_docs(docs: Option<&str>) -> Option<String> {
    docs.map(strip_playground_doc_blocks)
        .filter(|docs| !docs.is_empty())
}

fn explorer_traits(api: &ApiDefinition) -> Vec<&TraitDef> {
    let mut traits: Vec<&TraitDef> = api
        .traits
        .iter()
        .filter(|trait_def| service_order(&trait_def.name).is_some())
        .collect();
    traits.sort_by_key(|trait_def| {
        (
            service_order(&trait_def.name).unwrap_or(usize::MAX),
            trait_def.name.as_str(),
        )
    });
    traits
}

fn write_explorer_groups_array(out: &mut String, indent: &str, groups: &[ExplorerGroupRecord]) {
    writeln!(out, "{indent}groups: [").unwrap();
    for group in groups {
        writeln!(out, "{indent}  {{").unwrap();
        writeln!(out, "{}    id: {},", indent, ts_string_literal(&group.id)).unwrap();
        writeln!(
            out,
            "{}    name: {},",
            indent,
            ts_string_literal(&group.name)
        )
        .unwrap();
        if let Some(description) = &group.description {
            writeln!(
                out,
                "{}    description: {},",
                indent,
                ts_string_literal(description)
            )
            .unwrap();
        }
        writeln!(out, "{indent}    methods: [").unwrap();
        for method in &group.methods {
            writeln!(out, "{}      {},", indent, ts_string_literal(method)).unwrap();
        }
        writeln!(out, "{indent}    ],").unwrap();
        writeln!(out, "{indent}  }},").unwrap();
    }
    writeln!(out, "{indent}],").unwrap();
}

fn write_explorer_methods_array(out: &mut String, indent: &str, methods: &[ExplorerMethodRecord]) {
    writeln!(out, "{indent}methods: [").unwrap();
    for method in methods {
        writeln!(out, "{indent}  {{").unwrap();
        writeln!(out, "{}    id: {},", indent, ts_string_literal(&method.id)).unwrap();
        writeln!(
            out,
            "{}    name: {},",
            indent,
            ts_string_literal(&method.name)
        )
        .unwrap();
        writeln!(
            out,
            "{}    groupId: {},",
            indent,
            ts_string_literal(&method.group_id)
        )
        .unwrap();
        writeln!(
            out,
            "{}    groupName: {},",
            indent,
            ts_string_literal(&method.group_name)
        )
        .unwrap();
        writeln!(out, "{}    wireId: {},", indent, method.wire_id).unwrap();
        writeln!(
            out,
            "{}    pattern: {},",
            indent,
            ts_string_literal(method.pattern)
        )
        .unwrap();
        writeln!(
            out,
            "{}    request: {},",
            indent,
            ts_string_literal(&method.request)
        )
        .unwrap();
        writeln!(
            out,
            "{}    response: {},",
            indent,
            ts_string_literal(&method.response)
        )
        .unwrap();
        if let Some(error_type) = &method.error_type {
            writeln!(
                out,
                "{}    errorType: {},",
                indent,
                ts_string_literal(error_type)
            )
            .unwrap();
        }
        if let Some(description) = &method.description {
            writeln!(
                out,
                "{}    description: {},",
                indent,
                ts_string_literal(description)
            )
            .unwrap();
        }
        if let Some(client_example) = &method.client_example {
            writeln!(
                out,
                "{}    usageExample: {},",
                indent,
                ts_string_literal(client_example)
            )
            .unwrap();
        }
        writeln!(out, "{indent}  }},").unwrap();
    }
    writeln!(out, "{indent}],").unwrap();
}

fn write_explorer_types_array(out: &mut String, indent: &str, types: &[ExplorerTypeRecord]) {
    writeln!(out, "{indent}dataTypes: [").unwrap();
    for ty in types {
        writeln!(out, "{indent}  {{").unwrap();
        writeln!(out, "{}    id: {},", indent, ts_string_literal(&ty.id)).unwrap();
        writeln!(out, "{}    name: {},", indent, ts_string_literal(&ty.name)).unwrap();
        writeln!(
            out,
            "{}    category: {},",
            indent,
            ts_string_literal(&ty.category)
        )
        .unwrap();
        writeln!(
            out,
            "{}    definition: {},",
            indent,
            ts_string_literal(&ty.definition)
        )
        .unwrap();
        if let Some(description) = &ty.description {
            writeln!(
                out,
                "{}    description: {},",
                indent,
                ts_string_literal(description)
            )
            .unwrap();
        }
        writeln!(
            out,
            "{}    source: {},",
            indent,
            ts_string_literal(&ty.source)
        )
        .unwrap();
        if !ty.fields.is_empty() {
            writeln!(out, "{indent}    fields: [").unwrap();
            for field in &ty.fields {
                writeln!(out, "{indent}      {{").unwrap();
                writeln!(
                    out,
                    "{}        name: {},",
                    indent,
                    ts_string_literal(&field.name)
                )
                .unwrap();
                writeln!(
                    out,
                    "{}        type: {},",
                    indent,
                    ts_string_literal(&field.ty)
                )
                .unwrap();
                if let Some(description) = &field.description {
                    writeln!(
                        out,
                        "{}        description: {},",
                        indent,
                        ts_string_literal(description)
                    )
                    .unwrap();
                }
                writeln!(out, "{indent}      }},").unwrap();
            }
            writeln!(out, "{indent}    ],").unwrap();
        }
        if !ty.variants.is_empty() {
            writeln!(out, "{indent}    variants: [").unwrap();
            for variant in &ty.variants {
                writeln!(out, "{indent}      {{").unwrap();
                writeln!(
                    out,
                    "{}        name: {},",
                    indent,
                    ts_string_literal(&variant.name)
                )
                .unwrap();
                writeln!(
                    out,
                    "{}        type: {},",
                    indent,
                    ts_string_literal(&variant.ty)
                )
                .unwrap();
                if let Some(description) = &variant.description {
                    writeln!(
                        out,
                        "{}        description: {},",
                        indent,
                        ts_string_literal(description)
                    )
                    .unwrap();
                }
                writeln!(out, "{indent}      }},").unwrap();
            }
            writeln!(out, "{indent}    ],").unwrap();
        }
        writeln!(out, "{indent}  }},").unwrap();
    }
    writeln!(out, "{indent}],").unwrap();
}

fn protocol_minor(version: u32) -> String {
    format!("0.{version}")
}

fn explorer_group_id(name: &str) -> String {
    to_kebab_case(&service_name(name))
}

fn to_kebab_case(value: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            prev_dash = false;
        } else if !prev_dash && !out.is_empty() {
            out.push('-');
            prev_dash = true;
        }
    }
    if out.ends_with('-') {
        out.pop();
    }
    out
}
