//! Emit the typed `HostCallbacks` TypeScript surface from a parsed
//! `truapi-platform` rustdoc tree.
//!
//! One TS interface per Rust capability trait, plus a composite
//! `HostCallbacks` super-interface that mirrors the `Platform: A + B + ...`
//! super-trait so consumers can implement capabilities piecemeal. Named
//! types in trait signatures (e.g. `HostDevicePermissionRequest`) resolve
//! against `@parity/truapi`, the canonical typed client surface.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::{Result, bail};

use crate::platform::{
    PlatformDefinition, PlatformInner, PlatformMethod, PlatformReturn, PlatformTrait,
};
use crate::rustdoc::TypeRef;

/// Write the typed host-callbacks TS file into `output_dir`.
pub fn generate(definition: &PlatformDefinition, output_dir: &str) -> Result<()> {
    fs::create_dir_all(output_dir)?;
    let body = emit_host_callbacks(definition)?;
    fs::write(Path::new(output_dir).join("host-callbacks.ts"), body)?;
    Ok(())
}

fn emit_host_callbacks(definition: &PlatformDefinition) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "// Auto-generated by truapi-codegen. Do not edit.\n//\n\
        // Typed host-callbacks surface derived from the `truapi-platform`\n\
        // capability traits. One interface per Rust trait + a composite\n\
        // `HostCallbacks` interface that mirrors the `Platform` super-trait.\n"
    )
    .unwrap();

    let imports = collect_named_types(definition);
    if !imports.is_empty() {
        writeln!(out, "import type {{").unwrap();
        for name in &imports {
            writeln!(out, "  {name},").unwrap();
        }
        writeln!(out, "}} from \"@parity/truapi\";\n").unwrap();
    }

    for trait_def in &definition.traits {
        emit_trait_interface(&mut out, trait_def)?;
        writeln!(out).unwrap();
    }

    // The Rust super-trait `Platform` becomes `HostCallbacks` on the TS
    // surface: that is the name every host implementer reaches for, and
    // it stays stable even if the Rust trait is renamed.
    if let Some(super_trait) = &definition.super_trait {
        emit_super_interface(
            &mut out,
            "HostCallbacks",
            &super_trait.composes,
            super_trait.docs.as_deref(),
        );
    } else {
        let names: Vec<String> = definition.traits.iter().map(|t| t.name.clone()).collect();
        emit_super_interface(&mut out, "HostCallbacks", &names, None);
    }

    Ok(out)
}

fn emit_trait_interface(out: &mut String, trait_def: &PlatformTrait) -> Result<()> {
    write_jsdoc(out, "", trait_def.docs.as_deref());
    writeln!(out, "export interface {} {{", trait_def.name).unwrap();
    for (idx, method) in trait_def.methods.iter().enumerate() {
        if idx > 0 {
            writeln!(out).unwrap();
        }
        emit_method(out, method)?;
    }
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn emit_method(out: &mut String, method: &PlatformMethod) -> Result<()> {
    write_jsdoc(out, "  ", method.docs.as_deref());
    let params = method
        .params
        .iter()
        .map(|p| {
            let ts = ts_type(&p.type_ref)?;
            Ok(format!("{}: {ts}", to_camel_case(&p.name)))
        })
        .collect::<Result<Vec<_>>>()?
        .join(", ");
    let ret = format_return(&method.return_shape)?;
    writeln!(out, "  {}({params}): {ret};", to_camel_case(&method.name)).unwrap();
    Ok(())
}

fn emit_super_interface(out: &mut String, name: &str, composes: &[String], docs: Option<&str>) {
    write_jsdoc(out, "", docs);
    if composes.is_empty() {
        writeln!(out, "export interface {name} {{}}").unwrap();
        return;
    }
    let extends = composes.join(", ");
    writeln!(out, "export interface {name} extends {extends} {{}}").unwrap();
}

fn collect_named_types(definition: &PlatformDefinition) -> BTreeSet<String> {
    let mut out: BTreeSet<String> = BTreeSet::new();
    for trait_def in &definition.traits {
        for method in &trait_def.methods {
            for param in &method.params {
                collect_from_type(&param.type_ref, &mut out);
            }
            match &method.return_shape.inner {
                // Err type is not part of the TS signature (errors throw),
                // so don't import its name.
                PlatformInner::Result { ok, .. } => collect_from_type(ok, &mut out),
                PlatformInner::Stream(inner) => collect_from_type(inner, &mut out),
                PlatformInner::Plain(inner) => collect_from_type(inner, &mut out),
                PlatformInner::TraitObject(_) | PlatformInner::Unit => {}
            }
        }
    }
    // Filter out names defined locally (the capability trait interfaces).
    let local: BTreeSet<String> = definition.traits.iter().map(|t| t.name.clone()).collect();
    out.into_iter().filter(|n| !local.contains(n)).collect()
}

fn collect_from_type(ty: &TypeRef, out: &mut BTreeSet<String>) {
    match ty {
        TypeRef::Named { name, args } => {
            out.insert(name.clone());
            for arg in args {
                collect_from_type(arg, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_from_type(inner, out)
        }
        TypeRef::Tuple(items) => {
            for item in items {
                collect_from_type(item, out);
            }
        }
        TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => {}
    }
}

fn format_return(ret: &PlatformReturn) -> Result<String> {
    let inner = match &ret.inner {
        PlatformInner::Unit => "void".to_string(),
        PlatformInner::Result { ok, .. } => ts_type(ok)?,
        PlatformInner::Stream(item) => format!("AsyncIterable<{}>", ts_type(item)?),
        PlatformInner::TraitObject(name) => name.clone(),
        PlatformInner::Plain(ty) => ts_type(ty)?,
    };
    if ret.is_async {
        Ok(format!("Promise<{inner}>"))
    } else {
        Ok(inner)
    }
}

fn ts_type(ty: &TypeRef) -> Result<String> {
    match ty {
        TypeRef::Primitive(name) => match name.as_str() {
            "bool" => Ok("boolean".to_string()),
            "u8" | "u16" | "u32" | "i8" | "i16" | "i32" | "f32" | "f64" => Ok("number".to_string()),
            "u64" | "u128" | "i64" | "i128" => Ok("bigint".to_string()),
            "str" => Ok("string".to_string()),
            _ => bail!("Unsupported primitive type `{name}` in host callbacks generation"),
        },
        TypeRef::Named { name, args } => {
            if args.is_empty() {
                Ok(name.clone())
            } else {
                let rendered = args
                    .iter()
                    .map(ts_type)
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("{name}<{rendered}>"))
            }
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type(inner)?)),
        },
        TypeRef::Option(inner) => Ok(format!("{} | undefined", ts_type(inner)?)),
        TypeRef::Tuple(items) => {
            if items.is_empty() {
                Ok("void".to_string())
            } else {
                let rendered = items
                    .iter()
                    .map(ts_type)
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("[{rendered}]"))
            }
        }
        TypeRef::Array(inner, _len) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type(inner)?)),
        },
        TypeRef::Generic(name) => Ok(name.clone()),
        TypeRef::Unit => Ok("void".to_string()),
    }
}

fn write_jsdoc(out: &mut String, indent: &str, docs: Option<&str>) {
    let Some(docs) = docs else {
        return;
    };
    let docs = docs.trim();
    if docs.is_empty() {
        return;
    }
    writeln!(out, "{indent}/**").unwrap();
    for line in docs.lines() {
        if line.is_empty() {
            writeln!(out, "{indent} *").unwrap();
        } else {
            writeln!(out, "{indent} * {line}").unwrap();
        }
    }
    writeln!(out, "{indent} */").unwrap();
}

fn to_camel_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = false;
    for (idx, ch) in name.chars().enumerate() {
        if ch == '_' {
            upper_next = idx != 0;
            continue;
        }
        if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}
