//! Emit the typed `HostCallbacks` TypeScript surface from a parsed
//! `truapi-platform` rustdoc tree.
//!
//! One TS interface per Rust capability trait, plus a composite
//! `HostCallbacks` super-interface that mirrors the `Platform: A + B + ...`
//! super-trait so consumers can implement capabilities piecemeal. Named
//! types in trait signatures (e.g. `HostDevicePermissionRequest`) resolve
//! against `@parity/truapi`, the canonical typed client surface.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::{Result, bail};
use indoc::{formatdoc, writedoc};

use crate::platform::{
    PlatformDefinition, PlatformInner, PlatformMethod, PlatformParam, PlatformReturn, PlatformTrait,
};
use crate::rustdoc::{FieldDef, TypeDef, TypeDefKind, TypeRef, VariantDef, VariantFields};

/// Write the typed host-callbacks TS file and its WASM adapter into
/// `output_dir`. `codec_types` is the set of `@parity/truapi` type names that
/// carry a SCALE codec (structs and enums, not primitive aliases); the adapter
/// crosses those as bytes and passes everything else through unchanged.
pub fn generate(
    definition: &PlatformDefinition,
    codec_types: &BTreeSet<String>,
    output_dir: &str,
) -> Result<()> {
    fs::create_dir_all(output_dir)?;
    let body = emit_host_callbacks(definition)?;
    fs::write(Path::new(output_dir).join("host-callbacks.ts"), body)?;
    let adapter = emit_wasm_adapter(definition, codec_types)?;
    fs::write(
        Path::new(output_dir).join("host-callbacks-adapter.ts"),
        adapter,
    )?;
    Ok(())
}

fn emit_host_callbacks(definition: &PlatformDefinition) -> Result<String> {
    let mut out = String::new();
    writedoc!(
        out,
        r#"
        // Auto-generated by truapi-codegen. Do not edit.
        //
        // Typed host-callbacks surface derived from the `truapi-platform`
        // capability traits. One interface per Rust trait + a composite
        // `HostCallbacks` interface that mirrors the `Platform` super-trait.

        "#,
    )
    .unwrap();

    let imports = collect_named_types(definition);
    if !imports.is_empty() {
        let entries = imports
            .iter()
            .map(|name| format!("  {name},"))
            .collect::<Vec<_>>()
            .join("\n");
        writedoc!(
            out,
            r#"
            import type {{
            {entries}
            }} from "@parity/truapi";

            "#,
        )
        .unwrap();
    }

    for type_def in &definition.types {
        let rendered = match &type_def.kind {
            TypeDefKind::Enum(_) => emit_enum_type(type_def)?,
            _ => emit_struct_interface(type_def)?,
        };
        out.push_str(&rendered);
        out.push('\n');
    }

    for trait_def in &definition.traits {
        out.push_str(&emit_trait_interface(trait_def)?);
        out.push('\n');
    }

    // The Rust super-trait `Platform` becomes `HostCallbacks` on the TS
    // surface: that is the name every host implementer reaches for, and
    // it stays stable even if the Rust trait is renamed.
    let (composes, docs): (Vec<String>, Option<&str>) = match &definition.super_trait {
        Some(s) => (s.composes.clone(), s.docs.as_deref()),
        None => (
            definition.traits.iter().map(|t| t.name.clone()).collect(),
            None,
        ),
    };
    out.push_str(&emit_super_interface("HostCallbacks", &composes, docs));

    Ok(out)
}

/// Emit the `createWasmRawCallbacks` adapter that maps the typed
/// `HostCallbacks` surface onto the byte-oriented surface the WASM core
/// invokes. Named wire types cross as SCALE bytes (`.enc`/`.dec`); strings,
/// primitives, byte blobs and platform-local types (`AuthState`) pass through
/// unchanged. `ChainProvider` is delegated to the hand-written
/// `chainConnectAdapter` since its connection handle is bespoke.
fn emit_wasm_adapter(
    definition: &PlatformDefinition,
    codec_types: &BTreeSet<String>,
) -> Result<String> {
    // Only the capability traits the `Platform` super-trait composes are host
    // callbacks; returned handles like `JsonRpcConnection` are not.
    let composed: BTreeSet<String> = match &definition.super_trait {
        Some(s) => s.composes.iter().cloned().collect(),
        None => definition.traits.iter().map(|t| t.name.clone()).collect(),
    };
    let traits: Vec<&PlatformTrait> = definition
        .traits
        .iter()
        .filter(|t| composed.contains(&t.name))
        .collect();

    // Local types are emitted in `host-callbacks.ts` (e.g. `AuthState`); codec
    // types carry SCALE codecs and are imported as values for `.enc`/`.dec`.
    // Anything else named in a signature (e.g. the `NotificationId` alias) is a
    // non-codec `@parity/truapi` type the `RawCallbacks` interface imports for
    // its type only.
    let local: BTreeSet<String> = definition
        .traits
        .iter()
        .map(|t| t.name.clone())
        .chain(definition.types.iter().map(|s| s.name.clone()))
        .collect();
    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut extra_types: BTreeSet<String> = BTreeSet::new();
    for trait_def in &traits {
        for method in &trait_def.methods {
            for param in &method.params {
                collect_codec_imports(&param.type_ref, codec_types, &mut imports);
                collect_extra_named(&param.type_ref, codec_types, &local, &mut extra_types);
            }
            match &method.return_shape.inner {
                PlatformInner::Result { ok, .. } | PlatformInner::Plain(ok) => {
                    collect_codec_imports(ok, codec_types, &mut imports);
                    collect_extra_named(ok, codec_types, &local, &mut extra_types);
                }
                PlatformInner::Stream(item) => {
                    collect_codec_imports(stream_item(item), codec_types, &mut imports)
                }
                PlatformInner::Unit | PlatformInner::TraitObject(_) => {}
            }
        }
    }

    let mut out = String::new();
    writedoc!(
        out,
        r#"
        // Auto-generated by truapi-codegen. Do not edit.
        //
        // Adapts the typed `HostCallbacks` surface onto the byte-oriented
        // callback surface the WASM core invokes. Named wire types cross as
        // SCALE bytes (`.enc`/`.dec`); strings, primitives, byte blobs and
        // platform-local types pass through unchanged.

        "#,
    )
    .unwrap();
    if !imports.is_empty() {
        let entries = imports
            .iter()
            .map(|name| format!("  {name},"))
            .collect::<Vec<_>>()
            .join("\n");
        writedoc!(
            out,
            r#"
            import {{
            {entries}
            }} from "@parity/truapi";
            "#,
        )
        .unwrap();
    }
    if !extra_types.is_empty() {
        let entries = extra_types
            .iter()
            .map(|name| format!("  {name},"))
            .collect::<Vec<_>>()
            .join("\n");
        writedoc!(
            out,
            r#"
            import type {{
            {entries}
            }} from "@parity/truapi";
            "#,
        )
        .unwrap();
    }
    writedoc!(
        out,
        r#"
        import type {{ AuthState, HostCallbacks }} from "./host-callbacks.js";
        import type {{ ChainConnect }} from "../runtime.js";
        import {{
          chainConnectAdapter,
          createUnavailableCallbacks,
          driveResultStream,
        }} from "../adapter-support.js";

        "#,
    )
    .unwrap();
    out.push_str(&emit_raw_callbacks(&traits, codec_types));
    writedoc!(
        out,
        r#"
        /** Adapt typed host callbacks into the raw SCALE callback surface the
         *  WASM core invokes. Applied internally by `createWasmProvider`. */
        export function createWasmRawCallbacks(
          host: Partial<HostCallbacks>,
        ): RawCallbacks {{
          const unavailable = createUnavailableCallbacks();
          return {{
            ...unavailable,
        "#,
    )
    .unwrap();
    for trait_def in &traits {
        if trait_def.name == "ChainProvider" {
            writeln!(out, "    chainConnect: chainConnectAdapter(host),").unwrap();
            continue;
        }
        for method in &trait_def.methods {
            let entry = emit_adapter_entry(method, codec_types)?;
            writeln!(out, "    {entry}").unwrap();
        }
    }
    out.push_str("  };\n}\n");
    Ok(out)
}

/// Emit the `RawCallbacks` interface: the byte-oriented callback surface the
/// WASM core invokes (and `wasm.rs`'s `JsBridge` mirrors). Codec payloads cross
/// as `Uint8Array`, strings/primitives/blobs pass through, subscriptions take a
/// `sendItem` sink, and `chainConnect` is the bespoke optional handle.
fn emit_raw_callbacks(traits: &[&PlatformTrait], codec_types: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("export interface RawCallbacks {\n");
    for trait_def in traits {
        if trait_def.name == "ChainProvider" {
            continue;
        }
        for method in &trait_def.methods {
            out.push_str("  ");
            out.push_str(&raw_member(method, codec_types));
            out.push('\n');
        }
    }
    out.push_str("  chainConnect?: ChainConnect;\n");
    out.push_str("}\n");
    out
}

/// One `RawCallbacks` member signature for `method`.
fn raw_member(method: &PlatformMethod, codec_types: &BTreeSet<String>) -> String {
    let name = to_camel_case(&method.name);
    match &method.return_shape.inner {
        PlatformInner::Stream(_) => {
            let mut params: Vec<String> = method
                .params
                .iter()
                .map(|p| {
                    format!(
                        "{}: {}",
                        to_camel_case(&p.name),
                        raw_param_ts(&p.type_ref, codec_types)
                    )
                })
                .collect();
            params.push("sendItem: (item?: Uint8Array) => void".to_string());
            format!("{name}({}): (() => void) | void;", params.join(", "))
        }
        PlatformInner::TraitObject(_) => String::new(),
        inner => {
            let params = method
                .params
                .iter()
                .map(|p| {
                    format!(
                        "{}: {}",
                        to_camel_case(&p.name),
                        raw_param_ts(&p.type_ref, codec_types)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            let ok = match inner {
                PlatformInner::Result { ok, .. } | PlatformInner::Plain(ok) => {
                    raw_ok_ts(ok, codec_types)
                }
                _ => "void".to_string(),
            };
            // A synchronous (`!is_async`) callback is a fire-and-forget
            // notification (e.g. `authStateChanged`); everything else is async.
            if method.return_shape.is_async {
                format!("{name}({params}): Promise<{ok}>;")
            } else {
                format!("{name}({params}): {ok};")
            }
        }
    }
}

/// TS type for a `RawCallbacks` parameter under the byte boundary.
fn raw_param_ts(ty: &TypeRef, codec_types: &BTreeSet<String>) -> String {
    match ty {
        TypeRef::Named { name, .. } if codec_types.contains(name) => "Uint8Array".to_string(),
        TypeRef::Named { name, .. } => name.clone(),
        TypeRef::Vec(inner) | TypeRef::Array(inner, _) if matches!(inner.as_ref(), TypeRef::Primitive(p) if p == "u8") => {
            "Uint8Array".to_string()
        }
        TypeRef::Option(inner) => {
            format!("{} | null | undefined", raw_param_ts(inner, codec_types))
        }
        TypeRef::Primitive(p) => raw_primitive_ts(p),
        _ => "Uint8Array".to_string(),
    }
}

/// TS type for a `RawCallbacks` `Result` ok value under the byte boundary.
fn raw_ok_ts(ty: &TypeRef, codec_types: &BTreeSet<String>) -> String {
    match ty {
        TypeRef::Named { name, .. } if codec_types.contains(name) => "Uint8Array".to_string(),
        TypeRef::Named { name, .. } => name.clone(),
        TypeRef::Vec(inner) | TypeRef::Array(inner, _) if matches!(inner.as_ref(), TypeRef::Primitive(p) if p == "u8") => {
            "Uint8Array".to_string()
        }
        TypeRef::Option(inner) => format!("{} | null | undefined", raw_ok_ts(inner, codec_types)),
        TypeRef::Primitive(p) => raw_primitive_ts(p),
        TypeRef::Unit => "void".to_string(),
        TypeRef::Tuple(items) if items.is_empty() => "void".to_string(),
        _ => "Uint8Array".to_string(),
    }
}

fn raw_primitive_ts(p: &str) -> String {
    match p {
        "bool" => "boolean".to_string(),
        "str" => "string".to_string(),
        _ => "number".to_string(),
    }
}

/// Collect named types referenced by `ty` that are neither codec types nor
/// platform-local (e.g. the `NotificationId` alias), so the `RawCallbacks`
/// interface can import them from `@parity/truapi` for their type only.
fn collect_extra_named(
    ty: &TypeRef,
    codec_types: &BTreeSet<String>,
    local: &BTreeSet<String>,
    out: &mut BTreeSet<String>,
) {
    match ty {
        TypeRef::Named { name, args } => {
            if !codec_types.contains(name) && !local.contains(name) {
                out.insert(name.clone());
            }
            for arg in args {
                collect_extra_named(arg, codec_types, local, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_extra_named(inner, codec_types, local, out)
        }
        _ => {}
    }
}

/// Collect the `@parity/truapi` codec type names referenced by `ty` so the
/// adapter can import their `.enc`/`.dec`.
fn collect_codec_imports(ty: &TypeRef, codec_types: &BTreeSet<String>, out: &mut BTreeSet<String>) {
    match ty {
        TypeRef::Named { name, args } => {
            if codec_types.contains(name) {
                out.insert(name.clone());
            }
            for arg in args {
                collect_codec_imports(arg, codec_types, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_codec_imports(inner, codec_types, out)
        }
        _ => {}
    }
}

/// Unwrap a `Result<T, E>` stream item to its `T`; other item types pass
/// through. Streams carry `Result`s on the Rust side but `driveResultStream`
/// already unwraps them, so the adapter encodes the inner item type.
fn stream_item(item: &TypeRef) -> &TypeRef {
    if let TypeRef::Named { name, args } = item
        && name == "Result"
        && let Some(ok) = args.first()
    {
        return ok;
    }
    item
}

/// The call argument expression for one Rust param. Codec types arrive as
/// `Uint8Array` and are decoded; `u64`-family integers arrive as JS numbers and
/// are widened to `bigint`; everything else passes through. Arrow parameter
/// types are left to contextual inference from `RawCallbacks`, so only the
/// argument expression varies.
fn adapter_arg(param: &PlatformParam, codec_types: &BTreeSet<String>) -> String {
    let name = to_camel_case(&param.name);
    match &param.type_ref {
        TypeRef::Named { name: ty, .. } if codec_types.contains(ty) => {
            format!("{ty}.dec({name})")
        }
        TypeRef::Primitive(p) if matches!(p.as_str(), "u64" | "u128" | "i64" | "i128") => {
            format!("BigInt({name})")
        }
        _ => name,
    }
}

/// Comma-joined arrow parameter names for a method (excluding `sendItem`).
fn param_names(method: &PlatformMethod) -> String {
    method
        .params
        .iter()
        .map(|p| to_camel_case(&p.name))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Emit one entry of the adapter object literal for `method`: call the typed
/// host method when the host provides it, otherwise fall back to the
/// `createUnavailableCallbacks` default (which owns the absent-callback
/// semantics for every callback).
fn emit_adapter_entry(method: &PlatformMethod, codec_types: &BTreeSet<String>) -> Result<String> {
    let raw = to_camel_case(&method.name);
    let impl_expr = match &method.return_shape.inner {
        PlatformInner::Stream(item) => adapter_stream_impl(&raw, method, item, codec_types)?,
        PlatformInner::Result { ok, .. } => adapter_unary_impl(&raw, method, ok, codec_types)?,
        PlatformInner::Plain(ok) => adapter_unary_impl(&raw, method, ok, codec_types)?,
        PlatformInner::Unit => adapter_unary_impl(&raw, method, &TypeRef::Unit, codec_types)?,
        PlatformInner::TraitObject(_) => bail!("unexpected trait-object return on `{raw}`"),
    };
    Ok(format!(
        "{raw}: host.{raw} ? {impl_expr} : unavailable.{raw},"
    ))
}

/// The adapter implementation expression for a unary callback: decode codec
/// params, call the typed host method, SCALE-encode a codec result.
fn adapter_unary_impl(
    raw: &str,
    method: &PlatformMethod,
    ok: &TypeRef,
    codec_types: &BTreeSet<String>,
) -> Result<String> {
    let params = param_names(method);
    let args = method
        .params
        .iter()
        .map(|p| adapter_arg(p, codec_types))
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!("host.{raw}!({args})");
    let body = match ok {
        TypeRef::Named { name: ty, .. } if codec_types.contains(ty) => {
            format!("{ty}.enc(await {call})")
        }
        _ => format!("await {call}"),
    };
    Ok(format!("async ({params}) => {body}"))
}

/// The adapter implementation expression for a subscription callback: drive
/// the host's stream into `sendItem`, SCALE-encoding each codec item.
fn adapter_stream_impl(
    raw: &str,
    method: &PlatformMethod,
    item: &TypeRef,
    codec_types: &BTreeSet<String>,
) -> Result<String> {
    let args = method
        .params
        .iter()
        .map(|p| adapter_arg(p, codec_types))
        .collect::<Vec<_>>()
        .join(", ");
    let item_ty = stream_item(item);
    let is_unit = matches!(item_ty, TypeRef::Unit)
        || matches!(item_ty, TypeRef::Tuple(items) if items.is_empty());
    let item_expr = match item_ty {
        // Tick subscription: the item carries no value, so ignore it and emit
        // a bare tick to the core's sink.
        _ if is_unit => "() => sendItem()".to_string(),
        TypeRef::Named { name: ty, .. } if codec_types.contains(ty) => {
            format!("(item) => sendItem({ty}.enc(item))")
        }
        _ => "sendItem".to_string(),
    };
    let mut names: Vec<String> = method
        .params
        .iter()
        .map(|p| to_camel_case(&p.name))
        .collect();
    names.push("sendItem".to_string());
    let params = names.join(", ");
    let call = format!("host.{raw}!({args})");
    Ok(format!(
        "({params}) => driveResultStream({call}, {item_expr})"
    ))
}

fn emit_trait_interface(trait_def: &PlatformTrait) -> Result<String> {
    let jsdoc = render_jsdoc("", trait_def.docs.as_deref());
    let body = trait_def
        .methods
        .iter()
        .map(emit_method)
        .collect::<Result<Vec<_>>>()?
        .join("\n\n");
    Ok(formatdoc! {
        r#"
        {jsdoc}export interface {name} {{
        {body}
        }}
        "#,
        name = ts_local_name(&trait_def.name),
    })
}

fn emit_method(method: &PlatformMethod) -> Result<String> {
    let jsdoc = render_jsdoc("  ", method.docs.as_deref());
    let params = method
        .params
        .iter()
        .map(|p| {
            let ts = ts_type(&p.type_ref)?;
            Ok(format!("{}: {ts}", to_camel_case(&p.name)))
        })
        .collect::<Result<Vec<_>>>()?
        .join(", ");
    let ret = format_return(&method.return_shape)?;
    let name = to_camel_case(&method.name);
    // A Rust default body makes the method optional for host implementations.
    let optional = if method.has_default { "?" } else { "" };
    Ok(format!("{jsdoc}  {name}{optional}({params}): {ret};"))
}

/// Emit a TS interface for a local platform struct. `Option<T>` fields become
/// optional members so hosts receive plain objects with absent-when-`None`
/// properties.
fn emit_struct_interface(struct_def: &TypeDef) -> Result<String> {
    let TypeDefKind::Struct(fields) = &struct_def.kind else {
        bail!(
            "Platform struct `{}` must have named fields",
            struct_def.name
        );
    };
    if !struct_def.generic_params.is_empty() {
        bail!("Platform struct `{}` must not be generic", struct_def.name);
    }
    let jsdoc = render_jsdoc("", struct_def.docs.as_deref());
    let body = fields
        .iter()
        .map(|field| {
            let jsdoc = render_jsdoc("  ", field.docs.as_deref());
            let name = to_camel_case(&field.name);
            match &field.type_ref {
                TypeRef::Option(inner) => Ok(format!("{jsdoc}  {name}?: {};", ts_type(inner)?)),
                other => Ok(format!("{jsdoc}  {name}: {};", ts_type(other)?)),
            }
        })
        .collect::<Result<Vec<_>>>()?
        .join("\n\n");
    Ok(formatdoc! {
        r#"
        {jsdoc}export interface {name} {{
        {body}
        }}
        "#,
        name = struct_def.name,
    })
}

/// Emit a TS type for a local platform enum. Unit-only enums become string
/// literal unions; payload enums become `{ tag, value }` tagged unions
/// matching the `@parity/truapi` client convention.
fn emit_enum_type(enum_def: &TypeDef) -> Result<String> {
    let TypeDefKind::Enum(variants) = &enum_def.kind else {
        bail!("Platform enum `{}` must have variants", enum_def.name);
    };
    if !enum_def.generic_params.is_empty() {
        bail!("Platform enum `{}` must not be generic", enum_def.name);
    }
    let jsdoc = render_jsdoc("", enum_def.docs.as_deref());
    if variants
        .iter()
        .all(|variant| matches!(variant.fields, VariantFields::Unit))
    {
        let union = variants
            .iter()
            .map(|variant| format!("\"{}\"", variant.name))
            .collect::<Vec<_>>()
            .join(" | ");
        return Ok(format!(
            "{jsdoc}export type {name} = {union};\n",
            name = enum_def.name,
        ));
    }
    let mut body = String::new();
    for variant in variants {
        body.push_str(&render_jsdoc("  ", variant.docs.as_deref()));
        writeln!(body, "  | {}", enum_variant_type(variant)?).unwrap();
    }
    Ok(formatdoc! {
        r#"
        {jsdoc}export type {name} =
        {body};
        "#,
        name = enum_def.name,
        body = body.trim_end(),
    })
}

/// Render one enum variant as a `{ tag, value }` member. Unit variants mark
/// `value` optional so consumers can write `{ tag: "X" }`.
fn enum_variant_type(variant: &VariantDef) -> Result<String> {
    Ok(match &variant.fields {
        VariantFields::Unit => format!("{{ tag: \"{}\"; value?: undefined }}", variant.name),
        VariantFields::Unnamed(types) => format!(
            "{{ tag: \"{}\"; value: {} }}",
            variant.name,
            unnamed_variant_value_type(types)?
        ),
        VariantFields::Named(fields) => format!(
            "{{ tag: \"{}\"; value: {} }}",
            variant.name,
            inline_object_type(fields)?
        ),
    })
}

fn unnamed_variant_value_type(types: &[TypeRef]) -> Result<String> {
    match types {
        [single] => ts_type(single),
        many => {
            let rendered = many
                .iter()
                .map(ts_type)
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            Ok(format!("[{rendered}]"))
        }
    }
}

fn inline_object_type(fields: &[FieldDef]) -> Result<String> {
    let body = fields
        .iter()
        .map(|field| {
            let name = to_camel_case(&field.name);
            match &field.type_ref {
                TypeRef::Option(inner) => Ok(format!("{name}?: {}", ts_type(inner)?)),
                other => Ok(format!("{name}: {}", ts_type(other)?)),
            }
        })
        .collect::<Result<Vec<_>>>()?
        .join("; ");
    Ok(format!("{{ {body} }}"))
}

fn emit_super_interface(name: &str, composes: &[String], docs: Option<&str>) -> String {
    let jsdoc = render_jsdoc("", docs);
    if composes.is_empty() {
        return format!("{jsdoc}export interface {name} {{}}\n");
    }
    let extends = composes
        .iter()
        .map(|name| ts_local_name(name))
        .collect::<Vec<_>>()
        .join(", ");
    format!("{jsdoc}export interface {name} extends {extends} {{}}\n")
}

fn collect_named_types(definition: &PlatformDefinition) -> BTreeSet<String> {
    let mut out: BTreeSet<String> = BTreeSet::new();
    for trait_def in &definition.traits {
        for method in &trait_def.methods {
            for param in &method.params {
                collect_from_type(&param.type_ref, &mut out);
            }
            match &method.return_shape.inner {
                // Err type is not part of the TS signature (errors throw),
                // so don't import its name.
                PlatformInner::Result { ok, .. } => collect_from_type(ok, &mut out),
                PlatformInner::Stream(inner) => collect_from_type(inner, &mut out),
                PlatformInner::Plain(inner) => collect_from_type(inner, &mut out),
                // A trait object returns its bare trait name in the TS
                // signature; collect it so a non-local trait gets imported
                // rather than emitted as an undeclared name. Local traits are
                // filtered out below since their interfaces live in this file.
                PlatformInner::TraitObject(name) => {
                    out.insert(name.clone());
                }
                PlatformInner::Unit => {}
            }
        }
    }
    // Filter out names defined locally (the capability trait interfaces and
    // the platform struct/enum types emitted into this file).
    let local: BTreeSet<String> = definition
        .traits
        .iter()
        .map(|t| t.name.clone())
        .chain(definition.types.iter().map(|s| s.name.clone()))
        .collect();
    out.into_iter().filter(|n| !local.contains(n)).collect()
}

fn collect_from_type(ty: &TypeRef, out: &mut BTreeSet<String>) {
    match ty {
        TypeRef::Named { name, args } => {
            out.insert(name.clone());
            for arg in args {
                collect_from_type(arg, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_from_type(inner, out)
        }
        TypeRef::Tuple(items) => {
            for item in items {
                collect_from_type(item, out);
            }
        }
        TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => {}
    }
}

fn format_return(ret: &PlatformReturn) -> Result<String> {
    let inner = match &ret.inner {
        PlatformInner::Unit => "void".to_string(),
        PlatformInner::Result { ok, .. } => ts_type(ok)?,
        PlatformInner::Stream(item) => format!("AsyncIterable<{}>", ts_type(item)?),
        PlatformInner::TraitObject(name) => name.clone(),
        PlatformInner::Plain(ty) => ts_type(ty)?,
    };
    if ret.is_async {
        Ok(format!("Promise<{inner}>"))
    } else {
        Ok(inner)
    }
}

fn ts_type(ty: &TypeRef) -> Result<String> {
    match ty {
        TypeRef::Primitive(name) => match name.as_str() {
            "bool" => Ok("boolean".to_string()),
            "u8" | "u16" | "u32" | "i8" | "i16" | "i32" | "f32" | "f64" => Ok("number".to_string()),
            "u64" | "u128" | "i64" | "i128" => Ok("bigint".to_string()),
            "str" => Ok("string".to_string()),
            _ => bail!("Unsupported primitive type `{name}` in host callbacks generation"),
        },
        TypeRef::Named { name, args } => {
            if args.is_empty() {
                Ok(name.clone())
            } else {
                let rendered = args
                    .iter()
                    .map(ts_type)
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("{name}<{rendered}>"))
            }
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type(inner)?)),
        },
        TypeRef::Option(inner) => Ok(format!("{} | undefined", ts_type(inner)?)),
        TypeRef::Tuple(items) => {
            if items.is_empty() {
                Ok("void".to_string())
            } else {
                let rendered = items
                    .iter()
                    .map(ts_type)
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("[{rendered}]"))
            }
        }
        TypeRef::Array(inner, _len) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type(inner)?)),
        },
        TypeRef::Generic(name) => Ok(name.clone()),
        TypeRef::Unit => Ok("void".to_string()),
    }
}

fn ts_local_name(name: &str) -> String {
    match name {
        "Storage" => "HostStorage".to_string(),
        _ => name.to_string(),
    }
}

fn render_jsdoc(indent: &str, docs: Option<&str>) -> String {
    let Some(docs) = docs else {
        return String::new();
    };
    let docs = docs.trim();
    if docs.is_empty() {
        return String::new();
    }
    let body = docs
        .lines()
        .map(|line| {
            if line.is_empty() {
                format!("{indent} *")
            } else {
                format!("{indent} * {}", render_ts_doc_line(line))
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{indent}/**\n{body}\n{indent} */\n")
}

fn render_ts_doc_line(line: &str) -> String {
    line.replace("[`", "`")
        .replace("`]", "`")
        .replace("Ok(())", "success")
        .replace("None", "`undefined`")
}

fn to_camel_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = false;
    for (idx, ch) in name.chars().enumerate() {
        if ch == '_' {
            upper_next = idx != 0;
            continue;
        }
        if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}
