//! Emit the typed `HostCallbacks` TypeScript surface from a parsed
//! `truapi-platform` rustdoc tree.
//!
//! One TS interface per Rust capability trait, plus a composite
//! `HostCallbacks` super-interface that mirrors the `Platform: A + B + ...`
//! super-trait so consumers can implement capabilities piecemeal. Named
//! types in trait signatures (e.g. `HostDevicePermissionRequest`) resolve
//! against `@parity/truapi`, the canonical typed client surface.

use std::collections::BTreeSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::{Result, bail};
use indoc::{formatdoc, writedoc};

use crate::platform::{
    PlatformDefinition, PlatformInner, PlatformMethod, PlatformParam, PlatformReturn, PlatformTrait,
};
use crate::platform_callbacks::{
    callback_namespace, composed_traits, platform_trait_names, raw_callback_adapter_name,
    raw_callback_name, raw_callback_type_name, raw_callback_wire_name, stream_item, to_camel_case,
    trait_object_return_name,
};
use crate::rustdoc::{FieldDef, TypeDef, TypeDefKind, TypeRef, VariantDef, VariantFields};
use crate::ts::ts_string_literal;

/// Write the typed host-callbacks TS file and its WASM adapter/worker bridge.
///
/// `codec_types` is the set of `@parity/truapi` type names that carry a SCALE
/// codec (structs and enums, not primitive aliases); the adapter crosses those
/// as bytes and passes everything else through unchanged.
pub fn generate(
    definition: &PlatformDefinition,
    codec_types: &BTreeSet<String>,
    callbacks_output_dir: &str,
    adapter_output_dir: &str,
) -> Result<()> {
    fs::create_dir_all(callbacks_output_dir)?;
    fs::create_dir_all(adapter_output_dir)?;
    let local_codec_types = collect_local_bridge_payload_types(definition);
    let body = emit_host_callbacks(definition, codec_types, &local_codec_types)?;
    fs::write(
        Path::new(callbacks_output_dir).join("host-callbacks.ts"),
        body,
    )?;
    let adapter = emit_wasm_adapter(definition, codec_types, &local_codec_types)?;
    fs::write(
        Path::new(adapter_output_dir).join("host-callbacks-adapter.ts"),
        adapter,
    )?;
    let worker_callbacks = emit_worker_callbacks(definition, codec_types, &local_codec_types)?;
    fs::write(
        Path::new(adapter_output_dir).join("worker-callbacks.ts"),
        worker_callbacks,
    )?;
    Ok(())
}

/// Emit one `import`/`import type` block listing `names` (one per line) from
/// `module`. No-op when `names` is empty. Does not emit a trailing blank line.
fn emit_import_block(out: &mut String, type_only: bool, module: &str, names: &BTreeSet<String>) {
    if names.is_empty() {
        return;
    }
    let entries = names
        .iter()
        .map(|name| format!("  {name},"))
        .collect::<Vec<_>>()
        .join("\n");
    let keyword = if type_only { "import type" } else { "import" };
    writedoc!(
        out,
        r#"
        {keyword} {{
        {entries}
        }} from "{module}";
        "#,
    )
    .unwrap();
}

fn emit_host_callbacks(
    definition: &PlatformDefinition,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> Result<String> {
    let mut out = String::new();
    writedoc!(
        out,
        r#"
        // Auto-generated by truapi-codegen. Do not edit.
        //
        // Typed host-callbacks surface derived from the `truapi-platform`
        // capability traits. One interface per Rust trait + a composite
        // `HostCallbacks` interface that mirrors the `Platform` super-trait.

        "#,
    )
    .unwrap();

    let codec_imports = collect_local_codec_imports(definition, codec_types, local_codec_types);
    if !codec_imports.is_empty() || !local_codec_types.is_empty() {
        writedoc!(
            out,
            r#"
            import * as S from "@parity/truapi/scale";

            "#,
        )
        .unwrap();
    }
    if !codec_imports.is_empty() {
        emit_import_block(&mut out, false, "@parity/truapi", &codec_imports);
        out.push('\n');
    }

    let imports = collect_named_types(definition)
        .into_iter()
        .filter(|name| !codec_imports.contains(name))
        .collect::<BTreeSet<_>>();
    if !imports.is_empty() {
        emit_import_block(&mut out, true, "@parity/truapi", &imports);
        out.push('\n');
    }

    for type_def in &definition.types {
        let rendered = match &type_def.kind {
            TypeDefKind::Enum(_) => emit_enum_type(type_def)?,
            _ => emit_struct_interface(type_def)?,
        };
        out.push_str(&rendered);
        out.push('\n');
    }
    for type_def in definition
        .types
        .iter()
        .filter(|ty| local_codec_types.contains(&ty.name))
    {
        out.push_str(&emit_local_codec(type_def)?);
        out.push('\n');
    }

    for trait_def in &definition.traits {
        out.push_str(&emit_trait_interface(trait_def)?);
        out.push('\n');
    }

    // The Rust super-trait `Platform` becomes `HostCallbacks` on the TS
    // surface: that is the name every host implementer reaches for, and
    // it stays stable even if the Rust trait is renamed.
    let (composes, docs): (Vec<String>, Option<&str>) = match &definition.super_trait {
        Some(s) => (s.composes.clone(), s.docs.as_deref()),
        None => (
            definition.traits.iter().map(|t| t.name.clone()).collect(),
            None,
        ),
    };
    out.push_str(&emit_host_callback_composites(&composes, docs));

    Ok(out)
}

/// Emit the `createWasmRawCallbacks` adapter that maps the typed
/// `HostCallbacks` surface onto the byte-oriented surface the WASM core
/// invokes. Codec-backed wire and platform-local types cross as SCALE bytes
/// (`.enc`/`.dec`); strings, primitives and byte blobs pass through unchanged.
/// Trait-object returns are delegated to hand-written adapters whose names are
/// derived from the raw callback name.
fn emit_wasm_adapter(
    definition: &PlatformDefinition,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> Result<String> {
    // Only the capability traits the `Platform` super-trait composes are host
    // callbacks; returned handle traits are adapted separately.
    let traits = composed_traits(definition);
    let trait_names = platform_trait_names(definition);

    // Local types are emitted in `host-callbacks.ts` (e.g. `AuthState`); codec
    // types carry SCALE codecs and are imported as values for `.enc`/`.dec`.
    // Anything else named in a signature (e.g. the `NotificationId` alias) is a
    // non-codec `@parity/truapi` type the `RawCallbacks` interface imports for
    // its type only.
    let local = local_names(definition);
    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut extra_types: BTreeSet<String> = BTreeSet::new();
    let mut adapter_local_codec_types: BTreeSet<String> = BTreeSet::new();
    let mut runtime_types: BTreeSet<String> = BTreeSet::new();
    let mut support_imports: BTreeSet<String> = BTreeSet::new();
    for trait_def in &traits {
        for method in &trait_def.methods {
            for param in &method.params {
                collect_codec_imports(&param.type_ref, codec_types, &mut imports);
                collect_local_codec_names(
                    &param.type_ref,
                    local_codec_types,
                    &mut adapter_local_codec_types,
                );
                collect_extra_named(&param.type_ref, codec_types, &local, &mut extra_types);
            }
            if trait_object_return_name(method, &trait_names).is_some() {
                runtime_types.insert(raw_callback_type_name(trait_def, method, &trait_names));
                support_imports.insert(raw_callback_adapter_name(trait_def, method, &trait_names));
                continue;
            }
            match &method.return_shape.inner {
                PlatformInner::Result { ok, .. } | PlatformInner::Plain(ok) => {
                    collect_codec_imports(ok, codec_types, &mut imports);
                    collect_local_codec_names(
                        ok,
                        local_codec_types,
                        &mut adapter_local_codec_types,
                    );
                    collect_extra_named(ok, codec_types, &local, &mut extra_types);
                }
                PlatformInner::Stream(item) => {
                    support_imports.insert("driveResultStream".to_string());
                    extra_types.insert("GenericError".to_string());
                    collect_codec_imports(stream_item(item), codec_types, &mut imports);
                    collect_local_codec_names(
                        stream_item(item),
                        local_codec_types,
                        &mut adapter_local_codec_types,
                    );
                }
                PlatformInner::TraitObject(_) => {}
                PlatformInner::Unit => {}
            }
        }
    }

    let mut out = String::new();
    writedoc!(
        out,
        r#"
        // Auto-generated by truapi-codegen. Do not edit.
        //
        // Adapts the typed `HostCallbacks` surface onto the byte-oriented
        // callback surface the WASM core invokes. Codec-backed wire and
        // platform-local types cross as SCALE bytes (`.enc`/`.dec`); strings,
        // primitives and byte blobs pass through unchanged.

        "#,
    )
    .unwrap();
    emit_import_block(&mut out, false, "@parity/truapi", &imports);
    emit_import_block(&mut out, true, "@parity/truapi", &extra_types);
    emit_import_block(
        &mut out,
        false,
        "./host-callbacks.js",
        &adapter_local_codec_types,
    );
    writedoc!(
        out,
        r#"
        import type {{
          RequiredHostCallbacks,
        }} from "./host-callbacks.js";

        "#,
    )
    .unwrap();
    emit_import_block(&mut out, true, "../runtime.js", &runtime_types);
    emit_import_block(&mut out, false, "../adapter-support.js", &support_imports);
    if !runtime_types.is_empty() || !support_imports.is_empty() {
        out.push('\n');
    }
    out.push_str(&emit_raw_callbacks(
        &traits,
        codec_types,
        local_codec_types,
        &trait_names,
    ));
    writedoc!(
        out,
        r#"
        /** Adapt typed host callbacks into the raw SCALE callback surface the
         *  WASM core invokes. */
        export function createWasmRawCallbacks(
          callbacks: RequiredHostCallbacks,
        ): RawCallbacks {{
          return {{
        "#,
    )
    .unwrap();
    for trait_def in &traits {
        for method in &trait_def.methods {
            let entry = emit_adapter_entry(
                trait_def,
                method,
                codec_types,
                local_codec_types,
                &trait_names,
            )?;
            writeln!(out, "    {entry}").unwrap();
        }
    }
    out.push_str("  };\n}\n");
    Ok(out)
}

/// Emit the generated callback metadata/proxy used by the Web Worker bridge.
///
/// The lifecycle/transport pieces stay hand-written in `worker-runtime.ts` and
/// `create-worker-host-runtime.ts`; this file owns the mechanical callback
/// name, arity, host-hook installation and subscription metadata that already
/// exists in the parsed `truapi-platform` trait surface.
fn emit_worker_callbacks(
    definition: &PlatformDefinition,
    _codec_types: &BTreeSet<String>,
    _local_codec_types: &BTreeSet<String>,
) -> Result<String> {
    let traits = composed_traits(definition);
    let trait_names = platform_trait_names(definition);
    let mut callbacks = Vec::new();
    let mut subscriptions = Vec::new();
    let mut trait_object_callbacks = Vec::new();
    let mut runtime_types = BTreeSet::new();

    for trait_def in traits {
        for method in &trait_def.methods {
            if trait_object_return_name(method, &trait_names).is_some() {
                runtime_types.insert(raw_callback_type_name(trait_def, method, &trait_names));
                trait_object_callbacks.push((trait_def, method));
                continue;
            }
            match &method.return_shape.inner {
                PlatformInner::Stream(_) => subscriptions.push(method),
                PlatformInner::TraitObject(_) => {
                    unreachable!("trait-object callbacks are handled above")
                }
                _ => callbacks.push(method),
            }
        }
    }

    let mut out = String::new();
    writedoc!(
        out,
        r#"
        // Auto-generated by truapi-codegen. Do not edit.
        //
        // Worker-side metadata and proxy functions for the raw WASM callback
        // surface. The worker transport/lifecycle remains hand-written; this
        // file owns the callback names, host-hook arity, and
        // subscription payload shape derived from `truapi-platform`.

        import type {{ RawCallbacks }} from "./host-callbacks-adapter.js";
        import type {{ GenericError }} from "@parity/truapi";

        "#
    )
    .unwrap();
    emit_import_block(&mut out, true, "../runtime.js", &runtime_types);
    if !runtime_types.is_empty() {
        out.push('\n');
    }

    out.push_str(&const_name_array("CALLBACK_NAMES", &callbacks));
    out.push_str("export type CallbackName = typeof CALLBACK_NAMES[number];\n\n");
    out.push_str(&const_name_array("SUBSCRIPTION_NAMES", &subscriptions));
    out.push_str("export type SubscriptionName = typeof SUBSCRIPTION_NAMES[number];\n\n");

    out.push_str("export interface WorkerCallbackBridge {\n");
    out.push_str(
        "  callbackRequest(name: CallbackName, args: readonly unknown[]): Promise<unknown>;\n",
    );
    out.push_str("  startSubscription<T>(\n");
    out.push_str("    name: SubscriptionName,\n");
    out.push_str("    payload: Uint8Array | null,\n");
    out.push_str("    sendItem: (value: T) => void,\n");
    out.push_str("    sendError: (error: GenericError) => void,\n");
    out.push_str("  ): () => void;\n");
    for (trait_def, method) in &trait_object_callbacks {
        writeln!(
            out,
            "  {}: {};",
            raw_callback_wire_name(trait_def, method, &trait_names),
            raw_callback_type_name(trait_def, method, &trait_names)
        )
        .unwrap();
    }
    out.push_str("}\n\n");

    out.push_str(&emit_worker_callback_factory(
        "rawCallbacks",
        "CallbackName",
        &callbacks,
    )?);
    out.push('\n');
    out.push_str(&emit_worker_subscription_factory(&subscriptions)?);
    out.push('\n');

    writedoc!(
        out,
        r#"
        export function createWorkerRawCallbacks(
          bridge: WorkerCallbackBridge,
        ): Record<string, unknown> {{
          const callbacks: Record<string, unknown> = {{
            ...rawCallbacks(bridge),
            ...subscriptionRawCallbacks(bridge),
        "#
    )
    .unwrap();
    for (trait_def, method) in &trait_object_callbacks {
        let raw = raw_callback_wire_name(trait_def, method, &trait_names);
        writeln!(out, "    {raw}: bridge.{raw},").unwrap();
    }
    writedoc!(
        out,
        r#"
          }};
          return callbacks;
        }}

        export function startRawSubscription(
          callbacks: RawCallbacks,
          name: SubscriptionName,
          payload: Uint8Array | null,
          sendItem: (value?: unknown) => void,
          sendError: (error: GenericError) => void,
        ): (() => void) | void {{
        "#
    )
    .unwrap();
    out.push_str(&emit_start_raw_subscription_switch(&subscriptions)?);
    writedoc!(
        out,
        r#"
        }}
        "#
    )
    .unwrap();

    Ok(out)
}

/// All names defined locally in the platform crate: capability trait names plus
/// the struct/enum type names emitted into `host-callbacks.ts`.
fn local_names(definition: &PlatformDefinition) -> BTreeSet<String> {
    definition
        .traits
        .iter()
        .map(|t| t.name.clone())
        .chain(definition.types.iter().map(|s| s.name.clone()))
        .collect()
}

fn const_name_array(const_name: &str, methods: &[&PlatformMethod]) -> String {
    let entries = methods
        .iter()
        .map(|method| format!("  \"{}\",", raw_callback_name(method)))
        .collect::<Vec<_>>()
        .join("\n");
    format!("export const {const_name} = [\n{entries}\n] as const;\n")
}

fn emit_worker_callback_factory(
    function_name: &str,
    name_type: &str,
    methods: &[&PlatformMethod],
) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "function {function_name}(bridge: WorkerCallbackBridge): Required<Pick<RawCallbacks, {name_type}>> {{"
    )
    .unwrap();
    out.push_str("  return {\n");
    for method in methods {
        out.push_str(&emit_worker_callback_entry(method)?);
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    Ok(out)
}

fn emit_worker_callback_entry(method: &PlatformMethod) -> Result<String> {
    let raw = raw_callback_name(method);
    let args = method
        .params
        .iter()
        .map(|p| to_camel_case(&p.name))
        .collect::<Vec<_>>()
        .join(", ");
    let arg_array = if args.is_empty() {
        "[]".to_string()
    } else {
        format!("[{args}]")
    };
    if method.return_shape.is_async {
        Ok(format!(
            "    {raw}: ({args}) =>\n      bridge.callbackRequest(\"{raw}\", {arg_array}) as ReturnType<RawCallbacks[\"{raw}\"]>,\n"
        ))
    } else {
        match &method.return_shape.inner {
            PlatformInner::Unit => Ok(format!(
                "    {raw}: ({args}) =>\n      void bridge.callbackRequest(\"{raw}\", {arg_array}).catch(() => {{}}),\n"
            )),
            PlatformInner::Plain(_) => Ok(format!(
                "    {raw}: ({args}) =>\n      bridge.callbackRequest(\"{raw}\", {arg_array}) as ReturnType<RawCallbacks[\"{raw}\"]>,\n"
            )),
            PlatformInner::Result { .. }
            | PlatformInner::Stream(_)
            | PlatformInner::TraitObject(_) => {
                bail!("unsupported non-async worker callback return shape for `{raw}`")
            }
        }
    }
}

fn emit_worker_subscription_factory(methods: &[&PlatformMethod]) -> Result<String> {
    let mut out = String::new();
    out.push_str(
        "function subscriptionRawCallbacks(bridge: WorkerCallbackBridge): Required<Pick<RawCallbacks, SubscriptionName>> {\n",
    );
    out.push_str("  return {\n");
    for method in methods {
        let raw = raw_callback_name(method);
        let payload_param = worker_subscription_payload_param(method)?;
        if let Some(param) = payload_param {
            out.push_str(&format!(
                "    {raw}: ({param}, sendItem, sendError) =>\n      bridge.startSubscription(\"{raw}\", {param}, sendItem, sendError),\n"
            ));
        } else {
            out.push_str(&format!(
                "    {raw}: (sendItem, sendError) =>\n      bridge.startSubscription(\"{raw}\", null, sendItem, sendError),\n"
            ));
        }
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    Ok(out)
}

fn emit_start_raw_subscription_switch(methods: &[&PlatformMethod]) -> Result<String> {
    let mut out = String::new();
    out.push_str("  switch (name) {\n");
    for method in methods {
        let raw = raw_callback_name(method);
        if worker_subscription_payload_param(method)?.is_some() {
            out.push_str(&format!(
                "    case \"{raw}\":\n      if (payload === null) {{\n        console.warn(`[truapi worker] ${{name}} requires payload`);\n        return undefined;\n      }}\n      return callbacks.{raw}(payload, sendItem, sendError);\n"
            ));
        } else {
            out.push_str(&format!(
                "    case \"{raw}\":\n      return callbacks.{raw}(sendItem, sendError);\n"
            ));
        }
    }
    out.push_str("  }\n");
    Ok(out)
}

fn worker_subscription_payload_param(method: &PlatformMethod) -> Result<Option<String>> {
    match method.params.as_slice() {
        [] => Ok(None),
        [param] => Ok(Some(to_camel_case(&param.name))),
        _ => bail!(
            "subscription callback `{}` has more than one payload parameter",
            method.name
        ),
    }
}

fn collect_local_codec_names(
    ty: &TypeRef,
    local_codec_types: &BTreeSet<String>,
    out: &mut BTreeSet<String>,
) {
    match ty {
        TypeRef::Named { name, args } => {
            if local_codec_types.contains(name) {
                out.insert(name.clone());
            }
            for arg in args {
                collect_local_codec_names(arg, local_codec_types, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_local_codec_names(inner, local_codec_types, out);
        }
        TypeRef::Tuple(items) => {
            for item in items {
                collect_local_codec_names(item, local_codec_types, out);
            }
        }
        TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => {}
    }
}

/// Emit the complete `RawCallbacks` interface: the byte-oriented callback bag
/// produced by the typed host adapter. Codec payloads cross as `Uint8Array`,
/// strings/primitives/blobs pass through, subscriptions take a `sendItem` sink,
/// and trait-object returns use hand-written callback handle types.
fn emit_raw_callbacks(
    traits: &[&PlatformTrait],
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
    platform_trait_names: &BTreeSet<String>,
) -> String {
    let mut out = String::new();
    out.push_str("export interface RawCallbacks {\n");
    for trait_def in traits {
        for method in &trait_def.methods {
            out.push_str("  ");
            out.push_str(&raw_member(
                trait_def,
                method,
                codec_types,
                local_codec_types,
                platform_trait_names,
            ));
            out.push('\n');
        }
    }
    out.push_str("}\n");
    out
}

/// One `RawCallbacks` member signature for `method`.
fn raw_member(
    trait_def: &PlatformTrait,
    method: &PlatformMethod,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
    platform_trait_names: &BTreeSet<String>,
) -> String {
    let name = raw_callback_wire_name(trait_def, method, platform_trait_names);
    match &method.return_shape.inner {
        PlatformInner::Stream(_) => {
            let mut params: Vec<String> = method
                .params
                .iter()
                .map(|p| {
                    format!(
                        "{}: {}",
                        to_camel_case(&p.name),
                        raw_param_ts(&p.type_ref, codec_types, local_codec_types)
                    )
                })
                .collect();
            params.push("sendItem: (item?: Uint8Array) => void".to_string());
            params.push("sendError: (error: GenericError) => void".to_string());
            format!("{name}({}): (() => void) | void;", params.join(", "))
        }
        _ if trait_object_return_name(method, platform_trait_names).is_some() => {
            format!(
                "{}: {};",
                name,
                raw_callback_type_name(trait_def, method, platform_trait_names)
            )
        }
        inner => {
            let params = method
                .params
                .iter()
                .map(|p| {
                    format!(
                        "{}: {}",
                        to_camel_case(&p.name),
                        raw_param_ts(&p.type_ref, codec_types, local_codec_types)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            let ok = match inner {
                PlatformInner::Result { ok, .. } | PlatformInner::Plain(ok) => {
                    raw_ok_ts(ok, codec_types, local_codec_types)
                }
                _ => "void".to_string(),
            };
            // A synchronous (`!is_async`) callback is a fire-and-forget
            // notification (e.g. `authStateChanged`); everything else is async.
            if method.return_shape.is_async {
                format!("{name}({params}): Promise<{ok}>;")
            } else {
                format!("{name}({params}): {ok};")
            }
        }
    }
}

/// TS type for a `RawCallbacks` parameter under the byte boundary.
fn raw_param_ts(
    ty: &TypeRef,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> String {
    match ty {
        TypeRef::Named { name, .. } if codec_types.contains(name) => "Uint8Array".to_string(),
        TypeRef::Named { name, .. } if local_codec_types.contains(name) => "Uint8Array".to_string(),
        TypeRef::Named { name, .. } => name.clone(),
        TypeRef::Vec(inner) | TypeRef::Array(inner, _) if matches!(inner.as_ref(), TypeRef::Primitive(p) if p == "u8") => {
            "Uint8Array".to_string()
        }
        TypeRef::Option(inner) => {
            format!(
                "{} | null | undefined",
                raw_param_ts(inner, codec_types, local_codec_types)
            )
        }
        TypeRef::Primitive(p) => raw_primitive_ts(p),
        _ => "Uint8Array".to_string(),
    }
}

/// TS type for a `RawCallbacks` `Result` ok value under the byte boundary.
fn raw_ok_ts(
    ty: &TypeRef,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> String {
    match ty {
        TypeRef::Named { name, .. } if codec_types.contains(name) => "Uint8Array".to_string(),
        TypeRef::Named { name, .. } if local_codec_types.contains(name) => "Uint8Array".to_string(),
        TypeRef::Named { name, .. } => name.clone(),
        TypeRef::Vec(inner) | TypeRef::Array(inner, _) if matches!(inner.as_ref(), TypeRef::Primitive(p) if p == "u8") => {
            "Uint8Array".to_string()
        }
        TypeRef::Option(inner) => format!(
            "{} | null | undefined",
            raw_ok_ts(inner, codec_types, local_codec_types)
        ),
        TypeRef::Primitive(p) => raw_primitive_ts(p),
        TypeRef::Unit => "void".to_string(),
        TypeRef::Tuple(items) if items.is_empty() => "void".to_string(),
        _ => "Uint8Array".to_string(),
    }
}

fn raw_primitive_ts(p: &str) -> String {
    match p {
        "bool" => "boolean".to_string(),
        "str" => "string".to_string(),
        _ => "number".to_string(),
    }
}

/// Collect named types referenced by `ty` that are neither codec types nor
/// platform-local (e.g. the `NotificationId` alias), so the `RawCallbacks`
/// interface can import them from `@parity/truapi` for their type only.
fn collect_extra_named(
    ty: &TypeRef,
    codec_types: &BTreeSet<String>,
    local: &BTreeSet<String>,
    out: &mut BTreeSet<String>,
) {
    match ty {
        TypeRef::Named { name, args } => {
            if !codec_types.contains(name) && !local.contains(name) {
                out.insert(name.clone());
            }
            for arg in args {
                collect_extra_named(arg, codec_types, local, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_extra_named(inner, codec_types, local, out)
        }
        _ => {}
    }
}

/// Collect the `@parity/truapi` codec type names referenced by `ty` so the
/// adapter can import their `.enc`/`.dec`.
fn collect_codec_imports(ty: &TypeRef, codec_types: &BTreeSet<String>, out: &mut BTreeSet<String>) {
    match ty {
        TypeRef::Named { name, args } => {
            if codec_types.contains(name) {
                out.insert(name.clone());
            }
            for arg in args {
                collect_codec_imports(arg, codec_types, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_codec_imports(inner, codec_types, out)
        }
        _ => {}
    }
}

/// The call argument expression for one Rust param. Codec types arrive as
/// `Uint8Array` and are decoded; `u64`-family integers arrive as JS numbers and
/// are widened to `bigint`; everything else passes through. Arrow parameter
/// types are left to contextual inference from `RawCallbacks`, so only the
/// argument expression varies.
fn adapter_arg(
    param: &PlatformParam,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> String {
    let name = to_camel_case(&param.name);
    match &param.type_ref {
        TypeRef::Named { name: ty, .. }
            if codec_types.contains(ty) || local_codec_types.contains(ty) =>
        {
            format!("{ty}.dec({name})")
        }
        TypeRef::Primitive(p) if matches!(p.as_str(), "u64" | "u128" | "i64" | "i128") => {
            format!("BigInt({name})")
        }
        _ => name,
    }
}

/// Comma-joined arrow parameter names for a method (excluding `sendItem`).
fn param_names(method: &PlatformMethod) -> String {
    method
        .params
        .iter()
        .map(|p| to_camel_case(&p.name))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Emit one entry of the adapter object literal for `method`: every web worker
/// host provides a complete callback implementation, so missing capability
/// behavior is expressed inside the host callback rather than by omitting it.
fn emit_adapter_entry(
    trait_def: &PlatformTrait,
    method: &PlatformMethod,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
    platform_trait_names: &BTreeSet<String>,
) -> Result<String> {
    validate_adapter_codec_boundary(method, codec_types, local_codec_types)?;

    let raw = raw_callback_wire_name(trait_def, method, platform_trait_names);
    let host_method = format!("callbacks.{}.{}", callback_namespace(&trait_def.name), raw);
    if trait_object_return_name(method, platform_trait_names).is_some() {
        let adapter = raw_callback_adapter_name(trait_def, method, platform_trait_names);
        return Ok(format!(
            "{raw}: {adapter}(callbacks.{}),",
            callback_namespace(&trait_def.name)
        ));
    }
    let impl_expr = match &method.return_shape.inner {
        PlatformInner::Stream(item) => {
            adapter_stream_impl(&host_method, method, item, codec_types, local_codec_types)?
        }
        PlatformInner::Result { ok, .. } => {
            adapter_unary_impl(&host_method, method, ok, codec_types, local_codec_types)?
        }
        PlatformInner::Plain(ok) => {
            adapter_unary_impl(&host_method, method, ok, codec_types, local_codec_types)?
        }
        PlatformInner::Unit => adapter_unary_impl(
            &host_method,
            method,
            &TypeRef::Unit,
            codec_types,
            local_codec_types,
        )?,
        PlatformInner::TraitObject(_) => unreachable!("trait-object callbacks are handled above"),
    };
    Ok(format!("{raw}: {impl_expr},"))
}

fn validate_adapter_codec_boundary(
    method: &PlatformMethod,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> Result<()> {
    for param in &method.params {
        validate_adapter_codec_boundary_type(
            &param.type_ref,
            codec_types,
            local_codec_types,
            &format!("parameter `{}`", param.name),
            &method.name,
        )?;
    }

    match &method.return_shape.inner {
        PlatformInner::Result { ok, .. } | PlatformInner::Plain(ok) => {
            validate_adapter_codec_boundary_type(
                ok,
                codec_types,
                local_codec_types,
                "return value",
                &method.name,
            )?;
        }
        PlatformInner::Stream(item) => {
            validate_adapter_codec_boundary_type(
                stream_item(item),
                codec_types,
                local_codec_types,
                "stream item",
                &method.name,
            )?;
        }
        PlatformInner::Unit | PlatformInner::TraitObject(_) => {}
    }

    Ok(())
}

fn validate_adapter_codec_boundary_type(
    ty: &TypeRef,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
    position: &str,
    method_name: &str,
) -> Result<()> {
    if contains_non_direct_codec_type(ty, codec_types, local_codec_types) {
        bail!(
            "unsupported compound codec type in host callback `{method_name}` {position}: {ty:?}"
        );
    }
    Ok(())
}

/// The WASM adapter only knows how to translate a direct codec payload:
/// `Codec` maps to raw `Uint8Array` and the adapter emits `Codec.dec/enc`.
/// Containers such as `Vec<Codec>`, `Option<Codec>`, or `(Codec, ...)` would
/// still be declared as raw bytes at the WASM boundary, but no generated code
/// knows how to encode or decode the container. Reject those shapes at codegen.
fn contains_non_direct_codec_type(
    ty: &TypeRef,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> bool {
    fn walk(
        ty: &TypeRef,
        nested: bool,
        codec_types: &BTreeSet<String>,
        local_codec_types: &BTreeSet<String>,
    ) -> bool {
        match ty {
            TypeRef::Named { name, args } => {
                if codec_types.contains(name) || local_codec_types.contains(name) {
                    nested
                } else {
                    args.iter()
                        .any(|arg| walk(arg, true, codec_types, local_codec_types))
                }
            }
            TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
                walk(inner, true, codec_types, local_codec_types)
            }
            TypeRef::Tuple(items) => items
                .iter()
                .any(|item| walk(item, true, codec_types, local_codec_types)),
            TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => false,
        }
    }

    walk(ty, false, codec_types, local_codec_types)
}

/// The adapter implementation expression for a unary callback: decode codec
/// params, call the typed host method, SCALE-encode a codec result.
fn adapter_unary_impl(
    host_method: &str,
    method: &PlatformMethod,
    ok: &TypeRef,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> Result<String> {
    let params = param_names(method);
    let args = method
        .params
        .iter()
        .map(|p| adapter_arg(p, codec_types, local_codec_types))
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!("{host_method}({args})");
    let body = match ok {
        TypeRef::Named { name: ty, .. }
            if codec_types.contains(ty) || local_codec_types.contains(ty) =>
        {
            format!("{ty}.enc(await {call})")
        }
        _ => format!("await {call}"),
    };
    Ok(format!("async ({params}) => {body}"))
}

/// The adapter implementation expression for a subscription callback: drive
/// the host's stream into `sendItem`, SCALE-encoding each codec item.
fn adapter_stream_impl(
    host_method: &str,
    method: &PlatformMethod,
    item: &TypeRef,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> Result<String> {
    let args = method
        .params
        .iter()
        .map(|p| adapter_arg(p, codec_types, local_codec_types))
        .collect::<Vec<_>>()
        .join(", ");
    let item_ty = stream_item(item);
    let is_unit = matches!(item_ty, TypeRef::Unit)
        || matches!(item_ty, TypeRef::Tuple(items) if items.is_empty());
    let item_expr = match item_ty {
        // Tick subscription: the item carries no value, so ignore it and emit
        // a bare tick to the core's sink.
        _ if is_unit => "() => sendItem()".to_string(),
        TypeRef::Named { name: ty, .. }
            if codec_types.contains(ty) || local_codec_types.contains(ty) =>
        {
            format!("(item) => sendItem({ty}.enc(item))")
        }
        _ => "sendItem".to_string(),
    };
    let mut names: Vec<String> = method
        .params
        .iter()
        .map(|p| to_camel_case(&p.name))
        .collect();
    names.push("sendItem".to_string());
    names.push("sendError".to_string());
    let params = names.join(", ");
    let call = format!("{host_method}({args})");
    Ok(format!(
        "({params}) => driveResultStream({call}, {item_expr}, sendError)"
    ))
}

fn collect_local_bridge_payload_types(definition: &PlatformDefinition) -> BTreeSet<String> {
    let local: BTreeSet<String> = definition.types.iter().map(|ty| ty.name.clone()).collect();
    let mut out = BTreeSet::new();
    for trait_def in &definition.traits {
        for method in &trait_def.methods {
            for param in &method.params {
                collect_local_from_type(&param.type_ref, &local, &mut out);
            }
            match &method.return_shape.inner {
                PlatformInner::Result { ok, .. } | PlatformInner::Plain(ok) => {
                    collect_local_from_type(ok, &local, &mut out);
                }
                PlatformInner::Stream(item) => {
                    collect_local_from_type(stream_item(item), &local, &mut out)
                }
                PlatformInner::Unit | PlatformInner::TraitObject(_) => {}
            }
        }
    }
    let mut changed = true;
    while changed {
        changed = false;
        let referenced = definition
            .types
            .iter()
            .filter(|ty| out.contains(&ty.name))
            .collect::<Vec<_>>();
        for type_def in referenced {
            let before = out.len();
            collect_local_from_type_def(type_def, &local, &mut out);
            changed |= out.len() != before;
        }
    }
    out
}

fn collect_local_from_type_def(
    type_def: &TypeDef,
    local: &BTreeSet<String>,
    out: &mut BTreeSet<String>,
) {
    walk_type_def(type_def, out, &mut |ty, out| {
        collect_local_from_type(ty, local, out)
    });
}

fn collect_from_type_def(type_def: &TypeDef, out: &mut BTreeSet<String>) {
    walk_type_def(type_def, out, &mut |ty, out| collect_from_type(ty, out));
}

/// Walk every `TypeRef` reachable from a type definition's fields/variant
/// payloads, applying `leaf` to each. Callers supply the leaf collector that
/// decides which names land in `out`.
fn walk_type_def(
    type_def: &TypeDef,
    out: &mut BTreeSet<String>,
    leaf: &mut dyn FnMut(&TypeRef, &mut BTreeSet<String>),
) {
    match &type_def.kind {
        TypeDefKind::Alias(type_ref) => leaf(type_ref, out),
        TypeDefKind::Struct(fields) => {
            for field in fields {
                leaf(&field.type_ref, out);
            }
        }
        TypeDefKind::TupleStruct(fields) => {
            for field in fields {
                leaf(field, out);
            }
        }
        TypeDefKind::Enum(variants) => {
            for variant in variants {
                match &variant.fields {
                    VariantFields::Unit => {}
                    VariantFields::Unnamed(types) => {
                        for ty in types {
                            leaf(ty, out);
                        }
                    }
                    VariantFields::Named(fields) => {
                        for field in fields {
                            leaf(&field.type_ref, out);
                        }
                    }
                }
            }
        }
    }
}

fn collect_local_from_type(ty: &TypeRef, local: &BTreeSet<String>, out: &mut BTreeSet<String>) {
    match ty {
        TypeRef::Named { name, args } => {
            if local.contains(name) {
                out.insert(name.clone());
            }
            for arg in args {
                collect_local_from_type(arg, local, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_local_from_type(inner, local, out);
        }
        TypeRef::Tuple(items) => {
            for item in items {
                collect_local_from_type(item, local, out);
            }
        }
        TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => {}
    }
}

fn collect_local_codec_imports(
    definition: &PlatformDefinition,
    codec_types: &BTreeSet<String>,
    local_codec_types: &BTreeSet<String>,
) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for type_def in definition
        .types
        .iter()
        .filter(|ty| local_codec_types.contains(&ty.name))
    {
        collect_codec_imports_from_type_def(type_def, codec_types, &mut out);
    }
    out
}

fn collect_codec_imports_from_type_def(
    type_def: &TypeDef,
    codec_types: &BTreeSet<String>,
    out: &mut BTreeSet<String>,
) {
    match &type_def.kind {
        TypeDefKind::Struct(fields) => {
            for field in fields {
                collect_codec_imports(&field.type_ref, codec_types, out);
            }
        }
        TypeDefKind::TupleStruct(fields) => {
            for field in fields {
                collect_codec_imports(field, codec_types, out);
            }
        }
        TypeDefKind::Enum(variants) => {
            for variant in variants {
                match &variant.fields {
                    VariantFields::Unit => {}
                    VariantFields::Unnamed(types) => {
                        for ty in types {
                            collect_codec_imports(ty, codec_types, out);
                        }
                    }
                    VariantFields::Named(fields) => {
                        for field in fields {
                            collect_codec_imports(&field.type_ref, codec_types, out);
                        }
                    }
                }
            }
        }
        TypeDefKind::Alias(type_ref) => collect_codec_imports(type_ref, codec_types, out),
    }
}

fn emit_local_codec(type_def: &TypeDef) -> Result<String> {
    let jsdoc = render_jsdoc("", type_def.docs.as_deref());
    let expr = local_codec_expr_for_type(type_def)?;
    Ok(format!(
        "{jsdoc}export const {name}: S.Codec<{name}> = S.lazy((): S.Codec<{name}> => {expr});\n",
        name = type_def.name,
    ))
}

fn local_codec_expr_for_type(type_def: &TypeDef) -> Result<String> {
    match &type_def.kind {
        TypeDefKind::Alias(type_ref) => local_codec_expr(type_ref),
        TypeDefKind::Struct(fields) => local_struct_codec_expr(fields, &type_def.name),
        TypeDefKind::TupleStruct(fields) => local_tuple_codec_expr(fields),
        TypeDefKind::Enum(variants) => {
            if variants
                .iter()
                .all(|variant| matches!(variant.fields, VariantFields::Unit))
            {
                return Ok(format!(
                    "S.Status({})",
                    variants
                        .iter()
                        .map(|variant| ts_string_literal(&variant.name))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            let entries = variants
                .iter()
                .map(|variant| {
                    Ok(format!(
                        "{}: {}",
                        variant.name,
                        local_variant_codec_expr(&variant.fields)?
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            Ok(format!("S.TaggedUnion({{{entries}}})"))
        }
    }
}

fn local_variant_codec_expr(fields: &VariantFields) -> Result<String> {
    match fields {
        VariantFields::Unit => Ok("S._void".to_string()),
        VariantFields::Unnamed(types) => local_tuple_codec_expr(types),
        VariantFields::Named(fields) => {
            let type_name = inline_object_type(fields)?;
            local_struct_codec_expr(fields, &type_name)
        }
    }
}

fn local_tuple_codec_expr(types: &[TypeRef]) -> Result<String> {
    if types.is_empty() {
        Ok("S._void".to_string())
    } else if types.len() == 1 {
        local_codec_expr(&types[0])
    } else {
        Ok(format!(
            "S.Tuple({})",
            types
                .iter()
                .map(local_codec_expr)
                .collect::<Result<Vec<_>>>()?
                .join(", ")
        ))
    }
}

fn local_struct_codec_expr(fields: &[FieldDef], type_name: &str) -> Result<String> {
    let specs = fields
        .iter()
        .map(|field| {
            Ok(format!(
                "{}: {}",
                to_camel_case(&field.name),
                local_codec_expr(&field.type_ref)?
            ))
        })
        .collect::<Result<Vec<_>>>()?
        .join(", ");
    Ok(format!("S.Struct({{{specs}}}) as S.Codec<{type_name}>"))
}

fn local_codec_expr(ty: &TypeRef) -> Result<String> {
    match ty {
        TypeRef::Primitive(name) => match name.as_str() {
            "bool" => Ok("S.bool".to_string()),
            "u8" => Ok("S.u8".to_string()),
            "u16" => Ok("S.u16".to_string()),
            "u32" => Ok("S.u32".to_string()),
            "u64" => Ok("S.u64".to_string()),
            "u128" => Ok("S.u128".to_string()),
            "i8" => Ok("S.i8".to_string()),
            "i16" => Ok("S.i16".to_string()),
            "i32" => Ok("S.i32".to_string()),
            "i64" => Ok("S.i64".to_string()),
            "i128" => Ok("S.i128".to_string()),
            "str" => Ok("S.str".to_string()),
            _ => bail!("Unsupported primitive type `{name}` in host callback codec generation"),
        },
        TypeRef::Named { name, args } => {
            if args.is_empty() {
                Ok(name.clone())
            } else {
                let codecs = args
                    .iter()
                    .map(local_codec_expr)
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("{name}({codecs})"))
            }
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("S.Bytes()".to_string()),
            _ => Ok(format!("S.Vector({})", local_codec_expr(inner)?)),
        },
        TypeRef::Option(inner) => Ok(format!("S.Option({})", local_codec_expr(inner)?)),
        TypeRef::Tuple(items) => local_tuple_codec_expr(items),
        TypeRef::Array(inner, len) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok(format!("S.Bytes({len})")),
            _ => Ok(format!("S.Vector({})", local_codec_expr(inner)?)),
        },
        TypeRef::Generic(name) => {
            bail!("Generic `{name}` is not supported in host callback codecs")
        }
        TypeRef::Unit => Ok("S._void".to_string()),
    }
}

fn emit_trait_interface(trait_def: &PlatformTrait) -> Result<String> {
    let jsdoc = render_jsdoc("", trait_def.docs.as_deref());
    let body = trait_def
        .methods
        .iter()
        .map(emit_method)
        .collect::<Result<Vec<_>>>()?
        .join("\n\n");
    Ok(formatdoc! {
        r#"
        {jsdoc}export interface {name} {{
        {body}
        }}
        "#,
        name = trait_def.name.to_string(),
    })
}

fn emit_method(method: &PlatformMethod) -> Result<String> {
    let jsdoc = render_jsdoc("  ", method.docs.as_deref());
    let params = method
        .params
        .iter()
        .map(|p| {
            let ts = ts_type(&p.type_ref)?;
            Ok(format!("{}: {ts}", to_camel_case(&p.name)))
        })
        .collect::<Result<Vec<_>>>()?
        .join(", ");
    let ret = format_return(&method.return_shape)?;
    let name = to_camel_case(&method.name);
    // A Rust default body makes the method optional for host implementations.
    let optional = if method.has_default { "?" } else { "" };
    Ok(format!("{jsdoc}  {name}{optional}({params}): {ret};"))
}

/// Emit a TS interface for a local platform struct. `Option<T>` fields become
/// optional members so hosts receive plain objects with absent-when-`None`
/// properties.
fn emit_struct_interface(struct_def: &TypeDef) -> Result<String> {
    let TypeDefKind::Struct(fields) = &struct_def.kind else {
        bail!(
            "Platform struct `{}` must have named fields",
            struct_def.name
        );
    };
    if !struct_def.generic_params.is_empty() {
        bail!("Platform struct `{}` must not be generic", struct_def.name);
    }
    let jsdoc = render_jsdoc("", struct_def.docs.as_deref());
    let body = fields
        .iter()
        .map(|field| {
            let jsdoc = render_jsdoc("  ", field.docs.as_deref());
            let name = to_camel_case(&field.name);
            match &field.type_ref {
                TypeRef::Option(inner) => Ok(format!("{jsdoc}  {name}?: {};", ts_type(inner)?)),
                other => Ok(format!("{jsdoc}  {name}: {};", ts_type(other)?)),
            }
        })
        .collect::<Result<Vec<_>>>()?
        .join("\n\n");
    Ok(formatdoc! {
        r#"
        {jsdoc}export interface {name} {{
        {body}
        }}
        "#,
        name = struct_def.name,
    })
}

/// Emit a TS type for a local platform enum. Unit-only enums become string
/// literal unions; payload enums become `{ tag, value }` tagged unions
/// matching the `@parity/truapi` client convention.
fn emit_enum_type(enum_def: &TypeDef) -> Result<String> {
    let TypeDefKind::Enum(variants) = &enum_def.kind else {
        bail!("Platform enum `{}` must have variants", enum_def.name);
    };
    if !enum_def.generic_params.is_empty() {
        bail!("Platform enum `{}` must not be generic", enum_def.name);
    }
    let jsdoc = render_jsdoc("", enum_def.docs.as_deref());
    if variants
        .iter()
        .all(|variant| matches!(variant.fields, VariantFields::Unit))
    {
        let union = variants
            .iter()
            .map(|variant| format!("\"{}\"", variant.name))
            .collect::<Vec<_>>()
            .join(" | ");
        return Ok(format!(
            "{jsdoc}export type {name} = {union};\n",
            name = enum_def.name,
        ));
    }
    let mut body = String::new();
    for variant in variants {
        body.push_str(&render_jsdoc("  ", variant.docs.as_deref()));
        writeln!(body, "  | {}", enum_variant_type(variant)?).unwrap();
    }
    Ok(formatdoc! {
        r#"
        {jsdoc}export type {name} =
        {body};
        "#,
        name = enum_def.name,
        body = body.trim_end(),
    })
}

/// Render one enum variant as a `{ tag, value }` member. Unit variants mark
/// `value` optional so consumers can write `{ tag: "X" }`.
fn enum_variant_type(variant: &VariantDef) -> Result<String> {
    Ok(match &variant.fields {
        VariantFields::Unit => format!("{{ tag: \"{}\"; value?: undefined }}", variant.name),
        VariantFields::Unnamed(types) => format!(
            "{{ tag: \"{}\"; value: {} }}",
            variant.name,
            unnamed_variant_value_type(types)?
        ),
        VariantFields::Named(fields) => format!(
            "{{ tag: \"{}\"; value: {} }}",
            variant.name,
            inline_object_type(fields)?
        ),
    })
}

fn unnamed_variant_value_type(types: &[TypeRef]) -> Result<String> {
    match types {
        [single] => ts_type(single),
        many => {
            let rendered = many
                .iter()
                .map(ts_type)
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            Ok(format!("[{rendered}]"))
        }
    }
}

fn inline_object_type(fields: &[FieldDef]) -> Result<String> {
    let body = fields
        .iter()
        .map(|field| {
            let name = to_camel_case(&field.name);
            match &field.type_ref {
                TypeRef::Option(inner) => Ok(format!("{name}?: {}", ts_type(inner)?)),
                other => Ok(format!("{name}: {}", ts_type(other)?)),
            }
        })
        .collect::<Result<Vec<_>>>()?
        .join("; ");
    Ok(format!("{{ {body} }}"))
}

fn emit_host_callback_composites(composes: &[String], docs: Option<&str>) -> String {
    let jsdoc = render_jsdoc("", docs);
    if composes.is_empty() {
        return format!(
            "{jsdoc}export interface HostCallbacks {{}}\n\nexport interface RequiredHostCallbacks {{}}\n"
        );
    }
    let host_members = composes
        .iter()
        .map(|trait_name| format!("  {}: {};", callback_namespace(trait_name), trait_name))
        .collect::<Vec<_>>()
        .join("\n");
    let required_members = composes
        .iter()
        .map(|trait_name| {
            format!(
                "  {}: Required<{}>;",
                callback_namespace(trait_name),
                trait_name
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    formatdoc! {
        r#"
        {jsdoc}export interface HostCallbacks {{
        {host_members}
        }}

        export interface RequiredHostCallbacks {{
        {required_members}
        }}
        "#,
    }
}

fn collect_named_types(definition: &PlatformDefinition) -> BTreeSet<String> {
    let mut out: BTreeSet<String> = BTreeSet::new();
    for trait_def in &definition.traits {
        for method in &trait_def.methods {
            for param in &method.params {
                collect_from_type(&param.type_ref, &mut out);
            }
            match &method.return_shape.inner {
                // Err type is not part of the TS signature (errors throw),
                // so don't import its name.
                PlatformInner::Result { ok, .. } => collect_from_type(ok, &mut out),
                PlatformInner::Stream(inner) => collect_from_type(inner, &mut out),
                PlatformInner::Plain(inner) => collect_from_type(inner, &mut out),
                // A trait object returns its bare trait name in the TS
                // signature; collect it so a non-local trait gets imported
                // rather than emitted as an undeclared name. Local traits are
                // filtered out below since their interfaces live in this file.
                PlatformInner::TraitObject(name) => {
                    out.insert(name.clone());
                }
                PlatformInner::Unit => {}
            }
        }
    }
    for type_def in &definition.types {
        collect_from_type_def(type_def, &mut out);
    }
    // Filter out names defined locally (the capability trait interfaces and
    // the platform struct/enum types emitted into this file).
    let local = local_names(definition);
    out.into_iter().filter(|n| !local.contains(n)).collect()
}

fn collect_from_type(ty: &TypeRef, out: &mut BTreeSet<String>) {
    match ty {
        TypeRef::Named { name, args } => {
            out.insert(name.clone());
            for arg in args {
                collect_from_type(arg, out);
            }
        }
        TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
            collect_from_type(inner, out)
        }
        TypeRef::Tuple(items) => {
            for item in items {
                collect_from_type(item, out);
            }
        }
        TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => {}
    }
}

fn format_return(ret: &PlatformReturn) -> Result<String> {
    let inner = match &ret.inner {
        PlatformInner::Unit => "void".to_string(),
        PlatformInner::Result { ok, .. } => ts_type(ok)?,
        PlatformInner::Stream(item) => format!("AsyncIterable<{}>", ts_type(item)?),
        PlatformInner::TraitObject(name) => name.clone(),
        PlatformInner::Plain(ty) => ts_type(ty)?,
    };
    if ret.is_async {
        Ok(format!("Promise<{inner}>"))
    } else {
        Ok(inner)
    }
}

fn ts_type(ty: &TypeRef) -> Result<String> {
    match ty {
        TypeRef::Primitive(name) => match name.as_str() {
            "bool" => Ok("boolean".to_string()),
            "u8" | "u16" | "u32" | "i8" | "i16" | "i32" | "f32" | "f64" => Ok("number".to_string()),
            "u64" | "u128" | "i64" | "i128" => Ok("bigint".to_string()),
            "str" => Ok("string".to_string()),
            _ => bail!("Unsupported primitive type `{name}` in host callbacks generation"),
        },
        TypeRef::Named { name, args } => {
            if args.is_empty() {
                Ok(name.clone())
            } else {
                let rendered = args
                    .iter()
                    .map(ts_type)
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("{name}<{rendered}>"))
            }
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type(inner)?)),
        },
        TypeRef::Option(inner) => Ok(format!("{} | undefined", ts_type(inner)?)),
        TypeRef::Tuple(items) => {
            if items.is_empty() {
                Ok("void".to_string())
            } else {
                let rendered = items
                    .iter()
                    .map(ts_type)
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("[{rendered}]"))
            }
        }
        TypeRef::Array(inner, _len) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type(inner)?)),
        },
        TypeRef::Generic(name) => Ok(name.clone()),
        TypeRef::Unit => Ok("void".to_string()),
    }
}

fn render_jsdoc(indent: &str, docs: Option<&str>) -> String {
    let Some(docs) = docs else {
        return String::new();
    };
    let docs = docs.trim();
    if docs.is_empty() {
        return String::new();
    }
    let body = docs
        .lines()
        .map(|line| {
            if line.is_empty() {
                format!("{indent} *")
            } else {
                format!("{indent} * {}", render_ts_doc_line(line))
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{indent}/**\n{body}\n{indent} */\n")
}

fn render_ts_doc_line(line: &str) -> String {
    line.replace("[`", "`")
        .replace("`]", "`")
        .replace("Ok(())", "success")
        .replace("None", "`undefined`")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn named(name: &str) -> TypeRef {
        TypeRef::Named {
            name: name.to_string(),
            args: Vec::new(),
        }
    }

    fn codec_types() -> BTreeSet<String> {
        [
            "GenericError",
            "HostFeatureSupportedRequest",
            "HostFeatureSupportedResponse",
        ]
        .into_iter()
        .map(str::to_string)
        .collect()
    }

    fn platform_with_method(method: PlatformMethod) -> PlatformDefinition {
        PlatformDefinition {
            traits: vec![PlatformTrait {
                name: "Features".to_string(),
                docs: None,
                methods: vec![method],
            }],
            types: Vec::new(),
            super_trait: None,
        }
    }

    fn method_with_return(ok: TypeRef) -> PlatformMethod {
        PlatformMethod {
            name: "feature_supported".to_string(),
            docs: None,
            params: vec![PlatformParam {
                name: "request".to_string(),
                type_ref: named("HostFeatureSupportedRequest"),
            }],
            return_shape: PlatformReturn {
                is_async: true,
                inner: PlatformInner::Result {
                    ok,
                    err: named("GenericError"),
                },
            },
            has_default: false,
        }
    }

    fn method_with_param(param: TypeRef) -> PlatformMethod {
        PlatformMethod {
            name: "feature_supported".to_string(),
            docs: None,
            params: vec![PlatformParam {
                name: "request".to_string(),
                type_ref: param,
            }],
            return_shape: PlatformReturn {
                is_async: true,
                inner: PlatformInner::Result {
                    ok: named("HostFeatureSupportedResponse"),
                    err: named("GenericError"),
                },
            },
            has_default: false,
        }
    }

    fn assert_rejects_compound_codec(method: PlatformMethod, expected: &str) {
        let definition = platform_with_method(method);
        let err = emit_wasm_adapter(&definition, &codec_types(), &BTreeSet::new())
            .expect_err("compound codec boundary should fail codegen")
            .to_string();
        assert!(
            err.contains("unsupported compound codec type"),
            "unexpected error: {err}"
        );
        assert!(err.contains(expected), "unexpected error: {err}");
    }

    #[test]
    fn wasm_adapter_rejects_compound_codec_return_shapes() {
        let codec = named("HostFeatureSupportedResponse");
        assert_rejects_compound_codec(
            method_with_return(TypeRef::Vec(Box::new(codec.clone()))),
            "return value",
        );
        assert_rejects_compound_codec(
            method_with_return(TypeRef::Option(Box::new(codec.clone()))),
            "return value",
        );
        assert_rejects_compound_codec(
            method_with_return(TypeRef::Tuple(vec![codec])),
            "return value",
        );
    }

    #[test]
    fn wasm_adapter_rejects_compound_codec_param_shapes() {
        let codec = named("HostFeatureSupportedRequest");
        assert_rejects_compound_codec(
            method_with_param(TypeRef::Vec(Box::new(codec.clone()))),
            "parameter `request`",
        );
        assert_rejects_compound_codec(
            method_with_param(TypeRef::Option(Box::new(codec.clone()))),
            "parameter `request`",
        );
        assert_rejects_compound_codec(
            method_with_param(TypeRef::Tuple(vec![codec])),
            "parameter `request`",
        );
    }
}
