//! Versioned request and response wrappers for the unified TrUAPI contract.
//!
//! A versioned envelope is a SCALE enum whose variants (`V1`, `V2`, ...) are
//! successive versions of one logical message, newest last. A server normalizes
//! incoming values to [`Versioned::Latest`] with [`IntoLatest`], handles them in
//! latest terms, then maps results back to the caller's version with
//! [`FromLatest`]. The envelopes themselves are generated by `versioned_type!`.

use crate::CallError;

/// A versioned message envelope.
pub trait Versioned: Sized {
    /// The newest version's payload. Handlers operate exclusively on this.
    type Latest;

    /// Version number of the newest variant.
    const LATEST: u8;

    /// Version number of the variant currently held.
    fn version(&self) -> u8;
}

/// Upgrade a received envelope to its latest payload. Total by construction.
pub trait IntoLatest: Versioned {
    /// Convert whatever version is held into the latest payload.
    fn into_latest(self) -> Self::Latest;
}

/// Downgrade a latest payload into the variant a peer at `target` understands.
pub trait FromLatest: Versioned {
    /// Build the envelope for protocol version `target` (highest variant ≤ target).
    fn from_latest(latest: Self::Latest, target: u8) -> Self;
}

/// Converts framework-level runtime failures into a method's existing
/// domain-error payload before it crosses the public product/host wire.
pub trait FrameworkErrorFallback {
    fn denied() -> Self;
    fn unsupported() -> Self;
    fn malformed_frame(reason: String) -> Self;
    fn host_failure(reason: String) -> Self;
}

/// Convert an internal [`CallError`] into the versioned domain error expected
/// by the public wire protocol.
pub fn call_error_to_versioned<E>(error: CallError<E>, target_version: u8) -> E
where
    E: FromLatest,
    E::Latest: FrameworkErrorFallback,
{
    match error {
        CallError::Domain(error) => error,
        CallError::Denied => E::from_latest(E::Latest::denied(), target_version),
        CallError::Unsupported => E::from_latest(E::Latest::unsupported(), target_version),
        CallError::MalformedFrame { reason } => {
            E::from_latest(E::Latest::malformed_frame(reason), target_version)
        }
        CallError::HostFailure { reason } => {
            E::from_latest(E::Latest::host_failure(reason), target_version)
        }
    }
}

fn framework_reason(label: &str, reason: impl AsRef<str>) -> String {
    let reason = reason.as_ref();
    if reason.is_empty() {
        label.to_string()
    } else {
        format!("{label}: {reason}")
    }
}

impl FrameworkErrorFallback for crate::v01::GenericError {
    fn denied() -> Self {
        Self {
            reason: "denied".into(),
        }
    }

    fn unsupported() -> Self {
        Self {
            reason: "unsupported".into(),
        }
    }

    fn malformed_frame(reason: String) -> Self {
        Self {
            reason: framework_reason("malformed frame", reason),
        }
    }

    fn host_failure(reason: String) -> Self {
        Self {
            reason: framework_reason("host failure", reason),
        }
    }
}

macro_rules! unknown_reason_fallback {
    ($($ty:path),+ $(,)?) => {
        $(
            impl FrameworkErrorFallback for $ty {
                fn denied() -> Self {
                    Self::Unknown { reason: "denied".into() }
                }

                fn unsupported() -> Self {
                    Self::Unknown { reason: "unsupported".into() }
                }

                fn malformed_frame(reason: String) -> Self {
                    Self::Unknown {
                        reason: framework_reason("malformed frame", reason),
                    }
                }

                fn host_failure(reason: String) -> Self {
                    Self::Unknown {
                        reason: framework_reason("host failure", reason),
                    }
                }
            }
        )+
    };
}

unknown_reason_fallback!(
    crate::v01::HostPushNotificationError,
    crate::v01::HostLocalStorageReadError,
    crate::v01::HostDeriveEntropyError,
    crate::v01::HostPaymentBalanceSubscribeError,
    crate::v01::HostPaymentTopUpError,
    crate::v01::HostPaymentError,
    crate::v01::HostPaymentStatusSubscribeError,
    crate::v01::HostNavigateToError,
    crate::v01::RemoteStatementStoreCreateProofError,
    crate::v01::HostSignPayloadError,
    crate::v01::HostChatCreateRoomError,
    crate::v01::HostChatRegisterBotError,
    crate::v01::HostChatPostMessageError,
    crate::v01::ResourceAllocationError,
    crate::v01::PreimageSubmitError,
    crate::v01::HostRequestLoginError,
    crate::v01::HostAccountGetError,
    crate::v01::HostAccountCreateProofError,
    crate::v01::HostGetUserIdError,
);

impl FrameworkErrorFallback for crate::v01::HostHandshakeError {
    fn denied() -> Self {
        Self::Unknown(crate::v01::GenericError {
            reason: "denied".into(),
        })
    }

    fn unsupported() -> Self {
        Self::UnsupportedProtocolVersion
    }

    fn malformed_frame(reason: String) -> Self {
        Self::Unknown(crate::v01::GenericError {
            reason: framework_reason("malformed frame", reason),
        })
    }

    fn host_failure(reason: String) -> Self {
        Self::Unknown(crate::v01::GenericError {
            reason: framework_reason("host failure", reason),
        })
    }
}

impl FrameworkErrorFallback for crate::v01::HostCreateTransactionError {
    fn denied() -> Self {
        Self::PermissionDenied
    }

    fn unsupported() -> Self {
        Self::NotSupported {
            reason: "unsupported".into(),
        }
    }

    fn malformed_frame(reason: String) -> Self {
        Self::Unknown {
            reason: framework_reason("malformed frame", reason),
        }
    }

    fn host_failure(reason: String) -> Self {
        Self::Unknown {
            reason: framework_reason("host failure", reason),
        }
    }
}

impl FrameworkErrorFallback for crate::v01::CoinPaymentError {
    fn denied() -> Self {
        Self::Denied
    }

    fn unsupported() -> Self {
        Self::UserAgentCapabilityUnavailable
    }

    fn malformed_frame(_reason: String) -> Self {
        Self::Internal
    }

    fn host_failure(_reason: String) -> Self {
        Self::Internal
    }
}

pub mod account;
pub mod chain;
pub mod chat;
pub mod coin_payment;
pub mod entropy;
pub mod local_storage;
pub mod notifications;
pub mod payment;
pub mod permissions;
pub mod preimage;
pub mod resource_allocation;
pub mod signing;
pub mod statement_store;
pub mod system;
pub mod theme;

#[cfg(test)]
mod tests {
    use parity_scale_codec::{Decode, Encode};

    #[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
    struct ProbeV1 {
        a: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
    struct ProbeV2 {
        b: Vec<u8>,
    }

    truapi_macros::versioned_type! {
        enum MultiVersionProbe {
            V1 => ProbeV1,
            V2 => ProbeV2,
        }
    }

    // Multi-version envelopes assign positional SCALE codec indices (V1 -> 0,
    // V2 -> 1) and 1-based version numbers.
    #[test]
    fn multi_version_codec_indices_are_positional() {
        use super::Versioned;

        let v1 = MultiVersionProbe::V1(ProbeV1 { a: 7 });
        let v2 = MultiVersionProbe::V2(ProbeV2 {
            b: b"hello".to_vec(),
        });

        assert_eq!(v1.encode()[0], 0, "V1 encodes codec index 0");
        assert_eq!(v2.encode()[0], 1, "V2 encodes codec index 1");
        assert_eq!(v1.version(), 1);
        assert_eq!(v2.version(), 2);
        assert_eq!(MultiVersionProbe::LATEST, 2);
    }

    #[test]
    fn v1_discriminant_is_zero() {
        let v1 = super::permissions::HostDevicePermissionRequest::V1(
            crate::v01::HostDevicePermissionRequest::Camera,
        );
        assert_eq!(v1.encode()[0], 0, "V1 must encode discriminant 0");
    }

    #[test]
    fn unit_response_roundtrip() {
        let original = super::system::HostNavigateToResponse::V1;
        let decoded = super::system::HostNavigateToResponse::decode(&mut &original.encode()[..])
            .expect("decode");
        assert_eq!(original, decoded);
    }

    #[test]
    fn struct_variant_roundtrip() {
        let original = super::local_storage::HostLocalStorageWriteRequest::V1(
            crate::v01::HostLocalStorageWriteRequest {
                key: "greeting".into(),
                value: b"hello".to_vec(),
            },
        );
        let decoded =
            super::local_storage::HostLocalStorageWriteRequest::decode(&mut &original.encode()[..])
                .expect("decode");
        assert_eq!(original, decoded);
    }
}
