#!/usr/bin/env node
// Wires `yarn dev` to serve the local cargo doc through Next's static
// `public/` directory, so cargo-doc links from the playground stay
// http://localhost-relative (Chrome blocks file:// links from http://
// origins).
//
// 1. Symlink playground/public/cargo_doc → ../../target/doc/truapi.
// 2. Write playground/.env.development.local with
//    NEXT_PUBLIC_CARGO_DOC_BASE=/cargo_doc.
// Only consumed by `next dev`. `next build` ignores .env.development.local,
// so the deployed production URL still wins in CI.

import { readdir, writeFile, stat, mkdir, symlink, rm } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const PLAYGROUND = fileURLToPath(new URL("..", import.meta.url));
const ROOT = fileURLToPath(new URL("../..", import.meta.url));
const DOC_DIR = join(ROOT, "target/doc");
const CRATE_DOC = join(DOC_DIR, "truapi");
const STATIC_FILES = join(DOC_DIR, "static.files");
const PUBLIC_DIR = join(PLAYGROUND, "public/cargo_doc");
const PUBLIC_STATIC_FILES = join(PLAYGROUND, "public/static.files");
const OUT = join(PLAYGROUND, ".env.development.local");

await mkdir(dirname(PUBLIC_DIR), { recursive: true });

let crateExists = true;
try {
  await stat(CRATE_DOC);
} catch {
  crateExists = false;
  console.warn(
    `write-dev-env: ${CRATE_DOC} does not exist yet — run \`cargo doc -p truapi --no-deps\` to populate it.`,
  );
}

// Refresh public/cargo_doc as a fresh directory of symlinks. Each entry in
// target/doc/truapi/ is linked at the top level so URLs are
// /cargo_doc/api/... (no /truapi/ prefix), matching the deployed layout.
// rustdoc HTMLs reference static.files via `../../../static.files/`, which
// from /cargo_doc/api/<mod>/ resolves to the site root, so static.files is
// symlinked at public/static.files (sibling of public/cargo_doc).
await rm(PUBLIC_DIR, { recursive: true, force: true });
await rm(PUBLIC_STATIC_FILES, { force: true });
await mkdir(PUBLIC_DIR, { recursive: true });

if (crateExists) {
  for (const entry of await readdir(CRATE_DOC)) {
    await symlink(join(CRATE_DOC, entry), join(PUBLIC_DIR, entry));
  }
  try {
    await stat(STATIC_FILES);
    await symlink(STATIC_FILES, PUBLIC_STATIC_FILES, "dir");
  } catch {
    /* no static.files yet — cargo doc not built */
  }
}

await mkdir(dirname(OUT), { recursive: true });
await writeFile(
  OUT,
  `# Auto-generated by scripts/write-dev-env.mjs. Do not edit.\n` +
    `NEXT_PUBLIC_CARGO_DOC_BASE=/cargo_doc\n`,
);

console.log(
  `wrote ${relative(PLAYGROUND, OUT)}, ${relative(PLAYGROUND, PUBLIC_DIR)}/ (→ target/doc/truapi), and ${relative(PLAYGROUND, PUBLIC_STATIC_FILES)} (→ target/doc/static.files)`,
);
