//! Dart code generation from extracted API definitions.
//!
//! Sibling of [`crate::ts`]: consumes the same [`ApiDefinition`] IR and emits a
//! typed Dart client (`types.dart`, `wire_table.dart`, `client.dart`,
//! `index.dart`). The Rust crate stays the single source of truth — every Dart
//! type, codec, wire id, and doc comment is derived from the rustdoc JSON.
//!
//! Mapping highlights (mirrors `ts.rs`):
//! - Versioned `Vn` wrapper enums are not emitted as Dart types; each wrapper's
//!   selected (highest `≤ target`) inner type is emitted under its stripped
//!   public name, and the wire wrapping is `S.versioned(n - 1, innerCodec)`.
//! - Unit-only enums become Dart `enum`s; mixed enums become sealed classes.
//! - Structs become immutable classes; `Component<P>` becomes a generic class
//!   with a generic codec function.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::{Result, anyhow, bail};
use convert_case::{Case, Casing};

use crate::rustdoc::*;

/// Generate the Dart client into `output_dir`.
pub fn generate(
    api: &ApiDefinition,
    output_dir: &str,
    target_version: u32,
    codec_version: u8,
) -> Result<()> {
    fs::create_dir_all(output_dir)?;
    let g = Gen::new(api, target_version, codec_version);

    fs::write(Path::new(output_dir).join("types.dart"), g.types()?)?;
    fs::write(
        Path::new(output_dir).join("wire_table.dart"),
        g.wire_table()?,
    )?;
    fs::write(Path::new(output_dir).join("client.dart"), g.client()?)?;
    fs::write(
        Path::new(output_dir).join("index.dart"),
        format!(
            "{HEADER}\nexport 'types.dart';\nexport 'wire_table.dart';\nexport 'client.dart';\n"
        ),
    )?;
    Ok(())
}

/// Selected inner shape of a versioned wrapper variant.
enum WrapKind {
    Unit,
    Tuple(TypeRef),
}

/// A versioned wrapper enum (`Vn` variants), keyed by version number.
struct Wrapper {
    variants: BTreeMap<u32, WrapKind>,
}

struct Gen<'a> {
    api: &'a ApiDefinition,
    wrappers: HashMap<String, Wrapper>,
    target_version: u32,
    codec_version: u8,
    /// Full names of the version-prefixed types to emit (the selected version
    /// per base). Others are elided.
    emit_prefixed: HashSet<String>,
}

const HEADER: &str =
    "// Auto-generated by truapi-codegen. Do not edit.\n// ignore_for_file: type=lint\n";

impl<'a> Gen<'a> {
    fn new(api: &'a ApiDefinition, target_version: u32, codec_version: u8) -> Self {
        let wrappers = api
            .types
            .iter()
            .filter_map(|ty| detect_wrapper(ty).map(|w| (ty.name.clone(), w)))
            .collect();

        // Pick the highest version-prefixed inner per base (≤ target).
        let mut selected: BTreeMap<String, (u32, String)> = BTreeMap::new();
        for ty in &api.types {
            if let Some((version, base)) = version_prefixed_type(&ty.name) {
                if version > target_version {
                    continue;
                }
                let entry = selected
                    .entry(base.to_string())
                    .or_insert((version, ty.name.clone()));
                if version > entry.0 {
                    *entry = (version, ty.name.clone());
                }
            }
        }
        let emit_prefixed = selected.into_values().map(|(_, name)| name).collect();

        Self {
            api,
            wrappers,
            target_version,
            codec_version,
            emit_prefixed,
        }
    }

    // --- types.dart -------------------------------------------------------

    fn types(&self) -> Result<String> {
        let mut out = String::new();
        writeln!(
            out,
            "{HEADER}\nimport 'dart:typed_data';\n\nimport '../scale.dart' as S;\n"
        )
        .unwrap();

        for ty in &self.api.types {
            if detect_wrapper(ty).is_some() {
                continue; // wrapper enums are wire-only; not Dart types
            }
            if version_prefixed_type(&ty.name).is_some() && !self.emit_prefixed.contains(&ty.name) {
                continue;
            }
            let name = public_name(&ty.name);
            self.write_type(&mut out, ty, &name)?;
            writeln!(out).unwrap();
            self.write_type_codec(&mut out, ty, &name)?;
            writeln!(out).unwrap();
        }
        Ok(out)
    }

    fn write_type(&self, out: &mut String, ty: &TypeDef, name: &str) -> Result<()> {
        write_doc(out, "", ty.docs.as_deref());
        let generics = generic_decl(&ty.generic_params);
        match &ty.kind {
            TypeDefKind::Alias(target) => {
                writeln!(
                    out,
                    "typedef {name}{generics} = {};",
                    self.dart_type(target)?
                )
                .unwrap();
            }
            TypeDefKind::Struct(fields) => self.write_struct(out, name, &generics, fields)?,
            TypeDefKind::TupleStruct(types) => {
                self.write_tuple_struct(out, name, &generics, types)?
            }
            TypeDefKind::Enum(variants) => {
                if is_unit_only_enum(ty) {
                    self.write_unit_enum(out, name, variants)?;
                } else {
                    self.write_sealed_enum(out, name, &generics, variants)?;
                }
            }
        }
        Ok(())
    }

    fn write_struct(
        &self,
        out: &mut String,
        name: &str,
        generics: &str,
        fields: &[FieldDef],
    ) -> Result<()> {
        let dart: Vec<(String, String, bool)> = fields
            .iter()
            .map(|f| {
                let optional = matches!(f.type_ref, TypeRef::Option(_));
                Ok((field_name(&f.name), self.dart_type(&f.type_ref)?, optional))
            })
            .collect::<Result<_>>()?;

        writeln!(out, "class {name}{generics} {{").unwrap();
        // Constructor.
        writeln!(out, "  const {name}({{").unwrap();
        for (fname, _, optional) in &dart {
            if *optional {
                writeln!(out, "    this.{fname},").unwrap();
            } else {
                writeln!(out, "    required this.{fname},").unwrap();
            }
        }
        writeln!(out, "  }});").unwrap();
        // Fields.
        for ((fname, ftype, _), field) in dart.iter().zip(fields) {
            write_doc(out, "  ", field.docs.as_deref());
            writeln!(out, "  final {ftype} {fname};").unwrap();
        }
        // Equality + toString.
        write_value_equality(
            out,
            name,
            generics,
            &dart.iter().map(|(n, _, _)| n.clone()).collect::<Vec<_>>(),
        );
        writeln!(out, "}}").unwrap();
        Ok(())
    }

    fn write_tuple_struct(
        &self,
        out: &mut String,
        name: &str,
        generics: &str,
        types: &[TypeRef],
    ) -> Result<()> {
        let dart: Vec<(String, String)> = types
            .iter()
            .enumerate()
            .map(|(i, t)| Ok((format!("field{i}"), self.dart_type(t)?)))
            .collect::<Result<_>>()?;
        writeln!(out, "class {name}{generics} {{").unwrap();
        let params = dart
            .iter()
            .map(|(n, _)| format!("this.{n}"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "  const {name}({params});").unwrap();
        for (n, t) in &dart {
            writeln!(out, "  final {t} {n};").unwrap();
        }
        write_value_equality(
            out,
            name,
            generics,
            &dart.iter().map(|(n, _)| n.clone()).collect::<Vec<_>>(),
        );
        writeln!(out, "}}").unwrap();
        Ok(())
    }

    fn write_unit_enum(&self, out: &mut String, name: &str, variants: &[VariantDef]) -> Result<()> {
        writeln!(out, "enum {name} {{").unwrap();
        for variant in variants {
            write_doc(out, "  ", variant.docs.as_deref());
            writeln!(out, "  {},", enum_value_name(&variant.name)).unwrap();
        }
        writeln!(out, "}}").unwrap();
        Ok(())
    }

    fn write_sealed_enum(
        &self,
        out: &mut String,
        name: &str,
        generics: &str,
        variants: &[VariantDef],
    ) -> Result<()> {
        writeln!(out, "sealed class {name}{generics} {{").unwrap();
        writeln!(out, "  const {name}();").unwrap();
        writeln!(out, "}}").unwrap();

        for variant in variants {
            let vname = format!("{name}{}", variant.name);
            write_doc(out, "", variant.docs.as_deref());
            match &variant.fields {
                VariantFields::Unit => {
                    writeln!(
                        out,
                        "final class {vname}{generics} extends {name}{} {{",
                        type_args(generics)
                    )
                    .unwrap();
                    writeln!(out, "  const {vname}();").unwrap();
                    write_value_equality(out, &vname, generics, &[]);
                    writeln!(out, "}}").unwrap();
                }
                VariantFields::Unnamed(types) => {
                    let dart: Vec<(String, String)> = types
                        .iter()
                        .enumerate()
                        .map(|(i, t)| {
                            let fname = if types.len() == 1 {
                                "value".to_string()
                            } else {
                                format!("field{i}")
                            };
                            Ok((fname, self.dart_type(t)?))
                        })
                        .collect::<Result<_>>()?;
                    writeln!(
                        out,
                        "final class {vname}{generics} extends {name}{} {{",
                        type_args(generics)
                    )
                    .unwrap();
                    let params = dart
                        .iter()
                        .map(|(n, _)| format!("this.{n}"))
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(out, "  const {vname}({params});").unwrap();
                    for (n, t) in &dart {
                        writeln!(out, "  final {t} {n};").unwrap();
                    }
                    write_value_equality(
                        out,
                        &vname,
                        generics,
                        &dart.iter().map(|(n, _)| n.clone()).collect::<Vec<_>>(),
                    );
                    writeln!(out, "}}").unwrap();
                }
                VariantFields::Named(fields) => {
                    let dart: Vec<(String, String, bool)> = fields
                        .iter()
                        .map(|f| {
                            let optional = matches!(f.type_ref, TypeRef::Option(_));
                            Ok((field_name(&f.name), self.dart_type(&f.type_ref)?, optional))
                        })
                        .collect::<Result<_>>()?;
                    writeln!(
                        out,
                        "final class {vname}{generics} extends {name}{} {{",
                        type_args(generics)
                    )
                    .unwrap();
                    writeln!(out, "  const {vname}({{").unwrap();
                    for (fname, _, optional) in &dart {
                        if *optional {
                            writeln!(out, "    this.{fname},").unwrap();
                        } else {
                            writeln!(out, "    required this.{fname},").unwrap();
                        }
                    }
                    writeln!(out, "  }});").unwrap();
                    for (fname, ftype, _) in &dart {
                        writeln!(out, "  final {ftype} {fname};").unwrap();
                    }
                    write_value_equality(
                        out,
                        &vname,
                        generics,
                        &dart.iter().map(|(n, _, _)| n.clone()).collect::<Vec<_>>(),
                    );
                    writeln!(out, "}}").unwrap();
                }
            }
        }
        Ok(())
    }

    fn write_type_codec(&self, out: &mut String, ty: &TypeDef, name: &str) -> Result<()> {
        let codec_var = codec_name(name);
        if ty.generic_params.is_empty() {
            let expr = self.type_codec_expr(ty, name)?;
            writeln!(out, "final S.Codec<{name}> {codec_var} = {expr};").unwrap();
        } else {
            // Generic codec function: one Codec<P> param per generic parameter.
            let params = ty
                .generic_params
                .iter()
                .map(|p| format!("S.Codec<{p}> {}", codec_param(p)))
                .collect::<Vec<_>>()
                .join(", ");
            let generics = generic_decl(&ty.generic_params);
            let ret = format!("{name}{}", type_args(&generics));
            let expr = self.type_codec_expr(ty, &ret)?;
            writeln!(
                out,
                "S.Codec<{ret}> {codec_var}{generics}({params}) => {expr};"
            )
            .unwrap();
        }
        Ok(())
    }

    fn type_codec_expr(&self, ty: &TypeDef, type_name: &str) -> Result<String> {
        match &ty.kind {
            TypeDefKind::Alias(target) => self.codec_expr(target),
            TypeDefKind::Struct(fields) => self.struct_codec(type_name, fields),
            TypeDefKind::TupleStruct(types) => self.tuple_struct_codec(type_name, types),
            TypeDefKind::Enum(variants) => {
                if is_unit_only_enum(ty) {
                    Ok(format!(
                        "S.Codec<{type_name}>(\n  (out, v) => out.addByte(v.index),\n  (i) => {type_name}.values[i.takeByte()],\n)"
                    ))
                } else {
                    self.sealed_codec(type_name, variants)
                }
            }
        }
    }

    fn struct_codec(&self, type_name: &str, fields: &[FieldDef]) -> Result<String> {
        let mut enc = String::new();
        let mut dec = String::new();
        for field in fields {
            let fname = field_name(&field.name);
            let codec = self.codec_expr(&field.type_ref)?;
            writeln!(enc, "    {codec}.encInto(out, v.{fname});").unwrap();
            writeln!(dec, "    {fname}: {codec}.decFrom(i),").unwrap();
        }
        Ok(format!(
            "S.Codec<{type_name}>(\n  (out, v) {{\n{enc}  }},\n  (i) => {ctor}(\n{dec}  ),\n)",
            ctor = strip_type_args(type_name),
        ))
    }

    fn tuple_struct_codec(&self, type_name: &str, types: &[TypeRef]) -> Result<String> {
        let mut enc = String::new();
        let mut dec = String::new();
        for (i, ty) in types.iter().enumerate() {
            let codec = self.codec_expr(ty)?;
            writeln!(enc, "    {codec}.encInto(out, v.field{i});").unwrap();
            writeln!(dec, "    {codec}.decFrom(i),").unwrap();
        }
        Ok(format!(
            "S.Codec<{type_name}>(\n  (out, v) {{\n{enc}  }},\n  (i) => {ctor}(\n{dec}  ),\n)",
            ctor = strip_type_args(type_name),
        ))
    }

    fn sealed_codec(&self, type_name: &str, variants: &[VariantDef]) -> Result<String> {
        let base = strip_type_args(type_name);
        let mut enc = String::new();
        let mut dec = String::new();
        for (idx, variant) in variants.iter().enumerate() {
            let vname = format!("{base}{}", variant.name);
            match &variant.fields {
                VariantFields::Unit => {
                    writeln!(enc, "      case {vname}():\n        out.addByte({idx});").unwrap();
                    writeln!(dec, "      case {idx}:\n        return const {vname}();").unwrap();
                }
                VariantFields::Unnamed(types) => {
                    writeln!(enc, "      case {vname}():\n        out.addByte({idx});").unwrap();
                    let mut dec_args = Vec::new();
                    for (i, ty) in types.iter().enumerate() {
                        let codec = self.codec_expr(ty)?;
                        let accessor = if types.len() == 1 {
                            "value".to_string()
                        } else {
                            format!("field{i}")
                        };
                        writeln!(enc, "        {codec}.encInto(out, v.{accessor});").unwrap();
                        dec_args.push(format!("{codec}.decFrom(i)"));
                    }
                    writeln!(
                        dec,
                        "      case {idx}:\n        return {vname}({});",
                        dec_args.join(", ")
                    )
                    .unwrap();
                }
                VariantFields::Named(fields) => {
                    writeln!(enc, "      case {vname}():\n        out.addByte({idx});").unwrap();
                    let mut dec_args = Vec::new();
                    for field in fields {
                        let fname = field_name(&field.name);
                        let codec = self.codec_expr(&field.type_ref)?;
                        writeln!(enc, "        {codec}.encInto(out, v.{fname});").unwrap();
                        dec_args.push(format!("{fname}: {codec}.decFrom(i)"));
                    }
                    writeln!(
                        dec,
                        "      case {idx}:\n        return {vname}({});",
                        dec_args.join(", ")
                    )
                    .unwrap();
                }
            }
        }
        Ok(format!(
            "S.Codec<{type_name}>(\n  (out, v) {{\n    switch (v) {{\n{enc}    }}\n  }},\n  (i) {{\n    switch (i.takeByte()) {{\n{dec}      default:\n        throw FormatException('unknown {base} discriminant');\n    }}\n  }},\n)"
        ))
    }

    // --- wire_table.dart --------------------------------------------------

    fn wire_table(&self) -> Result<String> {
        let mut out = String::new();
        writeln!(out, "{HEADER}\nimport '../transport.dart';\n").unwrap();

        let mut entries: Vec<(u8, String)> = Vec::new();
        for trait_def in &self.api.traits {
            for method in &trait_def.methods {
                if !self.method_included(method)? {
                    continue;
                }
                let wc = wire_const(&trait_def.name, &method.name);
                let (sort, line) = self.wire_entry(method, &wc)?;
                entries.push((sort, line));
            }
        }
        entries.sort_by_key(|(s, _)| *s);
        for (_, line) in entries {
            writeln!(out, "{line}").unwrap();
        }
        Ok(out)
    }

    fn wire_entry(&self, method: &MethodDef, wc: &str) -> Result<(u8, String)> {
        match method.kind {
            MethodKind::Request => {
                let request = method
                    .wire
                    .request_id
                    .ok_or_else(|| anyhow!("method `{}` missing request_id", method.name))?;
                let response = method.wire.response_id.unwrap_or(request + 1);
                Ok((
                    request,
                    format!(
                        "const {wc} = RequestFrameIds(request: {request}, response: {response});"
                    ),
                ))
            }
            MethodKind::Subscription | MethodKind::ResultSubscription => {
                let start = method
                    .wire
                    .start_id
                    .ok_or_else(|| anyhow!("method `{}` missing start_id", method.name))?;
                let stop = method.wire.stop_id.unwrap_or(start + 1);
                let interrupt = method.wire.interrupt_id.unwrap_or(start + 2);
                let receive = method.wire.receive_id.unwrap_or(start + 3);
                Ok((
                    start,
                    format!(
                        "const {wc} = SubscriptionFrameIds(start: {start}, stop: {stop}, interrupt: {interrupt}, receive: {receive});"
                    ),
                ))
            }
        }
    }

    // --- client.dart ------------------------------------------------------

    fn client(&self) -> Result<String> {
        let mut out = String::new();
        writeln!(
            out,
            "{HEADER}\nimport 'dart:typed_data';\n\nimport '../result.dart';\nimport '../scale.dart' as S;\nimport '../transport.dart';\nimport 'types.dart';\nimport 'wire_table.dart' as W;\n"
        )
        .unwrap();
        writeln!(
            out,
            "const int defaultTruapiVersion = {};",
            self.target_version
        )
        .unwrap();
        writeln!(
            out,
            "const int defaultCodecVersion = {};\n",
            self.codec_version
        )
        .unwrap();

        let services = self.services()?;
        for (trait_def, methods) in &services {
            write_doc(&mut out, "", trait_def.docs.as_deref());
            writeln!(out, "class {}Client {{", trait_def.name).unwrap();
            writeln!(out, "  {}Client(this._transport);\n", trait_def.name).unwrap();
            writeln!(out, "  final Transport _transport;\n").unwrap();
            for method in methods {
                self.emit_method(&mut out, trait_def, method)?;
                writeln!(out).unwrap();
            }
            writeln!(out, "}}\n").unwrap();
        }

        // Facade.
        writeln!(out, "/// Typed TrUAPI client facade over a [Transport].").unwrap();
        writeln!(out, "class TruapiClient {{").unwrap();
        writeln!(out, "  TruapiClient(this._transport);\n").unwrap();
        writeln!(out, "  final Transport _transport;\n").unwrap();
        for (trait_def, _) in &services {
            let field = service_field(&trait_def.name);
            writeln!(
                out,
                "  late final {0}Client {field} = {0}Client(_transport);",
                trait_def.name
            )
            .unwrap();
        }
        writeln!(out, "}}\n").unwrap();

        self.emit_create_client(&mut out, &services)?;
        Ok(out)
    }

    fn emit_create_client(
        &self,
        out: &mut String,
        services: &[(&TraitDef, Vec<&MethodDef>)],
    ) -> Result<()> {
        let has_handshake = services.iter().any(|(t, methods)| {
            t.name == "System" && methods.iter().any(|m| m.name == "handshake")
        });

        if has_handshake {
            // The handshake (RFC 0009) negotiates the codec version. The host
            // may initiate it by pinging the product with a handshake request
            // frame; auto-answer it so the client is drop-in for such hosts.
            // Handshake is a fixed V1 method (wire version index 0).
            writeln!(
                out,
                "HandshakeResponder _handshakeResponder() => HandshakeResponder(\n  ids: W.{wc},\n  respond: (requestPayload, codecVersion) {{\n    final request = S.versioned(0, hostHandshakeRequestCodec).dec(requestPayload);\n    final responseCodec = S.versioned(0, S.result(S.unit, hostHandshakeErrorCodec));\n    final ok = request.codecVersion == codecVersion;\n    return responseCodec.enc(\n      ok\n          ? const Ok<S.Unit, HostHandshakeError>(S.unitValue)\n          : const Err<S.Unit, HostHandshakeError>(\n              HostHandshakeErrorUnsupportedProtocolVersion()),\n    );\n  }},\n);\n",
                wc = wire_const("System", "handshake"),
            )
            .unwrap();
        }

        let handshake_arg = if has_handshake {
            "\n    handshake: _handshakeResponder(),"
        } else {
            ""
        };

        writeln!(out, "/// Build a typed [TruapiClient] over [provider].").unwrap();
        writeln!(
            out,
            "TruapiClient createClient(\n  Provider provider, {{\n  int? truapiVersion,\n  int? codecVersion,\n}}) {{\n  final transport = createTransport(\n    provider,\n    truapiVersion: truapiVersion ?? defaultTruapiVersion,\n    codecVersion: codecVersion ?? defaultCodecVersion,{handshake_arg}\n  );\n  return TruapiClient(transport);\n}}"
        )
        .unwrap();
        Ok(())
    }

    fn emit_method(
        &self,
        out: &mut String,
        trait_def: &TraitDef,
        method: &MethodDef,
    ) -> Result<()> {
        let name = method_name(&method.name);
        let wc = wire_const(&trait_def.name, &method.name);
        let wire_version = self.method_wire_version(method)?;
        let payload = self.emit_payload(method, wire_version)?;
        write_doc(out, "  ", method.docs.as_deref());

        match (&method.kind, &method.return_type) {
            (MethodKind::Request, ReturnType::Result { ok, err }) => {
                let (ok_type, ok_codec) = self.resolve_inner(ok)?;
                let err_inner = call_error_inner(err).unwrap_or(err);
                let (err_type, err_codec) = self.resolve_inner(err_inner)?;
                let response_codec = match wire_version {
                    Some(v) => format!("S.versioned({}, S.result({ok_codec}, {err_codec}))", v - 1),
                    None => format!("S.result({ok_codec}, {err_codec})"),
                };
                writeln!(
                    out,
                    "  Future<Result<{ok_type}, {err_type}>> {name}({arg}) {{",
                    arg = payload.arg_decl
                )
                .unwrap();
                writeln!(
                    out,
                    "    return _transport.request<{ok_type}, {err_type}>(\n      ids: W.{wc},\n      payload: {pc}.enc({ax}),\n      decodeResponse: (p) => {response_codec}.dec(p),\n    );",
                    pc = payload.codec,
                    ax = payload.arg_expr,
                )
                .unwrap();
                writeln!(out, "  }}").unwrap();
            }
            (MethodKind::Subscription, ReturnType::Subscription(item)) => {
                let (item_type, item_codec) = self.resolve_inner(item)?;
                let decode_item = match wire_version {
                    Some(v) => format!("S.versioned({}, {item_codec})", v - 1),
                    None => item_codec,
                };
                writeln!(
                    out,
                    "  Stream<{item_type}> {name}({arg}) {{",
                    arg = payload.arg_decl
                )
                .unwrap();
                writeln!(
                    out,
                    "    return subscribeStream<{item_type}, Never>(\n      transport: _transport,\n      ids: W.{wc},\n      payload: {pc}.enc({ax}),\n      decodeItem: (p) => {decode_item}.dec(p),\n    );",
                    pc = payload.codec,
                    ax = payload.arg_expr,
                )
                .unwrap();
                writeln!(out, "  }}").unwrap();
            }
            (MethodKind::ResultSubscription, ReturnType::ResultSubscription { item, err }) => {
                let (item_type, item_codec) = self.resolve_inner(item)?;
                let err_inner = call_error_inner(err).unwrap_or(err);
                let (err_type, err_codec) = self.resolve_inner(err_inner)?;
                let decode_item = match wire_version {
                    Some(v) => format!("S.versioned({}, {item_codec})", v - 1),
                    None => item_codec,
                };
                let decode_interrupt = match wire_version {
                    Some(v) => format!("S.versioned({}, {err_codec})", v - 1),
                    None => err_codec,
                };
                writeln!(
                    out,
                    "  Stream<{item_type}> {name}({arg}) {{",
                    arg = payload.arg_decl
                )
                .unwrap();
                writeln!(
                    out,
                    "    return subscribeStream<{item_type}, {err_type}>(\n      transport: _transport,\n      ids: W.{wc},\n      payload: {pc}.enc({ax}),\n      decodeItem: (p) => {decode_item}.dec(p),\n      decodeInterrupt: (p) => {decode_interrupt}.dec(p),\n    );",
                    pc = payload.codec,
                    ax = payload.arg_expr,
                )
                .unwrap();
                writeln!(out, "  }}").unwrap();
            }
            (kind, ret) => bail!(
                "method `{}` kind {:?} does not match return {:?}",
                method.name,
                kind,
                ret
            ),
        }
        Ok(())
    }

    /// Lowered request payload: the public arg declaration, the value
    /// expression, and the wire codec (already versioned).
    fn emit_payload(&self, method: &MethodDef, wire_version: Option<u32>) -> Result<Payload> {
        match method.params.as_slice() {
            [] => {
                let version = wire_version.unwrap_or(1);
                Ok(Payload {
                    arg_decl: String::new(),
                    arg_expr: "S.unitValue".to_string(),
                    codec: format!("S.versioned({}, S.unit)", version - 1),
                })
            }
            [param] => {
                if let TypeRef::Named { name, args } = &param.type_ref
                    && args.is_empty()
                    && let Some(wrapper) = self.wrappers.get(name)
                {
                    let (version, kind) = self.select(wrapper)?;
                    return Ok(match kind {
                        WrapKind::Unit => Payload {
                            arg_decl: String::new(),
                            arg_expr: "S.unitValue".to_string(),
                            codec: format!("S.versioned({}, S.unit)", version - 1),
                        },
                        WrapKind::Tuple(inner) => Payload {
                            arg_decl: format!("{} request", self.dart_type(inner)?),
                            arg_expr: "request".to_string(),
                            codec: format!(
                                "S.versioned({}, {})",
                                version - 1,
                                self.codec_expr(inner)?
                            ),
                        },
                    });
                }
                // Non-wrapper single param (unversioned).
                Ok(Payload {
                    arg_decl: format!("{} request", self.dart_type(&param.type_ref)?),
                    arg_expr: "request".to_string(),
                    codec: self.codec_expr(&param.type_ref)?,
                })
            }
            _ => bail!(
                "method `{}` has more than one request parameter",
                method.name
            ),
        }
    }

    /// Resolve a (possibly versioned-wrapper) type to its public Dart type and
    /// its inner codec (no version byte — the version is applied by the caller).
    fn resolve_inner(&self, ty: &TypeRef) -> Result<(String, String)> {
        if let TypeRef::Named { name, args } = ty
            && args.is_empty()
            && let Some(wrapper) = self.wrappers.get(name)
        {
            let (_, kind) = self.select(wrapper)?;
            return Ok(match kind {
                WrapKind::Unit => ("S.Unit".to_string(), "S.unit".to_string()),
                WrapKind::Tuple(inner) => (self.dart_type(inner)?, self.codec_expr(inner)?),
            });
        }
        Ok((self.dart_type(ty)?, self.codec_expr(ty)?))
    }

    // --- shared helpers ---------------------------------------------------

    fn services(&self) -> Result<Vec<(&'a TraitDef, Vec<&'a MethodDef>)>> {
        let by_name: HashMap<&str, &TraitDef> = self
            .api
            .traits
            .iter()
            .map(|t| (t.name.as_str(), t))
            .collect();
        let mut out = Vec::new();
        for name in &self.api.public_trait_order {
            let Some(trait_def) = by_name.get(name.as_str()).copied() else {
                bail!("trait `{name}` in TrUApi but not extracted");
            };
            let methods = trait_def
                .methods
                .iter()
                .filter_map(|m| match self.method_included(m) {
                    Ok(true) => Some(Ok(m)),
                    Ok(false) => None,
                    Err(e) => Some(Err(e)),
                })
                .collect::<Result<Vec<_>>>()?;
            if !methods.is_empty() {
                out.push((trait_def, methods));
            }
        }
        Ok(out)
    }

    fn method_included(&self, method: &MethodDef) -> Result<bool> {
        let names = self.method_wrappers(method);
        if names.is_empty() {
            return Ok(true);
        }
        Ok(self.method_wire_version(method)?.is_some())
    }

    fn method_wire_version(&self, method: &MethodDef) -> Result<Option<u32>> {
        let names = self.method_wrappers(method);
        if names.is_empty() {
            return Ok(None);
        }
        let mut common: Option<Vec<u32>> = None;
        for name in names {
            let wrapper = self
                .wrappers
                .get(&name)
                .ok_or_else(|| anyhow!("unknown wrapper `{name}`"))?;
            let versions: Vec<u32> = wrapper
                .variants
                .keys()
                .filter(|v| **v <= self.target_version)
                .copied()
                .collect();
            common = Some(match common {
                Some(c) => c.into_iter().filter(|v| versions.contains(v)).collect(),
                None => versions,
            });
        }
        Ok(common.and_then(|v| v.into_iter().max()))
    }

    fn method_wrappers(&self, method: &MethodDef) -> Vec<String> {
        let mut names = Vec::new();
        for param in &method.params {
            self.collect_wrappers(&param.type_ref, &mut names);
        }
        match &method.return_type {
            ReturnType::Result { ok, err } => {
                self.collect_wrappers(ok, &mut names);
                self.collect_wrappers(call_error_inner(err).unwrap_or(err), &mut names);
            }
            ReturnType::Subscription(item) => self.collect_wrappers(item, &mut names),
            ReturnType::ResultSubscription { item, err } => {
                self.collect_wrappers(item, &mut names);
                self.collect_wrappers(call_error_inner(err).unwrap_or(err), &mut names);
            }
        }
        names.sort();
        names.dedup();
        names
    }

    fn collect_wrappers(&self, ty: &TypeRef, names: &mut Vec<String>) {
        match ty {
            TypeRef::Named { name, args } => {
                if args.is_empty() && self.wrappers.contains_key(name) {
                    names.push(name.clone());
                }
                for arg in args {
                    self.collect_wrappers(arg, names);
                }
            }
            TypeRef::Vec(inner) | TypeRef::Option(inner) | TypeRef::Array(inner, _) => {
                self.collect_wrappers(inner, names)
            }
            TypeRef::Tuple(items) => items.iter().for_each(|i| self.collect_wrappers(i, names)),
            TypeRef::Primitive(_) | TypeRef::Generic(_) | TypeRef::Unit => {}
        }
    }

    fn select<'w>(&self, wrapper: &'w Wrapper) -> Result<(u32, &'w WrapKind)> {
        wrapper
            .variants
            .iter()
            .filter(|(v, _)| **v <= self.target_version)
            .max_by_key(|(v, _)| **v)
            .map(|(v, k)| (*v, k))
            .ok_or_else(|| anyhow!("versioned wrapper has no variant <= target"))
    }

    // --- type & codec lowering -------------------------------------------

    fn dart_type(&self, ty: &TypeRef) -> Result<String> {
        match ty {
            TypeRef::Primitive(p) => Ok(dart_primitive_type(p)?.to_string()),
            TypeRef::Named { name, args } => {
                if args.is_empty()
                    && let Some(wrapper) = self.wrappers.get(name)
                {
                    let (_, kind) = self.select(wrapper)?;
                    return Ok(match kind {
                        WrapKind::Unit => "S.Unit".to_string(),
                        WrapKind::Tuple(inner) => self.dart_type(inner)?,
                    });
                }
                let base = public_name(name);
                if args.is_empty() {
                    Ok(base)
                } else {
                    let args = args
                        .iter()
                        .map(|a| self.dart_type(a))
                        .collect::<Result<Vec<_>>>()?
                        .join(", ");
                    Ok(format!("{base}<{args}>"))
                }
            }
            TypeRef::Vec(inner) | TypeRef::Array(inner, _) => match inner.as_ref() {
                TypeRef::Primitive(p) if p == "u8" => Ok("Uint8List".to_string()),
                _ => Ok(format!("List<{}>", self.dart_type(inner)?)),
            },
            TypeRef::Option(inner) => Ok(format!("{}?", self.dart_type(inner)?)),
            TypeRef::Tuple(items) => match items.len() {
                0 => Ok("S.Unit".to_string()),
                1 => self.dart_type(&items[0]),
                _ => {
                    let parts = items
                        .iter()
                        .map(|i| self.dart_type(i))
                        .collect::<Result<Vec<_>>>()?
                        .join(", ");
                    Ok(format!("({parts})"))
                }
            },
            TypeRef::Generic(name) => Ok(name.clone()),
            TypeRef::Unit => Ok("S.Unit".to_string()),
        }
    }

    fn codec_expr(&self, ty: &TypeRef) -> Result<String> {
        match ty {
            TypeRef::Primitive(p) => Ok(dart_primitive_codec(p)?.to_string()),
            TypeRef::Named { name, args } => {
                if args.is_empty() && self.wrappers.contains_key(name) {
                    bail!("nested versioned wrapper `{name}` in codec position is unsupported");
                }
                let codec = codec_name(&public_name(name));
                if args.is_empty() {
                    Ok(codec)
                } else {
                    let args = args
                        .iter()
                        .map(|a| self.codec_expr(a))
                        .collect::<Result<Vec<_>>>()?
                        .join(", ");
                    Ok(format!("{codec}({args})"))
                }
            }
            TypeRef::Vec(inner) => match inner.as_ref() {
                TypeRef::Primitive(p) if p == "u8" => Ok("S.bytes".to_string()),
                _ => Ok(format!("S.vector({})", self.codec_expr(inner)?)),
            },
            TypeRef::Array(inner, len) => match inner.as_ref() {
                TypeRef::Primitive(p) if p == "u8" => Ok(format!("S.bytesFixed({len})")),
                _ => Ok(format!("S.vectorFixed({}, {len})", self.codec_expr(inner)?)),
            },
            TypeRef::Option(inner) => Ok(format!("S.option({})", self.codec_expr(inner)?)),
            TypeRef::Tuple(items) => match items.len() {
                0 => Ok("S.unit".to_string()),
                1 => self.codec_expr(&items[0]),
                n @ 2..=4 => {
                    let parts = items
                        .iter()
                        .map(|i| self.codec_expr(i))
                        .collect::<Result<Vec<_>>>()?
                        .join(", ");
                    Ok(format!("S.tuple{n}({parts})"))
                }
                _ => bail!("tuples with more than 4 elements are not supported"),
            },
            TypeRef::Generic(name) => Ok(codec_param(name)),
            TypeRef::Unit => Ok("S.unit".to_string()),
        }
    }
}

struct Payload {
    arg_decl: String,
    arg_expr: String,
    codec: String,
}

// --- free helpers ---------------------------------------------------------

fn detect_wrapper(ty: &TypeDef) -> Option<Wrapper> {
    if !ty.generic_params.is_empty() {
        return None;
    }
    let TypeDefKind::Enum(variants) = &ty.kind else {
        return None;
    };
    if variants.is_empty() {
        return None;
    }
    let mut map = BTreeMap::new();
    for variant in variants {
        let version = variant_version(&variant.name)?;
        let kind = match &variant.fields {
            VariantFields::Unit => WrapKind::Unit,
            VariantFields::Unnamed(types) if types.len() == 1 => WrapKind::Tuple(types[0].clone()),
            _ => return None,
        };
        map.insert(version, kind);
    }
    Some(Wrapper { variants: map })
}

fn variant_version(name: &str) -> Option<u32> {
    let rest = name.strip_prefix('V')?;
    if rest.is_empty() {
        return None;
    }
    rest.parse().ok()
}

fn version_prefixed_type(name: &str) -> Option<(u32, &str)> {
    let rest = name.strip_prefix('V')?;
    if rest.len() < 3 {
        return None;
    }
    let (version, base) = rest.split_at(2);
    if base.is_empty() || !version.chars().all(|c| c.is_ascii_digit()) {
        return None;
    }
    Some((version.parse().ok()?, base))
}

fn public_name(name: &str) -> String {
    version_prefixed_type(name)
        .map(|(_, base)| base.to_string())
        .unwrap_or_else(|| name.to_string())
}

fn call_error_inner(ty: &TypeRef) -> Option<&TypeRef> {
    match ty {
        TypeRef::Named { name, args } if name == "CallError" && args.len() == 1 => Some(&args[0]),
        _ => None,
    }
}

fn is_unit_only_enum(ty: &TypeDef) -> bool {
    detect_wrapper(ty).is_none()
        && matches!(&ty.kind, TypeDefKind::Enum(variants)
            if !variants.is_empty()
                && variants.iter().all(|v| matches!(v.fields, VariantFields::Unit)))
}

fn dart_primitive_type(p: &str) -> Result<&'static str> {
    Ok(match p {
        "bool" => "bool",
        "u8" | "u16" | "u32" | "i8" | "i16" | "i32" => "int",
        "u64" | "u128" | "i64" | "i128" => "BigInt",
        "compact" => "BigInt",
        "optionBool" => "bool?",
        "str" => "String",
        "f32" | "f64" => "double",
        other => bail!("unsupported primitive `{other}` in Dart type generation"),
    })
}

fn dart_primitive_codec(p: &str) -> Result<&'static str> {
    Ok(match p {
        "bool" => "S.boolCodec",
        "u8" => "S.u8",
        "u16" => "S.u16",
        "u32" => "S.u32",
        "u64" => "S.u64",
        "u128" => "S.u128",
        "i8" => "S.i8",
        "i16" => "S.i16",
        "i32" => "S.i32",
        "i64" => "S.i64",
        "i128" => "S.i128",
        "compact" => "S.compact",
        "optionBool" => "S.optionBool",
        "str" => "S.str",
        other => bail!("unsupported primitive `{other}` in Dart codec generation"),
    })
}

fn codec_name(type_name: &str) -> String {
    format!("{}Codec", type_name.to_case(Case::Camel))
}

fn codec_param(generic: &str) -> String {
    format!("{}Codec", generic.to_case(Case::Camel))
}

fn field_name(name: &str) -> String {
    sanitize_ident(&name.to_case(Case::Camel))
}

fn method_name(name: &str) -> String {
    sanitize_ident(&strip_method_prefix(name).to_case(Case::Camel))
}

fn enum_value_name(name: &str) -> String {
    sanitize_ident(&name.to_case(Case::Camel))
}

fn service_field(trait_name: &str) -> String {
    sanitize_ident(&trait_name.to_case(Case::Camel))
}

fn wire_const(trait_name: &str, method_name: &str) -> String {
    format!("{trait_name}_{method_name}").to_case(Case::Camel)
}

fn strip_method_prefix(name: &str) -> String {
    for prefix in ["host_", "remote_", "product_"] {
        if let Some(rest) = name.strip_prefix(prefix) {
            return rest.to_string();
        }
    }
    name.to_string()
}

fn generic_decl(params: &[String]) -> String {
    if params.is_empty() {
        String::new()
    } else {
        format!("<{}>", params.join(", "))
    }
}

/// `<P, Q>` → `<P, Q>` reused as type-argument list (identity here, but kept
/// distinct for clarity at call sites).
fn type_args(generics: &str) -> String {
    generics.to_string()
}

/// Drop the generic parameter list from a type name to get its constructor
/// reference (e.g. `Component<P>` → `Component`).
fn strip_type_args(type_name: &str) -> String {
    match type_name.find('<') {
        Some(idx) => type_name[..idx].to_string(),
        None => type_name.to_string(),
    }
}

fn sanitize_ident(name: &str) -> String {
    const RESERVED: &[&str] = &[
        "abstract",
        "as",
        "assert",
        "async",
        "await",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "covariant",
        "default",
        "deferred",
        "do",
        "dynamic",
        "else",
        "enum",
        "export",
        "extends",
        "extension",
        "external",
        "factory",
        "false",
        "final",
        "finally",
        "for",
        "Function",
        "get",
        "hide",
        "if",
        "implements",
        "import",
        "in",
        "interface",
        "is",
        "late",
        "library",
        "mixin",
        "new",
        "null",
        "on",
        "operator",
        "part",
        "required",
        "rethrow",
        "return",
        "set",
        "show",
        "static",
        "super",
        "switch",
        "sync",
        "this",
        "throw",
        "true",
        "try",
        "typedef",
        "var",
        "void",
        "while",
        "with",
        "yield",
    ];
    if name.is_empty() {
        return "field".to_string();
    }
    if RESERVED.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Emit value-equality (`==`/`hashCode`) and `toString` for a generated class.
fn write_value_equality(out: &mut String, name: &str, generics: &str, fields: &[String]) {
    let type_with_generics = format!("{name}{}", type_args(generics));
    if fields.is_empty() {
        writeln!(out, "  @override").unwrap();
        writeln!(
            out,
            "  bool operator ==(Object other) => other is {type_with_generics};"
        )
        .unwrap();
        writeln!(out, "  @override").unwrap();
        writeln!(out, "  int get hashCode => {};", hash_seed(name)).unwrap();
        writeln!(out, "  @override").unwrap();
        writeln!(out, "  String toString() => '{name}()';").unwrap();
        return;
    }
    let cmp = fields
        .iter()
        .map(|f| format!("other.{f} == {f}"))
        .collect::<Vec<_>>()
        .join(" && ");
    writeln!(out, "  @override").unwrap();
    writeln!(
        out,
        "  bool operator ==(Object other) => other is {type_with_generics} && {cmp};"
    )
    .unwrap();
    let hash_args = fields.join(", ");
    writeln!(out, "  @override").unwrap();
    if fields.len() == 1 {
        writeln!(out, "  int get hashCode => {hash_args}.hashCode;").unwrap();
    } else {
        writeln!(out, "  int get hashCode => Object.hash({hash_args});").unwrap();
    }
    let to_str = fields
        .iter()
        .map(|f| format!("{f}: ${f}"))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(out, "  @override").unwrap();
    writeln!(out, "  String toString() => '{name}({to_str})';").unwrap();
}

fn hash_seed(name: &str) -> String {
    // Stable nonzero seed for fieldless classes.
    format!("{}", name.len() as u32 + 1)
}

/// Forward a Rust doc comment as Dart `///` lines, dropping ` ```ts ` example
/// blocks (which target the TypeScript playground).
fn write_doc(out: &mut String, indent: &str, docs: Option<&str>) {
    let Some(text) = docs else {
        return;
    };
    let mut in_ts = false;
    let mut lines: Vec<String> = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed == "```ts" {
            in_ts = true;
            continue;
        }
        if in_ts {
            if trimmed == "```" {
                in_ts = false;
            }
            continue;
        }
        lines.push(
            line.strip_prefix(' ')
                .unwrap_or(line)
                .trim_end()
                .to_string(),
        );
    }
    while lines.last().map(|l| l.trim().is_empty()).unwrap_or(false) {
        lines.pop();
    }
    while lines.first().map(|l| l.trim().is_empty()).unwrap_or(false) {
        lines.remove(0);
    }
    for line in lines {
        if line.is_empty() {
            writeln!(out, "{indent}///").unwrap();
        } else {
            writeln!(out, "{indent}/// {line}").unwrap();
        }
    }
}
