use anyhow::{Context, Result};
use clap::Parser;
use std::path::PathBuf;
use std::str::FromStr;

mod platform;
mod rust;
mod rustdoc;
mod ts;

#[derive(Parser)]
#[command(
    name = "truapi-codegen",
    about = "Generate TS client from TrUAPI Rust traits"
)]
struct Cli {
    /// Path to rustdoc JSON file (generated by `cargo +nightly rustdoc -p truapi --output-format json`)
    #[arg(short, long)]
    input: String,

    /// Output directory for generated files
    #[arg(short, long, default_value = "generated")]
    output: String,

    /// TrUAPI protocol version the **client** package is built against.
    ///
    /// Only affects the `@parity/truapi` client surface (and the playground
    /// and client-examples derived from it). The `@parity/truapi-host`
    /// output always covers every wire version a wrapper has shipped: a
    /// host must be able to dispatch frames from any client version it has
    /// shipped to.
    ///
    /// Defaults to the highest version any versioned wrapper in the Rust
    /// trait surface exposes, so an unconfigured run produces a client
    /// that speaks the latest wire format. Pass `V<N>` or `<N>` (e.g.
    /// `V1`, `V2`, or `2`) to pin to an older version.
    #[arg(long)]
    client_version: Option<ProtocolVersionArg>,

    /// Wire codec version for generated handshake calls.
    #[arg(long, default_value_t = 1)]
    codec_version: u8,

    /// Output directory for generated playground metadata (optional).
    #[arg(long)]
    playground_output: Option<String>,

    /// Output directory for generated TypeScript client example snippets (optional).
    #[arg(long)]
    client_examples_output: Option<String>,

    /// Output directory for the generated `@parity/truapi-host` TypeScript surface (optional).
    #[arg(long)]
    host_output: Option<String>,

    /// Output directory for the generated Rust dispatcher / wire-table (optional).
    ///
    /// When set, emits `dispatcher.rs` and `wire_table.rs` for the
    /// `truapi-server` crate to include.
    #[arg(long)]
    rust_output: Option<PathBuf>,

    /// Path to rustdoc JSON for the `truapi-platform` crate (optional).
    ///
    /// When provided together with `--platform-ts-output`, walks the
    /// platform crate's capability traits and emits the typed TS
    /// `HostCallbacks` surface so all host implementations (TS, Kotlin via
    /// UniFFI, Swift via UniFFI) track the same Rust source.
    #[arg(long)]
    platform_input: Option<String>,

    /// Output directory for the generated typed `HostCallbacks` TypeScript
    /// surface (optional). Only honored when `--platform-input` is also set.
    #[arg(long)]
    platform_ts_output: Option<String>,
}

#[derive(Clone, Copy, Debug)]
struct ProtocolVersionArg(u32);

impl ProtocolVersionArg {
    fn number(self) -> u32 {
        self.0
    }
}

impl FromStr for ProtocolVersionArg {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let number = value.strip_prefix('V').unwrap_or(value);
        if number.is_empty() {
            return Err("version must be written as V<N> or <N>".to_string());
        }
        let number = number
            .parse::<u32>()
            .map_err(|_| "version must be written as V<N> or <N>".to_string())?;
        if number == 0 {
            return Err("version must be at least V1".to_string());
        }
        Ok(Self(number))
    }
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let input = &cli.input;
    let json = std::fs::read_to_string(&cli.input)
        .with_context(|| format!("reading rustdoc JSON from {input}"))?;
    let krate = rustdoc::parse(&json).with_context(|| format!("parsing {input}"))?;
    let api = rustdoc::extract_api(&krate)
        .with_context(|| format!("extracting API definition from {input}"))?;
    let output = &cli.output;
    let client_version = cli
        .client_version
        .map(|v| v.number())
        .unwrap_or_else(|| ts::latest_wire_version(&api));
    ts::generate(&api, output, client_version, cli.codec_version)
        .with_context(|| format!("writing TypeScript client to {output}"))?;
    let codec_version = cli.codec_version;
    println!(
        "Generated TypeScript client for TrUAPI V{client_version} codec {codec_version} in {output}",
    );
    if let Some(path) = &cli.playground_output {
        ts::generate_playground_services(&api, path, client_version)
            .with_context(|| format!("writing playground metadata to {path}"))?;
        println!("Generated playground metadata in {path}");
    }
    if let Some(path) = &cli.client_examples_output {
        ts::generate_client_examples(&api, path, client_version)
            .with_context(|| format!("writing client examples to {path}"))?;
        println!("Generated client examples in {path}");
    }
    if let Some(path) = &cli.host_output {
        ts::generate_host(&api, path).with_context(|| format!("writing host package to {path}"))?;
        println!("Generated host package in {path}");
    }
    if let Some(path) = &cli.rust_output {
        rust::generate(&api, path)
            .with_context(|| format!("writing Rust dispatcher to {}", path.display()))?;
        println!("Wrote Rust dispatcher to {}", path.display());
    }
    if let (Some(input), Some(output)) = (&cli.platform_input, &cli.platform_ts_output) {
        let json = std::fs::read_to_string(input)
            .with_context(|| format!("reading platform rustdoc JSON from {input}"))?;
        let krate =
            rustdoc::parse(&json).with_context(|| format!("parsing platform rustdoc {input}"))?;
        let definition = platform::extract(&krate)
            .with_context(|| format!("extracting platform definition from {input}"))?;
        ts::generate_host_callbacks(&definition, output)
            .with_context(|| format!("writing host callbacks TS to {output}"))?;
        println!("Generated typed HostCallbacks TS surface in {output}");
    } else if cli.platform_input.is_some() != cli.platform_ts_output.is_some() {
        anyhow::bail!("--platform-input and --platform-ts-output must be provided together");
    }
    Ok(())
}
