//! Rust dispatcher code generation from extracted API definitions.
//!
//! Emits the wire dispatcher that the server uses to route incoming requests
//! to trait methods, decoding inner request types, re-wrapping them as
//! versioned enums, and unwrapping the versioned response back to the inner
//! type for the wire.

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::{bail, Result};

use crate::rustdoc::*;

/// Trait -> module name mapping is irregular so it must be hardcoded.
const TRAIT_MODULE_ORDER: &[(&str, &str)] = &[
    ("TrUApiCalls", "calls"),
    ("Permissions", "permissions"),
    ("LocalStorage", "local_storage"),
    ("AccountManagement", "account"),
    ("Signing", "signing"),
    ("Chat", "chat"),
    ("StatementStore", "statement_store"),
    ("Preimage", "preimage"),
    ("Payment", "payment"),
    ("EntropyDerivation", "entropy"),
    ("ChainInteraction", "chain"),
];

/// Whether a type is a single-variant `V<N>(..)` wrapper enum. The dispatcher
/// passes wrappers through opaquely, so we only need the set of names; the
/// inner shape no longer matters at codegen time.
fn is_versioned_wrapper(ty: &TypeDef) -> bool {
    if !ty.generic_params.is_empty() {
        return false;
    }
    let TypeDefKind::Enum(variants) = &ty.kind else {
        return false;
    };
    if variants.is_empty() {
        return false;
    }
    variants.iter().all(|v| {
        if !is_versioned_variant_name(&v.name) {
            return false;
        }
        match &v.fields {
            VariantFields::Unit | VariantFields::Named(_) => true,
            VariantFields::Unnamed(types) => types.len() == 1,
        }
    })
}

fn is_versioned_variant_name(name: &str) -> bool {
    let Some(rest) = name.strip_prefix('V') else {
        return false;
    };
    !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit())
}

fn collect_versioned_wrappers(api: &ApiDefinition) -> HashSet<String> {
    api.types
        .iter()
        .filter(|ty| is_versioned_wrapper(ty))
        .map(|ty| ty.name.clone())
        .collect()
}

/// Generates the Rust wire dispatcher into `output_dir/dispatcher.rs`.
pub fn generate(api: &ApiDefinition, output_dir: &str) -> Result<()> {
    fs::create_dir_all(output_dir)?;
    let dispatcher = generate_dispatcher(api)?;
    fs::write(Path::new(output_dir).join("dispatcher.rs"), dispatcher)?;
    let wire_table = generate_wire_table(api)?;
    fs::write(Path::new(output_dir).join("wire_table.rs"), wire_table)?;
    Ok(())
}

/// Builds the (discriminant, tag) → wire table from per-method `#[wire(...)]`
/// annotations. Request methods anchor on `request_id`; subscriptions anchor
/// on `start_id`. Omitted peer ids are inferred consecutively unless explicit
/// overrides are present. Duplicate ids and missing annotations both fail the
/// build.
fn generate_wire_table(api: &ApiDefinition) -> Result<String> {
    let mut entries: Vec<(u8, String)> = Vec::new();
    let mut seen: BTreeMap<u8, String> = BTreeMap::new();

    for trait_def in &api.traits {
        for method in &trait_def.methods {
            for (id, tag) in wire_table_entries(trait_def, method)? {
                if let Some(existing) = seen.insert(id, tag.clone()) {
                    bail!(
                        "wire id {} reused: `{}` and `{}` collide",
                        id,
                        existing,
                        tag
                    );
                }
                entries.push((id, tag));
            }
        }
    }

    entries.sort_by_key(|(id, _)| *id);

    let mut out = String::new();
    writeln!(
        out,
        "//! Wire-protocol discriminant table. Auto-generated by truapi-codegen. Do not edit."
    )
    .unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(
        out,
        "//! Each entry is (discriminant, tag). Tags are `<method>_<suffix>` where suffix is one"
    )
    .unwrap();
    writeln!(
        out,
        "//! of `request | response | start | stop | interrupt | receive`."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/// (id, tag) pairs sorted by id. Method ordering is part of the wire protocol;"
    )
    .unwrap();
    writeln!(
        out,
        "/// only ever append. Removed methods leave their slot empty (gap in id space)."
    )
    .unwrap();
    writeln!(out, "pub const WIRE_TABLE: &[(u8, &str)] = &[").unwrap();
    for (id, tag) in &entries {
        writeln!(out, "    ({}, \"{}\"),", id, tag).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/// Lookup discriminant for a tag string. O(N), but the table is small."
    )
    .unwrap();
    writeln!(out, "pub fn id_for_tag(tag: &str) -> Option<u8> {{").unwrap();
    writeln!(
        out,
        "    WIRE_TABLE.iter().find(|(_, t)| *t == tag).map(|(id, _)| *id)"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/// Lookup tag for a discriminant. O(log N) via binary search on the sorted table."
    )
    .unwrap();
    writeln!(out, "pub fn tag_for_id(id: u8) -> Option<&'static str> {{").unwrap();
    writeln!(
        out,
        "    WIRE_TABLE.binary_search_by_key(&id, |(i, _)| *i).ok().map(|idx| WIRE_TABLE[idx].1)"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "// Compile-time invariant: WIRE_TABLE must be sorted by id."
    )
    .unwrap();
    writeln!(
        out,
        "// Without this, `tag_for_id`'s binary search returns wrong results."
    )
    .unwrap();
    writeln!(out, "const _: () = {{").unwrap();
    writeln!(out, "    let mut i = 1;").unwrap();
    writeln!(out, "    while i < WIRE_TABLE.len() {{").unwrap();
    writeln!(out, "        assert!(WIRE_TABLE[i - 1].0 < WIRE_TABLE[i].0, \"WIRE_TABLE must be sorted by id\");").unwrap();
    writeln!(out, "        i += 1;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}};").unwrap();

    Ok(out)
}

fn wire_table_entries(trait_def: &TraitDef, method: &MethodDef) -> Result<Vec<(u8, String)>> {
    match method.kind {
        MethodKind::Request => {
            let request_id = method.wire.request_id.ok_or_else(|| {
                anyhow::anyhow!(
                    "method `{}::{}` is missing #[wire(request_id = N)] annotation",
                    trait_def.name,
                    method.name
                )
            })?;
            let response_id = method
                .wire
                .response_id
                .map_or_else(|| infer_wire_id(request_id, 1, &method.name), Ok)?;
            Ok(vec![
                (request_id, format!("{}_request", method.name)),
                (response_id, format!("{}_response", method.name)),
            ])
        }
        MethodKind::Subscription | MethodKind::ResultSubscription => {
            let start_id = method.wire.start_id.ok_or_else(|| {
                anyhow::anyhow!(
                    "method `{}::{}` is missing #[wire(start_id = N)] annotation",
                    trait_def.name,
                    method.name
                )
            })?;
            let stop_id = method
                .wire
                .stop_id
                .map_or_else(|| infer_wire_id(start_id, 1, &method.name), Ok)?;
            let interrupt_id = method
                .wire
                .interrupt_id
                .map_or_else(|| infer_wire_id(start_id, 2, &method.name), Ok)?;
            let receive_id = method
                .wire
                .receive_id
                .map_or_else(|| infer_wire_id(start_id, 3, &method.name), Ok)?;
            Ok(vec![
                (start_id, format!("{}_start", method.name)),
                (stop_id, format!("{}_stop", method.name)),
                (interrupt_id, format!("{}_interrupt", method.name)),
                (receive_id, format!("{}_receive", method.name)),
            ])
        }
    }
}

fn infer_wire_id(anchor_id: u8, offset: u8, method_name: &str) -> Result<u8> {
    anchor_id.checked_add(offset).ok_or_else(|| {
        anyhow::anyhow!(
            "wire id overflow on `{}` while inferring id from {}",
            method_name,
            anchor_id
        )
    })
}

fn generate_dispatcher(api: &ApiDefinition) -> Result<String> {
    let wrappers = collect_versioned_wrappers(api);
    let traits: HashMap<&str, &TraitDef> =
        api.traits.iter().map(|t| (t.name.as_str(), t)).collect();

    let mut ordered = Vec::new();
    for (trait_name, module) in TRAIT_MODULE_ORDER {
        let Some(trait_def) = traits.get(trait_name) else {
            bail!("Missing trait `{}` in extracted API", trait_name);
        };
        ordered.push((*module, *trait_def));
    }

    // Build per-module analysis eagerly so imports and function bodies agree.
    let mut modules = Vec::new();
    for (module, trait_def) in &ordered {
        modules.push(ModuleEmission::build(module, trait_def, &wrappers)?);
    }

    let mut out = String::new();
    write_header(&mut out);
    write_imports(&mut out, &modules);
    writeln!(out).unwrap();
    write_top_register(&mut out, &ordered);

    for module in &modules {
        writeln!(out).unwrap();
        out.push_str(&module.code);
    }

    Ok(out)
}

struct ModuleEmission {
    module: String,
    code: String,
    wrapper_types: BTreeSet<String>,
    runtime_helpers: BTreeSet<String>,
}

impl ModuleEmission {
    fn build(module: &str, trait_def: &TraitDef, wrappers: &HashSet<String>) -> Result<Self> {
        let mut wrapper_types = BTreeSet::new();
        let mut runtime_helpers = BTreeSet::new();

        let mut entries = Vec::with_capacity(trait_def.methods.len());
        for method in &trait_def.methods {
            let entry = MethodEmission::build(method, wrappers)?;
            entry.collect_types(&mut wrapper_types);
            entry.collect_runtime_helpers(&mut runtime_helpers);
            entries.push(entry);
        }

        let mut code = String::new();
        writeln!(
            code,
            "fn register_{}<P>(dispatcher: &mut Dispatcher, host: Arc<P>)",
            module
        )
        .unwrap();
        writeln!(code, "where").unwrap();
        writeln!(code, "    P: TrUApi + 'static,").unwrap();
        writeln!(code, "{{").unwrap();
        let last = entries.len().saturating_sub(1);
        for (idx, entry) in entries.iter().enumerate() {
            let host_expr = if idx == last { "host" } else { "host.clone()" };
            entry.write(&mut code, host_expr);
        }
        writeln!(code, "}}").unwrap();

        Ok(ModuleEmission {
            module: module.to_string(),
            code,
            wrapper_types,
            runtime_helpers,
        })
    }
}

struct MethodEmission {
    kind: EmissionKind,
    name: String,
    error_mapper: Option<String>,
    param_destructure: String,
    param_type: String,
    call_site: Option<String>,
    response_unwrap: Option<String>,
    subscription_item_type: Option<String>,
    subscription_item_unwrap: Option<String>,
    used_wrappers: Vec<String>,
}

enum EmissionKind {
    Request,
    Subscription,
    ResultSubscription,
}

impl MethodEmission {
    /// Wire-compat: request payloads and subscription items are full versioned
    /// wrappers (variant byte + inner). Request responses are returned to the
    /// runtime as wrapper values so it can encode `Versioned<Result<Ok, Err>>`
    /// for the negotiated version. The closure's `resp: Wrapper` annotation also
    /// keeps the wrapper import referenced (avoids `#[allow(unused_imports)]`).
    fn build(method: &MethodDef, wrappers: &HashSet<String>) -> Result<Self> {
        let mut used_wrappers = Vec::new();

        let (kind, return_type) = (&method.kind, &method.return_type);

        let request_wrapper =
            resolve_request_wrapper(&method.params, wrappers).ok_or_else(|| {
                anyhow::anyhow!(
                    "Method `{}`: expected a single versioned-wrapper request or no parameters",
                    method.name
                )
            })?;

        if let Some(name) = request_wrapper.as_deref() {
            used_wrappers.push(name.to_string());
        }

        // Wire compatibility note: the versioned wrapper variant byte is part of
        // the SCALE-encoded request payload (matches Novasama's `Enum({v1: ...})`
        // shape). The dispatcher therefore decodes the full request wrapper, with
        // no destructuring at the wire boundary. Variant unwrap happens inside the
        // trait impl (e.g. `let Wrapper::V2(inner) = req`).
        let (param_destructure, param_type, call_site) = match &request_wrapper {
            Some(wrapper_name) => (
                "request".to_string(),
                wrapper_name.clone(),
                Some("request".to_string()),
            ),
            // Subscription with no request param. Novasama still wraps the
            // start payload in `Enum({v1: _void})`, so a single variant byte
            // arrives on the wire even though the trait takes no arg. Decode
            // that byte as `u8` and discard, so the trailing-bytes invariant
            // in `decode_request_payload` holds.
            None => ("_: u8".to_string(), String::new(), None),
        };

        let emission_kind = match kind {
            MethodKind::Request => EmissionKind::Request,
            MethodKind::Subscription => EmissionKind::Subscription,
            MethodKind::ResultSubscription => EmissionKind::ResultSubscription,
        };

        let (error_mapper, response_unwrap, sub_item_type, sub_item_unwrap) = match return_type {
            ReturnType::Result { ok, err } => {
                let err_name = type_ref_root_name(err).ok_or_else(|| {
                    anyhow::anyhow!("Method `{}`: error type has no named root", method.name)
                })?;
                let resp_wrapper = resolve_response_wrapper(ok, wrappers).ok_or_else(|| {
                    anyhow::anyhow!(
                        "Method `{}`: response is not a versioned wrapper",
                        method.name
                    )
                })?;
                used_wrappers.push(resp_wrapper.to_string());
                let unwrap = format!("|resp: {}| resp", resp_wrapper);
                (Some(snake_case(err_name)), Some(unwrap), None, None)
            }
            ReturnType::Subscription(item) => {
                let item_wrapper = resolve_response_wrapper(item, wrappers).ok_or_else(|| {
                    anyhow::anyhow!(
                        "Method `{}`: subscription item is not a versioned wrapper",
                        method.name
                    )
                })?;
                used_wrappers.push(item_wrapper.to_string());
                let inner_type = item_wrapper.to_string();
                let sub_unwrap = "|x| x".to_string();
                (None, None, Some(inner_type), Some(sub_unwrap))
            }
            ReturnType::ResultSubscription { item, err } => {
                let err_name = type_ref_root_name(err).ok_or_else(|| {
                    anyhow::anyhow!("Method `{}`: error type has no named root", method.name)
                })?;
                let item_wrapper = resolve_response_wrapper(item, wrappers).ok_or_else(|| {
                    anyhow::anyhow!(
                        "Method `{}`: subscription item is not a versioned wrapper",
                        method.name
                    )
                })?;
                used_wrappers.push(item_wrapper.to_string());
                let inner_type = item_wrapper.to_string();
                let sub_unwrap = "|x| x".to_string();
                (
                    Some(snake_case(err_name)),
                    None,
                    Some(inner_type),
                    Some(sub_unwrap),
                )
            }
        };

        Ok(MethodEmission {
            kind: emission_kind,
            name: method.name.clone(),
            error_mapper,
            param_destructure,
            param_type,
            call_site,
            response_unwrap,
            subscription_item_type: sub_item_type,
            subscription_item_unwrap: sub_item_unwrap,
            used_wrappers,
        })
    }

    fn collect_types(&self, wrapper_types: &mut BTreeSet<String>) {
        for w in &self.used_wrappers {
            wrapper_types.insert(w.clone());
        }
    }

    fn collect_runtime_helpers(&self, helpers: &mut BTreeSet<String>) {
        match self.kind {
            EmissionKind::Request => {
                helpers.insert("register_request_cx".to_string());
            }
            EmissionKind::Subscription => {
                helpers.insert("register_subscription_cx".to_string());
                helpers.insert("subscription_items".to_string());
                helpers.insert("unit_interrupt".to_string());
            }
            EmissionKind::ResultSubscription => {
                helpers.insert("register_subscription_cx".to_string());
                helpers.insert("subscription_items_with_interrupt".to_string());
                helpers.insert("subscription_interrupt".to_string());
            }
        }
        if let Some(mapper) = &self.error_mapper {
            helpers.insert(mapper.clone());
        }
    }

    fn write(&self, out: &mut String, host_expr: &str) {
        match self.kind {
            EmissionKind::Request => {
                let mapper = self
                    .error_mapper
                    .as_deref()
                    .expect("request methods must have an error mapper");
                let call = self.call_site.as_deref().expect("request has call site");
                let unwrap = self
                    .response_unwrap
                    .as_deref()
                    .expect("request has response unwrap");
                let param_binding = self.closure_param_binding();

                writeln!(out, "    register_request_cx(").unwrap();
                writeln!(out, "        dispatcher,").unwrap();
                writeln!(out, "        \"{}\",", self.name).unwrap();
                writeln!(out, "        {},", host_expr).unwrap();
                writeln!(out, "        {},", mapper).unwrap();
                writeln!(out, "        |host, cx, {}| async move {{", param_binding).unwrap();
                writeln!(
                    out,
                    "            host.{}(&cx, {}).await.map({})",
                    self.name, call, unwrap
                )
                .unwrap();
                writeln!(out, "        }},").unwrap();
                writeln!(out, "    );").unwrap();
            }
            EmissionKind::Subscription => {
                let item_type = self
                    .subscription_item_type
                    .as_deref()
                    .expect("subscription has item type");
                let item_unwrap = self
                    .subscription_item_unwrap
                    .as_deref()
                    .expect("subscription has item unwrap");
                let param_binding = self.closure_param_binding();
                let mapper = self.error_mapper.as_deref().unwrap_or("unit_interrupt");

                writeln!(out, "    register_subscription_cx(").unwrap();
                writeln!(out, "        dispatcher,").unwrap();
                writeln!(out, "        \"{}\",", self.name).unwrap();
                writeln!(out, "        {},", host_expr).unwrap();
                writeln!(out, "        {},", mapper).unwrap();
                writeln!(out, "        |host, cx, {}| {{", param_binding).unwrap();
                writeln!(out, "            async move {{").unwrap();
                if let Some(call) = &self.call_site {
                    writeln!(
                        out,
                        "                let sub = host.{}(&cx, {}).await;",
                        self.name, call
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                let sub = host.{}(&cx).await;",
                        self.name
                    )
                    .unwrap();
                }
                writeln!(
                    out,
                    "                subscription_items::<{}, _>(sub.map({}))",
                    item_type, item_unwrap
                )
                .unwrap();
                writeln!(out, "            }}").unwrap();
                writeln!(out, "            .boxed()").unwrap();
                writeln!(out, "        }},").unwrap();
                writeln!(out, "    );").unwrap();
            }
            EmissionKind::ResultSubscription => {
                let mapper = self
                    .error_mapper
                    .as_deref()
                    .expect("result subscription has mapper");
                let call = self
                    .call_site
                    .as_deref()
                    .expect("result subscription has call");
                let item_type = self
                    .subscription_item_type
                    .as_deref()
                    .expect("result subscription has item type");
                let item_unwrap = self
                    .subscription_item_unwrap
                    .as_deref()
                    .expect("result subscription has item unwrap");
                let param_binding = self.closure_param_binding();

                writeln!(out, "    register_subscription_cx(").unwrap();
                writeln!(out, "        dispatcher,").unwrap();
                writeln!(out, "        \"{}\",", self.name).unwrap();
                writeln!(out, "        {},", host_expr).unwrap();
                writeln!(out, "        {},", mapper).unwrap();
                writeln!(out, "        |host, cx, {}| {{", param_binding).unwrap();
                writeln!(out, "            async move {{").unwrap();
                writeln!(
                    out,
                    "                match host.{}(&cx, {}).await {{",
                    self.name, call
                )
                .unwrap();
                writeln!(
                    out,
                    "                    Ok(sub) => subscription_items_with_interrupt::<{}, _, _>(sub.map({})),",
                    item_type, item_unwrap
                )
                .unwrap();
                writeln!(
                    out,
                    "                    Err(err) => subscription_interrupt::<{}, _>(err),",
                    item_type
                )
                .unwrap();
                writeln!(out, "                }}").unwrap();
                writeln!(out, "            }}").unwrap();
                writeln!(out, "            .boxed()").unwrap();
                writeln!(out, "        }},").unwrap();
                writeln!(out, "    );").unwrap();
            }
        }
    }

    fn closure_param_binding(&self) -> String {
        if self.param_type.is_empty() {
            self.param_destructure.clone()
        } else {
            format!("{}: {}", self.param_destructure, self.param_type)
        }
    }
}

fn resolve_request_wrapper(
    params: &[ParamDef],
    wrappers: &HashSet<String>,
) -> Option<Option<String>> {
    match params.len() {
        0 => Some(None),
        1 => {
            if let TypeRef::Named { name, args } = &params[0].type_ref {
                if args.is_empty() && wrappers.contains(name) {
                    return Some(Some(name.clone()));
                }
            }
            None
        }
        _ => None,
    }
}

fn resolve_response_wrapper<'a>(ty: &TypeRef, wrappers: &'a HashSet<String>) -> Option<&'a str> {
    if let TypeRef::Named { name, args } = ty {
        if args.is_empty() {
            return wrappers.get(name).map(String::as_str);
        }
    }
    None
}

fn type_ref_root_name(ty: &TypeRef) -> Option<&str> {
    if let TypeRef::Named { name, .. } = ty {
        Some(name.as_str())
    } else {
        None
    }
}

fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (idx, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if idx != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn write_header(out: &mut String) {
    writeln!(out, "//! Wire dispatcher for the unified `TrUApi` trait.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Auto-generated by truapi-codegen. Do not edit.").unwrap();
    writeln!(out).unwrap();
}

fn write_imports(out: &mut String, modules: &[ModuleEmission]) {
    let mut wrappers_by_module: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();
    let mut runtime: BTreeSet<String> = BTreeSet::new();

    for module in modules {
        wrappers_by_module
            .entry(module.module.as_str())
            .or_default()
            .extend(module.wrapper_types.iter().cloned());
        runtime.extend(module.runtime_helpers.iter().cloned());
    }
    runtime.insert("register_request_cx".to_string());
    runtime.insert("register_subscription_cx".to_string());

    writeln!(out, "use std::sync::Arc;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use futures::future::FutureExt;").unwrap();
    writeln!(out, "use futures::StreamExt;").unwrap();
    writeln!(out, "use truapi::api::TrUApi;").unwrap();

    for (module, items) in &wrappers_by_module {
        if items.is_empty() {
            continue;
        }
        writeln!(out, "use truapi::versioned::{}::{{", module).unwrap();
        for name in items {
            writeln!(out, "    {},", name).unwrap();
        }
        writeln!(out, "}};").unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "use crate::runtime::{{").unwrap();
    for name in &runtime {
        writeln!(out, "    {},", name).unwrap();
    }
    writeln!(out, "}};").unwrap();
    writeln!(out, "use crate::Dispatcher;").unwrap();
}

fn write_top_register(out: &mut String, ordered: &[(&str, &TraitDef)]) {
    writeln!(
        out,
        "pub(crate) fn register<P>(dispatcher: &mut Dispatcher, host: Arc<P>)"
    )
    .unwrap();
    writeln!(out, "where").unwrap();
    writeln!(out, "    P: TrUApi + 'static,").unwrap();
    writeln!(out, "{{").unwrap();
    let last = ordered.len().saturating_sub(1);
    for (idx, (module, _)) in ordered.iter().enumerate() {
        let host_expr = if idx == last { "host" } else { "host.clone()" };
        writeln!(out, "    register_{}(dispatcher, {});", module, host_expr).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

#[cfg(test)]
mod tests {
    //! Codegen-side unit tests. The codegen crate has no `lib.rs`, so we
    //! exercise private helpers from inside the module rather than via an
    //! integration test in `tests/`.

    use super::*;

    /// Build a synthetic `MethodDef` for a request method whose return type is
    /// a `Result<Wrapper, Err>` and whose single parameter is the same wrapper.
    fn make_request_method(name: &str, wire_id: u8) -> MethodDef {
        MethodDef {
            name: name.to_string(),
            kind: MethodKind::Request,
            params: vec![ParamDef {
                name: "request".to_string(),
                type_ref: TypeRef::Named {
                    name: "ReqWrapper".to_string(),
                    args: vec![],
                },
            }],
            return_type: ReturnType::Result {
                ok: TypeRef::Named {
                    name: "RespWrapper".to_string(),
                    args: vec![],
                },
                err: TypeRef::Named {
                    name: "ApiError".to_string(),
                    args: vec![],
                },
            },
            wire: WireAttrs {
                request_id: Some(wire_id),
                ..WireAttrs::default()
            },
            docs: None,
        }
    }

    fn parse_wire_table_entries(src: &str) -> Vec<(u8, String)> {
        // Lines look like `    (NN, "tag"),`.
        let mut out = Vec::new();
        for line in src.lines() {
            let trimmed = line.trim();
            let Some(rest) = trimmed.strip_prefix('(') else {
                continue;
            };
            let Some(rest) = rest.strip_suffix("),") else {
                continue;
            };
            let mut parts = rest.splitn(2, ',');
            let id = parts.next().unwrap().trim().parse::<u8>().unwrap();
            let tag = parts.next().unwrap().trim().trim_matches('"').to_string();
            out.push((id, tag));
        }
        out
    }

    /// Regression for `entries.sort_by_key(|(id, _)| *id)`. Even when the
    /// codegen sees methods declared in a non-monotonic order (e.g. trait
    /// authors group methods semantically rather than by id), the emitted
    /// `WIRE_TABLE` MUST be sorted, otherwise `tag_for_id`'s binary search
    /// returns wrong results and the compile-time `_: () = { ... }`
    /// invariant in the generated file would even refuse to build.
    #[test]
    fn generate_wire_table_sorts_entries_by_id() {
        // Methods declared OUT of id order: 50 first, then 10, then 30.
        let api = ApiDefinition {
            traits: vec![TraitDef {
                name: "Synthetic".to_string(),
                methods: vec![
                    make_request_method("z_method", 50),
                    make_request_method("a_method", 10),
                    make_request_method("m_method", 30),
                ],
                docs: None,
            }],
            types: vec![],
        };

        let src = generate_wire_table(&api).expect("generate_wire_table");
        let entries = parse_wire_table_entries(&src);

        // Each request method occupies 2 ids (request + response).
        let expected: Vec<(u8, String)> = vec![
            (10, "a_method_request".into()),
            (11, "a_method_response".into()),
            (30, "m_method_request".into()),
            (31, "m_method_response".into()),
            (50, "z_method_request".into()),
            (51, "z_method_response".into()),
        ];
        assert_eq!(
            entries, expected,
            "WIRE_TABLE was not sorted by id. Generated source:\n{src}",
        );

        // The emitted source also embeds a const-context assertion that the
        // table is sorted; smoke-check it shows up so a future refactor that
        // drops the guard fails this test.
        assert!(
            src.contains("WIRE_TABLE must be sorted by id"),
            "compile-time sort guard is missing from generated source",
        );
    }

    /// Duplicate `#[wire(...)]` annotations across methods must fail the
    /// build deterministically rather than silently overwriting an entry.
    #[test]
    fn generate_wire_table_rejects_duplicate_ids() {
        let api = ApiDefinition {
            traits: vec![TraitDef {
                name: "Synthetic".to_string(),
                methods: vec![
                    make_request_method("alpha", 10),
                    make_request_method("beta", 10), // collide on id 10
                ],
                docs: None,
            }],
            types: vec![],
        };
        let err = generate_wire_table(&api).expect_err("duplicate ids must error");
        let msg = format!("{err}");
        assert!(
            msg.contains("wire id 10 reused"),
            "unexpected error message: {msg}",
        );
    }

    /// A method missing `#[wire(...)]` must hard-error during codegen so
    /// no slot ever silently lacks a discriminant.
    #[test]
    fn generate_wire_table_rejects_missing_annotation() {
        let mut method = make_request_method("orphan", 0);
        method.wire = WireAttrs::default();
        let api = ApiDefinition {
            traits: vec![TraitDef {
                name: "Synthetic".to_string(),
                methods: vec![method],
                docs: None,
            }],
            types: vec![],
        };
        let err = generate_wire_table(&api).expect_err("missing annotation must error");
        let msg = format!("{err}");
        assert!(
            msg.contains("missing #[wire(request_id = N)]"),
            "unexpected error message: {msg}",
        );
    }

    fn make_subscription_method(name: &str, wire_id: u8) -> MethodDef {
        MethodDef {
            name: name.to_string(),
            kind: MethodKind::Subscription,
            params: vec![],
            return_type: ReturnType::Subscription(TypeRef::Named {
                name: "ItemWrapper".to_string(),
                args: vec![],
            }),
            wire: WireAttrs {
                start_id: Some(wire_id),
                ..WireAttrs::default()
            },
            docs: None,
        }
    }

    /// Bootstrap edge case: an `ApiDefinition` with no traits (or with traits
    /// that have no methods) must still produce a valid, compilable wire
    /// table source. The generated file is `include!`-ed by the dispatcher,
    /// so an emit failure here would block first-time codegen runs on a
    /// fresh codebase.
    #[test]
    fn generate_wire_table_handles_empty_input() {
        let cases = vec![
            ApiDefinition {
                traits: vec![],
                types: vec![],
            },
            ApiDefinition {
                traits: vec![TraitDef {
                    name: "Empty".to_string(),
                    methods: vec![],
                    docs: None,
                }],
                types: vec![],
            },
        ];
        for api in cases {
            let src = generate_wire_table(&api).expect("empty input must succeed");
            assert!(parse_wire_table_entries(&src).is_empty());
            // Slice declaration is emitted with a trailing newline before the
            // closing `];`, so the empty literal looks like `&[\n]`.
            assert!(
                src.contains("pub const WIRE_TABLE: &[(u8, &str)] = &[\n];"),
                "empty table should still be a valid empty slice. Got:\n{src}",
            );
            assert!(src.contains("pub fn id_for_tag"));
            assert!(src.contains("pub fn tag_for_id"));
            // The compile-time sort guard's `while i < WIRE_TABLE.len()` loop
            // is a no-op with an empty table, so the const block is still
            // emitted and well-formed.
            assert!(src.contains("WIRE_TABLE must be sorted by id"));
        }
    }

    /// Single-method subscription API → exactly 4 entries (start/stop/
    /// interrupt/receive) at consecutive ids. Verifies the per-method
    /// suffix expansion works for a minimal trait without sibling methods
    /// to mask off-by-ones.
    #[test]
    fn generate_wire_table_emits_four_entries_for_single_subscription() {
        let api = ApiDefinition {
            traits: vec![TraitDef {
                name: "Synthetic".to_string(),
                methods: vec![make_subscription_method("only_sub", 42)],
                docs: None,
            }],
            types: vec![],
        };
        let src = generate_wire_table(&api).expect("generate_wire_table");
        let entries = parse_wire_table_entries(&src);
        assert_eq!(
            entries,
            vec![
                (42, "only_sub_start".into()),
                (43, "only_sub_stop".into()),
                (44, "only_sub_interrupt".into()),
                (45, "only_sub_receive".into()),
            ],
        );
    }

    /// Wire ids that would overflow u8 when expanded for the 4-suffix
    /// subscription pattern must hard-error rather than silently wrap.
    /// E.g. base 253 + 3 = 256 → out of range.
    #[test]
    fn generate_wire_table_rejects_id_overflow() {
        let api = ApiDefinition {
            traits: vec![TraitDef {
                name: "Synthetic".to_string(),
                methods: vec![make_subscription_method("topples_off_end", 253)],
                docs: None,
            }],
            types: vec![],
        };
        let err = generate_wire_table(&api).expect_err("overflow must error");
        let msg = format!("{err}");
        assert!(
            msg.contains("overflow"),
            "unexpected overflow error message: {msg}",
        );
    }
}
