//! TypeScript code generation from extracted API definitions.

use std::collections::HashMap;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use anyhow::{bail, Result};

use crate::rustdoc::*;

#[derive(Default)]
struct CodecContext {
    generic_codecs: HashMap<String, String>,
}

/// A versioned enum wrapper like `enum HostSignPayloadRequest { V2(Inner) }`,
/// `enum HostCreateTransactionRequest { V2 { product_account_id, payload } }`,
/// or a multi-version enum `enum HostDevicePermissionRequest { V1(_), V2(_) }`.
///
/// The client generator unwraps the **latest** version at the method boundary
/// so callers keep working with inner types. Older versions are kept for
/// compatibility with pre-codegen products and only land on the server side;
/// the trait impl converts them through `From` (or matches explicitly).
#[derive(Debug, Clone)]
struct VersionedWrapper {
    /// Latest `V<N>` variant on the enum — what the client emits on outbound
    /// requests and expects on inbound responses.
    variant: String,
    kind: VersionedKind,
}

#[derive(Debug, Clone)]
enum VersionedKind {
    Unit,
    Tuple(TypeRef),
    Struct(Vec<FieldDef>),
}

fn detect_versioned_wrapper(ty: &TypeDef) -> Option<VersionedWrapper> {
    if !ty.generic_params.is_empty() {
        return None;
    }
    let TypeDefKind::Enum(variants) = &ty.kind else {
        return None;
    };
    if variants.is_empty() || !variants.iter().all(|v| is_versioned_variant_name(&v.name)) {
        return None;
    }
    // Pick the highest V<N> as the client-facing variant.
    let latest = variants
        .iter()
        .max_by_key(|v| version_number(&v.name).unwrap_or(0))?;
    let kind = match &latest.fields {
        VariantFields::Unit => VersionedKind::Unit,
        VariantFields::Unnamed(types) if types.len() == 1 => VersionedKind::Tuple(types[0].clone()),
        VariantFields::Named(fields) => VersionedKind::Struct(fields.clone()),
        _ => return None,
    };
    Some(VersionedWrapper {
        variant: latest.name.clone(),
        kind,
    })
}

fn is_versioned_variant_name(name: &str) -> bool {
    version_number(name).is_some()
}

fn version_number(name: &str) -> Option<u32> {
    let rest = name.strip_prefix('V')?;
    if rest.is_empty() {
        return None;
    }
    rest.parse().ok()
}

fn collect_versioned_wrappers(api: &ApiDefinition) -> HashMap<String, VersionedWrapper> {
    api.types
        .iter()
        .filter_map(|ty| detect_versioned_wrapper(ty).map(|w| (ty.name.clone(), w)))
        .collect()
}

fn versioned_wrapper_for<'a>(
    ty: &'a TypeRef,
    wrappers: &'a HashMap<String, VersionedWrapper>,
) -> Option<(&'a str, &'a VersionedWrapper)> {
    if let TypeRef::Named { name, args } = ty {
        if args.is_empty() {
            if let Some(wrapper) = wrappers.get(name) {
                return Some((name.as_str(), wrapper));
            }
        }
    }
    None
}

/// Generates the TypeScript client, types, and barrel files for an extracted
/// API definition into `output_dir`.
pub fn generate(api: &ApiDefinition, output_dir: &str) -> Result<()> {
    fs::create_dir_all(output_dir)?;

    let types_code = generate_types(api)?;
    fs::write(Path::new(output_dir).join("types.ts"), types_code)?;

    let client_code = generate_client(api)?;
    fs::write(Path::new(output_dir).join("client.ts"), client_code)?;

    let index_code = generate_index();
    fs::write(Path::new(output_dir).join("index.ts"), index_code)?;

    Ok(())
}

fn generate_index() -> String {
    "export * from './types.js';\nexport * from './client.js';\n".to_string()
}

fn generate_types(api: &ApiDefinition) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by truapi-codegen. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import * as S from '../scale.js';").unwrap();
    writeln!(out).unwrap();

    for ty in &api.types {
        write_type_definition(&mut out, ty)?;
        writeln!(out).unwrap();
        write_codec_definition(&mut out, ty)?;
        writeln!(out).unwrap();
    }

    Ok(out)
}

fn generate_client(api: &ApiDefinition) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by truapi-codegen. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import * as S from '../scale.js';").unwrap();
    writeln!(out, "import * as T from './types.js';").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export type Result<V, E> =").unwrap();
    writeln!(out, "  | {{ success: true; value: V }}").unwrap();
    writeln!(out, "  | {{ success: false; value: E }};").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "function mapResult<V, U, E>(result: Result<V, E>, map: (value: V) => U): Result<U, E> {{"
    )
    .unwrap();
    writeln!(
        out,
        "  return result.success ? {{ success: true, value: map(result.value) }} : result;"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface Subscription {{").unwrap();
    writeln!(out, "  unsubscribe: () => void;").unwrap();
    writeln!(out, "  subscriptionId: string;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "export interface TrUApiTransport {{").unwrap();
    writeln!(out, "  request<Request, Response>(method: string, value: Request, requestCodec: S.Codec<Request>, responseCodec: S.Codec<Response>): Promise<Response>;").unwrap();
    writeln!(out, "  subscribe<Start, Item, Interrupt = never>(method: string, value: Start, startCodec: S.Codec<Start>, itemCodec: S.Codec<Item>, callback: (data: Item) => void, interruptCodec?: S.Codec<Interrupt>, onInterrupt?: (data: Interrupt) => void): Subscription;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    let ctx = CodecContext::default();
    let wrappers = collect_versioned_wrappers(api);

    for trait_def in &api.traits {
        if trait_def.name == "TrUApi" {
            continue;
        }

        writeln!(out, "export class {}Client {{", trait_def.name).unwrap();
        writeln!(
            out,
            "  constructor(private readonly transport: TrUApiTransport) {{}}"
        )
        .unwrap();
        writeln!(out).unwrap();

        for method in &trait_def.methods {
            emit_method(&mut out, method, &wrappers, &ctx)?;
            writeln!(out).unwrap();
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "export interface TrUApiClient {{").unwrap();
    for trait_def in &api.traits {
        if trait_def.name == "TrUApi" {
            continue;
        }
        let field = to_camel_case(&trait_def.name);
        writeln!(out, "  readonly {}: {}Client;", field, trait_def.name).unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/** Creates the generated client facade by binding each service namespace to the"
    )
    .unwrap();
    writeln!(out, " * shared transport instance. */").unwrap();

    writeln!(
        out,
        "export function createClient(transport: TrUApiTransport): TrUApiClient {{"
    )
    .unwrap();
    writeln!(out, "  return {{").unwrap();
    for trait_def in &api.traits {
        if trait_def.name == "TrUApi" {
            continue;
        }
        let field = to_camel_case(&trait_def.name);
        writeln!(
            out,
            "    {}: new {}Client(transport),",
            field, trait_def.name
        )
        .unwrap();
    }
    writeln!(out, "  }};").unwrap();
    writeln!(out, "}}").unwrap();

    Ok(out)
}

/// Lowered method payload: the TS param list, the value expression passed to
/// the transport, and the codec used to encode it. The public method
/// signature stays ergonomic (inner v02 types), while the actual wire payload
/// is the versioned wrapper expected by the Rust dispatcher.
struct PayloadEmission {
    param_list: String,
    payload_expr: String,
    payload_codec: String,
}

fn emit_payload(
    params: &[ParamDef],
    wrappers: &HashMap<String, VersionedWrapper>,
    ctx: &CodecContext,
) -> Result<PayloadEmission> {
    // The unified contract always takes a single versioned-wrapper arg. On the
    // TS side callers pass the inner value directly, but we re-wrap before
    // handing bytes to the transport. The Rust dispatcher decodes the full
    // wrapper (variant byte included) from the wire payload; see
    // `rust_dispatcher::MethodEmission`.
    if params.len() == 1 {
        if let Some((wrapper_name, wrapper)) = versioned_wrapper_for(&params[0].type_ref, wrappers)
        {
            return match &wrapper.kind {
                VersionedKind::Unit => Ok(PayloadEmission {
                    param_list: String::new(),
                    payload_expr: format!(
                        "({{ tag: \"{}\", value: undefined }} as T.{})",
                        wrapper.variant, wrapper_name
                    ),
                    payload_codec: format!("T.{}", wrapper_name),
                }),
                VersionedKind::Tuple(inner) => {
                    let arg_name = param_name(&params[0].name);
                    let inner_ts = ts_type_qualified(inner)?;
                    Ok(PayloadEmission {
                        param_list: format!("{}: {}", arg_name, inner_ts),
                        payload_expr: format!(
                            "({{ tag: \"{}\", value: {} }} as T.{})",
                            wrapper.variant, arg_name, wrapper_name
                        ),
                        payload_codec: format!("T.{}", wrapper_name),
                    })
                }
                VersionedKind::Struct(fields) => {
                    let mut param_parts = Vec::new();
                    let mut value_parts = Vec::new();
                    for field in fields {
                        let (ts_name, optional) = ts_field_name(&field.name, &field.type_ref);
                        let arg = param_name(&field.name);
                        let ty_ts = if optional {
                            ts_inner_option_with_named(&field.type_ref, true)?
                        } else {
                            ts_type_with_named(&field.type_ref, true)?
                        };
                        let suffix = if optional { "?" } else { "" };
                        param_parts.push(format!("{}{}: {}", arg, suffix, ty_ts));
                        if arg == ts_name {
                            value_parts.push(arg.clone());
                        } else {
                            value_parts.push(format!("{}: {}", ts_name, arg));
                        }
                    }
                    Ok(PayloadEmission {
                        param_list: param_parts.join(", "),
                        payload_expr: format!(
                            "({{ tag: \"{}\", value: {{ {} }} }} as T.{})",
                            wrapper.variant,
                            value_parts.join(", "),
                            wrapper_name
                        ),
                        payload_codec: format!("T.{}", wrapper_name),
                    })
                }
            };
        }
    }

    Ok(PayloadEmission {
        param_list: ts_param_list(params)?,
        payload_expr: payload_expression(params)?,
        payload_codec: method_payload_codec_expr(params, true, ctx)?,
    })
}

/// Response shape after the versioned wrapper is stripped. TS callers see the
/// inner type, while the wire decoder consumes the full versioned wrapper.
struct ResponseEmission {
    inner_type_ts: String,
    wire_type_ts: String,
    wire_codec_expr: String,
    unwrap_expr: String,
}

fn emit_response(
    ty: &TypeRef,
    wrappers: &HashMap<String, VersionedWrapper>,
    ctx: &CodecContext,
) -> Result<ResponseEmission> {
    if let Some((wrapper_name, wrapper)) = versioned_wrapper_for(ty, wrappers) {
        return match &wrapper.kind {
            VersionedKind::Unit => Ok(ResponseEmission {
                inner_type_ts: "undefined".to_string(),
                wire_type_ts: format!("T.{}", wrapper_name),
                wire_codec_expr: format!("T.{}", wrapper_name),
                unwrap_expr: "(value) => value.value".to_string(),
            }),
            VersionedKind::Tuple(inner) => Ok(ResponseEmission {
                inner_type_ts: ts_type_qualified(inner)?,
                wire_type_ts: format!("T.{}", wrapper_name),
                wire_codec_expr: format!("T.{}", wrapper_name),
                unwrap_expr: "(value) => value.value".to_string(),
            }),
            VersionedKind::Struct(fields) => {
                let inline_ty = inline_object_type(fields, true)?;
                Ok(ResponseEmission {
                    inner_type_ts: inline_ty,
                    wire_type_ts: format!("T.{}", wrapper_name),
                    wire_codec_expr: format!("T.{}", wrapper_name),
                    unwrap_expr: "(value) => value.value".to_string(),
                })
            }
        };
    }

    Ok(ResponseEmission {
        inner_type_ts: ts_type_qualified(ty)?,
        wire_type_ts: ts_type_qualified(ty)?,
        wire_codec_expr: codec_expr(ty, true, ctx)?,
        unwrap_expr: "(value) => value".to_string(),
    })
}

fn emit_method(
    out: &mut String,
    method: &MethodDef,
    wrappers: &HashMap<String, VersionedWrapper>,
    ctx: &CodecContext,
) -> Result<()> {
    let ts_method_name = to_camel_case(&strip_prefix(&method.name));
    let payload = emit_payload(&method.params, wrappers, ctx)?;

    match (&method.kind, &method.return_type) {
        (MethodKind::Request, ReturnType::Result { ok, err }) => {
            let err_type = ts_type_qualified(err)?;
            let err_codec = codec_expr(err, true, ctx)?;
            let response = emit_response(ok, wrappers, ctx)?;
            let response_codec = format!("S.result({}, {})", response.wire_codec_expr, err_codec);

            writeln!(
                out,
                "  async {}({}): Promise<Result<{}, {}>> {{",
                ts_method_name, payload.param_list, response.inner_type_ts, err_type
            )
            .unwrap();
            writeln!(
                out,
                "    const result = await this.transport.request(\"{}\", {}, {}, {}) as Result<{}, {}>;",
                method.name,
                payload.payload_expr,
                payload.payload_codec,
                response_codec,
                response.wire_type_ts,
                err_type
            )
            .unwrap();
            writeln!(
                out,
                "    return mapResult(result, {});",
                response.unwrap_expr
            )
            .unwrap();
            writeln!(out, "  }}").unwrap();
        }
        (MethodKind::Subscription, ReturnType::Subscription(ty)) => {
            let response = emit_response(ty, wrappers, ctx)?;
            let callback_param = if payload.param_list.is_empty() {
                format!("callback: (value: {}) => void", response.inner_type_ts)
            } else {
                format!(
                    "{}, callback: (value: {}) => void",
                    payload.param_list, response.inner_type_ts
                )
            };

            writeln!(
                out,
                "  {}({}): Subscription {{",
                ts_method_name, callback_param
            )
            .unwrap();
            writeln!(
                out,
                "    return this.transport.subscribe(\"{}\", {}, {}, {}, (value) => callback(({})(value)));",
                method.name,
                payload.payload_expr,
                payload.payload_codec,
                response.wire_codec_expr,
                response.unwrap_expr
            )
            .unwrap();
            writeln!(out, "  }}").unwrap();
        }
        (MethodKind::ResultSubscription, ReturnType::ResultSubscription { item, err }) => {
            let err_type = ts_type_qualified(err)?;
            let err_codec = codec_expr(err, true, ctx)?;
            let response = emit_response(item, wrappers, ctx)?;
            let callback_param = if payload.param_list.is_empty() {
                format!(
                    "callback: (value: {}) => void, onError?: (error: {}) => void",
                    response.inner_type_ts, err_type
                )
            } else {
                format!(
                    "{}, callback: (value: {}) => void, onError?: (error: {}) => void",
                    payload.param_list, response.inner_type_ts, err_type
                )
            };

            writeln!(
                out,
                "  {}({}): Subscription {{",
                ts_method_name, callback_param
            )
            .unwrap();
            writeln!(
                out,
                "    return this.transport.subscribe(\"{}\", {}, {}, {}, (value) => callback(({})(value)), {}, onError);",
                method.name,
                payload.payload_expr,
                payload.payload_codec,
                response.wire_codec_expr,
                response.unwrap_expr,
                err_codec
            )
            .unwrap();
            writeln!(out, "  }}").unwrap();
        }
        (kind, return_type) => {
            bail!(
                "Generator internal mismatch for method `{}`: kind {:?} does not match return type {:?}",
                method.name,
                kind,
                return_type
            );
        }
    }

    Ok(())
}

fn write_type_definition(out: &mut String, ty: &TypeDef) -> Result<()> {
    let generic_decl = generic_param_declaration(&ty.generic_params);

    match &ty.kind {
        TypeDefKind::Alias(type_ref) => {
            writeln!(
                out,
                "export type {}{} = {};",
                ty.name,
                generic_decl,
                ts_type(type_ref)?
            )
            .unwrap();
        }
        TypeDefKind::Struct(fields) => {
            writeln!(out, "export interface {}{} {{", ty.name, generic_decl).unwrap();
            for field in fields {
                let (ts_name, optional) = ts_field_name(&field.name, &field.type_ref);
                if optional {
                    writeln!(
                        out,
                        "  {}?: {};",
                        ts_name,
                        ts_inner_option(&field.type_ref)?
                    )
                    .unwrap();
                } else {
                    writeln!(out, "  {}: {};", ts_name, ts_type(&field.type_ref)?).unwrap();
                }
            }
            writeln!(out, "}}").unwrap();
        }
        TypeDefKind::Enum(variants) => {
            writeln!(out, "export type {}{} =", ty.name, generic_decl).unwrap();
            for variant in variants {
                writeln!(
                    out,
                    "  | {{ tag: \"{}\"; value: {} }}",
                    variant.name,
                    variant_value_type(&variant.fields)?
                )
                .unwrap();
            }
            writeln!(out, ";").unwrap();
        }
    }

    Ok(())
}

fn write_codec_definition(out: &mut String, ty: &TypeDef) -> Result<()> {
    if ty.generic_params.is_empty() {
        let ctx = CodecContext::default();
        writeln!(
            out,
            "export const {}: S.Codec<{}> = S.lazy((): S.Codec<{}> => {});",
            ty.name,
            top_level_type_name(&ty.name, &ty.generic_params),
            top_level_type_name(&ty.name, &ty.generic_params),
            type_codec_expr(ty, &ctx)?
        )
        .unwrap();
        return Ok(());
    }

    let generic_decl = generic_param_declaration(&ty.generic_params);
    let codec_params = ty
        .generic_params
        .iter()
        .map(|param| format!("{}: S.Codec<{}>", codec_param_name(param), param))
        .collect::<Vec<_>>()
        .join(", ");
    let ctx = codec_context(&ty.generic_params);
    let type_name = top_level_type_name(&ty.name, &ty.generic_params);

    if ty.name == "Component" {
        writeln!(
            out,
            "/** Builds a codec for renderer components parameterized by the codec of their"
        )
        .unwrap();
        writeln!(out, " * `props` payload. */").unwrap();
    }
    writeln!(
        out,
        "export function {}{}({}): S.Codec<{}> {{",
        ty.name, generic_decl, codec_params, type_name
    )
    .unwrap();
    writeln!(
        out,
        "  return S.lazy((): S.Codec<{}> => {});",
        type_name,
        type_codec_expr(ty, &ctx)?
    )
    .unwrap();
    writeln!(out, "}}").unwrap();

    Ok(())
}

fn type_codec_expr(ty: &TypeDef, ctx: &CodecContext) -> Result<String> {
    match &ty.kind {
        TypeDefKind::Alias(type_ref) => codec_expr(type_ref, false, ctx),
        TypeDefKind::Struct(fields) => struct_codec_expr(
            fields,
            &top_level_type_name(&ty.name, &ty.generic_params),
            false,
            ctx,
        ),
        TypeDefKind::Enum(variants) => {
            let variants = variants
                .iter()
                .map(|variant| {
                    Ok(format!(
                        "{}: {}",
                        variant.name,
                        variant_codec_expr(&variant.fields, false, ctx)?
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            Ok(format!("S.taggedUnion({{{}}})", variants))
        }
    }
}

fn variant_value_type(fields: &VariantFields) -> Result<String> {
    match fields {
        VariantFields::Unit => Ok("undefined".to_string()),
        VariantFields::Unnamed(types) => {
            if types.len() == 1 {
                ts_type(&types[0])
            } else {
                Ok(format!(
                    "[{}]",
                    types
                        .iter()
                        .map(ts_type)
                        .collect::<Result<Vec<_>>>()?
                        .join(", ")
                ))
            }
        }
        VariantFields::Named(fields) => inline_object_type(fields, false),
    }
}

fn variant_codec_expr(
    fields: &VariantFields,
    qualified: bool,
    ctx: &CodecContext,
) -> Result<String> {
    match fields {
        VariantFields::Unit => Ok("S.unit".to_string()),
        VariantFields::Unnamed(types) => {
            if types.len() == 1 {
                codec_expr(&types[0], qualified, ctx)
            } else {
                let codecs = types
                    .iter()
                    .map(|ty| codec_expr(ty, qualified, ctx))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("S.tuple({})", codecs))
            }
        }
        VariantFields::Named(fields) => struct_codec_expr(
            fields,
            &inline_object_type(fields, qualified)?,
            qualified,
            ctx,
        ),
    }
}

fn struct_codec_expr(
    fields: &[FieldDef],
    type_name: &str,
    qualified: bool,
    ctx: &CodecContext,
) -> Result<String> {
    let field_specs = fields
        .iter()
        .map(|field| {
            let (name, _optional) = ts_field_name(&field.name, &field.type_ref);
            Ok(format!(
                "{}: {}",
                name,
                codec_expr(&field.type_ref, qualified, ctx)?
            ))
        })
        .collect::<Result<Vec<_>>>()?
        .join(", ");
    Ok(format!(
        "S.struct({{{}}}) as S.Codec<{}>",
        field_specs, type_name
    ))
}

fn inline_object_type(fields: &[FieldDef], qualified: bool) -> Result<String> {
    Ok(format!(
        "{{ {} }}",
        fields
            .iter()
            .map(|field| {
                let (name, optional) = ts_field_name(&field.name, &field.type_ref);
                if optional {
                    Ok(format!(
                        "{}?: {}",
                        name,
                        ts_inner_option_with_named(&field.type_ref, qualified)?
                    ))
                } else {
                    Ok(format!(
                        "{}: {}",
                        name,
                        ts_type_with_named(&field.type_ref, qualified)?
                    ))
                }
            })
            .collect::<Result<Vec<_>>>()?
            .join("; ")
    ))
}

fn method_payload_codec_expr(
    params: &[ParamDef],
    qualified: bool,
    ctx: &CodecContext,
) -> Result<String> {
    match params.len() {
        0 => Ok("S.unit".to_string()),
        1 => codec_expr(&params[0].type_ref, qualified, ctx),
        _ => {
            let codecs = params
                .iter()
                .map(|param| codec_expr(&param.type_ref, qualified, ctx))
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            Ok(format!("S.tuple({})", codecs))
        }
    }
}

fn codec_expr(ty: &TypeRef, qualified: bool, ctx: &CodecContext) -> Result<String> {
    match ty {
        TypeRef::Primitive(name) => match name.as_str() {
            "bool" => Ok("S.bool".to_string()),
            "u8" => Ok("S.u8".to_string()),
            "u16" => Ok("S.u16".to_string()),
            "u32" => Ok("S.u32".to_string()),
            "u64" => Ok("S.u64".to_string()),
            "u128" => Ok("S.u128".to_string()),
            "i8" => Ok("S.i8".to_string()),
            "i16" => Ok("S.i16".to_string()),
            "i32" => Ok("S.i32".to_string()),
            "i64" => Ok("S.i64".to_string()),
            "i128" => Ok("S.i128".to_string()),
            "f32" => Ok("S.f32".to_string()),
            "f64" => Ok("S.f64".to_string()),
            "str" => Ok("S.str".to_string()),
            _ => bail!(
                "Unsupported primitive type `{}` in TypeScript codec generation",
                name
            ),
        },
        TypeRef::Named { name, args } => {
            let target = if qualified {
                format!("T.{}", name)
            } else {
                name.clone()
            };

            if args.is_empty() {
                Ok(target)
            } else {
                let codecs = args
                    .iter()
                    .map(|arg| codec_expr(arg, qualified, ctx))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("{}({})", target, codecs))
            }
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("S.bytes".to_string()),
            _ => Ok(format!("S.vec({})", codec_expr(inner, qualified, ctx)?)),
        },
        TypeRef::Option(inner) => Ok(format!("S.option({})", codec_expr(inner, qualified, ctx)?)),
        TypeRef::Tuple(items) => {
            if items.is_empty() {
                Ok("S.unit".to_string())
            } else {
                let codecs = items
                    .iter()
                    .map(|item| codec_expr(item, qualified, ctx))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("S.tuple({})", codecs))
            }
        }
        TypeRef::Array(inner, len) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok(format!("S.byteArray({})", len)),
            _ => Ok(format!(
                "S.array({}, {})",
                codec_expr(inner, qualified, ctx)?,
                len
            )),
        },
        TypeRef::Generic(name) => ctx
            .generic_codecs
            .get(name)
            .cloned()
            .ok_or_else(|| anyhow::anyhow!("Missing codec for generic parameter `{}`", name)),
        TypeRef::Unit => Ok("S.unit".to_string()),
    }
}

fn ts_type(ty: &TypeRef) -> Result<String> {
    ts_type_with_named(ty, false)
}

fn ts_type_with_named(ty: &TypeRef, qualified: bool) -> Result<String> {
    match ty {
        TypeRef::Primitive(name) => match name.as_str() {
            "bool" => Ok("boolean".to_string()),
            "u8" | "u16" | "u32" | "i8" | "i16" | "i32" | "f32" | "f64" => Ok("number".to_string()),
            "u64" | "u128" | "i64" | "i128" => Ok("bigint".to_string()),
            "str" => Ok("string".to_string()),
            _ => bail!(
                "Unsupported primitive type `{}` in TypeScript type generation",
                name
            ),
        },
        TypeRef::Named { name, args } => {
            let target = if qualified {
                format!("T.{}", name)
            } else {
                name.clone()
            };

            if args.is_empty() {
                Ok(target)
            } else {
                let args = args
                    .iter()
                    .map(|arg| ts_type_with_named(arg, qualified))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                Ok(format!("{}<{}>", target, args))
            }
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type_with_named(inner, qualified)?)),
        },
        TypeRef::Option(inner) => Ok(format!(
            "{} | undefined",
            ts_type_with_named(inner, qualified)?
        )),
        TypeRef::Tuple(items) => {
            if items.is_empty() {
                Ok("undefined".to_string())
            } else {
                Ok(format!(
                    "[{}]",
                    items
                        .iter()
                        .map(|item| ts_type_with_named(item, qualified))
                        .collect::<Result<Vec<_>>>()?
                        .join(", ")
                ))
            }
        }
        TypeRef::Array(inner, _len) => match inner.as_ref() {
            TypeRef::Primitive(name) if name == "u8" => Ok("Uint8Array".to_string()),
            _ => Ok(format!("Array<{}>", ts_type_with_named(inner, qualified)?)),
        },
        TypeRef::Generic(name) => Ok(name.clone()),
        TypeRef::Unit => Ok("undefined".to_string()),
    }
}

fn ts_inner_option(ty: &TypeRef) -> Result<String> {
    ts_inner_option_with_named(ty, false)
}

fn ts_inner_option_with_named(ty: &TypeRef, qualified: bool) -> Result<String> {
    match ty {
        TypeRef::Option(inner) => ts_type_with_named(inner, qualified),
        other => ts_type_with_named(other, qualified),
    }
}

fn ts_type_qualified(ty: &TypeRef) -> Result<String> {
    ts_type_with_named(ty, true)
}

fn ts_field_name(name: &str, ty: &TypeRef) -> (String, bool) {
    let camel = to_camel_case(name);
    let optional = matches!(ty, TypeRef::Option(_));
    (camel, optional)
}

fn ts_param_list(params: &[ParamDef]) -> Result<String> {
    Ok(params
        .iter()
        .map(|param| {
            let name = param_name(&param.name);
            Ok(format!("{}: {}", name, ts_type_qualified(&param.type_ref)?))
        })
        .collect::<Result<Vec<_>>>()?
        .join(", "))
}

fn payload_expression(params: &[ParamDef]) -> Result<String> {
    match params.len() {
        0 => Ok("undefined".to_string()),
        1 => Ok(param_name(&params[0].name)),
        _ => {
            let names = params
                .iter()
                .map(|param| param_name(&param.name))
                .collect::<Vec<_>>()
                .join(", ");
            let types = params
                .iter()
                .map(|param| ts_type_qualified(&param.type_ref))
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            Ok(format!("[{}] as [{}]", names, types))
        }
    }
}

fn generic_param_declaration(params: &[String]) -> String {
    if params.is_empty() {
        String::new()
    } else {
        format!("<{}>", params.join(", "))
    }
}

fn top_level_type_name(name: &str, generic_params: &[String]) -> String {
    if generic_params.is_empty() {
        name.to_string()
    } else {
        format!("{}<{}>", name, generic_params.join(", "))
    }
}

fn codec_context(generic_params: &[String]) -> CodecContext {
    let generic_codecs = generic_params
        .iter()
        .map(|param| (param.clone(), codec_param_name(param)))
        .collect();
    CodecContext { generic_codecs }
}

fn codec_param_name(name: &str) -> String {
    format!("{}Codec", to_camel_case(name))
}

fn param_name(name: &str) -> String {
    let stripped = name.trim_start_matches('_');
    let camel = to_camel_case(stripped);
    if camel == "payload" || camel == "response" {
        format!("{}Arg", camel)
    } else {
        camel
    }
}

fn strip_prefix(name: &str) -> String {
    for prefix in ["host_", "remote_", "product_"] {
        if let Some(rest) = name.strip_prefix(prefix) {
            return rest.to_string();
        }
    }
    name.to_string()
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;
    for (index, ch) in s.chars().enumerate() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_uppercase().next().unwrap_or(ch));
            capitalize_next = false;
        } else if index == 0 {
            result.push(ch.to_lowercase().next().unwrap_or(ch));
        } else {
            result.push(ch);
        }
    }
    result
}
