// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(truapi_platformFFI)
import truapi_platformFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_truapi_platform_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_truapi_platform_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTruapiPlatformInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Review shown before a product asks to access another product account.
 */
public struct AccountAccessReview: Equatable, Hashable {
    /**
     * Product currently handling the request.
     */
    public var requestingProductId: String
    /**
     * Product whose account is being requested.
     */
    public var targetProductId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product currently handling the request.
         */requestingProductId: String, 
        /**
         * Product whose account is being requested.
         */targetProductId: String) {
        self.requestingProductId = requestingProductId
        self.targetProductId = targetProductId
    }

    

    
}

#if compiler(>=6)
extension AccountAccessReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountAccessReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccountAccessReview {
        return
            try AccountAccessReview(
                requestingProductId: FfiConverterString.read(from: &buf), 
                targetProductId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AccountAccessReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.requestingProductId, into: &buf)
        FfiConverterString.write(value.targetProductId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountAccessReview_lift(_ buf: RustBuffer) throws -> AccountAccessReview {
    return try FfiConverterTypeAccountAccessReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountAccessReview_lower(_ value: AccountAccessReview) -> RustBuffer {
    return FfiConverterTypeAccountAccessReview.lower(value)
}


/**
 * Review shown before a product derives a contextual alias (RFC 0004).
 */
public struct AccountAliasReview: Equatable, Hashable {
    /**
     * Product requesting the alias.
     */
    public var callingProductId: String
    /**
     * Product-scoped context the alias is bound to.
     */
    public var context: ProductProofContext
    /**
     * Ring the alias is derived against.
     */
    public var ringLocation: RingLocation

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product requesting the alias.
         */callingProductId: String, 
        /**
         * Product-scoped context the alias is bound to.
         */context: ProductProofContext, 
        /**
         * Ring the alias is derived against.
         */ringLocation: RingLocation) {
        self.callingProductId = callingProductId
        self.context = context
        self.ringLocation = ringLocation
    }

    

    
}

#if compiler(>=6)
extension AccountAliasReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountAliasReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccountAliasReview {
        return
            try AccountAliasReview(
                callingProductId: FfiConverterString.read(from: &buf), 
                context: FfiConverterTypeProductProofContext.read(from: &buf), 
                ringLocation: FfiConverterTypeRingLocation.read(from: &buf)
        )
    }

    public static func write(_ value: AccountAliasReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.callingProductId, into: &buf)
        FfiConverterTypeProductProofContext.write(value.context, into: &buf)
        FfiConverterTypeRingLocation.write(value.ringLocation, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountAliasReview_lift(_ buf: RustBuffer) throws -> AccountAliasReview {
    return try FfiConverterTypeAccountAliasReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountAliasReview_lower(_ value: AccountAliasReview) -> RustBuffer {
    return FfiConverterTypeAccountAliasReview.lower(value)
}


/**
 * Review shown before a product creates a ring-VRF proof (RFC 0004).
 */
public struct CreateProofReview: Equatable, Hashable {
    /**
     * Product requesting the proof.
     */
    public var callingProductId: String
    /**
     * Product-scoped context the proof's alias is bound to.
     */
    public var context: ProductProofContext
    /**
     * Ring the proof is generated against.
     */
    public var ringLocation: RingLocation
    /**
     * Opaque message bound into the proof.
     */
    public var message: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product requesting the proof.
         */callingProductId: String, 
        /**
         * Product-scoped context the proof's alias is bound to.
         */context: ProductProofContext, 
        /**
         * Ring the proof is generated against.
         */ringLocation: RingLocation, 
        /**
         * Opaque message bound into the proof.
         */message: Data) {
        self.callingProductId = callingProductId
        self.context = context
        self.ringLocation = ringLocation
        self.message = message
    }

    

    
}

#if compiler(>=6)
extension CreateProofReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCreateProofReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CreateProofReview {
        return
            try CreateProofReview(
                callingProductId: FfiConverterString.read(from: &buf), 
                context: FfiConverterTypeProductProofContext.read(from: &buf), 
                ringLocation: FfiConverterTypeRingLocation.read(from: &buf), 
                message: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: CreateProofReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.callingProductId, into: &buf)
        FfiConverterTypeProductProofContext.write(value.context, into: &buf)
        FfiConverterTypeRingLocation.write(value.ringLocation, into: &buf)
        FfiConverterData.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreateProofReview_lift(_ buf: RustBuffer) throws -> CreateProofReview {
    return try FfiConverterTypeCreateProofReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreateProofReview_lower(_ value: CreateProofReview) -> RustBuffer {
    return FfiConverterTypeCreateProofReview.lower(value)
}


/**
 * Review shown before a product learns the user's primary identity.
 */
public struct IdentityDisclosureReview: Equatable, Hashable {
    /**
     * Product currently handling the request.
     */
    public var productId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product currently handling the request.
         */productId: String) {
        self.productId = productId
    }

    

    
}

#if compiler(>=6)
extension IdentityDisclosureReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentityDisclosureReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IdentityDisclosureReview {
        return
            try IdentityDisclosureReview(
                productId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: IdentityDisclosureReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.productId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityDisclosureReview_lift(_ buf: RustBuffer) throws -> IdentityDisclosureReview {
    return try FfiConverterTypeIdentityDisclosureReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityDisclosureReview_lower(_ value: IdentityDisclosureReview) -> RustBuffer {
    return FfiConverterTypeIdentityDisclosureReview.lower(value)
}


/**
 * Review shown before a preimage is submitted.
 */
public struct PreimageSubmitReview: Equatable, Hashable {
    /**
     * Size of the preimage in bytes.
     */
    public var size: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Size of the preimage in bytes.
         */size: UInt64) {
        self.size = size
    }

    

    
}

#if compiler(>=6)
extension PreimageSubmitReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreimageSubmitReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreimageSubmitReview {
        return
            try PreimageSubmitReview(
                size: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: PreimageSubmitReview, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.size, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreimageSubmitReview_lift(_ buf: RustBuffer) throws -> PreimageSubmitReview {
    return try FfiConverterTypePreimageSubmitReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreimageSubmitReview_lower(_ value: PreimageSubmitReview) -> RustBuffer {
    return FfiConverterTypePreimageSubmitReview.lower(value)
}


/**
 * Review shown before allocating resources for a product. Names the
 * beneficiary product so the user knows which product receives the
 * (signing-capable) allowance key they are approving.
 */
public struct ResourceAllocationReview: Equatable, Hashable {
    /**
     * Product the allocation is requested for.
     */
    public var callingProductId: String
    /**
     * Resources to allocate.
     */
    public var resources: [AllocatableResource]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product the allocation is requested for.
         */callingProductId: String, 
        /**
         * Resources to allocate.
         */resources: [AllocatableResource]) {
        self.callingProductId = callingProductId
        self.resources = resources
    }

    

    
}

#if compiler(>=6)
extension ResourceAllocationReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeResourceAllocationReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResourceAllocationReview {
        return
            try ResourceAllocationReview(
                callingProductId: FfiConverterString.read(from: &buf), 
                resources: FfiConverterSequenceTypeAllocatableResource.read(from: &buf)
        )
    }

    public static func write(_ value: ResourceAllocationReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.callingProductId, into: &buf)
        FfiConverterSequenceTypeAllocatableResource.write(value.resources, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResourceAllocationReview_lift(_ buf: RustBuffer) throws -> ResourceAllocationReview {
    return try FfiConverterTypeResourceAllocationReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResourceAllocationReview_lower(_ value: ResourceAllocationReview) -> RustBuffer {
    return FfiConverterTypeResourceAllocationReview.lower(value)
}


/**
 * Decoded session fields a host shell needs to render account UI without
 * parsing the opaque session blob the core persists through [`CoreStorage`].
 */
public struct SessionUiInfo: Equatable, Hashable {
    /**
     * 32-byte sr25519 root public key of the active session.
     */
    public var publicKey: Bytes32
    /**
     * Wallet identity account id used for People-chain username lookup.
     */
    public var identityAccountId: Bytes32?
    /**
     * Short username from the People-chain identity record.
     */
    public var liteUsername: String?
    /**
     * Fully qualified username from the People-chain identity record.
     */
    public var fullUsername: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 32-byte sr25519 root public key of the active session.
         */publicKey: Bytes32, 
        /**
         * Wallet identity account id used for People-chain username lookup.
         */identityAccountId: Bytes32?, 
        /**
         * Short username from the People-chain identity record.
         */liteUsername: String?, 
        /**
         * Fully qualified username from the People-chain identity record.
         */fullUsername: String?) {
        self.publicKey = publicKey
        self.identityAccountId = identityAccountId
        self.liteUsername = liteUsername
        self.fullUsername = fullUsername
    }

    

    
}

#if compiler(>=6)
extension SessionUiInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionUiInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionUiInfo {
        return
            try SessionUiInfo(
                publicKey: FfiConverterTypeBytes32.read(from: &buf), 
                identityAccountId: FfiConverterOptionTypeBytes32.read(from: &buf), 
                liteUsername: FfiConverterOptionString.read(from: &buf), 
                fullUsername: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SessionUiInfo, into buf: inout [UInt8]) {
        FfiConverterTypeBytes32.write(value.publicKey, into: &buf)
        FfiConverterOptionTypeBytes32.write(value.identityAccountId, into: &buf)
        FfiConverterOptionString.write(value.liteUsername, into: &buf)
        FfiConverterOptionString.write(value.fullUsername, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionUiInfo_lift(_ buf: RustBuffer) throws -> SessionUiInfo {
    return try FfiConverterTypeSessionUiInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionUiInfo_lower(_ value: SessionUiInfo) -> RustBuffer {
    return FfiConverterTypeSessionUiInfo.lower(value)
}


/**
 * Review shown before signing an RFC-0023 VRF transcript.
 */
public struct SignVrfReview: Equatable, Hashable {
    /**
     * Product making the request.
     */
    public var callingProductId: String
    /**
     * Product account and exact ordered transcript.
     */
    public var request: HostAccountSignVrfRequest

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product making the request.
         */callingProductId: String, 
        /**
         * Product account and exact ordered transcript.
         */request: HostAccountSignVrfRequest) {
        self.callingProductId = callingProductId
        self.request = request
    }

    

    
}

#if compiler(>=6)
extension SignVrfReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignVrfReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignVrfReview {
        return
            try SignVrfReview(
                callingProductId: FfiConverterString.read(from: &buf), 
                request: FfiConverterTypeHostAccountSignVrfRequest.read(from: &buf)
        )
    }

    public static func write(_ value: SignVrfReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.callingProductId, into: &buf)
        FfiConverterTypeHostAccountSignVrfRequest.write(value.request, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignVrfReview_lift(_ buf: RustBuffer) throws -> SignVrfReview {
    return try FfiConverterTypeSignVrfReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignVrfReview_lower(_ value: SignVrfReview) -> RustBuffer {
    return FfiConverterTypeSignVrfReview.lower(value)
}


/**
 * Review shown before a product account signs a Statement Store proof
 * payload. Distinct from raw-message signing: the payload is the exact
 * unsigned statement, signed as-is (no `<Bytes>` envelope), so the host must
 * not present it with the raw-signing convention.
 */
public struct StatementStoreProductSignReview: Equatable, Hashable {
    /**
     * Product account that will sign the statement payload.
     */
    public var account: ProductAccountId
    /**
     * Exact unsigned statement payload to be signed.
     */
    public var payload: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product account that will sign the statement payload.
         */account: ProductAccountId, 
        /**
         * Exact unsigned statement payload to be signed.
         */payload: Data) {
        self.account = account
        self.payload = payload
    }

    

    
}

#if compiler(>=6)
extension StatementStoreProductSignReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStatementStoreProductSignReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StatementStoreProductSignReview {
        return
            try StatementStoreProductSignReview(
                account: FfiConverterTypeProductAccountId.read(from: &buf), 
                payload: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: StatementStoreProductSignReview, into buf: inout [UInt8]) {
        FfiConverterTypeProductAccountId.write(value.account, into: &buf)
        FfiConverterData.write(value.payload, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatementStoreProductSignReview_lift(_ buf: RustBuffer) throws -> StatementStoreProductSignReview {
    return try FfiConverterTypeStatementStoreProductSignReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatementStoreProductSignReview_lower(_ value: StatementStoreProductSignReview) -> RustBuffer {
    return FfiConverterTypeStatementStoreProductSignReview.lower(value)
}


/**
 * Auth/session lifecycle state the core projects for host UI. The core owns
 * every transition and emits states in order; hosts render the current state
 * and never derive auth UI from any other signal.
 */

public enum AuthState: Equatable, Hashable {
    
    /**
     * No active session and no login in progress.
     */
    case disconnected
    /**
     * A login is in progress: present the pairing deeplink/QR. Leave this
     * state only on a subsequent emission (connected, failed, or
     * disconnected after cancellation).
     */
    case pairing(
        /**
         * Wallet pairing deeplink to render as a QR code or open directly.
         */deeplink: String
    )
    /**
     * A session is active.
     */
    case connected(SessionUiInfo
    )
    /**
     * The last login attempt failed; show the reason and offer a retry.
     */
    case loginFailed(
        /**
         * Human-readable failure reason.
         */reason: String
    )
    /**
     * The wallet accepted the pairing request and the core is resolving and
     * persisting the session. Hosts should replace the pairing QR with an
     * in-progress presentation until a terminal state is emitted.
     */
    case authenticating





}

#if compiler(>=6)
extension AuthState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthState: FfiConverterRustBuffer {
    typealias SwiftType = AuthState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disconnected
        
        case 2: return .pairing(deeplink: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .connected(try FfiConverterTypeSessionUiInfo.read(from: &buf)
        )
        
        case 4: return .loginFailed(reason: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .authenticating
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AuthState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disconnected:
            writeInt(&buf, Int32(1))
        
        
        case let .pairing(deeplink):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(deeplink, into: &buf)
            
        
        case let .connected(v1):
            writeInt(&buf, Int32(3))
            FfiConverterTypeSessionUiInfo.write(v1, into: &buf)
            
        
        case let .loginFailed(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .authenticating:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthState_lift(_ buf: RustBuffer) throws -> AuthState {
    return try FfiConverterTypeAuthState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthState_lower(_ value: AuthState) -> RustBuffer {
    return FfiConverterTypeAuthState.lower(value)
}



/**
 * Review shown before a transaction-creation request is sent to the paired wallet.
 */

public enum CreateTransactionReview: Equatable, Hashable {
    
    /**
     * Product-account transaction request.
     */
    case product(ProductAccountTxPayload
    )
    /**
     * Legacy-account transaction request.
     */
    case legacyAccount(LegacyAccountTxPayload
    )





}

#if compiler(>=6)
extension CreateTransactionReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCreateTransactionReview: FfiConverterRustBuffer {
    typealias SwiftType = CreateTransactionReview

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CreateTransactionReview {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .product(try FfiConverterTypeProductAccountTxPayload.read(from: &buf)
        )
        
        case 2: return .legacyAccount(try FfiConverterTypeLegacyAccountTxPayload.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CreateTransactionReview, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .product(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeProductAccountTxPayload.write(v1, into: &buf)
            
        
        case let .legacyAccount(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeLegacyAccountTxPayload.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreateTransactionReview_lift(_ buf: RustBuffer) throws -> CreateTransactionReview {
    return try FfiConverterTypeCreateTransactionReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCreateTransactionReview_lower(_ value: CreateTransactionReview) -> RustBuffer {
    return FfiConverterTypeCreateTransactionReview.lower(value)
}



/**
 * Permission request whose authorization status can be inspected or updated
 * by host administration UI.
 */

public enum PermissionAuthorizationRequest: Equatable, Hashable {
    
    /**
     * Device-level permission such as camera, microphone, or location.
     */
    case device(HostDevicePermissionRequest
    )
    /**
     * Remote/product-scoped permission such as chain submit or HTTP access.
     */
    case remote(RemotePermissionRequest
    )
    /**
     * Product-scoped permission to disclose the user's primary identity.
     */
    case identityDisclosure
    /**
     * Product-scoped permission to access another product's account context.
     */
    case accountAccess(
        /**
         * Product whose account context may be accessed.
         */targetProductId: String
    )





}

#if compiler(>=6)
extension PermissionAuthorizationRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePermissionAuthorizationRequest: FfiConverterRustBuffer {
    typealias SwiftType = PermissionAuthorizationRequest

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PermissionAuthorizationRequest {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .device(try FfiConverterTypeHostDevicePermissionRequest.read(from: &buf)
        )
        
        case 2: return .remote(try FfiConverterTypeRemotePermissionRequest.read(from: &buf)
        )
        
        case 3: return .identityDisclosure
        
        case 4: return .accountAccess(targetProductId: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PermissionAuthorizationRequest, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .device(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeHostDevicePermissionRequest.write(v1, into: &buf)
            
        
        case let .remote(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeRemotePermissionRequest.write(v1, into: &buf)
            
        
        case .identityDisclosure:
            writeInt(&buf, Int32(3))
        
        
        case let .accountAccess(targetProductId):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(targetProductId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePermissionAuthorizationRequest_lift(_ buf: RustBuffer) throws -> PermissionAuthorizationRequest {
    return try FfiConverterTypePermissionAuthorizationRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePermissionAuthorizationRequest_lower(_ value: PermissionAuthorizationRequest) -> RustBuffer {
    return FfiConverterTypePermissionAuthorizationRequest.lower(value)
}



/**
 * Authorization status for a permission request.
 *
 * `NotDetermined` means the core has no persisted answer and will prompt the
 * host the next time the product requests this permission.
 */

public enum PermissionAuthorizationStatus: Equatable, Hashable {
    
    /**
     * No persisted authorization exists.
     */
    case notDetermined
    /**
     * Access is denied.
     */
    case denied
    /**
     * Access is authorized.
     */
    case authorized





}

#if compiler(>=6)
extension PermissionAuthorizationStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePermissionAuthorizationStatus: FfiConverterRustBuffer {
    typealias SwiftType = PermissionAuthorizationStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PermissionAuthorizationStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .notDetermined
        
        case 2: return .denied
        
        case 3: return .authorized
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PermissionAuthorizationStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .notDetermined:
            writeInt(&buf, Int32(1))
        
        
        case .denied:
            writeInt(&buf, Int32(2))
        
        
        case .authorized:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePermissionAuthorizationStatus_lift(_ buf: RustBuffer) throws -> PermissionAuthorizationStatus {
    return try FfiConverterTypePermissionAuthorizationStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePermissionAuthorizationStatus_lower(_ value: PermissionAuthorizationStatus) -> RustBuffer {
    return FfiConverterTypePermissionAuthorizationStatus.lower(value)
}



/**
 * Trusted kind of product executable attached to a TrUAPI connection.
 */

public enum ProductExecutionKind: Equatable, Hashable {
    
    /**
     * Visible single-page application entrypoint such as `app/index.html`.
     */
    case spa
    /**
     * Headless worker executable that provides the Chat modality.
     */
    case chat





}

#if compiler(>=6)
extension ProductExecutionKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProductExecutionKind: FfiConverterRustBuffer {
    typealias SwiftType = ProductExecutionKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProductExecutionKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .spa
        
        case 2: return .chat
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ProductExecutionKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .spa:
            writeInt(&buf, Int32(1))
        
        
        case .chat:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductExecutionKind_lift(_ buf: RustBuffer) throws -> ProductExecutionKind {
    return try FfiConverterTypeProductExecutionKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductExecutionKind_lower(_ value: ProductExecutionKind) -> RustBuffer {
    return FfiConverterTypeProductExecutionKind.lower(value)
}



/**
 * Review shown before a sign-payload request is sent to the paired wallet.
 */

public enum SignPayloadReview: Equatable, Hashable {
    
    /**
     * Product-account signing request.
     */
    case product(HostSignPayloadRequest
    )
    /**
     * Legacy-account signing request.
     */
    case legacyAccount(HostSignPayloadWithLegacyAccountRequest
    )





}

#if compiler(>=6)
extension SignPayloadReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignPayloadReview: FfiConverterRustBuffer {
    typealias SwiftType = SignPayloadReview

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignPayloadReview {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .product(try FfiConverterTypeHostSignPayloadRequest.read(from: &buf)
        )
        
        case 2: return .legacyAccount(try FfiConverterTypeHostSignPayloadWithLegacyAccountRequest.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignPayloadReview, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .product(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeHostSignPayloadRequest.write(v1, into: &buf)
            
        
        case let .legacyAccount(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeHostSignPayloadWithLegacyAccountRequest.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignPayloadReview_lift(_ buf: RustBuffer) throws -> SignPayloadReview {
    return try FfiConverterTypeSignPayloadReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignPayloadReview_lower(_ value: SignPayloadReview) -> RustBuffer {
    return FfiConverterTypeSignPayloadReview.lower(value)
}



/**
 * Review shown before a sign-raw request is sent to the paired wallet.
 */

public enum SignRawReview: Equatable, Hashable {
    
    /**
     * Product-account raw signing request.
     */
    case product(HostSignRawRequest
    )
    /**
     * Legacy-account raw signing request.
     */
    case legacyAccount(HostSignRawWithLegacyAccountRequest
    )





}

#if compiler(>=6)
extension SignRawReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignRawReview: FfiConverterRustBuffer {
    typealias SwiftType = SignRawReview

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignRawReview {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .product(try FfiConverterTypeHostSignRawRequest.read(from: &buf)
        )
        
        case 2: return .legacyAccount(try FfiConverterTypeHostSignRawWithLegacyAccountRequest.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignRawReview, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .product(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeHostSignRawRequest.write(v1, into: &buf)
            
        
        case let .legacyAccount(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeHostSignRawWithLegacyAccountRequest.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignRawReview_lift(_ buf: RustBuffer) throws -> SignRawReview {
    return try FfiConverterTypeSignRawReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignRawReview_lower(_ value: SignRawReview) -> RustBuffer {
    return FfiConverterTypeSignRawReview.lower(value)
}



/**
 * Review shown before a user-confirmed core action continues.
 */

public enum UserConfirmationReview: Equatable, Hashable {
    
    /**
     * Sign a SCALE payload with a product or legacy account.
     */
    case signPayload(SignPayloadReview
    )
    /**
     * Sign raw bytes with a product or legacy account.
     */
    case signRaw(SignRawReview
    )
    /**
     * Sign a Statement Store proof payload with a product account.
     */
    case statementStoreProductSign(StatementStoreProductSignReview
    )
    /**
     * Create a transaction with a product or legacy account.
     */
    case createTransaction(CreateTransactionReview
    )
    /**
     * Allow a product to derive a contextual alias for a ring.
     */
    case accountAlias(AccountAliasReview
    )
    /**
     * Allow a product to create a ring-VRF proof for a ring.
     */
    case createProof(CreateProofReview
    )
    /**
     * Allow a product to learn the user's primary identity.
     */
    case identityDisclosure(IdentityDisclosureReview
    )
    /**
     * Allocate resources for the requesting product.
     */
    case resourceAllocation(ResourceAllocationReview
    )
    /**
     * Submit a preimage to the host-selected backend.
     */
    case preimageSubmit(PreimageSubmitReview
    )
    /**
     * Allow a product to access another product account.
     */
    case accountAccess(AccountAccessReview
    )
    /**
     * Sign an RFC-0023 VRF transcript with a product account.
     */
    case signVrf(SignVrfReview
    )





}

#if compiler(>=6)
extension UserConfirmationReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserConfirmationReview: FfiConverterRustBuffer {
    typealias SwiftType = UserConfirmationReview

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserConfirmationReview {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .signPayload(try FfiConverterTypeSignPayloadReview.read(from: &buf)
        )
        
        case 2: return .signRaw(try FfiConverterTypeSignRawReview.read(from: &buf)
        )
        
        case 3: return .statementStoreProductSign(try FfiConverterTypeStatementStoreProductSignReview.read(from: &buf)
        )
        
        case 4: return .createTransaction(try FfiConverterTypeCreateTransactionReview.read(from: &buf)
        )
        
        case 5: return .accountAlias(try FfiConverterTypeAccountAliasReview.read(from: &buf)
        )
        
        case 6: return .createProof(try FfiConverterTypeCreateProofReview.read(from: &buf)
        )
        
        case 7: return .identityDisclosure(try FfiConverterTypeIdentityDisclosureReview.read(from: &buf)
        )
        
        case 8: return .resourceAllocation(try FfiConverterTypeResourceAllocationReview.read(from: &buf)
        )
        
        case 9: return .preimageSubmit(try FfiConverterTypePreimageSubmitReview.read(from: &buf)
        )
        
        case 10: return .accountAccess(try FfiConverterTypeAccountAccessReview.read(from: &buf)
        )
        
        case 11: return .signVrf(try FfiConverterTypeSignVrfReview.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UserConfirmationReview, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .signPayload(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeSignPayloadReview.write(v1, into: &buf)
            
        
        case let .signRaw(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeSignRawReview.write(v1, into: &buf)
            
        
        case let .statementStoreProductSign(v1):
            writeInt(&buf, Int32(3))
            FfiConverterTypeStatementStoreProductSignReview.write(v1, into: &buf)
            
        
        case let .createTransaction(v1):
            writeInt(&buf, Int32(4))
            FfiConverterTypeCreateTransactionReview.write(v1, into: &buf)
            
        
        case let .accountAlias(v1):
            writeInt(&buf, Int32(5))
            FfiConverterTypeAccountAliasReview.write(v1, into: &buf)
            
        
        case let .createProof(v1):
            writeInt(&buf, Int32(6))
            FfiConverterTypeCreateProofReview.write(v1, into: &buf)
            
        
        case let .identityDisclosure(v1):
            writeInt(&buf, Int32(7))
            FfiConverterTypeIdentityDisclosureReview.write(v1, into: &buf)
            
        
        case let .resourceAllocation(v1):
            writeInt(&buf, Int32(8))
            FfiConverterTypeResourceAllocationReview.write(v1, into: &buf)
            
        
        case let .preimageSubmit(v1):
            writeInt(&buf, Int32(9))
            FfiConverterTypePreimageSubmitReview.write(v1, into: &buf)
            
        
        case let .accountAccess(v1):
            writeInt(&buf, Int32(10))
            FfiConverterTypeAccountAccessReview.write(v1, into: &buf)
            
        
        case let .signVrf(v1):
            writeInt(&buf, Int32(11))
            FfiConverterTypeSignVrfReview.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserConfirmationReview_lift(_ buf: RustBuffer) throws -> UserConfirmationReview {
    return try FfiConverterTypeUserConfirmationReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserConfirmationReview_lower(_ value: UserConfirmationReview) -> RustBuffer {
    return FfiConverterTypeUserConfirmationReview.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeBytes32: FfiConverterRustBuffer {
    typealias SwiftType = Bytes32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeBytes32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeBytes32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAllocatableResource: FfiConverterRustBuffer {
    typealias SwiftType = [AllocatableResource]

    public static func write(_ value: [AllocatableResource], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAllocatableResource.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AllocatableResource] {
        let len: Int32 = try readInt(&buf)
        var seq = [AllocatableResource]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAllocatableResource.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_truapi_platform_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    uniffiEnsureTruapiInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTruapiPlatformInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all