//! Cross-language parity check: the Rust `WIRE_TABLE` and the TS
//! `wire-table.ts` must list the exact same `(method, request_id, response_id)`
//! tuples in the same order. A drift here means a product built against one
//! side will fail to decode frames produced by the other.
//!
//! Both files are auto-generated text artifacts of `truapi-codegen`; the
//! parser is a small line scanner so the test runs as part of `cargo test`
//! without any node/bun dependency.
//!
//! The TS file lives under `js/packages/truapi/src/generated/wire-table.ts`
//! and is `.gitignore`d (regenerated by `scripts/codegen.sh`). When the
//! generated file is absent, the test logs a skip notice and passes; once
//! the TS codegen lands and the file is regenerated, the parity check
//! becomes load-bearing automatically.

use std::path::PathBuf;

const RUST_TABLE: &str = include_str!("../src/generated/wire_table.rs");

#[derive(Debug, PartialEq, Eq)]
struct Row {
    method: String,
    request_or_start: u8,
    response_or_receive: u8,
    is_subscription: bool,
}

fn parse_rust(src: &str) -> Vec<Row> {
    // Walks the `pub const WIRE_TABLE: &[WireEntry] = &[ ... ];` body and
    // pulls out each `WireEntry { method: "x", kind: ... }`.
    let mut out = Vec::new();
    let mut iter = src.lines().peekable();
    while let Some(line) = iter.next() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("method: \"") else {
            continue;
        };
        let Some(end) = rest.find('"') else { continue };
        let method = rest[..end].to_string();
        let mut request_or_start = None;
        let mut response_or_receive = None;
        let mut is_subscription = false;
        for inner in iter.by_ref() {
            let t = inner.trim();
            if t.contains("WireKind::Subscription") {
                is_subscription = true;
            }
            if let Some(rest) = t
                .strip_prefix("request_id: ")
                .or_else(|| t.strip_prefix("start_id: "))
            {
                let n: u8 = rest.trim_end_matches(',').parse().unwrap_or(0);
                request_or_start = Some(n);
            }
            if let Some(rest) = t
                .strip_prefix("response_id: ")
                .or_else(|| t.strip_prefix("receive_id: "))
            {
                let n: u8 = rest.trim_end_matches(',').parse().unwrap_or(0);
                response_or_receive = Some(n);
            }
            if t == "},"
                && let (Some(rs), Some(rr)) = (request_or_start, response_or_receive)
            {
                out.push(Row {
                    method,
                    request_or_start: rs,
                    response_or_receive: rr,
                    is_subscription,
                });
                break;
            }
        }
    }
    out
}

fn parse_ts(src: &str) -> Vec<Row> {
    // The TS codegen emits one named `export const FOO_BAR = { ... }` per
    // method. The const name is `SCREAMING_SNAKE_CASE` of the method name;
    // we lowercase it to match the Rust `method:` strings.
    let mut out = Vec::new();
    let mut iter = src.lines().peekable();
    while let Some(line) = iter.next() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("export const ") else {
            continue;
        };
        let Some(name_end) = rest.find(|c: char| !(c.is_ascii_alphanumeric() || c == '_')) else {
            continue;
        };
        let method = rest[..name_end].to_ascii_lowercase();
        let mut request_or_start = None;
        let mut response_or_receive = None;
        let mut is_subscription = false;
        for inner in iter.by_ref() {
            let t = inner.trim();
            if t.starts_with("start:") || t.contains("SubscriptionFrameIds") {
                is_subscription = true;
            }
            if let Some(rest) = t
                .strip_prefix("request: ")
                .or_else(|| t.strip_prefix("start: "))
            {
                let n: u8 = rest.trim_end_matches(',').parse().unwrap_or(0);
                request_or_start = Some(n);
            }
            if let Some(rest) = t
                .strip_prefix("response: ")
                .or_else(|| t.strip_prefix("receive: "))
            {
                let n: u8 = rest.trim_end_matches(',').parse().unwrap_or(0);
                response_or_receive = Some(n);
            }
            if t.starts_with("} as const") || t == "}" {
                if let (Some(rs), Some(rr)) = (request_or_start, response_or_receive) {
                    out.push(Row {
                        method,
                        request_or_start: rs,
                        response_or_receive: rr,
                        is_subscription,
                    });
                }
                break;
            }
        }
    }
    out
}

#[test]
fn rust_and_ts_wire_tables_agree() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let ts_path = manifest
        .join("../../../js/packages/truapi/src/generated/wire-table.ts")
        .canonicalize();

    let ts_path = match ts_path {
        Ok(p) => p,
        Err(_) => {
            eprintln!(
                "skipping wire-table parity check: TS wire-table.ts is not present \
                 (run scripts/codegen.sh once the TS codegen is wired up)"
            );
            return;
        }
    };

    let ts_src = match std::fs::read_to_string(&ts_path) {
        Ok(s) => s,
        Err(_) => {
            eprintln!(
                "skipping wire-table parity check: could not read {}",
                ts_path.display()
            );
            return;
        }
    };

    let rust_rows = parse_rust(RUST_TABLE);
    let ts_rows = parse_ts(&ts_src);
    assert!(
        !rust_rows.is_empty(),
        "rust parser produced no entries; wire_table.rs format may have changed"
    );
    assert_eq!(
        rust_rows, ts_rows,
        "Rust WIRE_TABLE and TS wire-table.ts diverged. Regenerate both via \
         `scripts/codegen.sh` so the codegen pipeline produces them in lockstep.",
    );
}
