//! Cross-language parity check: the Rust `WIRE_TABLE` and the TS
//! `wire-table.ts` must list the exact same `(method, request_id, response_id)`
//! tuples in the same order. A drift here means a product built against one
//! side will fail to decode frames produced by the other.
//!
//! Both files are auto-generated text artifacts of `truapi-codegen`; the
//! parser is a small line scanner so the test runs as part of `cargo test`
//! without any node/bun dependency.
//!
//! The TS file lives under `js/packages/truapi/src/generated/wire-table.ts`
//! and is `.gitignore`d (regenerated by `scripts/codegen.sh`). When the
//! generated file is absent, the test logs a skip notice and passes; once
//! the TS codegen lands and the file is regenerated, the parity check
//! becomes load-bearing automatically.

use std::path::PathBuf;

const RUST_TABLE: &str = include_str!("../src/generated/wire_table.rs");

#[derive(Debug, PartialEq, Eq)]
struct Row {
    method: String,
    request_or_start: u8,
    response_or_receive: u8,
    /// Subscription `_stop` / `_interrupt` ids; `None` for request methods.
    stop: Option<u8>,
    interrupt: Option<u8>,
    is_subscription: bool,
}

/// Parse a wire id. A malformed id is a hard failure, never a silent `0`: a
/// defensive fallback here would let a symmetric codegen-format change collapse
/// both tables to `0`s and pass the parity check while real drift slipped by.
fn parse_id(raw: &str, method: &str) -> u8 {
    raw.trim_end_matches(',')
        .trim()
        .parse()
        .unwrap_or_else(|_| panic!("unparseable wire id for `{method}`: {raw:?}"))
}

fn parse_rust(src: &str) -> Vec<Row> {
    // The Rust codegen emits one named `pub const FOO_BAR: RequestFrameIds = ...`
    // (or `SubscriptionFrameIds`) per method. The const name is
    // `SCREAMING_SNAKE_CASE` of the method name; we lowercase it to match the
    // TS const names. This mirrors `parse_ts` below.
    let mut out = Vec::new();
    let mut iter = src.lines();
    while let Some(line) = iter.next() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("pub const ") else {
            continue;
        };
        let Some(colon) = rest.find(':') else {
            continue;
        };
        let is_subscription = rest.contains("SubscriptionFrameIds");
        // Skip non-id consts (e.g. `WIRE_TABLE: &[WireEntry]`).
        if !is_subscription && !rest.contains("RequestFrameIds") {
            continue;
        }
        let method = rest[..colon].trim().to_ascii_lowercase();
        let mut request_or_start = None;
        let mut response_or_receive = None;
        let mut stop = None;
        let mut interrupt = None;
        for inner in iter.by_ref() {
            let t = inner.trim();
            if t.starts_with("};") {
                break;
            }
            if let Some(rest) = t
                .strip_prefix("request_id: ")
                .or_else(|| t.strip_prefix("start_id: "))
            {
                request_or_start = Some(parse_id(rest, &method));
            }
            if let Some(rest) = t
                .strip_prefix("response_id: ")
                .or_else(|| t.strip_prefix("receive_id: "))
            {
                response_or_receive = Some(parse_id(rest, &method));
            }
            if let Some(rest) = t.strip_prefix("stop_id: ") {
                stop = Some(parse_id(rest, &method));
            }
            if let Some(rest) = t.strip_prefix("interrupt_id: ") {
                interrupt = Some(parse_id(rest, &method));
            }
        }
        if let (Some(rs), Some(rr)) = (request_or_start, response_or_receive) {
            out.push(Row {
                method,
                request_or_start: rs,
                response_or_receive: rr,
                stop,
                interrupt,
                is_subscription,
            });
        }
    }
    out
}

fn parse_ts(src: &str) -> Vec<Row> {
    // The TS codegen emits one named `export const FOO_BAR = { ... }` per
    // method. The const name is `SCREAMING_SNAKE_CASE` of the method name;
    // we lowercase it to match the Rust `method:` strings.
    let mut out = Vec::new();
    let mut iter = src.lines().peekable();
    while let Some(line) = iter.next() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("export const ") else {
            continue;
        };
        let Some(name_end) = rest.find(|c: char| !(c.is_ascii_alphanumeric() || c == '_')) else {
            continue;
        };
        let method = rest[..name_end].to_ascii_lowercase();
        let mut request_or_start = None;
        let mut response_or_receive = None;
        let mut stop = None;
        let mut interrupt = None;
        let mut is_subscription = false;
        for inner in iter.by_ref() {
            let t = inner.trim();
            if t.starts_with("start:") || t.contains("SubscriptionFrameIds") {
                is_subscription = true;
            }
            if let Some(rest) = t
                .strip_prefix("request: ")
                .or_else(|| t.strip_prefix("start: "))
            {
                request_or_start = Some(parse_id(rest, &method));
            }
            if let Some(rest) = t
                .strip_prefix("response: ")
                .or_else(|| t.strip_prefix("receive: "))
            {
                response_or_receive = Some(parse_id(rest, &method));
            }
            if let Some(rest) = t.strip_prefix("stop: ") {
                stop = Some(parse_id(rest, &method));
            }
            if let Some(rest) = t.strip_prefix("interrupt: ") {
                interrupt = Some(parse_id(rest, &method));
            }
            if t.starts_with("} as const") || t == "}" {
                if let (Some(rs), Some(rr)) = (request_or_start, response_or_receive) {
                    out.push(Row {
                        method,
                        request_or_start: rs,
                        response_or_receive: rr,
                        stop,
                        interrupt,
                        is_subscription,
                    });
                }
                break;
            }
        }
    }
    out
}

#[test]
fn rust_and_ts_wire_tables_agree() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let ts_path = manifest
        .join("../../../js/packages/truapi/src/generated/wire-table.ts")
        .canonicalize();

    let ts_path = match ts_path {
        Ok(p) => p,
        Err(_) => {
            eprintln!(
                "skipping wire-table parity check: TS wire-table.ts is not present \
                 (run scripts/codegen.sh once the TS codegen is wired up)"
            );
            return;
        }
    };

    let ts_src = match std::fs::read_to_string(&ts_path) {
        Ok(s) => s,
        Err(_) => {
            eprintln!(
                "skipping wire-table parity check: could not read {}",
                ts_path.display()
            );
            return;
        }
    };

    let rust_rows = parse_rust(RUST_TABLE);
    let ts_rows = parse_ts(&ts_src);
    // Lower bound pinned to the known table size so a parser/codegen regression
    // that quietly shrinks both tables in lockstep cannot pass: `assert_eq!`
    // alone is satisfied by two equal-but-truncated tables.
    const MIN_EXPECTED_ROWS: usize = 60;
    assert!(
        rust_rows.len() >= MIN_EXPECTED_ROWS,
        "rust parser produced {} entries (expected >= {MIN_EXPECTED_ROWS}); \
         wire_table.rs format may have changed",
        rust_rows.len()
    );
    assert!(
        ts_rows.len() >= MIN_EXPECTED_ROWS,
        "ts parser produced {} entries (expected >= {MIN_EXPECTED_ROWS}); \
         wire-table.ts format may have changed",
        ts_rows.len()
    );
    assert_eq!(
        rust_rows, ts_rows,
        "Rust WIRE_TABLE and TS wire-table.ts diverged. Regenerate both via \
         `scripts/codegen.sh` so the codegen pipeline produces them in lockstep.",
    );
}
