// Auto-generated by truapi-codegen. Do not edit.

export interface MethodInfo {
  name: string;
  type: "unary" | "subscription";
  description?: string;
  requestDescription?: string;
  defaultRequest?: string;
  noParams?: boolean;
}

export interface ServiceInfo {
  name: string;
  methods: MethodInfo[];
}

export const services: ServiceInfo[] = [
  {
    name: "TrUAPI Calls",
    methods: [
      {
        name: "host_handshake",
        type: "unary",
        description:
          'Negotiates the wire codec version with the product. Required for\ncompatibility with `@novasamatech/host-api`-built products that gate\n"connected" state on a successful handshake response.\n\nDefault impl accepts codec version `1` (Novasama\'s `JAM_CODEC_PROTOCOL_ID`)\nand rejects everything else with `UnsupportedProtocolVersion`. Hosts that\nwant to gate handshake on additional preconditions can override.',
        noParams: true,
      },
      {
        name: "host_feature_supported",
        type: "unary",
        description: "Queries whether the host supports a specific feature.",
        requestDescription: "V01HostFeatureSupportedRequest",
        defaultRequest:
          '{ "tag": "Chain", "value": { "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2" } }',
      },
      {
        name: "host_push_notification",
        type: "unary",
        description: "Sends a push notification to the user.",
        requestDescription: "V01HostPushNotificationRequest",
        defaultRequest: '{ "text": "Hello!", "deeplink": null }',
      },
      {
        name: "host_navigate_to",
        type: "unary",
        description: "Requests the host to open a URL.",
        requestDescription: "V01HostNavigateToRequest",
        defaultRequest: '{ "url": "https://example.com" }',
      },
    ],
  },
  {
    name: "Permissions",
    methods: [
      {
        name: "host_device_permission",
        type: "unary",
        description: "Request a device-capability permission from the user.",
        requestDescription: "V02HostDevicePermissionRequest",
        defaultRequest: '{ "tag": "Camera" }',
      },
      {
        name: "remote_permission",
        type: "unary",
        description: "Request one or more remote-operation permissions.",
        requestDescription: "V02RemotePermissionRequest",
        defaultRequest:
          '{ "permissions": [{ "tag": "Remote", "value": { "domains": ["api.example.com"] } }] }',
      },
    ],
  },
  {
    name: "Local Storage",
    methods: [
      {
        name: "host_local_storage_read",
        type: "unary",
        description: "Read a value by key.",
        requestDescription: "V01HostLocalStorageReadRequest",
        defaultRequest: '{ "key": "test-key" }',
      },
      {
        name: "host_local_storage_write",
        type: "unary",
        description: "Write a value to a key.",
        requestDescription: "V01HostLocalStorageWriteRequest",
        defaultRequest: '{ "key": "test-key", "value": "0x48656c6c6f" }',
      },
      {
        name: "host_local_storage_clear",
        type: "unary",
        description: "Clear a value by key.",
        requestDescription: "V01HostLocalStorageClearRequest",
        defaultRequest: '{ "key": "test-key" }',
      },
    ],
  },
  {
    name: "Account Management",
    methods: [
      {
        name: "host_account_connection_status_subscribe",
        type: "subscription",
        description: "Subscribe to account connection status changes.",
        noParams: true,
      },
      {
        name: "host_account_get",
        type: "unary",
        description: "Retrieve a product-scoped account.",
        requestDescription: "V01HostAccountGetRequest",
        defaultRequest:
          '{ "productAccountId": { "dotNsIdentifier": "truapi-playground.dot", "derivationIndex": 0 } }',
      },
      {
        name: "host_account_get_alias",
        type: "unary",
        description: "Retrieve a contextual alias for a product account.",
        requestDescription: "V01HostAccountGetAliasRequest",
        defaultRequest:
          '{ "productAccountId": { "dotNsIdentifier": "truapi-playground.dot", "derivationIndex": 0 } }',
      },
      {
        name: "host_account_create_proof",
        type: "unary",
        description: "Generate a ring VRF proof for a product account.",
        requestDescription: "V01HostAccountCreateProofRequest",
        defaultRequest:
          '{ "productAccountId": { "dotNsIdentifier": "truapi-playground.dot", "derivationIndex": 0 }, "ringLocation": { "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "ringRootHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "hints": { "palletInstance": 42 } }, "context": "0x" }',
      },
      {
        name: "host_get_legacy_accounts",
        type: "unary",
        description: "List non-product accounts the user owns.",
        noParams: true,
      },
      {
        name: "host_get_user_id",
        type: "unary",
        description: "Fetch the user's primary identity (V0.2+).",
        noParams: true,
      },
    ],
  },
  {
    name: "Signing",
    methods: [
      {
        name: "host_create_transaction",
        type: "unary",
        description: "Construct a signed extrinsic for a product account.",
        requestDescription: "V01HostCreateTransactionRequest",
        defaultRequest:
          '{ "productAccountId": { "dotNsIdentifier": "truapi-playground.dot", "derivationIndex": 0 }, "payload": { "tag": "V1", "value": { "signer": null, "callData": "0x0000", "extensions": [], "txExtVersion": 0, "context": { "metadata": "0x", "tokenSymbol": "DOT", "tokenDecimals": 10, "bestBlockHeight": 0 } } } }',
      },
      {
        name: "host_create_transaction_with_legacy_account",
        type: "unary",
        description: "Construct a signed extrinsic for a non-product account.",
        requestDescription: "V01HostCreateTransactionWithLegacyAccountRequest",
        defaultRequest:
          '{ "payload": { "tag": "V1", "value": { "signer": null, "callData": "0x0000", "extensions": [], "txExtVersion": 0, "context": { "metadata": "0x", "tokenSymbol": "DOT", "tokenDecimals": 10, "bestBlockHeight": 0 } } } }',
      },
      {
        name: "host_sign_raw",
        type: "unary",
        description: "Sign raw bytes or a message.",
        requestDescription: "V02HostSignRawRequest",
        defaultRequest:
          '{ "account": { "dotNsIdentifier": "truapi-playground.dot", "derivationIndex": 0 }, "data": { "tag": "Bytes", "value": { "bytes": "0x48656c6c6f" } } }',
      },
      {
        name: "host_sign_payload",
        type: "unary",
        description: "Sign a Substrate extrinsic payload.",
        requestDescription: "V02HostSignPayloadRequest",
        defaultRequest:
          '{ "account": { "dotNsIdentifier": "truapi-playground.dot", "derivationIndex": 0 }, "blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "blockNumber": "0x00000000", "era": "0x00", "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "method": "0x00000000", "nonce": "0x00000000", "signedExtensions": [], "specVersion": "0x00000000", "tip": "0x00000000000000000000000000000000", "transactionVersion": "0x00000000", "version": 4 }',
      },
    ],
  },
  {
    name: "Chat",
    methods: [
      {
        name: "host_chat_create_room",
        type: "unary",
        description: "Create a chat room.",
        requestDescription: "V01HostChatCreateRoomRequest",
        defaultRequest:
          '{ "roomId": "test-room", "name": "Test Room", "icon": "" }',
      },
      {
        name: "host_chat_register_bot",
        type: "unary",
        description: "Register a chat bot.",
        requestDescription: "V01HostChatRegisterBotRequest",
        defaultRequest:
          '{ "botId": "test-bot", "name": "Test Bot", "icon": "" }',
      },
      {
        name: "host_chat_list_subscribe",
        type: "subscription",
        description: "Subscribe to the list of chat rooms.",
        noParams: true,
      },
      {
        name: "host_chat_post_message",
        type: "unary",
        description: "Post a message to a chat room.",
        requestDescription: "V01HostChatPostMessageRequest",
        defaultRequest:
          '{ "roomId": "test-room", "payload": { "tag": "Text", "value": "Hello from playground!" } }',
      },
      {
        name: "host_chat_action_subscribe",
        type: "subscription",
        description: "Subscribe to received chat actions.",
        noParams: true,
      },
      {
        name: "product_chat_custom_message_render_subscribe",
        type: "subscription",
        description:
          "Subscribe to custom message render requests from the host. Each\nemitted item is a [`CustomRendererNode`](crate::v01::CustomRendererNode)\ntree describing the rendered UI.",
        requestDescription: "V01ProductChatCustomMessageRenderSubscribeRequest",
        defaultRequest:
          '{ "messageId": "msg-1", "messageType": "custom-render-demo", "payload": { "bytes": "0x" } }',
      },
      {
        name: "host_chat_create_simple_group",
        type: "unary",
        description: "Create a simple group chat room (V0.2+).",
        requestDescription: "V02HostChatCreateSimpleGroupRequest",
        defaultRequest:
          '{ "roomId": "test-simple-group", "name": "Test Group", "icon": "" }',
      },
    ],
  },
  {
    name: "Statement Store",
    methods: [
      {
        name: "remote_statement_store_subscribe",
        type: "subscription",
        description: "Subscribe to statements matching a topic filter.",
        requestDescription: "V02RemoteStatementStoreSubscribeRequest",
        defaultRequest: '{ "tag": "MatchAll", "value": [] }',
      },
      {
        name: "remote_statement_store_create_proof",
        type: "unary",
        description: "Create a proof for a statement.",
        requestDescription: "V01RemoteStatementStoreCreateProofRequest",
        defaultRequest:
          '{ "productAccountId": { "dotNsIdentifier": "truapi-playground.dot", "derivationIndex": 0 }, "statement": { "proof": null, "decryptionKey": null, "expiry": "9999999999999n", "channel": null, "topics": [], "data": null } }',
      },
      {
        name: "remote_statement_store_submit",
        type: "unary",
        description:
          "Submit a signed statement to the network. The request body is the\n[`SignedStatement`](crate::v01::SignedStatement) directly (no wrapping\nstruct), matching upstream `triangle-js-sdks`.",
        requestDescription: "SignedStatement",
        defaultRequest:
          '{ "proof": { "tag": "Sr25519", "value": { "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "signer": "0x0000000000000000000000000000000000000000000000000000000000000000" } }, "decryptionKey": null, "expiry": null, "channel": null, "topics": [], "data": null }',
      },
    ],
  },
  {
    name: "Preimage",
    methods: [
      {
        name: "remote_preimage_lookup_subscribe",
        type: "subscription",
        description: "Subscribe to preimage lookups for a given key.",
        requestDescription: "V01RemotePreimageLookupSubscribeRequest",
        defaultRequest:
          '{ "key": "0x0000000000000000000000000000000000000000000000000000000000000000" }',
      },
    ],
  },
  {
    name: "Chain Interaction",
    methods: [
      {
        name: "remote_chain_head_follow",
        type: "subscription",
        description: "Follow the chain head and receive block events.",
        requestDescription: "V01RemoteChainHeadFollowRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "withRuntime": false }',
      },
      {
        name: "remote_chain_head_header",
        type: "unary",
        description: "Fetch a block header.",
        requestDescription: "V01RemoteChainHeadHeaderRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "followSubscriptionId": "", "hash": "0x0000000000000000000000000000000000000000000000000000000000000000" }',
      },
      {
        name: "remote_chain_head_body",
        type: "unary",
        description: "Fetch a block body.",
        requestDescription: "V01RemoteChainHeadBodyRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "followSubscriptionId": "", "hash": "0x0000000000000000000000000000000000000000000000000000000000000000" }',
      },
      {
        name: "remote_chain_head_storage",
        type: "unary",
        description: "Query runtime storage at a specific block.",
        requestDescription: "V01RemoteChainHeadStorageRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "followSubscriptionId": "", "hash": "0x0000000000000000000000000000000000000000000000000000000000000000", "items": [{ "key": "0x26aa394eea5630e07c48ae0c9558cef7", "queryType": { "tag": "Value" } }], "childTrie": null }',
      },
      {
        name: "remote_chain_head_call",
        type: "unary",
        description: "Invoke a runtime call at a specific block.",
        requestDescription: "V01RemoteChainHeadCallRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "followSubscriptionId": "", "hash": "0x0000000000000000000000000000000000000000000000000000000000000000", "function": "Core_version", "callParameters": "0x" }',
      },
      {
        name: "remote_chain_head_unpin",
        type: "unary",
        description: "Release pinned blocks.",
        requestDescription: "V01RemoteChainHeadUnpinRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "followSubscriptionId": "", "hashes": ["0x0000000000000000000000000000000000000000000000000000000000000000"] }',
      },
      {
        name: "remote_chain_head_continue",
        type: "unary",
        description: "Continue a paused chain-head operation.",
        requestDescription: "V01RemoteChainHeadContinueRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "followSubscriptionId": "", "operationId": "op-id" }',
      },
      {
        name: "remote_chain_head_stop_operation",
        type: "unary",
        description: "Stop a chain-head operation.",
        requestDescription: "V01RemoteChainHeadStopOperationRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "followSubscriptionId": "", "operationId": "op-id" }',
      },
      {
        name: "remote_chain_spec_genesis_hash",
        type: "unary",
        description: "Fetch the canonical genesis hash for a chain.",
        requestDescription: "V01RemoteChainSpecGenesisHashRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2" }',
      },
      {
        name: "remote_chain_spec_chain_name",
        type: "unary",
        description: "Fetch the display name of a chain.",
        requestDescription: "V01RemoteChainSpecChainNameRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2" }',
      },
      {
        name: "remote_chain_spec_properties",
        type: "unary",
        description: "Fetch the JSON-encoded properties of a chain.",
        requestDescription: "V01RemoteChainSpecPropertiesRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2" }',
      },
      {
        name: "remote_chain_transaction_broadcast",
        type: "unary",
        description: "Broadcast a signed transaction.",
        requestDescription: "V01RemoteChainTransactionBroadcastRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "transaction": "0x" }',
      },
      {
        name: "remote_chain_transaction_stop",
        type: "unary",
        description: "Stop a transaction broadcast.",
        requestDescription: "V01RemoteChainTransactionStopRequest",
        defaultRequest:
          '{ "genesisHash": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2", "operationId": "op-id" }',
      },
    ],
  },
  {
    name: "Payment",
    methods: [
      {
        name: "host_payment_balance_subscribe",
        type: "subscription",
        description: "Subscribe to payment balance updates.",
        noParams: true,
      },
      {
        name: "host_payment_top_up",
        type: "unary",
        description: "Top up the user's payment balance.",
        requestDescription: "V02HostPaymentTopUpRequest",
        defaultRequest:
          '{ "amount": "0n", "source": { "tag": "ProductAccount", "value": { "derivationIndex": 0 } } }',
      },
      {
        name: "host_payment_request",
        type: "unary",
        description: "Request a payment from the user.",
        requestDescription: "V02HostPaymentRequestRequest",
        defaultRequest:
          '{ "amount": "0n", "destination": "0x0000000000000000000000000000000000000000000000000000000000000000" }',
      },
      {
        name: "host_payment_status_subscribe",
        type: "subscription",
        description:
          "Subscribe to payment lifecycle updates for a specific payment.",
        requestDescription: "V02HostPaymentStatusSubscribeRequest",
        defaultRequest: '{ "paymentId": "payment-id" }',
      },
    ],
  },
  {
    name: "Entropy Derivation",
    methods: [
      {
        name: "host_derive_entropy",
        type: "unary",
        description:
          "Derive 32 bytes of entropy from the user's root BIP-39 entropy for the\ngiven key.",
        requestDescription: "V02HostDeriveEntropyRequest",
        defaultRequest: '{ "context": "0x" }',
      },
    ],
  },
];
