// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD0
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod0)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD1
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD2
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD3
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod3)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD4
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod4)(uint64_t, RustBuffer, int8_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD5
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod5)(uint64_t, RustBuffer, int8_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD6
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod6)(uint64_t, RustBuffer, int8_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD7
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod7)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD8
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod8)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD9
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod9)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_HOST_CALLBACKS
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_HOST_CALLBACKS
typedef struct UniffiVTableCallbackInterfaceHostCallbacks {
    UniffiCallbackInterfaceHostCallbacksMethod0 _Nonnull onCoreLog;
    UniffiCallbackInterfaceHostCallbacksMethod1 _Nonnull onCoreResponse;
    UniffiCallbackInterfaceHostCallbacksMethod2 _Nonnull navigateTo;
    UniffiCallbackInterfaceHostCallbacksMethod3 _Nonnull pushNotification;
    UniffiCallbackInterfaceHostCallbacksMethod4 _Nonnull devicePermission;
    UniffiCallbackInterfaceHostCallbacksMethod5 _Nonnull remotePermission;
    UniffiCallbackInterfaceHostCallbacksMethod6 _Nonnull featureSupported;
    UniffiCallbackInterfaceHostCallbacksMethod7 _Nonnull localStorageRead;
    UniffiCallbackInterfaceHostCallbacksMethod8 _Nonnull localStorageWrite;
    UniffiCallbackInterfaceHostCallbacksMethod9 _Nonnull localStorageClear;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceHostCallbacks;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVETRUAPICORE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVETRUAPICORE
void*_Nonnull uniffi_truapi_server_fn_clone_nativetruapicore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVETRUAPICORE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVETRUAPICORE
void uniffi_truapi_server_fn_free_nativetruapicore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CONSTRUCTOR_NATIVETRUAPICORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CONSTRUCTOR_NATIVETRUAPICORE_NEW
void*_Nonnull uniffi_truapi_server_fn_constructor_nativetruapicore_new(uint64_t callbacks, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_CLEAR_ACTIVE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_CLEAR_ACTIVE_SESSION
void uniffi_truapi_server_fn_method_nativetruapicore_clear_active_session(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_DEBUG_SMOKE_FEATURE_REQUEST_FRAME
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_DEBUG_SMOKE_FEATURE_REQUEST_FRAME
RustBuffer uniffi_truapi_server_fn_method_nativetruapicore_debug_smoke_feature_request_frame(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_RECEIVE_FROM_PRODUCT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_RECEIVE_FROM_PRODUCT
int8_t uniffi_truapi_server_fn_method_nativetruapicore_receive_from_product(void*_Nonnull ptr, RustBuffer frame, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_SET_ACTIVE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_SET_ACTIVE_SESSION
int8_t uniffi_truapi_server_fn_method_nativetruapicore_set_active_session(void*_Nonnull ptr, RustBuffer pubkey, RustBuffer lite_username, RustBuffer full_username, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
RustBuffer uniffi_truapi_server_fn_method_nativetruapicore_start_ws_bridge(void*_Nonnull ptr, uint16_t bind_port, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
void uniffi_truapi_server_fn_method_nativetruapicore_stop_ws_bridge(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_INIT_CALLBACK_VTABLE_HOSTCALLBACKS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_INIT_CALLBACK_VTABLE_HOSTCALLBACKS
void uniffi_truapi_server_fn_init_callback_vtable_hostcallbacks(const UniffiVTableCallbackInterfaceHostCallbacks* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_ALLOC
RustBuffer ffi_truapi_server_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_truapi_server_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FREE
void ffi_truapi_server_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_RESERVE
RustBuffer ffi_truapi_server_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U8
void ffi_truapi_server_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U8
void ffi_truapi_server_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U8
void ffi_truapi_server_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_truapi_server_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I8
void ffi_truapi_server_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I8
void ffi_truapi_server_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I8
void ffi_truapi_server_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I8
int8_t ffi_truapi_server_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U16
void ffi_truapi_server_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U16
void ffi_truapi_server_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U16
void ffi_truapi_server_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_truapi_server_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I16
void ffi_truapi_server_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I16
void ffi_truapi_server_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I16
void ffi_truapi_server_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I16
int16_t ffi_truapi_server_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U32
void ffi_truapi_server_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U32
void ffi_truapi_server_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U32
void ffi_truapi_server_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_truapi_server_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I32
void ffi_truapi_server_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I32
void ffi_truapi_server_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I32
void ffi_truapi_server_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I32
int32_t ffi_truapi_server_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U64
void ffi_truapi_server_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U64
void ffi_truapi_server_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U64
void ffi_truapi_server_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_truapi_server_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I64
void ffi_truapi_server_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I64
void ffi_truapi_server_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I64
void ffi_truapi_server_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I64
int64_t ffi_truapi_server_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F32
void ffi_truapi_server_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F32
void ffi_truapi_server_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F32
void ffi_truapi_server_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F32
float ffi_truapi_server_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F64
void ffi_truapi_server_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F64
void ffi_truapi_server_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F64
void ffi_truapi_server_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F64
double ffi_truapi_server_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_POINTER
void ffi_truapi_server_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_POINTER
void ffi_truapi_server_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_POINTER
void ffi_truapi_server_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_truapi_server_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_truapi_server_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_truapi_server_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_truapi_server_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_truapi_server_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_VOID
void ffi_truapi_server_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_VOID
void ffi_truapi_server_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_VOID
void ffi_truapi_server_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_VOID
void ffi_truapi_server_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_CLEAR_ACTIVE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_CLEAR_ACTIVE_SESSION
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_clear_active_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_DEBUG_SMOKE_FEATURE_REQUEST_FRAME
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_DEBUG_SMOKE_FEATURE_REQUEST_FRAME
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_debug_smoke_feature_request_frame(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_RECEIVE_FROM_PRODUCT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_RECEIVE_FROM_PRODUCT
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_receive_from_product(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_SET_ACTIVE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_SET_ACTIVE_SESSION
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_set_active_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_start_ws_bridge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_stop_ws_bridge(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_CONSTRUCTOR_NATIVETRUAPICORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_CONSTRUCTOR_NATIVETRUAPICORE_NEW
uint16_t uniffi_truapi_server_checksum_constructor_nativetruapicore_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_ON_CORE_LOG
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_ON_CORE_LOG
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_on_core_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_ON_CORE_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_ON_CORE_RESPONSE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_on_core_response(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_NAVIGATE_TO
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_NAVIGATE_TO
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_navigate_to(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_PUSH_NOTIFICATION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_PUSH_NOTIFICATION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_push_notification(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_DEVICE_PERMISSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_DEVICE_PERMISSION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_device_permission(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_REMOTE_PERMISSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_REMOTE_PERMISSION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_remote_permission(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_FEATURE_SUPPORTED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_FEATURE_SUPPORTED
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_feature_supported(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_READ
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_READ
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_local_storage_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_WRITE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_local_storage_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_CLEAR
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_CLEAR
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_local_storage_clear(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_UNIFFI_CONTRACT_VERSION
uint32_t ffi_truapi_server_uniffi_contract_version(void
    
);
#endif

