/// TrUAPI Dart host dispatcher.
///
/// For host applications (e.g. a Flutter desktop host) that implement the
/// protocol the products inside them call. Implement the generated
/// `TruapiHostHandlers` (one typed handler group per service) and wire them to
/// a [Provider] with `createTruapiServer`:
///
/// ```dart
/// import 'package:truapi/host.dart';
///
/// final server = createTruapiServer(provider, MyHostHandlers());
/// // ... later:
/// server.dispose();
/// ```
///
/// Handlers receive and return the inner (selected-version) protocol types
/// (the same `types.dart` the client uses); the generated dispatch entries
/// handle versioned wire wrapping, SCALE encode/decode, and the
/// request/subscription frame lifecycle.
library;

export 'src/result.dart';
export 'src/scale.dart' show Codec, Input, Unit, unitValue;
export 'src/transport.dart'
    show
        Provider,
        ProtocolMessage,
        RequestFrameIds,
        SubscriptionFrameIds,
        SubscriptionInterrupted,
        decodeWireMessage,
        encodeWireMessage;
export 'src/host/host_server.dart';
// Generated by `truapi-codegen --dart-host-output`:
export 'src/generated/types.dart';
export 'src/generated/host.dart';
