// AUTO-GENERATED by explorer/scripts/aggregate-diagnosis-matrix.mjs.
// Source: per-host diagnosis reports run from the playground's Diagnosis
// screen. Do not edit by hand — rerun `npm run generate-matrix` instead.

import type { CompatibilityMatrix } from "./compatibility-types";

export const compatibility: CompatibilityMatrix = {
  "generatedAt": "2026-06-02T13:12:17.219Z",
  "hosts": [
    {
      "label": "Desktop",
      "mode": "Desktop",
      "reportedAt": "2026-06-02T13:11:33.130Z"
    },
    {
      "label": "Web",
      "mode": "Web",
      "reportedAt": "2026-06-02T12:52:16.980Z"
    },
    {
      "label": "Android",
      "mode": "Android",
      "reportedAt": "2026-06-01T17:52:07.578Z"
    },
    {
      "label": "iOS",
      "mode": "iOS",
      "reportedAt": ""
    }
  ],
  "methods": [
    {
      "id": "Account/connection_status_subscribe",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Account/get_account",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Account/get_account_alias",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Account/create_account_proof",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }"
      }
    },
    {
      "id": "Account/get_legacy_accounts",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Account/get_user_id",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "fail",
        "iOS": null
      }
    },
    {
      "id": "Account/request_login",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/follow_head_subscribe",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/get_head_header",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/get_head_body",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/get_head_storage",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/call_head",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/unpin_head",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/continue_head",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/stop_head_operation",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/get_spec_genesis_hash",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/get_spec_chain_name",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/get_spec_properties",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/broadcast_transaction",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chain/stop_transaction",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Chat/create_room",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }"
      }
    },
    {
      "id": "Chat/register_bot",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }"
      }
    },
    {
      "id": "Chat/list_subscribe",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "fail",
        "iOS": null
      }
    },
    {
      "id": "Chat/post_message",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }"
      }
    },
    {
      "id": "Chat/action_subscribe",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "fail",
        "iOS": null
      }
    },
    {
      "id": "Chat/custom_message_render_subscribe",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "subscription delivered no events in 6s",
        "Web": "subscription delivered no events in 6s"
      }
    },
    {
      "id": "Entropy/derive",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Local Storage/read",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Local Storage/write",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Local Storage/clear",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Notifications/send_push_notification",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Notifications/cancel_push_notification",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Payment/balance_subscribe",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "pass",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"name\": \"SubscriptionError\", \"reason\": { \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } } }",
        "Web": "{ \"name\": \"SubscriptionError\", \"reason\": { \"tag\": \"PermissionDenied\" } }"
      }
    },
    {
      "id": "Payment/top_up",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "pass",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Payments are not supported in dot.li\" } }"
      }
    },
    {
      "id": "Payment/request",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "topUp failed: { \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "topUp failed: { \"tag\": \"Unknown\", \"value\": { \"reason\": \"Payments are not supported in dot.li\" } }"
      }
    },
    {
      "id": "Payment/status_subscribe",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "topUp failed: { \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "topUp failed: { \"tag\": \"Unknown\", \"value\": { \"reason\": \"Payments are not supported in dot.li\" } }"
      }
    },
    {
      "id": "Permissions/request_device_permission",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Permissions/request_remote_permission",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Preimage/lookup_subscribe",
      "results": {
        "Desktop": "fail",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      },
      "details": {
        "Desktop": "submit failed: { \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }"
      }
    },
    {
      "id": "Preimage/submit",
      "results": {
        "Desktop": "fail",
        "Web": "pass",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }"
      }
    },
    {
      "id": "Resource Allocation/request",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Signing/create_transaction",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "fail",
        "iOS": null
      }
    },
    {
      "id": "Signing/create_transaction_with_legacy_account",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Account can't be derived from product account id\" } }"
      }
    },
    {
      "id": "Signing/sign_raw_with_legacy_account",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Account can't be derived from product account id\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Account can't be derived from product account id\" } }"
      }
    },
    {
      "id": "Signing/sign_payload_with_legacy_account",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Account can't be derived from product account id\" } }",
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Account can't be derived from product account id\" } }"
      }
    },
    {
      "id": "Signing/sign_raw",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Signing/sign_payload",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Statement Store/subscribe",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "fail",
        "iOS": null
      }
    },
    {
      "id": "Statement Store/create_proof",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Statement Store/submit",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": "fail",
        "iOS": null
      },
      "details": {
        "Desktop": "submit failed: { \"reason\": \"Submit failed, statement already expired\" }",
        "Web": "submit failed: { \"reason\": \"Submit failed, statement already expired\" }"
      }
    },
    {
      "id": "Statement Store/create_proof_authorized",
      "results": {
        "Desktop": "pass",
        "Web": "fail",
        "Android": "pass",
        "iOS": null
      },
      "details": {
        "Web": "{ \"tag\": \"Unknown\", \"value\": { \"reason\": \"Not implemented\" } }"
      }
    },
    {
      "id": "System/handshake",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "System/feature_supported",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "System/navigate_to",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Theme/subscribe",
      "results": {
        "Desktop": "pass",
        "Web": "pass",
        "Android": "pass",
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/create_purse",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/query_purse",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/rebalance_purse",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/delete_purse",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/create_receivable",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/create_cheque",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/deposit",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/refund",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    },
    {
      "id": "Coin Payment/listen_for_payment",
      "results": {
        "Desktop": "fail",
        "Web": "fail",
        "Android": null,
        "iOS": null
      }
    }
  ]
};
