// TrUAPI host scaffold — a starting point for a Flutter/Dart host.
//
// Copy this into your host app and replace each `throw UnimplementedError(...)`
// with your host logic, then start the server with your transport Provider:
//
//   final server = createTruapiServer(provider, ScaffoldHostHandlers());
//   // ... later: server.dispose();
//
// Backing notes (heuristic — adjust to your host):
//   smoldart (light client, when ready): Chain, Preimage, Payment, CoinPayment,
//                                         StatementStore
//   host-local:                          System, Theme, LocalStorage,
//                                         Notifications, Permissions, Entropy,
//                                         ResourceAllocation
//   wallet / keystore:                   Account, Signing
//   messaging:                           Chat
//
// This file is a one-shot scaffold (not regenerated by the build): edit freely.

import 'dart:typed_data';

import 'package:truapi/truapi.dart';

/// Account lookup, aliasing, and proof generation.
class AccountHandlers implements AccountHostHandlers {
  @override
  Stream<HostAccountConnectionStatusSubscribeItem> connectionStatusSubscribe(
          CallContext ctx) =>
      throw UnimplementedError(
          'Account.connectionStatusSubscribe: not implemented');
  @override
  Future<Result<HostAccountGetResponse, HostAccountGetError>> getAccount(
          CallContext ctx, HostAccountGetRequest request) =>
      throw UnimplementedError('Account.getAccount: not implemented');
  @override
  Future<Result<HostAccountGetAliasResponse, HostAccountGetError>>
      getAccountAlias(CallContext ctx, HostAccountGetAliasRequest request) =>
          throw UnimplementedError('Account.getAccountAlias: not implemented');
  @override
  Future<Result<HostAccountCreateProofResponse, HostAccountCreateProofError>>
      createAccountProof(
              CallContext ctx, HostAccountCreateProofRequest request) =>
          throw UnimplementedError(
              'Account.createAccountProof: not implemented');
  @override
  Future<Result<HostGetLegacyAccountsResponse, HostAccountGetError>>
      getLegacyAccounts(CallContext ctx) => throw UnimplementedError(
          'Account.getLegacyAccounts: not implemented');
  @override
  Future<Result<HostGetUserIdResponse, HostGetUserIdError>> getUserId(
          CallContext ctx) =>
      throw UnimplementedError('Account.getUserId: not implemented');
  @override
  Future<Result<HostRequestLoginResponse, HostRequestLoginError>> requestLogin(
          CallContext ctx, HostRequestLoginRequest request) =>
      throw UnimplementedError('Account.requestLogin: not implemented');
}

/// Chain interaction methods.
class ChainHandlers implements ChainHostHandlers {
  @override
  Stream<RemoteChainHeadFollowItem> followHeadSubscribe(
          CallContext ctx, RemoteChainHeadFollowRequest request) =>
      throw UnimplementedError('Chain.followHeadSubscribe: not implemented');
  @override
  Future<Result<RemoteChainHeadHeaderResponse, GenericError>> getHeadHeader(
          CallContext ctx, RemoteChainHeadHeaderRequest request) =>
      throw UnimplementedError('Chain.getHeadHeader: not implemented');
  @override
  Future<Result<RemoteChainHeadBodyResponse, GenericError>> getHeadBody(
          CallContext ctx, RemoteChainHeadBodyRequest request) =>
      throw UnimplementedError('Chain.getHeadBody: not implemented');
  @override
  Future<Result<RemoteChainHeadStorageResponse, GenericError>> getHeadStorage(
          CallContext ctx, RemoteChainHeadStorageRequest request) =>
      throw UnimplementedError('Chain.getHeadStorage: not implemented');
  @override
  Future<Result<RemoteChainHeadCallResponse, GenericError>> callHead(
          CallContext ctx, RemoteChainHeadCallRequest request) =>
      throw UnimplementedError('Chain.callHead: not implemented');
  @override
  Future<Result<Unit, GenericError>> unpinHead(
          CallContext ctx, RemoteChainHeadUnpinRequest request) =>
      throw UnimplementedError('Chain.unpinHead: not implemented');
  @override
  Future<Result<Unit, GenericError>> continueHead(
          CallContext ctx, RemoteChainHeadContinueRequest request) =>
      throw UnimplementedError('Chain.continueHead: not implemented');
  @override
  Future<Result<Unit, GenericError>> stopHeadOperation(
          CallContext ctx, RemoteChainHeadStopOperationRequest request) =>
      throw UnimplementedError('Chain.stopHeadOperation: not implemented');
  @override
  Future<Result<RemoteChainSpecGenesisHashResponse, GenericError>>
      getSpecGenesisHash(
              CallContext ctx, RemoteChainSpecGenesisHashRequest request) =>
          throw UnimplementedError('Chain.getSpecGenesisHash: not implemented');
  @override
  Future<Result<RemoteChainSpecChainNameResponse, GenericError>>
      getSpecChainName(
              CallContext ctx, RemoteChainSpecChainNameRequest request) =>
          throw UnimplementedError('Chain.getSpecChainName: not implemented');
  @override
  Future<Result<RemoteChainSpecPropertiesResponse, GenericError>>
      getSpecProperties(
              CallContext ctx, RemoteChainSpecPropertiesRequest request) =>
          throw UnimplementedError('Chain.getSpecProperties: not implemented');
  @override
  Future<Result<RemoteChainTransactionBroadcastResponse, GenericError>>
      broadcastTransaction(CallContext ctx,
              RemoteChainTransactionBroadcastRequest request) =>
          throw UnimplementedError(
              'Chain.broadcastTransaction: not implemented');
  @override
  Future<Result<Unit, GenericError>> stopTransaction(
          CallContext ctx, RemoteChainTransactionStopRequest request) =>
      throw UnimplementedError('Chain.stopTransaction: not implemented');
}

/// Chat room, bot, and message APIs.
class ChatHandlers implements ChatHostHandlers {
  @override
  Future<Result<HostChatCreateRoomResponse, HostChatCreateRoomError>>
      createRoom(CallContext ctx, HostChatCreateRoomRequest request) =>
          throw UnimplementedError('Chat.createRoom: not implemented');
  @override
  Future<Result<HostChatRegisterBotResponse, HostChatRegisterBotError>>
      registerBot(CallContext ctx, HostChatRegisterBotRequest request) =>
          throw UnimplementedError('Chat.registerBot: not implemented');
  @override
  Stream<HostChatListSubscribeItem> listSubscribe(CallContext ctx) =>
      throw UnimplementedError('Chat.listSubscribe: not implemented');
  @override
  Future<Result<HostChatPostMessageResponse, HostChatPostMessageError>>
      postMessage(CallContext ctx, HostChatPostMessageRequest request) =>
          throw UnimplementedError('Chat.postMessage: not implemented');
  @override
  Stream<HostChatActionSubscribeItem> actionSubscribe(CallContext ctx) =>
      throw UnimplementedError('Chat.actionSubscribe: not implemented');
  @override
  Stream<CustomRendererNode> customMessageRenderSubscribe(CallContext ctx,
          ProductChatCustomMessageRenderSubscribeRequest request) =>
      throw UnimplementedError(
          'Chat.customMessageRenderSubscribe: not implemented');
}

/// CoinPayment operations.
///
/// RFC 0017 describes `Resolvable<T>` values for long-running operations.
/// TrUAPI represents those as subscriptions whose items are the RFC status
/// updates.
class CoinPaymentHandlers implements CoinPaymentHostHandlers {
  @override
  Future<Result<HostCoinPaymentCreatePurseResponse, CoinPaymentError>>
      createPurse(CallContext ctx, HostCoinPaymentCreatePurseRequest request) =>
          throw UnimplementedError('CoinPayment.createPurse: not implemented');
  @override
  Future<Result<HostCoinPaymentQueryPurseResponse, CoinPaymentError>>
      queryPurse(CallContext ctx, HostCoinPaymentQueryPurseRequest request) =>
          throw UnimplementedError('CoinPayment.queryPurse: not implemented');
  @override
  Stream<CoinPaymentStatus> rebalancePurse(
          CallContext ctx, HostCoinPaymentRebalancePurseRequest request) =>
      throw UnimplementedError('CoinPayment.rebalancePurse: not implemented');
  @override
  Stream<CoinPaymentStatus> deletePurse(
          CallContext ctx, HostCoinPaymentDeletePurseRequest request) =>
      throw UnimplementedError('CoinPayment.deletePurse: not implemented');
  @override
  Future<Result<HostCoinPaymentCreateReceivableResponse, CoinPaymentError>>
      createReceivable(CallContext ctx,
              HostCoinPaymentCreateReceivableRequest request) =>
          throw UnimplementedError(
              'CoinPayment.createReceivable: not implemented');
  @override
  Future<Result<HostCoinPaymentCreateChequeResponse, CoinPaymentError>>
      createCheque(
              CallContext ctx, HostCoinPaymentCreateChequeRequest request) =>
          throw UnimplementedError('CoinPayment.createCheque: not implemented');
  @override
  Stream<CoinPaymentStatus> deposit(
          CallContext ctx, HostCoinPaymentDepositRequest request) =>
      throw UnimplementedError('CoinPayment.deposit: not implemented');
  @override
  Stream<CoinPaymentStatus> refund(
          CallContext ctx, HostCoinPaymentRefundRequest request) =>
      throw UnimplementedError('CoinPayment.refund: not implemented');
  @override
  Stream<HostCoinPaymentListenForItem> listenForPayment(
          CallContext ctx, HostCoinPaymentListenForRequest request) =>
      throw UnimplementedError('CoinPayment.listenForPayment: not implemented');
}

/// Deterministic entropy derivation.
class EntropyHandlers implements EntropyHostHandlers {
  @override
  Future<Result<HostDeriveEntropyResponse, HostDeriveEntropyError>> derive(
          CallContext ctx, HostDeriveEntropyRequest request) =>
      throw UnimplementedError('Entropy.derive: not implemented');
}

/// Local key/value storage scoped to the calling product.
class LocalStorageHandlers implements LocalStorageHostHandlers {
  @override
  Future<Result<HostLocalStorageReadResponse, HostLocalStorageReadError>> read(
          CallContext ctx, HostLocalStorageReadRequest request) =>
      throw UnimplementedError('LocalStorage.read: not implemented');
  @override
  Future<Result<Unit, HostLocalStorageReadError>> write(
          CallContext ctx, HostLocalStorageWriteRequest request) =>
      throw UnimplementedError('LocalStorage.write: not implemented');
  @override
  Future<Result<Unit, HostLocalStorageReadError>> clear(
          CallContext ctx, HostLocalStorageClearRequest request) =>
      throw UnimplementedError('LocalStorage.clear: not implemented');
}

/// Notification methods for locally-rendered push notifications.
class NotificationsHandlers implements NotificationsHostHandlers {
  @override
  Future<Result<HostPushNotificationResponse, HostPushNotificationError>>
      sendPushNotification(
              CallContext ctx, HostPushNotificationRequest request) =>
          throw UnimplementedError(
              'Notifications.sendPushNotification: not implemented');
  @override
  Future<Result<Unit, GenericError>> cancelPushNotification(
          CallContext ctx, HostPushNotificationCancelRequest request) =>
      throw UnimplementedError(
          'Notifications.cancelPushNotification: not implemented');
}

/// Payment request and balance/status subscription methods.
class PaymentHandlers implements PaymentHostHandlers {
  @override
  Stream<HostPaymentBalanceSubscribeItem> balanceSubscribe(
          CallContext ctx, HostPaymentBalanceSubscribeRequest request) =>
      throw UnimplementedError('Payment.balanceSubscribe: not implemented');
  @override
  Future<Result<HostPaymentResponse, HostPaymentError>> request(
          CallContext ctx, HostPaymentRequest request) =>
      throw UnimplementedError('Payment.request: not implemented');
  @override
  Stream<HostPaymentStatusSubscribeItem> statusSubscribe(
          CallContext ctx, HostPaymentStatusSubscribeRequest request) =>
      throw UnimplementedError('Payment.statusSubscribe: not implemented');
  @override
  Future<Result<Unit, HostPaymentTopUpError>> topUp(
          CallContext ctx, HostPaymentTopUpRequest request) =>
      throw UnimplementedError('Payment.topUp: not implemented');
}

/// Permission request methods.
class PermissionsHandlers implements PermissionsHostHandlers {
  @override
  Future<Result<HostDevicePermissionResponse, GenericError>>
      requestDevicePermission(
              CallContext ctx, HostDevicePermissionRequest request) =>
          throw UnimplementedError(
              'Permissions.requestDevicePermission: not implemented');
  @override
  Future<Result<RemotePermissionResponse, GenericError>>
      requestRemotePermission(
              CallContext ctx, RemotePermissionRequest request) =>
          throw UnimplementedError(
              'Permissions.requestRemotePermission: not implemented');
}

/// Preimage lookup and submission methods.
class PreimageHandlers implements PreimageHostHandlers {
  @override
  Stream<RemotePreimageLookupSubscribeItem> lookupSubscribe(
          CallContext ctx, RemotePreimageLookupSubscribeRequest request) =>
      throw UnimplementedError('Preimage.lookupSubscribe: not implemented');
  @override
  Future<Result<Uint8List, PreimageSubmitError>> submit(
          CallContext ctx, Uint8List request) =>
      throw UnimplementedError('Preimage.submit: not implemented');
}

/// Resource pre-allocation (allowance management).
class ResourceAllocationHandlers implements ResourceAllocationHostHandlers {
  @override
  Future<Result<HostRequestResourceAllocationResponse, ResourceAllocationError>>
      request(CallContext ctx, HostRequestResourceAllocationRequest request) =>
          throw UnimplementedError(
              'ResourceAllocation.request: not implemented');
}

/// Signing operations.
class SigningHandlers implements SigningHostHandlers {
  @override
  Future<Result<HostCreateTransactionResponse, HostCreateTransactionError>>
      createTransaction(CallContext ctx, ProductAccountTxPayload request) =>
          throw UnimplementedError(
              'Signing.createTransaction: not implemented');
  @override
  Future<
          Result<HostCreateTransactionWithLegacyAccountResponse,
              HostCreateTransactionError>>
      createTransactionWithLegacyAccount(
              CallContext ctx, LegacyAccountTxPayload request) =>
          throw UnimplementedError(
              'Signing.createTransactionWithLegacyAccount: not implemented');
  @override
  Future<Result<HostSignPayloadResponse, HostSignPayloadError>>
      signRawWithLegacyAccount(
              CallContext ctx, HostSignRawWithLegacyAccountRequest request) =>
          throw UnimplementedError(
              'Signing.signRawWithLegacyAccount: not implemented');
  @override
  Future<Result<HostSignPayloadResponse, HostSignPayloadError>>
      signPayloadWithLegacyAccount(CallContext ctx,
              HostSignPayloadWithLegacyAccountRequest request) =>
          throw UnimplementedError(
              'Signing.signPayloadWithLegacyAccount: not implemented');
  @override
  Future<Result<HostSignPayloadResponse, HostSignPayloadError>> signRaw(
          CallContext ctx, HostSignRawRequest request) =>
      throw UnimplementedError('Signing.signRaw: not implemented');
  @override
  Future<Result<HostSignPayloadResponse, HostSignPayloadError>> signPayload(
          CallContext ctx, HostSignPayloadRequest request) =>
      throw UnimplementedError('Signing.signPayload: not implemented');
}

/// Statement store methods.
class StatementStoreHandlers implements StatementStoreHostHandlers {
  @override
  Stream<RemoteStatementStoreSubscribeItem> subscribe(
          CallContext ctx, RemoteStatementStoreSubscribeRequest request) =>
      throw UnimplementedError('StatementStore.subscribe: not implemented');
  @override
  Future<
          Result<RemoteStatementStoreCreateProofResponse,
              RemoteStatementStoreCreateProofError>>
      createProof(CallContext ctx,
              RemoteStatementStoreCreateProofRequest request) =>
          throw UnimplementedError(
              'StatementStore.createProof: not implemented');
  @override
  Future<
          Result<RemoteStatementStoreCreateProofResponse,
              RemoteStatementStoreCreateProofError>>
      createProofAuthorized(CallContext ctx, Statement request) =>
          throw UnimplementedError(
              'StatementStore.createProofAuthorized: not implemented');
  @override
  Future<Result<Unit, GenericError>> submit(
          CallContext ctx, SignedStatement request) =>
      throw UnimplementedError('StatementStore.submit: not implemented');
}

/// General-purpose TrUAPI methods for handshake, feature detection,
/// and navigation.
class SystemHandlers implements SystemHostHandlers {
  @override
  Future<Result<Unit, HostHandshakeError>> handshake(
          CallContext ctx, HostHandshakeRequest request) =>
      throw UnimplementedError('System.handshake: not implemented');
  @override
  Future<Result<HostFeatureSupportedResponse, GenericError>> featureSupported(
          CallContext ctx, HostFeatureSupportedRequest request) =>
      throw UnimplementedError('System.featureSupported: not implemented');
  @override
  Future<Result<Unit, HostNavigateToError>> navigateTo(
          CallContext ctx, HostNavigateToRequest request) =>
      throw UnimplementedError('System.navigateTo: not implemented');
}

/// Host theme subscription.
class ThemeHandlers implements ThemeHostHandlers {
  @override
  Stream<HostThemeSubscribeItem> subscribe(CallContext ctx) =>
      throw UnimplementedError('Theme.subscribe: not implemented');
}

/// Aggregates every service handler. Pass to `createTruapiServer`.
class ScaffoldHostHandlers implements TruapiHostHandlers {
  @override
  final AccountHostHandlers account = AccountHandlers();
  @override
  final ChainHostHandlers chain = ChainHandlers();
  @override
  final ChatHostHandlers chat = ChatHandlers();
  @override
  final CoinPaymentHostHandlers coinPayment = CoinPaymentHandlers();
  @override
  final EntropyHostHandlers entropy = EntropyHandlers();
  @override
  final LocalStorageHostHandlers localStorage = LocalStorageHandlers();
  @override
  final NotificationsHostHandlers notifications = NotificationsHandlers();
  @override
  final PaymentHostHandlers payment = PaymentHandlers();
  @override
  final PermissionsHostHandlers permissions = PermissionsHandlers();
  @override
  final PreimageHostHandlers preimage = PreimageHandlers();
  @override
  final ResourceAllocationHostHandlers resourceAllocation =
      ResourceAllocationHandlers();
  @override
  final SigningHostHandlers signing = SigningHandlers();
  @override
  final StatementStoreHostHandlers statementStore = StatementStoreHandlers();
  @override
  final SystemHostHandlers system = SystemHandlers();
  @override
  final ThemeHostHandlers theme = ThemeHandlers();
}
