//! SSO pairing bootstrap helpers.
//!
//! This module owns the byte shape of the QR/deeplink payload described in
//! `docs/design/host-contract-and-core-impl/H - sso-pairing-protocol.md`.
//! The inter-host pairing flow is specified in host-spec B.1:
//! <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L10-L103>
//! The deeplink route and hex construction rules are specified in host-spec L:
//! <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/L-url-schemes.md?plain=1#L17-L33>
//! Session crypto and statement-store framing are specified in host-spec B.2-B.4:
//! <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L105-L183>
//! The SCALE handshake codecs are kept wire-compatible with host-papp's v2
//! handshake codec:
//! <https://github.com/paritytech/triangle-js-sdks/blob/afb26e2c78bf1134886c1248c1bf2b6b4dc1fce9/packages/host-papp/src/sso/auth/scale/handshakeV2.ts>

use chacha20poly1305::ChaCha20Poly1305;
use chacha20poly1305::aead::{Aead, KeyInit};
use hkdf::Hkdf;
use parity_scale_codec::{Decode, Encode};
use schnorrkel::{ExpansionMode, MiniSecretKey, SignatureError};
use sha2::Sha256;
use thiserror::Error;
use truapi_platform::PairingHostConfig;
#[cfg(test)]
use truapi_platform::{HostInfo, PlatformInfo};
use x25519_dalek::{PublicKey, StaticSecret};

use crate::host_logic::session::SsoSessionInfo;

const HANDSHAKE_TOPIC_SUFFIX: &[u8] = b"topic";
const HANDSHAKE_CHANNEL_SUFFIX: &[u8] = b"channel";

/// Byte length of the ChaCha20-Poly1305 nonce prepended to encrypted payloads.
pub const AEAD_NONCE_LEN: usize = 12;
const SESSION_PREFIX: &[u8] = b"session";
const PIN_SEPARATOR: &[u8] = b"/";
const REQUEST_CHANNEL_SUFFIX: &[u8] = b"request";
const RESPONSE_CHANNEL_SUFFIX: &[u8] = b"response";

/// QR/deeplink bootstrap material generated by the host for one pairing flow.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PairingBootstrap {
    /// Wallet deeplink (rendered as QR) carrying the hex-encoded proposal.
    pub deeplink: String,
    /// Statement-store topic to watch for the wallet's encrypted answer.
    pub topic: [u8; 32],
    /// Host's sr25519 statement-store public key advertised in the proposal.
    pub statement_store_public_key: [u8; 32],
    /// Host's 64-byte expanded sr25519 statement-store secret.
    pub statement_store_secret: [u8; 64],
    /// Host's raw X25519 public key advertised in the proposal.
    pub encryption_public_key: [u8; 32],
    /// Host's X25519 secret used to decrypt the wallet's answer.
    pub encryption_secret_key: [u8; 32],
}

/// Persistable device identity reused across pairing attempts.
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct PairingDeviceIdentity {
    /// 64-byte expanded sr25519 statement-store secret.
    pub statement_store_secret: [u8; 64],
    /// sr25519 statement-store public key matching the secret.
    pub statement_store_public_key: [u8; 32],
    /// X25519 secret key.
    pub encryption_secret_key: [u8; 32],
    /// Raw X25519 public key matching the secret key.
    pub encryption_public_key: [u8; 32],
}

/// Errors that can occur while generating pairing bootstrap material.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum PairingBootstrapError {
    /// The platform randomness source failed.
    #[error("failed to generate random pairing material: {0}")]
    Random(#[source] getrandom::Error),
    /// The generated sr25519 seed could not be expanded.
    #[error("failed to expand sr25519 pairing key: {0:?}")]
    Sr25519Key(SignatureError),
}

/// Error while decoding a pairing deeplink or bare handshake payload.
#[derive(Debug, Error)]
pub enum PairingDeeplinkDecodeError {
    /// The `handshake` payload is not valid hex.
    #[error("invalid pairing deeplink hex: {0}")]
    InvalidHex(#[source] hex::FromHexError),
    /// The decoded bytes are not a valid handshake proposal.
    #[error("invalid pairing handshake proposal: {0}")]
    InvalidHandshakeProposal(#[source] parity_scale_codec::Error),
    /// The proposal decoded successfully but extra bytes remained.
    #[error("invalid pairing handshake proposal: trailing bytes")]
    TrailingBytes,
}

/// Versioned SCALE payload embedded in the pairing deeplink.
///
/// Host-spec B.1.1 defines the deeplink as lowercase hex of this SCALE payload:
/// <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L12-L22>
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub enum VersionedHandshakeProposal {
    /// v2 proposal carrying the host device keys and display metadata.
    #[codec(index = 1)]
    V2(v2::Proposal),
}

/// Versioned encrypted response posted by the wallet to the pairing topic.
///
/// Host-spec B.1.4 defines the encrypted answer statement and matching topic:
/// <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L62-L83>
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub enum VersionedHandshakeResponse {
    /// v2 answer encrypted to the host's advertised X25519 key.
    #[codec(index = 1)]
    V2 {
        /// Nonce-prefixed ChaCha20-Poly1305 ciphertext of a [`v2::EncryptedResponse`].
        encrypted_message: Vec<u8>,
        /// Wallet's ephemeral X25519 public key for the ECDH key agreement.
        public_key: [u8; 32],
    },
}

/// Host-papp v2 handshake wire types.
pub mod v2;

/// Encrypted statement-channel envelope shared with the wallet.
///
/// Host-spec B.4.1 defines this request/response wrapper:
/// <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L151-L175>
///
/// Mirrors `@novasamatech/statement-store` session statement data:
/// <https://github.com/paritytech/triangle-js-sdks/blob/afb26e2c78bf1134886c1248c1bf2b6b4dc1fce9/packages/statement-store/src/session/scale/statementData.ts>
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub enum SsoStatementData {
    /// Batch of remote messages posted on a session request channel.
    Request {
        /// Sender-chosen id echoed back by the matching `Response`.
        request_id: String,
        /// SCALE-encoded remote messages.
        data: Vec<Vec<u8>>,
    },
    /// Ack for a previously received request.
    Response {
        /// Id of the request being acknowledged.
        request_id: String,
        /// `SsoResponseCode` discriminant; zero means accepted.
        response_code: u8,
    },
}

/// Decode a pairing deeplink (or its bare handshake hex) into the advertised
/// handshake proposal. Inverse of [`build_pairing_deeplink`].
pub fn decode_pairing_deeplink(
    deeplink: &str,
) -> Result<VersionedHandshakeProposal, PairingDeeplinkDecodeError> {
    let hex_payload = match deeplink.split_once("?handshake=") {
        Some((_, hex_payload)) => hex_payload,
        None => deeplink,
    };
    let encoded =
        hex::decode(hex_payload.trim()).map_err(PairingDeeplinkDecodeError::InvalidHex)?;
    let mut input = encoded.as_slice();
    let proposal = VersionedHandshakeProposal::decode(&mut input)
        .map_err(PairingDeeplinkDecodeError::InvalidHandshakeProposal)?;
    if !input.is_empty() {
        return Err(PairingDeeplinkDecodeError::TrailingBytes);
    }
    Ok(proposal)
}

/// Encrypt a v2 handshake response for the host that advertised
/// `host_encryption_public_key`. Inverse of [`decrypt_v2_handshake_response`]:
/// a fresh ephemeral X25519 key is used per response so each Pending/Success
/// statement carries an independent ciphertext.
pub fn encrypt_v2_handshake_response(
    host_encryption_public_key: [u8; 32],
    response: &v2::EncryptedResponse,
) -> Result<VersionedHandshakeResponse, String> {
    let (ephemeral_secret, ephemeral_public) =
        generate_x25519_keypair().map_err(|err| err.to_string())?;
    let shared_secret = shared_secret(ephemeral_secret, host_encryption_public_key)?;
    let aead_key = aead_key_from_shared_secret(&shared_secret)?;
    let encrypted_message =
        encrypt_chacha20_poly1305(aead_key, &response.encode(), "handshake response")?;
    Ok(VersionedHandshakeResponse::V2 {
        encrypted_message,
        public_key: ephemeral_public,
    })
}

/// Decode wallet-posted pairing handshake data from SCALE bytes.
pub fn decode_app_handshake_data(blob: &[u8]) -> Result<VersionedHandshakeResponse, String> {
    let mut input = blob;
    let value: VersionedHandshakeResponse =
        Decode::decode(&mut input).map_err(|err| format!("invalid app handshake data: {err}"))?;
    if !input.is_empty() {
        return Err("invalid app handshake data: trailing bytes".to_string());
    }
    Ok(value)
}

/// Decrypt a v2 handshake response.
pub fn decrypt_v2_handshake_response(
    core_encryption_secret_key: [u8; 32],
    wallet_ephemeral_public_key: [u8; 32],
    encrypted_message: &[u8],
) -> Result<v2::EncryptedResponse, String> {
    let shared_secret = shared_secret(core_encryption_secret_key, wallet_ephemeral_public_key)?;
    let plaintext = decrypt_chacha20_poly1305(
        aead_key_from_shared_secret(&shared_secret)?,
        encrypted_message,
        "handshake answer",
    )?;
    let mut input = plaintext.as_slice();
    let value = v2::EncryptedResponse::decode(&mut input)
        .map_err(|err| format!("invalid SSO V2 handshake response: {err}"))?;
    if !input.is_empty() {
        return Err("invalid SSO V2 handshake response: trailing bytes".to_string());
    }
    Ok(value)
}

/// Derive the persistent SSO session channels from a successful handshake.
pub fn establish_sso_session_info(
    bootstrap: &PairingBootstrap,
    peer_statement_account_id: [u8; 32],
    peer_sso_enc_pub_key: [u8; 32],
) -> Result<SsoSessionInfo, String> {
    let shared_secret = shared_secret(bootstrap.encryption_secret_key, peer_sso_enc_pub_key)?;
    let session_id_own = create_session_id(
        shared_secret,
        bootstrap.statement_store_public_key,
        peer_statement_account_id,
    );
    let session_id_peer = create_session_id(
        shared_secret,
        peer_statement_account_id,
        bootstrap.statement_store_public_key,
    );

    Ok(SsoSessionInfo {
        ss_secret: bootstrap.statement_store_secret,
        ss_public_key: bootstrap.statement_store_public_key,
        enc_secret: bootstrap.encryption_secret_key,
        peer_enc_pubkey: peer_sso_enc_pub_key,
        identity_account_id: peer_statement_account_id,
        session_id_own,
        session_id_peer,
        request_channel: keyed_hash(session_id_own, REQUEST_CHANNEL_SUFFIX),
        response_channel: keyed_hash(session_id_own, RESPONSE_CHANNEL_SUFFIX),
        peer_request_channel: keyed_hash(session_id_peer, REQUEST_CHANNEL_SUFFIX),
    })
}

/// Signing-host key material answering one pairing proposal.
///
/// The statement keypair signs every session statement (its public key is the
/// `identityAccountId` the pairing host binds the session to), and the X25519
/// secret is the persistent `sso` key both sides feed into the session ECDH.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResponderIdentity {
    /// Expanded Ed25519 secret used to sign session statements.
    pub statement_secret: [u8; 64],
    /// Ed25519 public key advertised as the session identity account.
    pub statement_public_key: [u8; 32],
    /// X25519 secret key used to derive the shared session channels.
    pub encryption_secret_key: [u8; 32],
    /// Raw X25519 public key advertised during pairing.
    pub encryption_public_key: [u8; 32],
}

/// Derive the SSO session channels from the responder (signing host)
/// perspective after answering the handshake advertised by
/// `host_statement_account_id` / `host_encryption_public_key`.
///
/// Mirror of [`establish_sso_session_info`]: the responder's `session_id_own`
/// equals the pairing host's `session_id_peer` and vice versa, so statements
/// built from either side land on the topics the other side subscribes to.
pub fn establish_responder_session_info(
    identity: &ResponderIdentity,
    host_statement_account_id: [u8; 32],
    host_encryption_public_key: [u8; 32],
) -> Result<SsoSessionInfo, String> {
    let shared_secret = shared_secret(identity.encryption_secret_key, host_encryption_public_key)?;
    let session_id_own = create_session_id(
        shared_secret,
        identity.statement_public_key,
        host_statement_account_id,
    );
    let session_id_peer = create_session_id(
        shared_secret,
        host_statement_account_id,
        identity.statement_public_key,
    );

    Ok(SsoSessionInfo {
        ss_secret: identity.statement_secret,
        ss_public_key: identity.statement_public_key,
        enc_secret: identity.encryption_secret_key,
        peer_enc_pubkey: host_encryption_public_key,
        identity_account_id: host_statement_account_id,
        session_id_own,
        session_id_peer,
        request_channel: keyed_hash(session_id_own, REQUEST_CHANNEL_SUFFIX),
        response_channel: keyed_hash(session_id_own, RESPONSE_CHANNEL_SUFFIX),
        peer_request_channel: keyed_hash(session_id_peer, REQUEST_CHANNEL_SUFFIX),
    })
}

/// Statement channel acknowledging requests the peer initiated: the peer's
/// own `response` channel seen from this side of the session.
pub fn peer_response_channel(session: &SsoSessionInfo) -> [u8; 32] {
    keyed_hash(session.session_id_peer, RESPONSE_CHANNEL_SUFFIX)
}

/// Derive an RFC-0022 X25519 keypair from BIP-39 entropy and an ECDH domain.
///
/// `root = blake2b256(entropy, key = "ecdh")`, then one hard keyed-hash
/// junction `//{domain}`. X25519 clamps the resulting private bytes.
pub fn derive_x25519_keypair_from_entropy(entropy: &[u8], domain: &[u8]) -> ([u8; 32], [u8; 32]) {
    let root = blake2b256_keyed(entropy, b"ecdh");
    let chain_code = normalize_chain_code(domain.encode());
    let secret_bytes = blake2b256_keyed(&root, &chain_code);
    let secret = StaticSecret::from(secret_bytes);
    let public = PublicKey::from(&secret).to_bytes();
    (secret_bytes, public)
}

/// Encrypt session-channel statement data with a random nonce.
pub fn encrypt_session_statement_data(
    session: &SsoSessionInfo,
    data: &SsoStatementData,
) -> Result<Vec<u8>, String> {
    let mut nonce = [0u8; AEAD_NONCE_LEN];
    getrandom::getrandom(&mut nonce)
        .map_err(|err| format!("failed to generate ChaCha20-Poly1305 nonce: {err}"))?;
    encrypt_session_statement_data_with_nonce(session, data, nonce)
}

/// Encrypt session-channel statement data with a caller-supplied nonce.
pub fn encrypt_session_statement_data_with_nonce(
    session: &SsoSessionInfo,
    data: &SsoStatementData,
    nonce: [u8; AEAD_NONCE_LEN],
) -> Result<Vec<u8>, String> {
    encrypt_chacha20_poly1305_with_nonce(
        session_aead_key(session)?,
        &data.encode(),
        nonce,
        "statement data",
    )
}

/// Decrypt session-channel statement data.
pub fn decrypt_session_statement_data(
    session: &SsoSessionInfo,
    encrypted_message: &[u8],
) -> Result<SsoStatementData, String> {
    let plaintext = decrypt_session_message(session, encrypted_message)?;
    let mut input = plaintext.as_slice();
    let data = SsoStatementData::decode(&mut input)
        .map_err(|err| format!("invalid SSO statement data: {err}"))?;
    if !input.is_empty() {
        return Err("invalid SSO statement data: trailing bytes".to_string());
    }
    Ok(data)
}

fn decrypt_session_message(
    session: &SsoSessionInfo,
    encrypted_message: &[u8],
) -> Result<Vec<u8>, String> {
    decrypt_chacha20_poly1305(
        session_aead_key(session)?,
        encrypted_message,
        "statement data",
    )
}

fn encrypt_chacha20_poly1305(
    key: [u8; 32],
    plaintext: &[u8],
    label: &str,
) -> Result<Vec<u8>, String> {
    let mut nonce = [0u8; AEAD_NONCE_LEN];
    getrandom::getrandom(&mut nonce)
        .map_err(|err| format!("failed to generate ChaCha20-Poly1305 nonce: {err}"))?;
    encrypt_chacha20_poly1305_with_nonce(key, plaintext, nonce, label)
}

fn encrypt_chacha20_poly1305_with_nonce(
    key: [u8; 32],
    plaintext: &[u8],
    nonce: [u8; AEAD_NONCE_LEN],
    label: &str,
) -> Result<Vec<u8>, String> {
    let cipher = ChaCha20Poly1305::new((&key).into());
    let mut encrypted = nonce.to_vec();
    encrypted.extend(
        cipher
            .encrypt((&nonce).into(), plaintext)
            .map_err(|err| format!("failed to encrypt SSO {label}: {err}"))?,
    );
    Ok(encrypted)
}

fn decrypt_chacha20_poly1305(
    key: [u8; 32],
    encrypted_message: &[u8],
    label: &str,
) -> Result<Vec<u8>, String> {
    if encrypted_message.len() < AEAD_NONCE_LEN + 16 {
        return Err(format!("encrypted SSO {label} is too short"));
    }
    let (nonce, ciphertext) = encrypted_message.split_at(AEAD_NONCE_LEN);
    let nonce: &[u8; AEAD_NONCE_LEN] = nonce
        .try_into()
        .expect("nonce slice has the checked fixed length");
    let cipher = ChaCha20Poly1305::new((&key).into());
    cipher
        .decrypt(nonce.into(), ciphertext)
        .map_err(|err| format!("failed to decrypt SSO {label}: {err}"))
}

fn session_aead_key(session: &SsoSessionInfo) -> Result<[u8; 32], String> {
    let shared_secret = shared_secret(session.enc_secret, session.peer_enc_pubkey)?;
    aead_key_from_shared_secret(&shared_secret)
}

fn aead_key_from_shared_secret(shared_secret: &[u8; 32]) -> Result<[u8; 32], String> {
    let hkdf = Hkdf::<Sha256>::new(None, shared_secret);
    let mut aead_key = [0u8; 32];
    hkdf.expand(&[], &mut aead_key)
        .map_err(|err| format!("failed to derive AEAD key: {err}"))?;
    Ok(aead_key)
}

fn shared_secret(own_secret_key: [u8; 32], peer_public_key: [u8; 32]) -> Result<[u8; 32], String> {
    let secret = StaticSecret::from(own_secret_key);
    let peer_public = PublicKey::from(peer_public_key);
    let shared = secret.diffie_hellman(&peer_public);
    if !shared.was_contributory() {
        return Err("invalid X25519 public key".to_string());
    }
    Ok(shared.to_bytes())
}

fn create_session_id(
    shared_secret: [u8; 32],
    account_a: [u8; 32],
    account_b: [u8; 32],
) -> [u8; 32] {
    let mut message = Vec::with_capacity(SESSION_PREFIX.len() + 32 + 32 + 2);
    message.extend_from_slice(SESSION_PREFIX);
    message.extend_from_slice(&account_a);
    message.extend_from_slice(&account_b);
    message.extend_from_slice(PIN_SEPARATOR);
    message.extend_from_slice(PIN_SEPARATOR);
    keyed_hash(shared_secret, &message)
}

fn keyed_hash(key: [u8; 32], message: &[u8]) -> [u8; 32] {
    blake2b256_keyed(message, &key)
}

fn blake2b256_keyed(message: &[u8], key: &[u8]) -> [u8; 32] {
    blake2b_simd::Params::new()
        .hash_length(32)
        .key(key)
        .hash(message)
        .as_bytes()
        .try_into()
        .expect("hash_length(32) configures BLAKE2b output to exactly 32 bytes; qed")
}

/// Create one-shot pairing bootstrap material from runtime config.
pub fn create_pairing_bootstrap(
    config: &PairingHostConfig,
) -> Result<PairingBootstrap, PairingBootstrapError> {
    create_pairing_bootstrap_from_identity(config, generate_pairing_device_identity()?)
}

/// Generate a fresh persistable pairing device identity.
pub fn generate_pairing_device_identity() -> Result<PairingDeviceIdentity, PairingBootstrapError> {
    let (statement_store_secret, statement_store_public_key) = generate_statement_store_keypair()?;
    let (encryption_secret_key, encryption_public_key) = generate_x25519_keypair()?;

    Ok(PairingDeviceIdentity {
        statement_store_secret,
        statement_store_public_key,
        encryption_secret_key,
        encryption_public_key,
    })
}

/// Create pairing bootstrap material from an existing device identity.
pub fn create_pairing_bootstrap_from_identity(
    config: &PairingHostConfig,
    identity: PairingDeviceIdentity,
) -> Result<PairingBootstrap, PairingBootstrapError> {
    let deeplink = build_pairing_deeplink(
        &config.pairing_deeplink_scheme,
        identity.statement_store_public_key,
        identity.encryption_public_key,
        config,
    );
    let topic = bootstrap_topic(
        identity.statement_store_public_key,
        identity.encryption_public_key,
    );

    Ok(PairingBootstrap {
        deeplink,
        topic,
        statement_store_public_key: identity.statement_store_public_key,
        statement_store_secret: identity.statement_store_secret,
        encryption_public_key: identity.encryption_public_key,
        encryption_secret_key: identity.encryption_secret_key,
    })
}

/// Build the wallet deeplink that carries the v2 handshake proposal.
pub fn build_pairing_deeplink(
    scheme: &str,
    statement_store_public_key: [u8; 32],
    encryption_public_key: [u8; 32],
    config: &PairingHostConfig,
) -> String {
    let handshake = VersionedHandshakeProposal::V2(v2::Proposal {
        device: v2::Device {
            statement_account_id: statement_store_public_key,
            encryption_public_key,
        },
        metadata: handshake_metadata(config),
    });
    format!(
        "{scheme}://pair?handshake={}",
        hex::encode(handshake.encode())
    )
}

fn handshake_metadata(config: &PairingHostConfig) -> Vec<v2::MetadataEntry> {
    let mut entries = vec![v2::MetadataEntry(
        v2::MetadataKey::HostName,
        config.host.host_info.name.clone(),
    )];
    if let Some(value) = &config.host.host_info.version {
        entries.push(v2::MetadataEntry(
            v2::MetadataKey::HostVersion,
            value.clone(),
        ));
    }
    if let Some(value) = &config.host.host_info.icon {
        entries.push(v2::MetadataEntry(v2::MetadataKey::HostIcon, value.clone()));
    }
    if let Some(value) = &config.host.platform_info.kind {
        entries.push(v2::MetadataEntry(
            v2::MetadataKey::PlatformType,
            value.clone(),
        ));
    }
    if let Some(value) = &config.host.platform_info.version {
        entries.push(v2::MetadataEntry(
            v2::MetadataKey::PlatformVersion,
            value.clone(),
        ));
    }
    entries
}

/// Derive the statement-store pairing topic from advertised host keys.
pub fn bootstrap_topic(
    statement_store_public_key: [u8; 32],
    encryption_public_key: [u8; 32],
) -> [u8; 32] {
    let mut message =
        Vec::with_capacity(encryption_public_key.len() + HANDSHAKE_TOPIC_SUFFIX.len());
    message.extend_from_slice(&encryption_public_key);
    message.extend_from_slice(HANDSHAKE_TOPIC_SUFFIX);

    keyed_hash(statement_store_public_key, &message)
}

/// Derive the statement channel for pairing answer statements from advertised
/// host keys. Distinct from [`bootstrap_topic`] so a `Success` answer replaces
/// an earlier `Pending` status in the store.
pub fn bootstrap_channel(
    statement_store_public_key: [u8; 32],
    encryption_public_key: [u8; 32],
) -> [u8; 32] {
    let mut message =
        Vec::with_capacity(encryption_public_key.len() + HANDSHAKE_CHANNEL_SUFFIX.len());
    message.extend_from_slice(&encryption_public_key);
    message.extend_from_slice(HANDSHAKE_CHANNEL_SUFFIX);

    keyed_hash(statement_store_public_key, &message)
}

fn generate_statement_store_keypair() -> Result<([u8; 64], [u8; 32]), PairingBootstrapError> {
    let mut seed = [0u8; 32];
    getrandom::getrandom(&mut seed).map_err(PairingBootstrapError::Random)?;
    let mini_secret =
        MiniSecretKey::from_bytes(&seed).map_err(PairingBootstrapError::Sr25519Key)?;
    let keypair = mini_secret.expand_to_keypair(ExpansionMode::Ed25519);
    Ok((keypair.secret.to_bytes(), keypair.public.to_bytes()))
}

fn generate_x25519_keypair() -> Result<([u8; 32], [u8; 32]), PairingBootstrapError> {
    let mut secret_bytes = [0u8; 32];
    getrandom::getrandom(&mut secret_bytes).map_err(PairingBootstrapError::Random)?;
    let secret = StaticSecret::from(secret_bytes);
    let public = PublicKey::from(&secret).to_bytes();
    Ok((secret_bytes, public))
}

fn normalize_chain_code(encoded: Vec<u8>) -> [u8; 32] {
    let mut chain_code = [0u8; 32];
    if encoded.len() > chain_code.len() {
        chain_code = sp_crypto_hashing::blake2_256(&encoded);
    } else {
        chain_code[..encoded.len()].copy_from_slice(&encoded);
    }
    chain_code
}

#[cfg(test)]
mod tests {
    use super::*;

    const SS_PUBLIC: [u8; 32] = [
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
        0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d,
        0x1e, 0x1f,
    ];

    fn x25519_keypair(seed: u8) -> ([u8; 32], [u8; 32]) {
        let secret_bytes = [seed; 32];
        let secret = StaticSecret::from(secret_bytes);
        (secret_bytes, PublicKey::from(&secret).to_bytes())
    }

    fn runtime_config() -> PairingHostConfig {
        PairingHostConfig::new(
            HostInfo {
                name: "Polkadot Web".to_string(),
                icon: Some("https://example.invalid/dotli.png".to_string()),
                version: Some("1.2.3".to_string()),
            },
            PlatformInfo {
                kind: Some("Firefox".to_string()),
                version: Some("192.32".to_string()),
            },
            [0; 32],
            [0xbb; 32],
            "polkadotapp".to_string(),
        )
        .expect("test runtime config is valid")
    }

    fn response(public_key: [u8; 32]) -> v2::EncryptedResponse {
        v2::EncryptedResponse::Success(Box::new(v2::Success {
            identity_account_id: [8; 32],
            root_account_id: [7; 32],
            identity_chat_private_key: [6; 32],
            sso_enc_pub_key: public_key,
            device_enc_pub_key: public_key,
            root_entropy_source: [5; 32],
        }))
    }

    fn bootstrap(secret: [u8; 32], public: [u8; 32]) -> PairingBootstrap {
        PairingBootstrap {
            deeplink: "polkadotapp://pair?handshake=00".to_string(),
            topic: [0x11; 32],
            statement_store_public_key: [0x22; 32],
            statement_store_secret: [0x33; 64],
            encryption_public_key: public,
            encryption_secret_key: secret,
        }
    }

    #[test]
    fn pairing_deeplink_carries_raw_x25519_key() {
        let (_, public) = x25519_keypair(1);
        let deeplink = build_pairing_deeplink("polkadotapp", SS_PUBLIC, public, &runtime_config());
        assert!(deeplink.starts_with("polkadotapp://pair?handshake=01"));

        let VersionedHandshakeProposal::V2(proposal) = decode_pairing_deeplink(&deeplink).unwrap();
        assert_eq!(proposal.device.statement_account_id, SS_PUBLIC);
        assert_eq!(proposal.device.encryption_public_key, public);
        assert_eq!(proposal.device.encryption_public_key.len(), 32);
    }

    #[test]
    fn deeplink_decoder_accepts_bare_hex_and_rejects_trailing_bytes() {
        let (_, public) = x25519_keypair(1);
        let deeplink = build_pairing_deeplink("polkadotapp", SS_PUBLIC, public, &runtime_config());
        let hex_payload = deeplink.split("handshake=").nth(1).unwrap();
        assert_eq!(
            decode_pairing_deeplink(hex_payload).unwrap(),
            decode_pairing_deeplink(&deeplink).unwrap()
        );
        assert!(matches!(
            decode_pairing_deeplink(&format!("{deeplink}00")).unwrap_err(),
            PairingDeeplinkDecodeError::TrailingBytes
        ));
    }

    #[test]
    fn app_handshake_codec_uses_32_byte_ephemeral_key() {
        let (_, public) = x25519_keypair(2);
        let answer = VersionedHandshakeResponse::V2 {
            encrypted_message: vec![0xde, 0xad],
            public_key: public,
        };
        assert_eq!(decode_app_handshake_data(&answer.encode()).unwrap(), answer);
    }

    #[test]
    fn handshake_x25519_chacha_round_trip_and_authentication() {
        let (host_secret, host_public) = x25519_keypair(1);
        let sensitive = response(x25519_keypair(2).1);
        let VersionedHandshakeResponse::V2 {
            mut encrypted_message,
            public_key,
        } = encrypt_v2_handshake_response(host_public, &sensitive).unwrap();

        assert_eq!(
            decrypt_v2_handshake_response(host_secret, public_key, &encrypted_message).unwrap(),
            sensitive
        );
        let last = encrypted_message.len() - 1;
        encrypted_message[last] ^= 1;
        assert!(
            decrypt_v2_handshake_response(host_secret, public_key, &encrypted_message).is_err()
        );
    }

    #[test]
    fn rejects_short_handshake_ciphertext_and_small_order_key() {
        assert!(
            decrypt_v2_handshake_response([1; 32], x25519_keypair(2).1, &[0; AEAD_NONCE_LEN + 15],)
                .unwrap_err()
                .contains("too short")
        );
        assert_eq!(
            shared_secret([1; 32], [0; 32]).unwrap_err(),
            "invalid X25519 public key"
        );
    }

    #[test]
    fn rfc0022_entropy_domains_produce_stable_distinct_keys() {
        let sso = derive_x25519_keypair_from_entropy(&[0xAB; 16], b"sso");
        let chat = derive_x25519_keypair_from_entropy(&[0xAB; 16], b"chat");
        assert_eq!(sso, derive_x25519_keypair_from_entropy(&[0xAB; 16], b"sso"));
        assert_ne!(sso, chat);
        assert_eq!(
            PublicKey::from(&StaticSecret::from(sso.0)).to_bytes(),
            sso.1
        );
        let cross_platform_entropy: [u8; 32] = std::array::from_fn(|index| (index + 1) as u8);
        let (sso_secret, _) = derive_x25519_keypair_from_entropy(&cross_platform_entropy, b"sso");
        let (chat_secret, _) = derive_x25519_keypair_from_entropy(&cross_platform_entropy, b"chat");
        assert_eq!(
            hex::encode(sso_secret),
            "c2c0f3112da0aa390a7d7b644a7f073b80782e49a3240685bc071046d6cc8ad3"
        );
        assert_eq!(
            hex::encode(chat_secret),
            "88705746a9788fb8bc232cc463b243a2828e470b932ce60a16426cc79b4618b1"
        );
    }

    #[test]
    fn generated_bootstrap_uses_matching_x25519_keypair() {
        let generated = create_pairing_bootstrap(&runtime_config()).unwrap();
        assert_eq!(
            PublicKey::from(&StaticSecret::from(generated.encryption_secret_key)).to_bytes(),
            generated.encryption_public_key
        );
        assert_eq!(
            generated.topic,
            bootstrap_topic(
                generated.statement_store_public_key,
                generated.encryption_public_key,
            )
        );
    }

    #[test]
    fn derives_pinned_topic_and_channel_vectors() {
        let (_, public) = x25519_keypair(1);
        assert_eq!(
            hex::encode(bootstrap_topic(SS_PUBLIC, public)),
            "ec8c8d7993ef1b367a704f34cec0fa1fe01d0a060a918688f26b23e88452a6af"
        );
        assert_eq!(
            hex::encode(bootstrap_channel(SS_PUBLIC, public)),
            "f7df2ba8c948e35c35edfaf8bad6cb4a8c4e0373f64bab787f68620a88f7c51f"
        );
    }

    #[test]
    fn responder_session_mirrors_pairing_session() {
        let host = create_pairing_bootstrap(&runtime_config()).unwrap();
        let (responder_secret, responder_public) =
            derive_x25519_keypair_from_entropy(&[0xAB; 16], b"sso");
        let responder = ResponderIdentity {
            statement_secret: [0x44; 64],
            statement_public_key: [0x55; 32],
            encryption_secret_key: responder_secret,
            encryption_public_key: responder_public,
        };
        let responder_session = establish_responder_session_info(
            &responder,
            host.statement_store_public_key,
            host.encryption_public_key,
        )
        .unwrap();
        let host_session =
            establish_sso_session_info(&host, responder.statement_public_key, responder_public)
                .unwrap();

        assert_eq!(
            responder_session.session_id_own,
            host_session.session_id_peer
        );
        assert_eq!(
            responder_session.session_id_peer,
            host_session.session_id_own
        );
        assert_eq!(
            responder_session.request_channel,
            host_session.peer_request_channel
        );
        assert_eq!(
            peer_response_channel(&responder_session),
            host_session.response_channel
        );

        let data = SsoStatementData::Request {
            request_id: "req-1".to_string(),
            data: vec![vec![0xde, 0xad]],
        };
        let encrypted = encrypt_session_statement_data(&responder_session, &data).unwrap();
        assert_eq!(
            decrypt_session_statement_data(&host_session, &encrypted).unwrap(),
            data
        );
    }

    #[test]
    fn session_statement_uses_nonce_ciphertext_tag_framing() {
        let (host_secret, host_public) = x25519_keypair(1);
        let (_, peer_public) = x25519_keypair(2);
        let session = establish_sso_session_info(
            &bootstrap(host_secret, host_public),
            [0x55; 32],
            peer_public,
        )
        .unwrap();
        let data = SsoStatementData::Request {
            request_id: "req-1".to_string(),
            data: vec![vec![0xde, 0xad]],
        };
        let nonce = [9u8; AEAD_NONCE_LEN];
        let encrypted = encrypt_session_statement_data_with_nonce(&session, &data, nonce).unwrap();

        assert_eq!(&encrypted[..AEAD_NONCE_LEN], nonce);
        assert_eq!(encrypted.len(), AEAD_NONCE_LEN + data.encode().len() + 16);
        assert_eq!(
            decrypt_session_statement_data(&session, &encrypted).unwrap(),
            data
        );
    }
}
