//! SSO pairing bootstrap helpers.
//!
//! This module owns the byte shape of the QR/deeplink payload described in
//! `docs/design/host-contract-and-core-impl/H - sso-pairing-protocol.md`.
//! The inter-host pairing flow is specified in host-spec B.1:
//! <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L10-L103>
//! The deeplink route and hex construction rules are specified in host-spec L:
//! <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/L-url-schemes.md?plain=1#L17-L33>
//! Session crypto and statement-store framing are specified in host-spec B.2-B.4:
//! <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L105-L183>
//! The SCALE handshake codecs are kept wire-compatible with host-papp's v2
//! handshake codec:
//! <https://github.com/paritytech/triangle-js-sdks/blob/18c12d3bd1c51a9520eb247dc038ace2996dc2e7/packages/host-papp/src/sso/auth/scale/handshakeV2.ts#L43-L115>

use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Nonce};
use hkdf::Hkdf;
use p256::ecdh::diffie_hellman;
use p256::elliptic_curve::sec1::ToEncodedPoint;
use p256::{PublicKey, SecretKey};
use parity_scale_codec::{Decode, Encode};
use schnorrkel::{ExpansionMode, MiniSecretKey};
use sha2::Sha256;
use thiserror::Error;
use truapi_platform::PairingHostConfig;
#[cfg(test)]
use truapi_platform::{HostInfo, PlatformInfo};

use crate::host_logic::session::SsoSessionInfo;

const HANDSHAKE_TOPIC_SUFFIX: &[u8] = b"topic";
const MAX_P256_SECRET_ATTEMPTS: usize = 64;
/// Byte length of the AES-GCM nonce prepended to encrypted SSO payloads.
pub const AES_GCM_NONCE_LEN: usize = 12;
const SESSION_PREFIX: &[u8] = b"session";
const PIN_SEPARATOR: &[u8] = b"/";
const REQUEST_CHANNEL_SUFFIX: &[u8] = b"request";
const RESPONSE_CHANNEL_SUFFIX: &[u8] = b"response";

/// QR/deeplink bootstrap material generated by the host for one pairing flow.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PairingBootstrap {
    pub deeplink: String,
    pub topic: [u8; 32],
    pub statement_store_public_key: [u8; 32],
    pub statement_store_secret: [u8; 64],
    pub encryption_public_key: [u8; 65],
    pub encryption_secret_key: [u8; 32],
}

/// Persistable device identity reused across pairing attempts.
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct PairingDeviceIdentity {
    pub statement_store_secret: [u8; 64],
    pub statement_store_public_key: [u8; 32],
    pub encryption_secret_key: [u8; 32],
    pub encryption_public_key: [u8; 65],
}

/// Errors that can occur while generating pairing bootstrap material.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum PairingBootstrapError {
    #[error("failed to generate random pairing material: {0}")]
    Random(String),
    #[error("failed to generate P-256 pairing key")]
    InvalidP256Secret,
}

/// Versioned SCALE payload embedded in the pairing deeplink.
///
/// Host-spec B.1.1 defines the deeplink as lowercase hex of this SCALE payload:
/// <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L12-L22>
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub enum VersionedHandshakeProposal {
    #[codec(index = 1)]
    V2(v2::Proposal),
}

/// Versioned encrypted response posted by the wallet to the pairing topic.
///
/// Host-spec B.1.4 defines the encrypted answer statement and matching topic:
/// <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L62-L83>
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub enum VersionedHandshakeResponse {
    #[codec(index = 1)]
    V2 {
        encrypted_message: Vec<u8>,
        public_key: [u8; 65],
    },
}

/// Host-papp v2 handshake wire types.
pub mod v2;

/// Encrypted statement-channel envelope shared with the wallet.
///
/// Host-spec B.4.1 defines this request/response wrapper:
/// <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/B-inter-host.md?plain=1#L151-L175>
///
/// Mirrors `@novasamatech/statement-store` session statement data:
/// <https://github.com/paritytech/triangle-js-sdks/blob/18c12d3bd1c51a9520eb247dc038ace2996dc2e7/packages/statement-store/src/session/scale/statementData.ts#L33-L46>
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub enum SsoStatementData {
    Request {
        request_id: String,
        data: Vec<Vec<u8>>,
    },
    Response {
        request_id: String,
        response_code: u8,
    },
}

/// Decode a pairing deeplink (or its bare handshake hex) into the advertised
/// handshake proposal. Inverse of [`build_pairing_deeplink`].
pub fn decode_pairing_deeplink(deeplink: &str) -> Result<VersionedHandshakeProposal, String> {
    let hex_payload = match deeplink.split_once("?handshake=") {
        Some((_, hex_payload)) => hex_payload,
        None => deeplink,
    };
    let encoded = hex::decode(hex_payload.trim())
        .map_err(|err| format!("invalid pairing deeplink hex: {err}"))?;
    let mut input = encoded.as_slice();
    let proposal = VersionedHandshakeProposal::decode(&mut input)
        .map_err(|err| format!("invalid pairing handshake proposal: {err}"))?;
    if !input.is_empty() {
        return Err("invalid pairing handshake proposal: trailing bytes".to_string());
    }
    Ok(proposal)
}

/// Encrypt a v2 handshake response for the host that advertised
/// `host_encryption_public_key`. Inverse of [`decrypt_v2_handshake_response`]:
/// a fresh ephemeral P-256 key is used per response so each Pending/Success
/// statement carries an independent ciphertext.
pub fn encrypt_v2_handshake_response(
    host_encryption_public_key: [u8; 65],
    response: &v2::EncryptedResponse,
) -> Result<VersionedHandshakeResponse, String> {
    let (ephemeral_secret, ephemeral_public) =
        generate_p256_keypair().map_err(|err| err.to_string())?;
    let shared_secret = shared_secret(ephemeral_secret, host_encryption_public_key)?;
    let aes_key = aes_key_from_shared_secret(&shared_secret)?;
    let mut nonce = [0u8; AES_GCM_NONCE_LEN];
    getrandom::getrandom(&mut nonce)
        .map_err(|err| format!("failed to generate AES-GCM nonce: {err}"))?;
    let cipher = Aes256Gcm::new_from_slice(&aes_key)
        .map_err(|err| format!("failed to initialize AES-GCM: {err}"))?;
    let mut encrypted_message = nonce.to_vec();
    encrypted_message.extend(
        cipher
            .encrypt(Nonce::from_slice(&nonce), response.encode().as_slice())
            .map_err(|err| format!("failed to encrypt SSO handshake response: {err}"))?,
    );
    Ok(VersionedHandshakeResponse::V2 {
        encrypted_message,
        public_key: ephemeral_public,
    })
}

/// Decode wallet-posted pairing handshake data from SCALE bytes.
pub fn decode_app_handshake_data(blob: &[u8]) -> Result<VersionedHandshakeResponse, String> {
    let mut input = blob;
    let value: VersionedHandshakeResponse =
        Decode::decode(&mut input).map_err(|err| format!("invalid app handshake data: {err}"))?;
    if !input.is_empty() {
        return Err("invalid app handshake data: trailing bytes".to_string());
    }
    Ok(value)
}

/// Decrypt a v2 handshake response.
pub fn decrypt_v2_handshake_response(
    core_encryption_secret_key: [u8; 32],
    wallet_ephemeral_public_key: [u8; 65],
    encrypted_message: &[u8],
) -> Result<v2::EncryptedResponse, String> {
    let plaintext = decrypt_p256_hkdf_aes_gcm(
        core_encryption_secret_key,
        wallet_ephemeral_public_key,
        encrypted_message,
    )?;
    let mut input = plaintext.as_slice();
    let value = v2::EncryptedResponse::decode(&mut input)
        .map_err(|err| format!("invalid SSO V2 handshake response: {err}"))?;
    if !input.is_empty() {
        return Err("invalid SSO V2 handshake response: trailing bytes".to_string());
    }
    Ok(value)
}

/// Derive the persistent SSO session channels from a successful handshake.
pub fn establish_sso_session_info(
    bootstrap: &PairingBootstrap,
    peer_statement_account_id: [u8; 32],
    peer_sso_enc_pub_key: [u8; 65],
) -> Result<SsoSessionInfo, String> {
    let shared_secret = shared_secret(bootstrap.encryption_secret_key, peer_sso_enc_pub_key)?;
    let shared_secret_bytes: [u8; 32] = (*shared_secret.raw_secret_bytes()).into();
    let session_id_own = create_session_id(
        shared_secret_bytes,
        bootstrap.statement_store_public_key,
        peer_statement_account_id,
    );
    let session_id_peer = create_session_id(
        shared_secret_bytes,
        peer_statement_account_id,
        bootstrap.statement_store_public_key,
    );

    Ok(SsoSessionInfo {
        ss_secret: bootstrap.statement_store_secret,
        ss_public_key: bootstrap.statement_store_public_key,
        enc_secret: bootstrap.encryption_secret_key,
        peer_enc_pubkey: peer_sso_enc_pub_key,
        identity_account_id: peer_statement_account_id,
        session_id_own,
        session_id_peer,
        request_channel: keyed_hash(session_id_own, REQUEST_CHANNEL_SUFFIX),
        response_channel: keyed_hash(session_id_own, RESPONSE_CHANNEL_SUFFIX),
        peer_request_channel: keyed_hash(session_id_peer, REQUEST_CHANNEL_SUFFIX),
    })
}

/// Signing-host key material answering one pairing proposal.
///
/// The statement keypair signs every session statement (its public key is the
/// `identityAccountId` the pairing host binds the session to), and the P-256
/// secret is the persistent `sso_enc` key both sides feed into the session
/// ECDH.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResponderIdentity {
    pub statement_secret: [u8; 64],
    pub statement_public_key: [u8; 32],
    pub encryption_secret_key: [u8; 32],
    pub encryption_public_key: [u8; 65],
}

/// Derive the SSO session channels from the responder (signing host)
/// perspective after answering the handshake advertised by
/// `host_statement_account_id` / `host_encryption_public_key`.
///
/// Mirror of [`establish_sso_session_info`]: the responder's `session_id_own`
/// equals the pairing host's `session_id_peer` and vice versa, so statements
/// built from either side land on the topics the other side subscribes to.
pub fn establish_responder_session_info(
    identity: &ResponderIdentity,
    host_statement_account_id: [u8; 32],
    host_encryption_public_key: [u8; 65],
) -> Result<SsoSessionInfo, String> {
    let shared_secret = shared_secret(identity.encryption_secret_key, host_encryption_public_key)?;
    let shared_secret_bytes: [u8; 32] = (*shared_secret.raw_secret_bytes()).into();
    let session_id_own = create_session_id(
        shared_secret_bytes,
        identity.statement_public_key,
        host_statement_account_id,
    );
    let session_id_peer = create_session_id(
        shared_secret_bytes,
        host_statement_account_id,
        identity.statement_public_key,
    );

    Ok(SsoSessionInfo {
        ss_secret: identity.statement_secret,
        ss_public_key: identity.statement_public_key,
        enc_secret: identity.encryption_secret_key,
        peer_enc_pubkey: host_encryption_public_key,
        identity_account_id: host_statement_account_id,
        session_id_own,
        session_id_peer,
        request_channel: keyed_hash(session_id_own, REQUEST_CHANNEL_SUFFIX),
        response_channel: keyed_hash(session_id_own, RESPONSE_CHANNEL_SUFFIX),
        peer_request_channel: keyed_hash(session_id_peer, REQUEST_CHANNEL_SUFFIX),
    })
}

/// Statement channel acknowledging requests the peer initiated: the peer's
/// own `response` channel seen from this side of the session.
pub fn peer_response_channel(session: &SsoSessionInfo) -> [u8; 32] {
    keyed_hash(session.session_id_peer, RESPONSE_CHANNEL_SUFFIX)
}

/// Derive a deterministic P-256 keypair from BIP-39 entropy and a domain
/// label. Host-spec C.4 leaves signing-host P-256 derivation
/// implementation-defined; this scheme only needs to be stable per entropy.
pub fn derive_p256_keypair_from_entropy(
    entropy: &[u8],
    label: &[u8],
) -> Result<([u8; 32], [u8; 65]), PairingBootstrapError> {
    for attempt in 0..MAX_P256_SECRET_ATTEMPTS {
        let mut message = Vec::with_capacity(label.len() + 1);
        message.extend_from_slice(label);
        message.push(attempt as u8);
        let candidate = blake2b256_keyed(&message, entropy);
        let Ok(secret) = SecretKey::from_slice(&candidate) else {
            continue;
        };
        let public = secret.public_key().to_encoded_point(false);
        let public = public.as_bytes();
        if public.len() != 65 {
            return Err(PairingBootstrapError::InvalidP256Secret);
        }
        let mut encryption_public_key = [0u8; 65];
        encryption_public_key.copy_from_slice(public);
        return Ok((candidate, encryption_public_key));
    }

    Err(PairingBootstrapError::InvalidP256Secret)
}

/// Encrypt session-channel statement data with a random nonce.
pub fn encrypt_session_statement_data(
    session: &SsoSessionInfo,
    data: &SsoStatementData,
) -> Result<Vec<u8>, String> {
    let mut nonce = [0u8; AES_GCM_NONCE_LEN];
    getrandom::getrandom(&mut nonce)
        .map_err(|err| format!("failed to generate AES-GCM nonce: {err}"))?;
    encrypt_session_statement_data_with_nonce(session, data, nonce)
}

/// Encrypt session-channel statement data with a caller-supplied nonce.
pub fn encrypt_session_statement_data_with_nonce(
    session: &SsoSessionInfo,
    data: &SsoStatementData,
    nonce: [u8; AES_GCM_NONCE_LEN],
) -> Result<Vec<u8>, String> {
    let aes_key = session_aes_key(session)?;
    let cipher = Aes256Gcm::new_from_slice(&aes_key)
        .map_err(|err| format!("failed to initialize AES-GCM: {err}"))?;
    let mut encrypted = nonce.to_vec();
    encrypted.extend(
        cipher
            .encrypt(Nonce::from_slice(&nonce), data.encode().as_slice())
            .map_err(|err| format!("failed to encrypt SSO statement data: {err}"))?,
    );
    Ok(encrypted)
}

/// Decrypt session-channel statement data.
pub fn decrypt_session_statement_data(
    session: &SsoSessionInfo,
    encrypted_message: &[u8],
) -> Result<SsoStatementData, String> {
    let plaintext = decrypt_session_message(session, encrypted_message)?;
    let mut input = plaintext.as_slice();
    let data = SsoStatementData::decode(&mut input)
        .map_err(|err| format!("invalid SSO statement data: {err}"))?;
    if !input.is_empty() {
        return Err("invalid SSO statement data: trailing bytes".to_string());
    }
    Ok(data)
}

/// Decrypt an SSO handshake answer using P-256 ECDH, HKDF-SHA256, and AES-GCM.
fn decrypt_p256_hkdf_aes_gcm(
    own_secret_key: [u8; 32],
    peer_public_key: [u8; 65],
    encrypted_message: &[u8],
) -> Result<Vec<u8>, String> {
    if encrypted_message.len() < AES_GCM_NONCE_LEN {
        return Err("encrypted SSO handshake answer is too short".to_string());
    }
    let shared_secret = shared_secret(own_secret_key, peer_public_key)?;
    let aes_key = aes_key_from_shared_secret(&shared_secret)?;

    decrypt_aes_gcm_with_key(aes_key, encrypted_message, "handshake answer")
}

fn decrypt_session_message(
    session: &SsoSessionInfo,
    encrypted_message: &[u8],
) -> Result<Vec<u8>, String> {
    decrypt_aes_gcm_with_key(
        session_aes_key(session)?,
        encrypted_message,
        "statement data",
    )
}

/// Decrypt a nonce-prefixed AES-GCM payload with the already-derived channel key.
fn decrypt_aes_gcm_with_key(
    aes_key: [u8; 32],
    encrypted_message: &[u8],
    label: &str,
) -> Result<Vec<u8>, String> {
    if encrypted_message.len() < AES_GCM_NONCE_LEN {
        return Err(format!("encrypted SSO {label} is too short"));
    }
    let (nonce, ciphertext) = encrypted_message.split_at(AES_GCM_NONCE_LEN);
    let cipher = Aes256Gcm::new_from_slice(&aes_key)
        .map_err(|err| format!("failed to initialize AES-GCM: {err}"))?;
    cipher
        .decrypt(Nonce::from_slice(nonce), ciphertext)
        .map_err(|err| format!("failed to decrypt SSO {label}: {err}"))
}

/// Derive the AES-GCM session key for encrypted statement-channel messages.
fn session_aes_key(session: &SsoSessionInfo) -> Result<[u8; 32], String> {
    let shared_secret = shared_secret(session.enc_secret, session.peer_enc_pubkey)?;
    aes_key_from_shared_secret(&shared_secret)
}

/// Expand a P-256 ECDH shared secret into a 32-byte AES-GCM key.
fn aes_key_from_shared_secret(
    shared_secret: &p256::ecdh::SharedSecret,
) -> Result<[u8; 32], String> {
    let hkdf = Hkdf::<Sha256>::new(None, shared_secret.raw_secret_bytes());
    let mut aes_key = [0u8; 32];
    hkdf.expand(&[], &mut aes_key)
        .map_err(|err| format!("failed to derive AES key: {err}"))?;
    Ok(aes_key)
}

/// Compute the P-256 ECDH shared secret from our private key and the peer public key.
fn shared_secret(
    own_secret_key: [u8; 32],
    peer_public_key: [u8; 65],
) -> Result<p256::ecdh::SharedSecret, String> {
    let secret = SecretKey::from_slice(&own_secret_key)
        .map_err(|err| format!("invalid P-256 secret key: {err}"))?;
    let peer_public = PublicKey::from_sec1_bytes(&peer_public_key)
        .map_err(|err| format!("invalid P-256 public key: {err}"))?;
    Ok(diffie_hellman(
        secret.to_nonzero_scalar(),
        peer_public.as_affine(),
    ))
}

fn create_session_id(
    shared_secret: [u8; 32],
    account_a: [u8; 32],
    account_b: [u8; 32],
) -> [u8; 32] {
    let mut message = Vec::with_capacity(SESSION_PREFIX.len() + 32 + 32 + 2);
    message.extend_from_slice(SESSION_PREFIX);
    message.extend_from_slice(&account_a);
    message.extend_from_slice(&account_b);
    message.extend_from_slice(PIN_SEPARATOR);
    message.extend_from_slice(PIN_SEPARATOR);
    keyed_hash(shared_secret, &message)
}

fn keyed_hash(key: [u8; 32], message: &[u8]) -> [u8; 32] {
    blake2b256_keyed(message, &key)
}

fn blake2b256_keyed(message: &[u8], key: &[u8]) -> [u8; 32] {
    blake2b_simd::Params::new()
        .hash_length(32)
        .key(key)
        .hash(message)
        .as_bytes()
        .try_into()
        .expect("BLAKE2b-256 returns 32 bytes")
}

/// Create one-shot pairing bootstrap material from runtime config.
pub fn create_pairing_bootstrap(
    config: &PairingHostConfig,
) -> Result<PairingBootstrap, PairingBootstrapError> {
    create_pairing_bootstrap_from_identity(config, generate_pairing_device_identity()?)
}

/// Generate a fresh persistable pairing device identity.
pub fn generate_pairing_device_identity() -> Result<PairingDeviceIdentity, PairingBootstrapError> {
    let (statement_store_secret, statement_store_public_key) = generate_statement_store_keypair()?;
    let (encryption_secret_key, encryption_public_key) = generate_p256_keypair()?;

    Ok(PairingDeviceIdentity {
        statement_store_secret,
        statement_store_public_key,
        encryption_secret_key,
        encryption_public_key,
    })
}

/// Create pairing bootstrap material from an existing device identity.
pub fn create_pairing_bootstrap_from_identity(
    config: &PairingHostConfig,
    identity: PairingDeviceIdentity,
) -> Result<PairingBootstrap, PairingBootstrapError> {
    let deeplink = build_pairing_deeplink(
        &config.pairing_deeplink_scheme,
        identity.statement_store_public_key,
        identity.encryption_public_key,
        config,
    );
    let topic = bootstrap_topic(
        identity.statement_store_public_key,
        identity.encryption_public_key,
    );

    Ok(PairingBootstrap {
        deeplink,
        topic,
        statement_store_public_key: identity.statement_store_public_key,
        statement_store_secret: identity.statement_store_secret,
        encryption_public_key: identity.encryption_public_key,
        encryption_secret_key: identity.encryption_secret_key,
    })
}

/// Build the wallet deeplink that carries the v2 handshake proposal.
pub fn build_pairing_deeplink(
    scheme: &str,
    statement_store_public_key: [u8; 32],
    encryption_public_key: [u8; 65],
    config: &PairingHostConfig,
) -> String {
    let handshake = VersionedHandshakeProposal::V2(v2::Proposal {
        device: v2::Device {
            statement_account_id: statement_store_public_key,
            encryption_public_key,
        },
        metadata: handshake_metadata(config),
    });
    format!(
        "{scheme}://pair?handshake={}",
        hex::encode(handshake.encode())
    )
}

fn handshake_metadata(config: &PairingHostConfig) -> Vec<v2::MetadataEntry> {
    let mut entries = vec![v2::MetadataEntry(
        v2::MetadataKey::HostName,
        config.host.host_info.name.clone(),
    )];
    if let Some(value) = &config.host.host_info.version {
        entries.push(v2::MetadataEntry(
            v2::MetadataKey::HostVersion,
            value.clone(),
        ));
    }
    if let Some(value) = &config.host.host_info.icon {
        entries.push(v2::MetadataEntry(v2::MetadataKey::HostIcon, value.clone()));
    }
    if let Some(value) = &config.host.platform_info.kind {
        entries.push(v2::MetadataEntry(
            v2::MetadataKey::PlatformType,
            value.clone(),
        ));
    }
    if let Some(value) = &config.host.platform_info.version {
        entries.push(v2::MetadataEntry(
            v2::MetadataKey::PlatformVersion,
            value.clone(),
        ));
    }
    entries
}

/// Derive the statement-store pairing topic from advertised host keys.
pub fn bootstrap_topic(
    statement_store_public_key: [u8; 32],
    encryption_public_key: [u8; 65],
) -> [u8; 32] {
    let mut message =
        Vec::with_capacity(encryption_public_key.len() + HANDSHAKE_TOPIC_SUFFIX.len());
    message.extend_from_slice(&encryption_public_key);
    message.extend_from_slice(HANDSHAKE_TOPIC_SUFFIX);

    keyed_hash(statement_store_public_key, &message)
}

fn generate_statement_store_keypair() -> Result<([u8; 64], [u8; 32]), PairingBootstrapError> {
    let mut seed = [0u8; 32];
    getrandom::getrandom(&mut seed)
        .map_err(|err| PairingBootstrapError::Random(err.to_string()))?;
    let mini_secret = MiniSecretKey::from_bytes(&seed)
        .map_err(|err| PairingBootstrapError::Random(err.to_string()))?;
    let keypair = mini_secret.expand_to_keypair(ExpansionMode::Ed25519);
    Ok((keypair.secret.to_bytes(), keypair.public.to_bytes()))
}

fn generate_p256_keypair() -> Result<([u8; 32], [u8; 65]), PairingBootstrapError> {
    for _ in 0..MAX_P256_SECRET_ATTEMPTS {
        let mut candidate = [0u8; 32];
        getrandom::getrandom(&mut candidate)
            .map_err(|err| PairingBootstrapError::Random(err.to_string()))?;
        let Ok(secret) = SecretKey::from_slice(&candidate) else {
            continue;
        };
        let public = secret.public_key().to_encoded_point(false);
        let public = public.as_bytes();
        if public.len() != 65 {
            return Err(PairingBootstrapError::InvalidP256Secret);
        }
        let mut encryption_public_key = [0u8; 65];
        encryption_public_key.copy_from_slice(public);
        let mut encryption_secret_key = [0u8; 32];
        encryption_secret_key.copy_from_slice(secret.to_bytes().as_slice());
        return Ok((encryption_secret_key, encryption_public_key));
    }

    Err(PairingBootstrapError::InvalidP256Secret)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SS_PUBLIC: [u8; 32] = [
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
        0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d,
        0x1e, 0x1f,
    ];
    const ENC_PUBLIC: [u8; 65] = [
        0x04, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
        0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c,
        0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b,
        0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a,
        0x3b, 0x3c, 0x3d, 0x3e, 0x3f,
    ];

    fn runtime_config() -> PairingHostConfig {
        PairingHostConfig::new(
            HostInfo {
                name: "Polkadot Web".to_string(),
                icon: Some("https://example.invalid/dotli.png".to_string()),
                version: Some("1.2.3".to_string()),
            },
            PlatformInfo {
                kind: Some("Firefox".to_string()),
                version: Some("192.32".to_string()),
            },
            [0; 32],
            [0xbb; 32],
            "polkadotapp".to_string(),
        )
        .expect("test runtime config is valid")
    }

    #[test]
    fn builds_v2_pairing_deeplink() {
        let config = runtime_config();
        let deeplink = build_pairing_deeplink("polkadotapp", SS_PUBLIC, ENC_PUBLIC, &config);

        assert!(deeplink.starts_with("polkadotapp://pair?handshake=01"));
        let encoded = hex::decode(deeplink.split("handshake=").nth(1).unwrap()).unwrap();
        let decoded = <VersionedHandshakeProposal as Decode>::decode(&mut &encoded[..]).unwrap();
        let VersionedHandshakeProposal::V2(proposal) = decoded;
        assert_eq!(proposal.device.statement_account_id, SS_PUBLIC);
        assert_eq!(proposal.device.encryption_public_key, ENC_PUBLIC);
        assert!(proposal.metadata.contains(&v2::MetadataEntry(
            v2::MetadataKey::HostName,
            "Polkadot Web".to_string()
        )));
    }

    #[test]
    fn builds_dev_pairing_deeplink() {
        let deeplink =
            build_pairing_deeplink("polkadotappdev", SS_PUBLIC, ENC_PUBLIC, &runtime_config());

        assert!(deeplink.starts_with("polkadotappdev://pair?handshake="));
    }

    #[test]
    fn derives_bootstrap_topic_vector() {
        assert_eq!(
            hex::encode(bootstrap_topic(SS_PUBLIC, ENC_PUBLIC)),
            "031c589833c39b1dfbe3c1304ced75fa7b0d841035db008e5b407bfadd2779a4"
        );
    }

    #[test]
    fn generated_bootstrap_uses_real_key_shapes() {
        let config = runtime_config();

        let bootstrap = create_pairing_bootstrap(&config).unwrap();

        assert!(
            bootstrap
                .deeplink
                .starts_with("polkadotapp://pair?handshake=")
        );
        assert_eq!(bootstrap.encryption_public_key[0], 0x04);
        assert_eq!(
            bootstrap.topic,
            bootstrap_topic(
                bootstrap.statement_store_public_key,
                bootstrap.encryption_public_key
            )
        );
    }

    #[test]
    fn decodes_app_handshake_response() {
        let answer = VersionedHandshakeResponse::V2 {
            encrypted_message: vec![0xde, 0xad],
            public_key: ENC_PUBLIC,
        };

        assert_eq!(decode_app_handshake_data(&answer.encode()).unwrap(), answer);
    }

    #[test]
    fn rejects_app_handshake_trailing_bytes() {
        let mut encoded = VersionedHandshakeResponse::V2 {
            encrypted_message: vec![0xde, 0xad],
            public_key: ENC_PUBLIC,
        }
        .encode();
        encoded.push(0);

        assert_eq!(
            decode_app_handshake_data(&encoded).unwrap_err(),
            "invalid app handshake data: trailing bytes"
        );
    }

    #[test]
    fn decrypts_v2_handshake_response() {
        let core_secret = SecretKey::from_slice(&[1; 32]).unwrap();
        let wallet_ephemeral_secret = SecretKey::from_slice(&[2; 32]).unwrap();
        let wallet_ephemeral_public = wallet_ephemeral_secret.public_key().to_encoded_point(false);
        let mut wallet_ephemeral_public_bytes = [0u8; 65];
        wallet_ephemeral_public_bytes.copy_from_slice(wallet_ephemeral_public.as_bytes());

        let shared_secret = diffie_hellman(
            wallet_ephemeral_secret.to_nonzero_scalar(),
            core_secret.public_key().as_affine(),
        );
        let hkdf = Hkdf::<Sha256>::new(None, shared_secret.raw_secret_bytes());
        let mut aes_key = [0u8; 32];
        hkdf.expand(&[], &mut aes_key).unwrap();

        let sensitive = v2::EncryptedResponse::Success(Box::new(v2::Success {
            identity_account_id: [8; 32],
            root_account_id: [7; 32],
            identity_chat_private_key: [6; 32],
            sso_enc_pub_key: ENC_PUBLIC,
            device_enc_pub_key: ENC_PUBLIC,
            root_entropy_source: [5; 32],
        }));
        let nonce = [9u8; AES_GCM_NONCE_LEN];
        let cipher = Aes256Gcm::new_from_slice(&aes_key).unwrap();
        let mut encrypted = nonce.to_vec();
        encrypted.extend(
            cipher
                .encrypt(Nonce::from_slice(&nonce), sensitive.encode().as_slice())
                .unwrap(),
        );

        assert_eq!(
            decrypt_v2_handshake_response(
                core_secret.to_bytes().into(),
                wallet_ephemeral_public_bytes,
                &encrypted
            )
            .unwrap(),
            sensitive
        );
    }

    #[test]
    fn rejects_short_handshake_ciphertext() {
        assert_eq!(
            decrypt_v2_handshake_response([1; 32], ENC_PUBLIC, &[0; AES_GCM_NONCE_LEN - 1])
                .unwrap_err(),
            "encrypted SSO handshake answer is too short"
        );
    }

    #[test]
    fn establishes_session_ids_and_channels() {
        let core_secret = SecretKey::from_slice(&[1; 32]).unwrap();
        let core_public = core_secret.public_key().to_encoded_point(false);
        let mut core_public_bytes = [0u8; 65];
        core_public_bytes.copy_from_slice(core_public.as_bytes());
        let bootstrap = PairingBootstrap {
            deeplink: "polkadotapp://pair?handshake=00".to_string(),
            topic: [0x11; 32],
            statement_store_public_key: [0x22; 32],
            statement_store_secret: [0x33; 64],
            encryption_public_key: core_public_bytes,
            encryption_secret_key: [1; 32],
        };
        let peer_secret = SecretKey::from_slice(&[2; 32]).unwrap();
        let peer_public = peer_secret.public_key().to_encoded_point(false);
        let peer_public: [u8; 65] = peer_public.as_bytes().try_into().unwrap();

        let info = establish_sso_session_info(&bootstrap, [0x55; 32], peer_public).unwrap();

        assert_eq!(info.ss_secret, [0x33; 64]);
        assert_eq!(info.ss_public_key, [0x22; 32]);
        assert_eq!(info.enc_secret, [1; 32]);
        assert_eq!(info.peer_enc_pubkey, peer_public);
        assert_eq!(info.identity_account_id, [0x55; 32]);
        assert_ne!(info.session_id_own, info.session_id_peer);
        assert_eq!(
            info.request_channel,
            keyed_hash(info.session_id_own, b"request")
        );
        assert_eq!(
            info.response_channel,
            keyed_hash(info.session_id_own, b"response")
        );
        assert_eq!(
            info.peer_request_channel,
            keyed_hash(info.session_id_peer, b"request")
        );
    }

    #[test]
    fn decodes_pairing_deeplink_round_trip() {
        let config = runtime_config();
        let deeplink = build_pairing_deeplink("polkadotapp", SS_PUBLIC, ENC_PUBLIC, &config);

        let decoded = decode_pairing_deeplink(&deeplink).unwrap();

        let VersionedHandshakeProposal::V2(proposal) = decoded;
        assert_eq!(proposal.device.statement_account_id, SS_PUBLIC);
        assert_eq!(proposal.device.encryption_public_key, ENC_PUBLIC);
    }

    #[test]
    fn decodes_bare_handshake_hex() {
        let config = runtime_config();
        let deeplink = build_pairing_deeplink("polkadotapp", SS_PUBLIC, ENC_PUBLIC, &config);
        let hex_payload = deeplink.split("handshake=").nth(1).unwrap();

        assert_eq!(
            decode_pairing_deeplink(hex_payload).unwrap(),
            decode_pairing_deeplink(&deeplink).unwrap()
        );
    }

    #[test]
    fn rejects_pairing_deeplink_with_trailing_bytes() {
        let config = runtime_config();
        let deeplink = build_pairing_deeplink("polkadotapp", SS_PUBLIC, ENC_PUBLIC, &config);

        let err = decode_pairing_deeplink(&format!("{deeplink}00")).unwrap_err();

        assert_eq!(err, "invalid pairing handshake proposal: trailing bytes");
    }

    #[test]
    fn encrypted_handshake_response_round_trips_through_host_decrypt() {
        let host_secret = SecretKey::from_slice(&[1; 32]).unwrap();
        let host_public: [u8; 65] = host_secret
            .public_key()
            .to_encoded_point(false)
            .as_bytes()
            .try_into()
            .unwrap();
        let response = v2::EncryptedResponse::Success(Box::new(v2::Success {
            identity_account_id: [8; 32],
            root_account_id: [7; 32],
            identity_chat_private_key: [6; 32],
            sso_enc_pub_key: ENC_PUBLIC,
            device_enc_pub_key: ENC_PUBLIC,
            root_entropy_source: [5; 32],
        }));

        let VersionedHandshakeResponse::V2 {
            encrypted_message,
            public_key,
        } = encrypt_v2_handshake_response(host_public, &response).unwrap();

        assert_eq!(
            decrypt_v2_handshake_response(
                host_secret.to_bytes().into(),
                public_key,
                &encrypted_message
            )
            .unwrap(),
            response
        );
    }

    fn responder_identity() -> ResponderIdentity {
        let (statement_secret, statement_public_key) = generate_statement_store_keypair().unwrap();
        let (encryption_secret_key, encryption_public_key) =
            derive_p256_keypair_from_entropy(&[0xAB; 16], b"sso-encryption").unwrap();
        ResponderIdentity {
            statement_secret,
            statement_public_key,
            encryption_secret_key,
            encryption_public_key,
        }
    }

    /// The responder-perspective session must mirror the host-perspective
    /// session: swapped session ids, aligned channels, and one shared AES key
    /// so either side can decrypt the other's statement data.
    #[test]
    fn responder_session_mirrors_host_session() {
        let config = runtime_config();
        let host_bootstrap = create_pairing_bootstrap(&config).unwrap();
        let responder = responder_identity();

        let responder_session = establish_responder_session_info(
            &responder,
            host_bootstrap.statement_store_public_key,
            host_bootstrap.encryption_public_key,
        )
        .unwrap();
        let host_session = establish_sso_session_info(
            &host_bootstrap,
            responder.statement_public_key,
            responder.encryption_public_key,
        )
        .unwrap();

        assert_eq!(
            responder_session.session_id_own,
            host_session.session_id_peer
        );
        assert_eq!(
            responder_session.session_id_peer,
            host_session.session_id_own
        );
        assert_eq!(
            responder_session.request_channel,
            host_session.peer_request_channel
        );
        assert_eq!(
            peer_response_channel(&responder_session),
            host_session.response_channel
        );

        let data = SsoStatementData::Request {
            request_id: "req-1".to_string(),
            data: vec![vec![0xde, 0xad]],
        };
        let encrypted = encrypt_session_statement_data(&responder_session, &data).unwrap();
        assert_eq!(
            decrypt_session_statement_data(&host_session, &encrypted).unwrap(),
            data
        );
    }

    #[test]
    fn statement_data_codec_round_trips_request_and_response() {
        let request = SsoStatementData::Request {
            request_id: "req-1".to_string(),
            data: vec![vec![0xde, 0xad], vec![0xbe, 0xef]],
        };
        let response = SsoStatementData::Response {
            request_id: "req-1".to_string(),
            response_code: 0,
        };

        assert_eq!(
            SsoStatementData::decode(&mut &request.encode()[..]).unwrap(),
            request
        );
        assert_eq!(
            SsoStatementData::decode(&mut &response.encode()[..]).unwrap(),
            response
        );
        assert_eq!(request.encode()[0], 0);
        assert_eq!(response.encode()[0], 1);
    }

    #[test]
    fn encrypts_and_decrypts_session_statement_data() {
        let core_secret = SecretKey::from_slice(&[1; 32]).unwrap();
        let core_public = core_secret.public_key().to_encoded_point(false);
        let mut core_public_bytes = [0u8; 65];
        core_public_bytes.copy_from_slice(core_public.as_bytes());
        let bootstrap = PairingBootstrap {
            deeplink: "polkadotapp://pair?handshake=00".to_string(),
            topic: [0x11; 32],
            statement_store_public_key: [0x22; 32],
            statement_store_secret: [0x33; 64],
            encryption_public_key: core_public_bytes,
            encryption_secret_key: [1; 32],
        };
        let peer_secret = SecretKey::from_slice(&[2; 32]).unwrap();
        let peer_public = peer_secret
            .public_key()
            .to_encoded_point(false)
            .as_bytes()
            .try_into()
            .unwrap();
        let session = establish_sso_session_info(&bootstrap, [0x55; 32], peer_public).unwrap();
        let data = SsoStatementData::Request {
            request_id: "req-1".to_string(),
            data: vec![vec![0xde, 0xad]],
        };
        let nonce = [9u8; AES_GCM_NONCE_LEN];

        let encrypted = encrypt_session_statement_data_with_nonce(&session, &data, nonce).unwrap();

        assert_eq!(&encrypted[..AES_GCM_NONCE_LEN], nonce);
        assert_eq!(
            decrypt_session_statement_data(&session, &encrypted).unwrap(),
            data
        );
    }
}
