// Auto-generated by truapi-codegen. Do not edit.
//
// Typed host-callbacks surface derived from the `truapi-platform`
// capability traits. One interface per Rust trait + a composite
// `HostCallbacks` interface that mirrors the `Platform` super-trait.

import * as S from "@parity/truapi/scale";

import {
  HostDevicePermissionRequest,
  HostRequestResourceAllocationRequest,
  HostSignPayloadRequest,
  HostSignPayloadWithLegacyAccountRequest,
  HostSignRawRequest,
  HostSignRawWithLegacyAccountRequest,
  LegacyAccountTxPayload,
  ProductAccountTxPayload,
  RemotePermissionRequest,
} from "@parity/truapi";

import type {
  GenericError,
  HostDevicePermissionResponse,
  HostFeatureSupportedRequest,
  HostFeatureSupportedResponse,
  HostPushNotificationRequest,
  HostPushNotificationResponse,
  NotificationId,
  RemotePermissionResponse,
  Result,
  ThemeVariant,
} from "@parity/truapi";

/**
 * Review shown before a product asks to access another product account.
 */
export interface AccountAccessReview {
  /**
   * Product currently handling the request.
   */
  requestingProductId: string;

  /**
   * Product whose account is being requested.
   */
  targetProductId: string;
}

/**
 * Review shown before a product asks to alias another product account.
 */
export interface AccountAliasReview {
  /**
   * Product currently handling the request.
   */
  requestingProductId: string;

  /**
   * Product whose account is being requested.
   */
  targetProductId: string;
}

/**
 * Auth/session lifecycle state the core projects for host UI. The core owns
 * every transition and emits states in order; hosts render the current state
 * and never derive auth UI from any other signal.
 */
export type AuthState =
  /**
   * No active session and no login in progress.
   */
  | { tag: "Disconnected"; value?: undefined }
  /**
   * A login is in progress: present the pairing deeplink/QR. Leave this
   * state only on a subsequent emission (connected, failed, or
   * disconnected after cancellation).
   */
  | { tag: "Pairing"; value: { deeplink: string } }
  /**
   * A session is active.
   */
  | { tag: "Connected"; value: SessionUiInfo }
  /**
   * The last login attempt failed; show the reason and offer a retry.
   */
  | { tag: "LoginFailed"; value: { reason: string } };

/**
 * Core-owned host-private storage slots. Products never address these slots;
 * the host chooses the backing store for each slot.
 *
 * Storage is host-local; `storage.md` records the current status quo:
 * <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/storage.md?plain=1#L1-L7>
 */
export type CoreStorageKey =
  /**
   * Opaque SSO/auth session blob.
   */
  | { tag: "AuthSession"; value?: undefined }
  /**
   * Pairing device identity used during SSO flows.
   */
  | { tag: "PairingDeviceIdentity"; value?: undefined }
  /**
   * Persisted authorization for one product-scoped permission request.
   */
  | { tag: "PermissionAuthorization"; value: { productId: string; request: PermissionAuthorizationRequest } }
  /**
   * Persisted allowance-slot keys for one paired SSO session.
   */
  | { tag: "AllowanceKeys"; value: { sessionId: string } }
  /**
   * Last processed SSO pairing response statement for the pairing device.
   */
  | { tag: "LastProcessedPairingStatement"; value?: undefined };

/**
 * Review shown before a transaction-creation request is sent to the paired wallet.
 */
export type CreateTransactionReview =
  /**
   * Product-account transaction request.
   */
  | { tag: "Product"; value: ProductAccountTxPayload }
  /**
   * Legacy-account transaction request.
   */
  | { tag: "LegacyAccount"; value: LegacyAccountTxPayload };

/**
 * Review shown before a product learns the user's primary identity.
 */
export interface IdentityDisclosureReview {
  /**
   * Product currently handling the request.
   */
  productId: string;
}

/**
 * Permission request whose authorization status can be inspected or updated
 * by host administration UI.
 */
export type PermissionAuthorizationRequest =
  /**
   * Device-level permission such as camera, microphone, or location.
   */
  | { tag: "Device"; value: HostDevicePermissionRequest }
  /**
   * Remote/product-scoped permission such as chain submit or HTTP access.
   */
  | { tag: "Remote"; value: RemotePermissionRequest }
  /**
   * Product-scoped permission to disclose the user's primary identity.
   */
  | { tag: "IdentityDisclosure"; value?: undefined };

/**
 * Authorization status for a permission request.
 *
 * `NotDetermined` means the core has no persisted answer and will prompt the
 * host the next time the product requests this permission.
 */
export type PermissionAuthorizationStatus = "NotDetermined" | "Denied" | "Authorized";

/**
 * Review shown before a preimage is submitted.
 */
export interface PreimageSubmitReview {
  /**
   * Size of the preimage in bytes.
   */
  size: bigint;
}

/**
 * Decoded session fields a host shell needs to render account UI without
 * parsing the opaque session blob the core persists through `CoreStorage`.
 */
export interface SessionUiInfo {
  /**
   * 32-byte sr25519 root public key of the active session.
   */
  publicKey: Uint8Array;

  /**
   * Wallet identity account id used for People-chain username lookup.
   */
  identityAccountId?: Uint8Array;

  /**
   * Short username from the People-chain identity record.
   */
  liteUsername?: string;

  /**
   * Fully qualified username from the People-chain identity record.
   */
  fullUsername?: string;
}

/**
 * Review shown before a sign-payload request is sent to the paired wallet.
 */
export type SignPayloadReview =
  /**
   * Product-account signing request.
   */
  | { tag: "Product"; value: HostSignPayloadRequest }
  /**
   * Legacy-account signing request.
   */
  | { tag: "LegacyAccount"; value: HostSignPayloadWithLegacyAccountRequest };

/**
 * Review shown before a sign-raw request is sent to the paired wallet.
 */
export type SignRawReview =
  /**
   * Product-account raw signing request.
   */
  | { tag: "Product"; value: HostSignRawRequest }
  /**
   * Legacy-account raw signing request.
   */
  | { tag: "LegacyAccount"; value: HostSignRawWithLegacyAccountRequest };

/**
 * Review shown before a user-confirmed core action continues.
 */
export type UserConfirmationReview =
  /**
   * Sign a SCALE payload with a product or legacy account.
   */
  | { tag: "SignPayload"; value: SignPayloadReview }
  /**
   * Sign raw bytes with a product or legacy account.
   */
  | { tag: "SignRaw"; value: SignRawReview }
  /**
   * Create a transaction with a product or legacy account.
   */
  | { tag: "CreateTransaction"; value: CreateTransactionReview }
  /**
   * Allow a product to request another product account alias.
   */
  | { tag: "AccountAlias"; value: AccountAliasReview }
  /**
   * Allow a product to learn the user's primary identity.
   */
  | { tag: "IdentityDisclosure"; value: IdentityDisclosureReview }
  /**
   * Allocate resources for the requesting product.
   */
  | { tag: "ResourceAllocation"; value: HostRequestResourceAllocationRequest }
  /**
   * Submit a preimage to the host-selected backend.
   */
  | { tag: "PreimageSubmit"; value: PreimageSubmitReview }
  /**
   * Allow a product to access another product account.
   */
  | { tag: "AccountAccess"; value: AccountAccessReview };

/**
 * Review shown before a product asks to access another product account.
 */
export const AccountAccessReview: S.Codec<AccountAccessReview> = S.lazy((): S.Codec<AccountAccessReview> => S.Struct({requestingProductId: S.str, targetProductId: S.str}) as S.Codec<AccountAccessReview>);

/**
 * Review shown before a product asks to alias another product account.
 */
export const AccountAliasReview: S.Codec<AccountAliasReview> = S.lazy((): S.Codec<AccountAliasReview> => S.Struct({requestingProductId: S.str, targetProductId: S.str}) as S.Codec<AccountAliasReview>);

/**
 * Auth/session lifecycle state the core projects for host UI. The core owns
 * every transition and emits states in order; hosts render the current state
 * and never derive auth UI from any other signal.
 */
export const AuthState: S.Codec<AuthState> = S.lazy((): S.Codec<AuthState> => S.TaggedUnion({Disconnected: S._void, Pairing: S.Struct({deeplink: S.str}) as S.Codec<{ deeplink: string }>, Connected: SessionUiInfo, LoginFailed: S.Struct({reason: S.str}) as S.Codec<{ reason: string }>}));

/**
 * Core-owned host-private storage slots. Products never address these slots;
 * the host chooses the backing store for each slot.
 *
 * Storage is host-local; `storage.md` records the current status quo:
 * <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/storage.md?plain=1#L1-L7>
 */
export const CoreStorageKey: S.Codec<CoreStorageKey> = S.lazy((): S.Codec<CoreStorageKey> => S.TaggedUnion({AuthSession: S._void, PairingDeviceIdentity: S._void, PermissionAuthorization: S.Struct({productId: S.str, request: PermissionAuthorizationRequest}) as S.Codec<{ productId: string; request: PermissionAuthorizationRequest }>, AllowanceKeys: S.Struct({sessionId: S.str}) as S.Codec<{ sessionId: string }>, LastProcessedPairingStatement: S._void}));

/**
 * Review shown before a transaction-creation request is sent to the paired wallet.
 */
export const CreateTransactionReview: S.Codec<CreateTransactionReview> = S.lazy((): S.Codec<CreateTransactionReview> => S.TaggedUnion({Product: ProductAccountTxPayload, LegacyAccount: LegacyAccountTxPayload}));

/**
 * Review shown before a product learns the user's primary identity.
 */
export const IdentityDisclosureReview: S.Codec<IdentityDisclosureReview> = S.lazy((): S.Codec<IdentityDisclosureReview> => S.Struct({productId: S.str}) as S.Codec<IdentityDisclosureReview>);

/**
 * Permission request whose authorization status can be inspected or updated
 * by host administration UI.
 */
export const PermissionAuthorizationRequest: S.Codec<PermissionAuthorizationRequest> = S.lazy((): S.Codec<PermissionAuthorizationRequest> => S.TaggedUnion({Device: HostDevicePermissionRequest, Remote: RemotePermissionRequest, IdentityDisclosure: S._void}));

/**
 * Authorization status for a permission request.
 *
 * `NotDetermined` means the core has no persisted answer and will prompt the
 * host the next time the product requests this permission.
 */
export const PermissionAuthorizationStatus: S.Codec<PermissionAuthorizationStatus> = S.lazy((): S.Codec<PermissionAuthorizationStatus> => S.Status("NotDetermined", "Denied", "Authorized"));

/**
 * Review shown before a preimage is submitted.
 */
export const PreimageSubmitReview: S.Codec<PreimageSubmitReview> = S.lazy((): S.Codec<PreimageSubmitReview> => S.Struct({size: S.u64}) as S.Codec<PreimageSubmitReview>);

/**
 * Decoded session fields a host shell needs to render account UI without
 * parsing the opaque session blob the core persists through `CoreStorage`.
 */
export const SessionUiInfo: S.Codec<SessionUiInfo> = S.lazy((): S.Codec<SessionUiInfo> => S.Struct({publicKey: S.Bytes(32), identityAccountId: S.Option(S.Bytes(32)), liteUsername: S.Option(S.str), fullUsername: S.Option(S.str)}) as S.Codec<SessionUiInfo>);

/**
 * Review shown before a sign-payload request is sent to the paired wallet.
 */
export const SignPayloadReview: S.Codec<SignPayloadReview> = S.lazy((): S.Codec<SignPayloadReview> => S.TaggedUnion({Product: HostSignPayloadRequest, LegacyAccount: HostSignPayloadWithLegacyAccountRequest}));

/**
 * Review shown before a sign-raw request is sent to the paired wallet.
 */
export const SignRawReview: S.Codec<SignRawReview> = S.lazy((): S.Codec<SignRawReview> => S.TaggedUnion({Product: HostSignRawRequest, LegacyAccount: HostSignRawWithLegacyAccountRequest}));

/**
 * Review shown before a user-confirmed core action continues.
 */
export const UserConfirmationReview: S.Codec<UserConfirmationReview> = S.lazy((): S.Codec<UserConfirmationReview> => S.TaggedUnion({SignPayload: SignPayloadReview, SignRaw: SignRawReview, CreateTransaction: CreateTransactionReview, AccountAlias: AccountAliasReview, IdentityDisclosure: IdentityDisclosureReview, ResourceAllocation: HostRequestResourceAllocationRequest, PreimageSubmit: PreimageSubmitReview, AccountAccess: AccountAccessReview}));

/**
 * Host auth UI driven by core-owned `AuthState` transitions.
 */
export interface AuthPresenter {
  /**
   * Observe an auth state change. Emitted only when the state actually
   * changes, in transition order. Default is a no-op for hosts that
   * render no auth UI.
   */
  authStateChanged?(state: AuthState): void;
}

/**
 * JSON-RPC provider factory for chain access.
 *
 * The platform provides a way to get a JSON-RPC connection for a given chain.
 * The server runtime manages the chainHead v1 state machine on top of this.
 * Host-spec N.6 requires products to access chains through host-mediated
 * providers:
 * <https://github.com/paritytech/host-spec/blob/adb3989208ae1c2107dbf0159611353e6989422c/spec/N-shared-infrastructure.md?plain=1#L91-L102>
 */
export interface ChainProvider {
  /**
   * Open a JSON-RPC connection for the chain identified by `genesis_hash`.
   * Drop the returned connection to disconnect.
   */
  connect(genesisHash: Uint8Array): Promise<JsonRpcConnection>;
}

/**
 * Core-owned administration API exposed to host UI.
 *
 * Hosts call this surface to drive global runtime actions or inspect/update
 * core-owned state without going through a product-scoped TrUAPI request.
 */
export interface CoreAdmin {
  /**
   * Best-effort logout/disconnect. Clears the active session and emits the
   * resulting auth state transition.
   */
  disconnectSession(): Promise<void>;

  /**
   * Read a stored permission authorization status without prompting.
   */
  getPermissionAuthorizationStatus(request: PermissionAuthorizationRequest): Promise<PermissionAuthorizationStatus>;

  /**
   * Read stored permission authorization statuses without prompting.
   *
   * Results are returned in the same order as `requests`.
   */
  getPermissionAuthorizationStatuses(requests: Array<PermissionAuthorizationRequest>): Promise<Array<PermissionAuthorizationStatus>>;

  /**
   * Update a stored permission authorization status. `NotDetermined` clears
   * the stored value so the next product request prompts again.
   */
  setPermissionAuthorizationStatus(request: PermissionAuthorizationRequest, status: PermissionAuthorizationStatus): Promise<void>;
}

/**
 * Host-private persistence for core-owned state.
 */
export interface CoreStorage {
  /**
   * Read a core-owned value by typed slot.
   */
  readCoreStorage(key: CoreStorageKey): Promise<Uint8Array | undefined>;

  /**
   * Write a core-owned value by typed slot.
   */
  writeCoreStorage(key: CoreStorageKey, value: Uint8Array): Promise<void>;

  /**
   * Clear a core-owned value by typed slot.
   */
  clearCoreStorage(key: CoreStorageKey): Promise<void>;
}

/**
 * Feature-support probing. The host answers whether it can service a given
 * capability (currently scoped to per-chain support).
 */
export interface Features {
  /**
   * Report whether the requested feature is supported.
   */
  featureSupported(request: HostFeatureSupportedRequest): Promise<HostFeatureSupportedResponse>;
}

/**
 * A live JSON-RPC connection to a chain.
 */
export interface JsonRpcConnection {
  /**
   * Send a JSON-RPC request string.
   */
  send(request: string): void;

  /**
   * Stream of JSON-RPC response strings.
   */
  responses(): AsyncIterable<string>;

  /**
   * Close the connection lease.
   *
   * Hosts may keep a shared underlying transport alive, but this handle
   * must stop receiving responses and release any per-caller resources.
   */
  close(): void;
}

/**
 * Open URLs in the system browser. Input is already trimmed, categorized,
 * and (where needed) normalized by the core; the host implementation only
 * needs to hand the URL to the OS URL handler.
 */
export interface Navigation {
  /**
   * Open the given URL in the system browser.
   */
  navigateTo(url: string): Promise<void>;
}

/**
 * Deliver push notifications.
 */
export interface Notifications {
  /**
   * Schedule or immediately display the given notification and return the
   * host-assigned id.
   */
  pushNotification(notification: HostPushNotificationRequest): Promise<HostPushNotificationResponse>;

  /**
   * Cancel a notification by id. Idempotent: cancelling an already-fired or
   * unknown id still returns `success`.
   */
  cancelNotification?(id: NotificationId): Promise<void>;
}

/**
 * Pairing-host-only administration API exposed to host UI.
 */
export interface PairingHostAdmin {
  /**
   * Cancel any in-flight pairing request.
   */
  cancelPairing(): void;

  /**
   * Notify the core that the persisted auth-session blob may have changed.
   *
   * The host owns persistence and change detection. The pairing core owns
   * decoding that blob into live `SessionState` / `AuthState`.
   */
  notifySessionStoreChanged(): void;
}

/**
 * Permission prompts. Device permissions (camera, mic, NFC, ...) are separate
 * from remote permissions (domain access, chain submit, ...), so the platform
 * surface mirrors that split.
 */
export interface Permissions {
  /**
   * Prompt the user for a device-level permission.
   */
  devicePermission(request: HostDevicePermissionRequest): Promise<HostDevicePermissionResponse>;

  /**
   * Prompt the user for a remote (product-scoped) permission bundle.
   */
  remotePermission(request: RemotePermissionRequest): Promise<RemotePermissionResponse>;
}

/**
 * Host preimage backend. The core owns wire mapping and subscription
 * lifecycle; the host owns the selected backend.
 */
export interface PreimageHost {
  /**
   * Submit the preimage and return its key.
   */
  submitPreimage?(value: Uint8Array, bulletinAllowanceKey: Uint8Array): Promise<Uint8Array>;

  /**
   * Emits current value/miss immediately, then future updates.
   */
  lookupPreimage(key: Uint8Array): AsyncIterable<Result<Uint8Array | undefined, GenericError>>;
}

/**
 * Product-scoped key-value storage.
 *
 * The core namespaces product keys before calling this trait. Host
 * implementations should treat `key` as an opaque OS-style storage key.
 */
export interface ProductStorage {
  /**
   * Read a value by key.
   */
  read(key: string): Promise<Uint8Array | undefined>;

  /**
   * Write a value to a key.
   */
  write(key: string, value: Uint8Array): Promise<void>;

  /**
   * Clear a value at a key.
   */
  clear(key: string): Promise<void>;
}

/**
 * Host theme source.
 */
export interface ThemeHost {
  /**
   * Emits current theme immediately, then future changes.
   */
  subscribeTheme(): AsyncIterable<Result<ThemeVariant, GenericError>>;
}

/**
 * Local user confirmation UI for sensitive core-owned operations.
 */
export interface UserConfirmation {
  /**
   * Confirm a reviewed action before the core continues.
   */
  confirmUserAction(review: UserConfirmationReview): Promise<boolean>;
}

/** @deprecated Use the namespaced `HostCallbacks` shape instead. */
export interface FlatHostCallbacks extends Navigation, Notifications, Permissions, Features, ProductStorage, CoreStorage, ChainProvider, AuthPresenter, UserConfirmation, ThemeHost, PreimageHost {}

/**
 * Combined platform interface. A host must provide all capability traits.
 */
export interface HostCallbacks {
  navigation: Navigation;
  notifications: Notifications;
  permissions: Permissions;
  features: Features;
  productStorage: ProductStorage;
  coreStorage: CoreStorage;
  chain: ChainProvider;
  auth: AuthPresenter;
  userConfirmation: UserConfirmation;
  theme: ThemeHost;
  preimage: PreimageHost;
}

export interface RequiredHostCallbacks {
  navigation: Required<Navigation>;
  notifications: Required<Notifications>;
  permissions: Required<Permissions>;
  features: Required<Features>;
  productStorage: Required<ProductStorage>;
  coreStorage: Required<CoreStorage>;
  chain: Required<ChainProvider>;
  auth: Required<AuthPresenter>;
  userConfirmation: Required<UserConfirmation>;
  theme: Required<ThemeHost>;
  preimage: Required<PreimageHost>;
}
