// Auto-generated by truapi-codegen. Do not edit.
//
// Typed host-callbacks surface derived from the `truapi-platform`
// capability traits. One interface per Rust trait + a composite
// `HostCallbacks` interface that mirrors the `Platform` super-trait.

import type {
  HostDevicePermissionRequest,
  HostDevicePermissionResponse,
  HostFeatureSupportedRequest,
  HostFeatureSupportedResponse,
  HostPushNotificationRequest,
  RemotePermissionRequest,
  RemotePermissionResponse,
} from "@parity/truapi";

/**
 * JSON-RPC provider factory for chain access.
 *
 * The platform provides a way to get a JSON-RPC connection for a given chain.
 * The server runtime manages the chainHead v1 state machine on top of this.
 */
export interface ChainProvider {
  /**
   * Open a JSON-RPC connection for the chain identified by `genesis_hash`.
   * Drop the returned connection to disconnect.
   */
  connect(genesisHash: Uint8Array): Promise<JsonRpcConnection>;
}

/**
 * Feature-support probing. The host answers whether it can service a given
 * capability (currently scoped to per-chain support).
 */
export interface Features {
  /**
   * Report whether the requested feature is supported.
   */
  featureSupported(request: HostFeatureSupportedRequest): Promise<HostFeatureSupportedResponse>;
}

/**
 * A live JSON-RPC connection to a chain.
 */
export interface JsonRpcConnection {
  /**
   * Send a JSON-RPC request string.
   */
  send(request: string): void;

  /**
   * Stream of JSON-RPC response strings.
   */
  responses(): AsyncIterable<string>;
}

/**
 * Open URLs in the system browser. Input is already trimmed, categorized,
 * and (where needed) normalized by the core; the host implementation only
 * needs to hand the URL to the OS URL handler.
 */
export interface Navigation {
  /**
   * Open the given URL in the system browser.
   */
  navigateTo(url: string): Promise<void>;
}

/**
 * Deliver push notifications.
 */
export interface Notifications {
  /**
   * Push the given notification to the user.
   */
  pushNotification(notification: HostPushNotificationRequest): Promise<void>;
}

/**
 * Permission prompts. v0.1 keeps device permissions (camera, mic, NFC, ...)
 * separate from remote permissions (domain access, chain submit, ...), so the
 * platform surface mirrors that split.
 */
export interface Permissions {
  /**
   * Prompt the user for a device-level permission.
   */
  devicePermission(request: HostDevicePermissionRequest): Promise<HostDevicePermissionResponse>;

  /**
   * Prompt the user for a remote (product-scoped) permission bundle.
   */
  remotePermission(request: RemotePermissionRequest): Promise<RemotePermissionResponse>;
}

/**
 * Scoped key-value storage. The platform namespaces keys so different products
 * cannot read each other's data.
 */
export interface Storage {
  /**
   * Read a value by key.
   */
  read(key: string): Promise<Uint8Array | undefined>;

  /**
   * Write a value to a key.
   */
  write(key: string, value: Uint8Array): Promise<void>;

  /**
   * Clear a value at a key.
   */
  clear(key: string): Promise<void>;
}

/**
 * Combined platform interface. A host must provide all capability traits.
 */
export interface HostCallbacks extends Navigation, Notifications, Permissions, Features, Storage, ChainProvider {}
