// Auto-generated by truapi-codegen. Do not edit.
//
// Adapts the typed `HostCallbacks` surface onto the byte-oriented
// callback surface the WASM core invokes. Named wire types cross as
// SCALE bytes (`.enc`/`.dec`); strings, primitives, byte blobs and
// platform-local types pass through unchanged.

import {
  HostDevicePermissionRequest,
  HostDevicePermissionResponse,
  HostFeatureSupportedRequest,
  HostFeatureSupportedResponse,
  HostPushNotificationRequest,
  HostPushNotificationResponse,
  RemotePermissionRequest,
  RemotePermissionResponse,
  ThemeVariant,
} from "@parity/truapi";
import type {
  NotificationId,
} from "@parity/truapi";
import type { AuthState, HostCallbacks } from "./host-callbacks.js";
import type { ChainConnect } from "../runtime.js";
import {
  chainConnectAdapter,
  createUnavailableCallbacks,
  driveResultStream,
} from "../adapter-support.js";

export interface RawCallbacks {
  authStateChanged(state: AuthState): void;
  featureSupported(request: Uint8Array): Promise<Uint8Array>;
  navigateTo(url: string): Promise<void>;
  pushNotification(notification: Uint8Array): Promise<Uint8Array>;
  cancelNotification(id: NotificationId): Promise<void>;
  devicePermission(request: Uint8Array): Promise<Uint8Array>;
  remotePermission(request: Uint8Array): Promise<Uint8Array>;
  confirmPreimageSubmit(size: number): Promise<void>;
  submitPreimage(value: Uint8Array): Promise<Uint8Array>;
  lookupPreimage(key: Uint8Array, sendItem: (item?: Uint8Array) => void): (() => void) | void;
  readSession(): Promise<Uint8Array | null | undefined>;
  writeSession(value: Uint8Array): Promise<void>;
  clearSession(): Promise<void>;
  subscribeSessionStore(sendItem: (item?: Uint8Array) => void): (() => void) | void;
  read(key: string): Promise<Uint8Array | null | undefined>;
  write(key: string, value: Uint8Array): Promise<void>;
  clear(key: string): Promise<void>;
  subscribeTheme(sendItem: (item?: Uint8Array) => void): (() => void) | void;
  confirmSignPayload(review: Uint8Array): Promise<boolean>;
  confirmSignRaw(review: Uint8Array): Promise<boolean>;
  confirmCreateTransaction(review: Uint8Array): Promise<boolean>;
  confirmAccountAlias(review: Uint8Array): Promise<boolean>;
  confirmResourceAllocation(review: Uint8Array): Promise<boolean>;
  chainConnect?: ChainConnect;
}
/** Adapt typed host callbacks into the raw SCALE callback surface the
 *  WASM core invokes. Applied internally by `createWasmProvider`. */
export function createWasmRawCallbacks(
  host: Partial<HostCallbacks>,
): RawCallbacks {
  const unavailable = createUnavailableCallbacks();
  return {
    ...unavailable,
    authStateChanged: host.authStateChanged ? async (state) => await host.authStateChanged!(state) : unavailable.authStateChanged,
    chainConnect: chainConnectAdapter(host),
    featureSupported: host.featureSupported ? async (request) => HostFeatureSupportedResponse.enc(await host.featureSupported!(HostFeatureSupportedRequest.dec(request))) : unavailable.featureSupported,
    navigateTo: host.navigateTo ? async (url) => await host.navigateTo!(url) : unavailable.navigateTo,
    pushNotification: host.pushNotification ? async (notification) => HostPushNotificationResponse.enc(await host.pushNotification!(HostPushNotificationRequest.dec(notification))) : unavailable.pushNotification,
    cancelNotification: host.cancelNotification ? async (id) => await host.cancelNotification!(id) : unavailable.cancelNotification,
    devicePermission: host.devicePermission ? async (request) => HostDevicePermissionResponse.enc(await host.devicePermission!(HostDevicePermissionRequest.dec(request))) : unavailable.devicePermission,
    remotePermission: host.remotePermission ? async (request) => RemotePermissionResponse.enc(await host.remotePermission!(RemotePermissionRequest.dec(request))) : unavailable.remotePermission,
    confirmPreimageSubmit: host.confirmPreimageSubmit ? async (size) => await host.confirmPreimageSubmit!(BigInt(size)) : unavailable.confirmPreimageSubmit,
    submitPreimage: host.submitPreimage ? async (value) => await host.submitPreimage!(value) : unavailable.submitPreimage,
    lookupPreimage: host.lookupPreimage ? (key, sendItem) => driveResultStream(host.lookupPreimage!(key), sendItem) : unavailable.lookupPreimage,
    readSession: host.readSession ? async () => await host.readSession!() : unavailable.readSession,
    writeSession: host.writeSession ? async (value) => await host.writeSession!(value) : unavailable.writeSession,
    clearSession: host.clearSession ? async () => await host.clearSession!() : unavailable.clearSession,
    subscribeSessionStore: host.subscribeSessionStore ? (sendItem) => driveResultStream(host.subscribeSessionStore!(), () => sendItem()) : unavailable.subscribeSessionStore,
    read: host.read ? async (key) => await host.read!(key) : unavailable.read,
    write: host.write ? async (key, value) => await host.write!(key, value) : unavailable.write,
    clear: host.clear ? async (key) => await host.clear!(key) : unavailable.clear,
    subscribeTheme: host.subscribeTheme ? (sendItem) => driveResultStream(host.subscribeTheme!(), (item) => sendItem(ThemeVariant.enc(item))) : unavailable.subscribeTheme,
    confirmSignPayload: host.confirmSignPayload ? async (review) => await host.confirmSignPayload!(review) : unavailable.confirmSignPayload,
    confirmSignRaw: host.confirmSignRaw ? async (review) => await host.confirmSignRaw!(review) : unavailable.confirmSignRaw,
    confirmCreateTransaction: host.confirmCreateTransaction ? async (review) => await host.confirmCreateTransaction!(review) : unavailable.confirmCreateTransaction,
    confirmAccountAlias: host.confirmAccountAlias ? async (review) => await host.confirmAccountAlias!(review) : unavailable.confirmAccountAlias,
    confirmResourceAllocation: host.confirmResourceAllocation ? async (review) => await host.confirmResourceAllocation!(review) : unavailable.confirmResourceAllocation,
  };
}
