// Auto-generated by truapi-codegen. Do not edit.
//
// Worker-side metadata and proxy functions for the raw WASM callback
// surface. The worker transport/lifecycle remains hand-written; this
// file owns the callback names, host-hook arity, and
// subscription payload shape derived from `truapi-platform`.

import type { RawCallbacks } from "./host-callbacks-adapter.js";

import type { BulletinAllowanceSigner } from "./host-callbacks.js";

export interface WorkerBulletinAllowanceSigner {
  publicKey: Uint8Array;
  signerId: number;
}

import type {
  ChainConnect,
} from "../runtime.js";

export const CALLBACK_NAMES = [
  "authStateChanged",
  "readCoreStorage",
  "writeCoreStorage",
  "clearCoreStorage",
  "featureSupported",
  "navigateTo",
  "pushNotification",
  "cancelNotification",
  "devicePermission",
  "remotePermission",
  "submitPreimage",
  "read",
  "write",
  "clear",
  "confirmUserAction",
] as const;
export type CallbackName = typeof CALLBACK_NAMES[number];

export const SUBSCRIPTION_NAMES = [
  "lookupPreimage",
  "subscribeTheme",
] as const;
export type SubscriptionName = typeof SUBSCRIPTION_NAMES[number];

export interface WorkerCallbackBridge {
  callbackRequest(name: CallbackName, args: readonly unknown[]): Promise<unknown>;
  registerBulletinAllowanceSigner(signer: BulletinAllowanceSigner): WorkerBulletinAllowanceSigner;
  startSubscription<T>(
    name: SubscriptionName,
    payload: Uint8Array | null,
    sendItem: (value: T) => void,
  ): () => void;
  chainConnect: ChainConnect;
}

function rawCallbacks(bridge: WorkerCallbackBridge): Required<Pick<RawCallbacks, CallbackName>> {
  return {
    authStateChanged: (state) =>
      void bridge.callbackRequest("authStateChanged", [state]).catch(() => {}),
    readCoreStorage: (key) =>
      bridge.callbackRequest("readCoreStorage", [key]) as ReturnType<RawCallbacks["readCoreStorage"]>,
    writeCoreStorage: (key, value) =>
      bridge.callbackRequest("writeCoreStorage", [key, value]) as ReturnType<RawCallbacks["writeCoreStorage"]>,
    clearCoreStorage: (key) =>
      bridge.callbackRequest("clearCoreStorage", [key]) as ReturnType<RawCallbacks["clearCoreStorage"]>,
    featureSupported: (request) =>
      bridge.callbackRequest("featureSupported", [request]) as ReturnType<RawCallbacks["featureSupported"]>,
    navigateTo: (url) =>
      bridge.callbackRequest("navigateTo", [url]) as ReturnType<RawCallbacks["navigateTo"]>,
    pushNotification: (notification) =>
      bridge.callbackRequest("pushNotification", [notification]) as ReturnType<RawCallbacks["pushNotification"]>,
    cancelNotification: (id) =>
      bridge.callbackRequest("cancelNotification", [id]) as ReturnType<RawCallbacks["cancelNotification"]>,
    devicePermission: (request) =>
      bridge.callbackRequest("devicePermission", [request]) as ReturnType<RawCallbacks["devicePermission"]>,
    remotePermission: (request) =>
      bridge.callbackRequest("remotePermission", [request]) as ReturnType<RawCallbacks["remotePermission"]>,
    submitPreimage: (value, bulletinAllowanceSigner) =>
      bridge.callbackRequest("submitPreimage", [value, bridge.registerBulletinAllowanceSigner(bulletinAllowanceSigner)]) as ReturnType<RawCallbacks["submitPreimage"]>,
    read: (key) =>
      bridge.callbackRequest("read", [key]) as ReturnType<RawCallbacks["read"]>,
    write: (key, value) =>
      bridge.callbackRequest("write", [key, value]) as ReturnType<RawCallbacks["write"]>,
    clear: (key) =>
      bridge.callbackRequest("clear", [key]) as ReturnType<RawCallbacks["clear"]>,
    confirmUserAction: (review) =>
      bridge.callbackRequest("confirmUserAction", [review]) as ReturnType<RawCallbacks["confirmUserAction"]>,
  };
}

function subscriptionRawCallbacks(bridge: WorkerCallbackBridge): Required<Pick<RawCallbacks, SubscriptionName>> {
  return {
    lookupPreimage: (key, sendItem) =>
      bridge.startSubscription("lookupPreimage", key, sendItem),
    subscribeTheme: (sendItem) =>
      bridge.startSubscription("subscribeTheme", null, sendItem),
  };
}

export function createWorkerRawCallbacks(
  bridge: WorkerCallbackBridge,
): Record<string, unknown> {
  const callbacks: Record<string, unknown> = {
    ...rawCallbacks(bridge),
    ...subscriptionRawCallbacks(bridge),
    chainConnect: bridge.chainConnect,
  };
  return callbacks;
}

export function startRawSubscription(
  callbacks: RawCallbacks,
  name: SubscriptionName,
  payload: Uint8Array | null,
  sendItem: (value?: unknown) => void,
): (() => void) | void {
  switch (name) {
    case "lookupPreimage":
      if (payload === null) {
        console.warn(`[truapi worker] ${name} requires payload`);
        return undefined;
      }
      return callbacks.lookupPreimage(payload, sendItem);
    case "subscribeTheme":
      return callbacks.subscribeTheme(sendItem);
  }
}
